### ISSUE TITLE
GENSKIP_PKMJD keyword not working

### ISSUE THREAD

**Issue by jalasker** [RickKessler/SNANA#100]
Including these lines in SIMGEN_INCLUDE file: 

GENRANGE_PEAKMJD: 56450.0  58185    # Y1-5
GENSKIP_PKMJD: 56704 56845      # Y1 End = Feb 9, 2014 = 56697, Y2 Start = Aug 6, 2014 = 56875
GENSKIP_PKMJD: 56775 57204      # Y2 End = Feb 15, 2015 = 57068, Y3 Start = Jul 31, 2015 = 57234
GENSKIP_PKMJD: 57454 57556      # Y3 End = Feb 29, 2016 = 57447, Y4 Start = Jul 17, 2016 = 57586
GENSKIP_PKMJD: 57809 57949      # Y4 End = Feb 18, 2017 = 57802, Y5 Start = Aug 14, 2017 = 57979

produces a uniform distribution of simulated PEAKMJDs without any clear gaps in the MJD regions specified.

**Comment by RickKessler** [comment]
this key works only in SIMLIB_HEADER, and not in sim-input file. Not sure it's worth using this key for current and future surveys since the lost out-of-season time is no more than factor of 2, and it adds normalization confusion.
