### ISSUE TITLE
simulated host spectrum scale does not match what's defined

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#1000]
host spectrum simulated using TAKE_SPECTRUM_HOSTSNFRAC doesn't match the scale defined
an example can be found here: $SNANA_DEBUG/mdai/hostspec
to reproduce, run: ./TEST.CMD
thanks!

**Comment by RickKessler** [comment]
SCALE_HOST_CONFUSION is now written to data files, both TEXT and FITS. To see example,
./TEST.CMD 
./GREP_DATAFILE
