### ISSUE TITLE
host contamination scale is off

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#1003]
The host contamination scale is off using the HOSTSNFRAC option
an example can be found here: $SNANA_DEBUG/mdai/hostspec_scale
in the above dir run: ./TEST.CMD

**Comment by RickKessler** [comment]
Fixed HOSTSNFRAC integration to use bins with F_HOST>0  and F_PEAK(SN)>0. Updated manual to clarify integration.
<img width="1100" alt="HOSTSNFRAC" src="https://user-images.githubusercontent.com/24592476/191322858-15a6551f-c13b-496f-a865-f245107492d2.png">
