### ISSUE TITLE
ZTF binaries

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#101]
Seems there is an issue from midway to midway2 migration with some binaries. For security reasons,  not putting absolute paths but explain what is the difference in the error.

Read filter-integral flux-table from binary file: 
	 $ZTF_ROOT(with project2)/simsed_binaries/SIMSED.CART-MOSFIT_ZTF_MSIP-gr.BINARY 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by read_SIMSED_TABBINARY
   Binary file KCOR_FILE: '$ZTF_ROOT(with project instead project2)/kcor/20180711/kcor_ZTF.fits' 
   but current KCOR_FILE: '$ZTF_ROOT(with project2)/kcor/20180711/kcor_ZTF.fits'

**Comment by RickKessler** [comment]
Please provide ABORT message without modifications; commentary can be added separately. I cannot 'ls' things like $ZTF_ROOT(with project2)/kcor/20180711/kcor_ZTF.fits

**Comment by RickKessler** [comment]
the ZTF binaries need to be re-made. The abort most likely means that an original file is either no longer there, or the date stamp has been updated. In either case, the binaries are stale and should be re-made.
