### ISSUE TITLE
Merging task failing when using append fitres

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1012]
I'm running LCfit on a big biascor simulations and I'm using the command:

However, this crashes at the merging stage with this error:
```
# FATAL ERROR ABORT
#   ERROR merging table files:
#       Missing expected PIP_BIASCOR_S3XL_DES5YRSIMBIAS_4D_P21FIXB/FITOPT000.FITRES
#       Missing expected PIP_BIASCOR_S3XL_DES5YRSIMBIAS_4D_P21FIXB/FITOPT000.ROOT
#
# FATAL ERROR ABORT
#   Check CPU0089*.LOG for merge crash
#

```

Here is the output and logs : /scratch/midway2/rkessler/PIPPIN_OUTPUT/BIASCOR_S3XL/2_LCFIT/D3_DES5YRSIMBIAS_4D_P21FIXB/output/SPLIT_JOBS_LCFIT
Running ls- ltr in this folder will show you the merging files:
MERGE_PIP_BIASCOR_S3XL_DES5YRSIMBIAS_4D_P21FIXB_FITOPT000.ROOT
and the empty MERGE_PIP_BIASCOR_S3XL_DES5YRSIMBIAS_4D_P21FIXB_FITOPT000.FITRES
Also, CPU0089_JOBLIST_midway2-login1.LOG has the failed error message.

I run a test on a much smaller simulation test (1000 times smaller than the biascor sim) and everything worked perfectly (see /scratch/midway2/rkessler/PIPPIN_OUTPUT/BIASCOR_S3XL/2_LCFIT/D3_DES5YRSIMBIAS_4D_P21FIXB_MINTEST)
So maybe it's a problem of a file being too big or SNANA not waiting long enough for a MERGE task to finish?

**Comment by RickKessler** [comment]
I re-ran the MERGE command interactively and it worked fine; however, I noticed that the combine_fitres memory usage was 2.15 GB, which exceeds the default 2GB allocation for LCFIT task. So I would suggest setting 
BATCH_MEM: 4GB
in the CONFIG block

**Comment by maria-vincenzi** [comment]
the suggestions above fixed problem in the specific example I sent.
but I still find there's something crashing when I run things on data here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_SMP/2_LCFIT/Dsys_DATADES5YRSMP/broken_output
I tried increasing the memory, reducing number of fitopts and various different attempts but for some reason the file:
MERGE_DES5YR_SMP_FITOPT000.FITRES (see inside /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_SMP/2_LCFIT/Dsys_DATADES5YRSMP/broken_output/SPLIT_JOBS_LCFIT) is empty.

**Comment by maria-vincenzi** [comment]
copied the folder above into 
from Dsys_DATADES5YRSMP to Dsys_DATADES5YRSMP_example to avoid clobbering
