### ISSUE TITLE
Add w0-Om ellipse to WFIT_SUMMARY.FITRES

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1019]
Add the covariance between w0 and Om to WFIT_SUMMARY.FITRES

**Comment by RickKessler** [comment]
rho_womm added to YAML output from wfit, and propagated to WFIT_SUMMARY.FITRES by submit_batch_jobs. Note that WFIT_SUMMARY_AVG.FITRES is not updated.
