### ISSUE TITLE
multiple sims initialized with NGENTOT_LC=0

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#102]
Hi Rick,

3/25 of my simulations in one particular cosmology (w=-0.85, omega_m=0.1) were initialized with NGENTOT_LC=0 and were aborted. I found that the command at the beginning of the 3 aborted sims had `NGENTOT_LC 0 NGEN_LC 0`, whereas the successful sims had `NGENTOT_LC 7769 NGEN_LC 0`.

I've copied a successful simlog (`TMP_hele_PIP_HELEN_DES3YR_CI2D_DESSIM_w_0_85_omega_m_0_1-0022_49657_SNIa.LOG`)and an unsuccessful one (`TMP_hele_PIP_HELEN_DES3YR_CI2D_DESSIM_w_0_85_omega_m_0_1-0001_49657_SNIa.LOG`) to `$SNANA_DEBUG/helen`. 

the full output of the simulations in this cosmology can be found in `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_DES3YR_CI2D/1_SIM/DESSIM_w_0_85_omega_m_0_1`.

Thanks for your help!

**Comment by RickKessler** [comment]
This is indeed very strange. My hunch is a disk issue where a few jobs were unable to read SIMnorm_PIP_HELEN_DES3YR_CI2D_DESSIM_w_0_85_omega_m_0_1_SNIa.LOG and thus a blank string was interpreted as zero events. I will look into trapping this error.

**Comment by RickKessler** [comment]
I added abort trap if NPER_SEASON is a null string, and maybe get better diagnostics. Other than that, try to re-submit.
