### ISSUE TITLE
Fiducial H0 in SALT2mu gives bias best fits

### ISSUE THREAD

**Issue by RyanCamo** [RickKessler/SNANA#1020]
As discussed in the posterior validation meeting, the choice of H0 seems to bias the best fit parameters. These results were generated with CosmoMC - I will be checking these results with WFi as suggested by Patrick.

**Comment by RyanCamo** [comment]
I reran the above tests with WFit and got the same issues. The directory for the H0 tests using WFit can be found at $PIPPIN_OUTPUT/RC_TEST_S32. 

I also reran tests with more reasonable H0 (mostly default H0=70) values however used some extreme om, w  for the fiducial cosmology and also found issues with the best fit parameters.

For example a fiducial om=0, w=-1 used on data created with om=0.3, w=-1. After 20 realisations the mean of the best fit parameters was om = 0.228, w=-0.86. This was done with CosmoMC (let me know if you want me to rerun these with WFit) and the output directory can be found at $PIPPIN_OUTPUT/RC_SALT2MU

**Comment by RickKessler** [comment]
in SALT2mu.exe program (BBC), chi2max cut definition has been updated to essentially marginalize over H0. Expectation is to recover a small number of events. For now, the new chi2max cut is implemented with debug_flag=1031 ... this new cut definition will become default after checking a few more data samples.

**Comment by RickKessler** [comment]
New chi2max cut is now default; no longer need debug_flag=1031
