### ISSUE TITLE
BBC crashing because of crazy events in C11 sims

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1023]
when running BBC on C11 simulations I very often get these errors
```
  PRE-ABORT DUMP from function makeMap_sigmu_biasCor :
	 z=0.607660  a=0.120000  b=4.200000  gDM=0.060000
	 ia,ib,ig = 0, 1, 1
	 istat_cov = 0
	 IDSAMPLE=3 (DES(C3))
	  mB = 13.365664 +_ 0.780541
	  x1 = -0.713608 +_ 0.964750
	   c = 0.140110 +_ 2.571040

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by makeMap_sigmu_biasCor
   Invalid muErrsq=103.331119 for ievt=3462792 (SNID=35896300)
   Something is messed up.
```

for now the only solution I found is to manually remove these 3/4 events from the C11 FITRES file.
is there a better way to make sure BBC doesn't crash when hitting these crazy events (but just ignores them
)

**Comment by RickKessler** [comment]
Note this SALT2 fitPar value in the dump: c = 0.140110 +_ 2.571040
To avoid such larger errors, add this to BBC-input
CUTWIN cERR  0  2.0
(look at cERR distribution and  select appropriate cut)
