### ISSUE TITLE
Non-Ia models crashing for LSST

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1024]
Hello! 

within /project2/rkessler/SURVEYS/LSST/USERS/rhlozek/castor/

running snlc_sim.exe on either of the two files causes a segfault:

SIMGEN_INCLUDE_TDE-MOSFIT.INPUT
SIMGEN_INCLUDE_MOSFIT_SLSN_MAGNETAR.INPUT

Both are pointing to LSST-ready models in the $PLASTICC_MODELS, so I'm not sure what's up!

**Comment by RickKessler** [comment]
if you copied these INCLUDE files from $PLASTICC area, they are meant to be included in another input file, and they won't run on their own.
