### ISSUE TITLE
ZPERR issues in Foundation 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1025]
Good afternoon! 

We are encountering some strange ZPERR problems in Foundation. The original Foundation SIMLIB had specified ZPERR as 0.001. I have created a SIMLIB here: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/LOW-REDSHIFT/FOUND_YSE_FIXEDZPERR.SIMLIB
which is otherwise identical except the ZPERR is set to 0.015.

Fitted simulations with this new simlib can be found here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-FOUNDFIX/2_LCFIT/

There are two sets of sims, both made with the same SIMLIB: one has a FUDGE_MAG_ERR of 'g .015 r .015 i .015  z .02' (F3_FUDGE) and the other does not (F3_NOFUDGE).

The SNANA manual states:
```If there are no meta-data, the default ZPERR is 0.01, which imposes an SNR ceiling of 100 in the
simulation. Arbitrary ZPERR values can be input via &SNLCINP as shown in the following example:
SIMLIB_ZPERR_LIST = 'u .02 gri .01 z 0.015'
Any band not listed above gets the default ZPERR=0.01```

For the F3_NOFUDGE version, we are getting SNRMAX values well above 100 in our simulations, making us believe that this is not being propagated properly.

**Comment by RickKessler** [comment]
Yah, the manual was sort'of correct but left out an important caveat. Below is an updated snippet of the ZPERR description, along with the SMEARFLAG_ZEROPT options.

<img width="838" alt="manual-SMEARFLAG" src="https://user-images.githubusercontent.com/24592476/192900344-be7df498-6553-4009-b089-afa6a8f84338.png">
<img width="880" alt="manual_ZPERR-upsate" src="https://user-images.githubusercontent.com/24592476/192900351-2d9b4e12-ffea-4950-acac-bc878a28f454.png">
