### ISSUE TITLE
Add host related parameters to SNANA

### ISSUE THREAD

**Issue by wisemanp** [RickKessler/SNANA#1030]
Hi Rick, 
We have additional host-related parameters that we would like to track from the HOSTLIB through the simulation to the FITRES. They are SN_AGE and GAL_AGE. These are important for testing age and dust-based scatter models and biascors. 

Cheers, Phil & Brodie

**Comment by RickKessler** [comment]
HOSTLIB_STOREPAR:  SN_AGE,GAL_AGE

**Comment by wisemanp** [comment]
We used HOSTLIB_STOREPAR but neither SN_AGE or GAL_AGE show up in the ROOT file when using sntable_dump.py. HOSTLIB_STOREPAR is being parsed but not making it to the ROOT file.

**Comment by RickKessler** [comment]
Can you provide example under $SNANA_DEBUG ? According to the manual,
"these “STOREPAR” paramaters are automatically propagated into the SNTABLEs and ascii fitres file", so looks like a bug.

**Comment by wisemanp** [comment]
Have made an example on $SNANA_DEBUG/wisemanp/ with SIM.CMD and FIT.CMD

**Comment by RickKessler** [comment]
In a long-ago refactor of read/write utilities, the read-back of SIM_HOSTLIB params was accidentally left out for FITS format, and buggy for TEXT format. Fixed read-back. for both formats. This information goes to ROOT file automatically; to get this info into FITRES-TEXT file, set
 &SNLCINP
     SNTABLE_LIST = 'FITRES(text:host)'

or extract from ROOT file.

**Comment by wisemanp** [comment]
Thanks Rick, this now works.
