### ISSUE TITLE
Simsed Binaries issue

### ISSUE THREAD

**Issue by marlena6** [RickKessler/SNANA#1037]
Getting error when running submit_batch_jobs.sh on `$LSST_SNANA_ROOT/PLASTICC_DEV/survey_config/SIMGEN_MASTER_SCOTCH_10k_Z3_TDE.INPUT`
(currently set to an SLSN run to check, earlier tried it with TDE):

```
- FATAL ERROR ABORT called by read_SIMSED_TABBINARY 
  - Binary table mis-match =>  
  - Try deleting /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/ROOT/PLASTICC/model_libs/SIMSED_BINARIES/config_SCOTCH//SIMSED.SLSN-I-MOSFIT_LSST-ugrizY.BINARY
```

**Comment by RickKessler** [comment]
Can you try re-making the binary tables under 
    $PLASTICC_MODELS/SIMSED_BINARIES/config_SCOTCH

**Comment by marlena6** [comment]
This fixed the issue! Thanks.
