### ISSUE TITLE
Duplicate CIDs

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#104]
Hello Rick!

With the dawn of BS20 and needing two separate simulations (a high mass and low mass sim), could we please add an option to toggle the duplicate CIDs flag in SALT2mu? Right now, when combining the simulated high mass and low mass samples, I have to rewrite the CIDs for each FITRES file.

Thank you!

**Comment by RickKessler** [comment]
I don't understand the request; please clarify.

**Comment by bap37** [comment]
Yeah, sorry. SALT2mu currently automatically aborts if it detects duplicate CIDs. This is all well and good for normal operation, but for the BS20 model, this becomes an issue. We need to make two different simulations - one with low mass galaxies, the other with high mass. 

The issue is that neither Dillon nor I have found a way to generate these two simulations without having duplicate CIDs. We can explain better in person sometime if that works better

**Comment by RickKessler** [comment]
if you create both sims in the same SIMGEN-master job, the there is a way to guarantee unique CIDs in all simulated GENVERSIONs. In the simgen-master file, make sure to have
RESET_CIDOFF:  2
