### ISSUE TITLE
No error for incorrect input key and filename in master file

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#105]
sim_SNmix doesn't abort with the following key/value in the master file:    

    SIMGEN_INFILE_IA: simulation/SIMGEN_WFIRST_NON1A_Photozv2.INPUT
It runs fine and says success, but actually doesn't do anything because the input file should actually be:

    simulation/SIMGEN_WFIRST_NONIA_Photozv2.INPUT
(NON1A-->NONIa)
and the key should be:

    SIMGEN_INFILE_Ia
(IA-->Ia)
Do you want to make it abort when the key is wrong and/or no input file is found?

Example of this issue can be found in:

    $SNANA_DEBUG/wfirst_lensing_cc

**Comment by RickKessler** [comment]
hard to check for every possible wrong key ... an invalid key is ignored as a comment. However, note that SIMGEN_INFILE_Ia and SIMGEN_INFILE_SNIa are both valid keys.

**Comment by djones1040** [comment]
Hi Rick - shouldn't sim_SNmix abort if no valid SIMGEN_INFILE is given?  Is there a valid use case where one would not provide either a SIMGEN_INFILE_Ia or SIMGEN_INFILE_NONIa?

**Comment by RickKessler** [comment]
sim_SNmix checks input keys for SNIa and for NONIa ... works if either or both are specified. If no SIMGEN_INFILE is provided, then it should abort ... let me know if indeed no SIMGEN_INFILEs are given. Above I couldn't find your simgen-master file

**Comment by jpierel14** [comment]
That is what's happening, there is no viable SNIa or NONIa file in the sim and it is not aborting. the simgen-master should be in:

    $SNANA_DIR/wfirst_lensing_cc/simulation

**Comment by RickKessler** [comment]
fixed to abort if no SIMGEN_INFILE_[Ia,SNIa,NONIa] key is read.
