### ISSUE TITLE
kcor.exe crashes when extending the wavelength range

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1050]
Afternoon - 

Trying to extend some SNIa stuff into the UV. We realised that the AB system is only defined up to about 1700 Angstroms, so we tried to extend it using a custom efficiency and the BD17 system. Unfortunately, this results in a segfault when doing:

```
cd /project2/rkessler/SURVEYS/LSST/USERS/rhlozek/castor
kcor.exe kcor_LSST_CASTOR.input
```

**Comment by RickKessler** [comment]
fixed to allow comment lines in sed primary file.
