### ISSUE TITLE
Issues with NSPLITRAN and multiple FITOPTS

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1057]
I'm having issues running BBC jobs with multiple fitopts using the same events + NSPLITRAN. The first FITOPT will finish its first iteration, but the second fitopt never starts, and I don't get any error messages out.
If I check the most recent log (e.g., $PIPPIN_OUTPUT/GT_SALT23_PUB_1SIM_SMEARZP/6_BIASCOR/3YR_common_322_in/output_ITER1/SCRIPTS_BBCFIT/CPU0000_JOBLIST_midway2-login2.LOG) I see this at the bottom:
Wait for ../OUTPUT_BBCFIT/FITOPT000_MUOPT000.FITRES.gz
But NSPLITRAN jobs won't make an OUTPUT_BBCFIT directory, so it seems to just wait forever.

The input file is /scratch/midway2/rkessler/PIPPIN_OUTPUT/GT_SALT23_PUB_1SIM_SMEARZP/6_BIASCOR/3YR_common_322_in/3YR_common_322_in.input

**Comment by RickKessler** [comment]
fixed a few bugs.
