### ISSUE TITLE
PSNID NML file no longer working 

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#106]
A PSNID NML file that worked 2 weeks ago no longer works 
split_and_fit.pl /scratch/midway2/masao/psnid_dessims/SNANA_PSNID_MARIASIMS.NML.  It cannot locate the SIMS that I think are there.  The warning says:

 Path(PIP_MV_CCMASAO_IaPec-00*): /scratch/midway2/rkessler/SNDATA_ROOT/SIM
 WARNING SIM does not exist !!!
 Path(PIP_MV_CCMASAO_CCv4-00*): /scratch/midway2/rkessler/SNDATA_ROOT/SIM
 WARNING SIM does not exist !!!

Did something change?

If you do  du -hs /scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-00*  you can see all the sims:

8.0M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0001
7.7M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0002
7.5M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0003
7.5M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0004
7.5M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0005
7.5M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0006
7.4M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0007
7.8M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0008
7.5M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0009
7.5M	/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_MV_CCMASAO_CCv4-0010

So it looks like the sims are where they are supposed to be.
Same for IaPec

Thanks for your help

**Comment by RickKessler** [comment]
cleaned up garbage in PATH_SNDATA_SIM.LIST file, and then it worked.
