### ISSUE TITLE
chi2max cut at the end rejects all events 

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1060]
Folder:
/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/chi2REJECT_ALL
Run FAIL_REPEAT_OUTPUT_BBCFIT_FITOPT000_MUOPT014.CMD
In this SALT2mu job, chi2max cut at the end rejects all events and I'm not sure why.

**Comment by RickKessler** [comment]
This fit suffered from CrazyERR in which all of the M0 errors are way smaller than naive stat error and thus the entire fit is repeated. At the start of the repeat fit, the chi2max function found -infinity for M0 offset (H0 marg), so I modify code to skip chi2max cut on repeated fit. Now the fit finishes, but the results are still crazy.
