### ISSUE TITLE
wfit occasionally fails catastrophically

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#1069]
path to example of failed wfit: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MISMATCH_TO_WFIT_WITH_CC_LOWZ/6_BIASCOR/BCOR_WRONGHOST_SERSIC_SCALE/output/PIP_HELEN_MISMATCH_TO_WFIT_WITH_CC_LOWZ_DESSIM_WRONGHOST_SERSIC-0025`

the other realizations of the same simulation were fit successfully, i.e. `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MISMATCH_TO_WFIT_WITH_CC_LOWZ/6_BIASCOR/BCOR_WRONGHOST_SERSIC_SCALE/output/PIP_HELEN_MISMATCH_TO_WFIT_WITH_CC_LOWZ_DESSIM_WRONGHOST_SERSIC-0024`

this also seems to be a problem only for these simulations generated with `HOSTLIB_SCALE_SERSIC_SIZE: 0.8`. i don't see any examples of this happening for the set of otherwise identical simulations that don't scale the Sersic parameters.

**Comment by RickKessler** [comment]
crazy fit-errors were identified in this case, and the fit was repeated. But a bug crept in that forced all the fit-par ranges to be zero. Fixed.
