### ISSUE TITLE
Add CUTWIN_IDSAMPLE

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1073]
Add a feature:
CUTWIN_IDSAMPLE(1,2,3)” VARNAME MIN MAX

**Comment by RickKessler** [comment]
Done:

SALT2mu.exe | grep CUTWIN_
CUTWIN_IDSAMPLE(0,3,4):   zHD .01 .03  # apply cut only to IDSAMPLE 0,3 & 4
CUTWIN_SURVEY(CFA3,CFA4): zHD .01 .03  # apply cut only to CFA3 & CFA4 surveys
