### ISSUE TITLE
Weird crashes when fitting dat files with spectra 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1074]
Hello! When I try to fit some data files with spectra, I get a particular error: 

```   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by RDSPEC_DRIVER
   Invalid NLAMBIN = ***
   MXLAM_SPECTRUM=***```

Which is confusing, because these don't seem to be parsed or required anywhere in the file itself! 

This can be replicated by running snlc_fit.exe on  /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/WEIRDO_SPEC/ZTFDR2_fitDATA.nml

**Comment by bap37** [comment]
I fixed the NLAM carriage return - the problem persists though!

**Comment by RickKessler** [comment]
after fixing abort print, NLAM=59244 exceeds bound fo 20000.
