### ISSUE TITLE
Binning issue in SALT2mu_SUBPROCESS 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1076]
When running SALT2mu_SUBPROCESS and binning by HOST_COLOR, it appears that the binning is not being properly parsed. When the bins are set to be HOST_COLOR(2,-2:4), the SUBPROCESS table only counts ~50 supernova in the "high" colour bin. But the data indicates that there should be about half the sample - see /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/D2D_SMP/DATA_HOST_COLOR.pdf

This process can be replicated by running RUNTEST_SUBPROCESS_DATA in /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/D2D_SMP

**Comment by RickKessler** [comment]
fixed bug : make sure to call malloc_TABLEVAR_HOST() only for IFILE==0.
