### ISSUE TITLE
vpec uncertainties not included in MUERR calculations

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1086]
Testing BBC4D on simulations and not recovering chi2 of 1 (always <0.1, especially in low-z).
Found that the issue is that vpec errors are not included in the muerr calculations 

USEMASK = USEMASK_BIASCOR_COVTOT  
instead of  USEMASK = USEMASK_BIASCOR_COVTOT  + USEMASK_BIASCOR_ZMUERR

**Comment by RickKessler** [comment]
Change in function makeMap_sigmu_biasCor().
