### ISSUE TITLE
Lensed SN sim fails with seg fault

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#1088]
We have a debug directory set up in `$SNANA_DEBUG/Justin/lensing_sim`, use `sh FAIL_REPEAT_CL_0_Ia_mul_SNIaMODEL0-0001_28277.CMD` to reproduce the error below.

Here is the error:

Begin Generating Lightcurves.
  Found Max dN/dz * wgt = 6.158459e+02 at z =    2.968
         Finished generating        1 of 10 (CID=387340)
         Finished generating        2 of 10 (CID=45316)

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f4642af246c in waitpid () from /lib64/libc.so.6
#1  0x00007f4642a6ff62 in do_system () from /lib64/libc.so.6
#2  0x00007f4646f76e59 in TUnixSystem::StackTrace() () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#3  0x00007f4646f78a5c in TUnixSystem::DispatchSignals(ESignals) () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#4  <signal handler called>
#5  0x00000000004d2973 in get_ZTRUE_HOSTLIB ()
#6  0x00000000004dabaa in GEN_SNHOST_GALID ()
#7  0x00000000004db669 in GEN_SNHOST_DRIVER ()
#8  0x00000000004295b5 in gen_event_driver ()
#9  0x00000000004419f1 in main ()
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00000000004d2973 in get_ZTRUE_HOSTLIB ()
#6  0x00000000004dabaa in GEN_SNHOST_GALID ()
#7  0x00000000004db669 in GEN_SNHOST_DRIVER ()
#8  0x00000000004295b5 in gen_event_driver ()
#9  0x00000000004419f1 in main ()
===========================================================

**Comment by RickKessler** [comment]
Last September (2022), ZMAX_SNANA was increased to 10 but the max HOSTLIB redshift was mistakenly ignored because it was independently hard-wired to 4.1 (and we forgot about it). The fix here is to set ZMAX_HOSTLIB = ZMAX_SNANA to avoid such conflicts.
