### ISSUE TITLE
lcfit error Invalid IFILT_OBS= 42(L) 

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#1089]
see summary log at `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_PLASTICC/2_LCFIT/FIT_PLASTICC_SIM_IA_EXTERNAL/FAIL_SUMMARY.LOG`
note that the sim input to the lcfit is not exactly a straightforward output from pippin, so if you notice anything unusual it may be that

**Comment by RickKessler** [comment]
found corrupted sim data files, so unclear what caused error.
