### ISSUE TITLE
[FEATURE REQUEST] Allow different columns in the FITRES files passed to SALT2mu

### ISSUE THREAD

**Issue by Samreay** [RickKessler/SNANA#109]
The idea being that Ive allowing users to point to external biascor sims which have had every machine learning classification that we know of run on them. But someone might want to run with the data or a data-like-sim and only use SNN, or SNIRF, or NN. At the moment, they would have to either manually strip out the columns in the fitres files made by the other classifiers, or also run things they dont want to use in the end.

It would be great if there was an option to fill missing columns with NaN (such that if something tries to use them it dies) or if there was even a way to have separate columns in the data vs the biascor (though maybe this is already possible, I haven't checked!) The former is preferable (because then we wouldnt have to waste CPU running all the classifiers on the lowz sample only to throw the results out when we tell salt2mu that theyre spec confirmed)

An example would be using the DES biascor sim with classification here: 

`/scratch/midway2/rkessler/PIPPIN_OUTPUT/GLOBAL/5_MERGE/MERGE_D_DESSIMBIAS3YRIA_G10/output/PIP_GLOBAL_DESSIMBIAS3YRIA_G10/FITOPT000.FITRES` 

and the lowz bias correction sim without classification here: 

`/scratch/midway2/rkessler/PIPPIN_OUTPUT/GLOBAL/2_LCFIT/L_LOWZSIMBIAS_G10/output/PIP_GLOBAL_LOWZSIMBIAS_G10/FITOPT000.FITRES`

**Comment by RickKessler** [comment]
Done. See SNANA manual Sec 10.1
