### ISSUE TITLE
SALT2/3 trainopts are always required with submit_batch_jobs.sh

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#1090]
Training SALT2 or SALT3 models with submit batch jobs always required a trainopt to be specified - otherwise the job aborts with the message:

> FATAL ERROR ABORT :
>    object of type 'NoneType' has no len()

This is a problem as a default surface is always trained in addition to the trainopts; there is currently no way to just train a default surface without also submitting a superfluous trainopt job.

Example command to reproduce error:
`cd /project2/rkessler/SURVEYS/DES/USERS/gtaylor/SALT3_TRAINING/SALT3-FRAG-highmass`
`submit_batch_jobs.sh training_master_abort.input`

**Comment by RickKessler** [comment]
remove TRAINOPT key seems to work.
