### ISSUE TITLE
Lensing sim fails with no hostlib

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#1096]
I think we had this error before but it's back, I don't want to run the sim with a hostlib because I just want to force the redshifts to be what is in the lenslib and not be adjusted to whatever is in the hostlib and don't really care what the host looks like at this point. I get a segfault at lc generation when the hostlib is removed from the sim_roman.input file here: `$SNANA_DEBUG/Justin/lensing_sim`

**Comment by RickKessler** [comment]
add if(USE_HOSTLIB) in a few places so that code runs without crashing.
