### ISSUE TITLE
create_cov error "Cannot find biasCor sim-data folder UNKNOWN"

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#1098]
logs and scripts here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MISMATCH_TO_WFIT_WCOV/7_CREATE_COV/IA_ONLY_WRONGHOST/output/SCRIPTS_COVMAT`

**Comment by OmegaLambda1998** [comment]
I have the same issue here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_V_LAMBDACDM/7_CREATE_COV/COV_OMW_NO_OMPRI_5/output/SCRIPTS_COVMAT`

**Comment by RickKessler** [comment]
I think I fixed this already for Patrick; try again.
