### ISSUE TITLE
Using an older SNANA version possibly ignored?

### ISSUE THREAD

**Issue by RyanCamo** [RickKessler/SNANA#1100]
I ran 2 BBC jobs in the output directory:

 /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_SNANA

 One using (what I think is) an older version of SNANA. However when I look at the SUBMIT.INFO file after the job was completed I see:

```
Required info 
CWD:     /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_SNANA/6_BIASCOR
ARG_LIST:  BBCNOM.input --snana_dir /project2/rkessler/PRODUCTS/SNANA/SNANA_v11_04c
...
SNANA_VERSION:  v11_05b-25-g149a56d
```

```
Required info 
CWD:     /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC_SNANA/6_BIASCOR
ARG_LIST:  BBCNOM_new.input
....
SNANA_VERSION:  v11_05b-25-g149a56d
```

Im unsure if the printed SNANA_VERSION is wrong or the flag was ignored?

**Comment by RickKessler** [comment]
can you clarify how you ran the old SNANA version?

**Comment by RyanCamo** [comment]
I ran submit_batch_jobs.sh BBCNOM.input --snana_dir /project2/rkessler/PRODUCTS/SNANA/SNANA_v11_04c

**Comment by RickKessler** [comment]
I didn't test the SNANA-version printing for the situation above, so I'm not sure what it does in this case. To be sure about using older code, check the executables specified in your CPU*.CMD files.

**Comment by RyanCamo** [comment]
These files point the the right SNANA_DIR, thanks!
