### ISSUE TITLE
USESIM_REDSHIFT not a known command line argument

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#1101]
see logs here `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MISMATCH_TO_WFIT_WCOV/2_LCFIT/DESFITSYS_DESSIM_WRONGHOST_SERSIC/output/SPLIT_JOBS_LCFIT`

**Comment by RickKessler** [comment]
fixed parsing bug.
