### ISSUE TITLE
SALT2 Surface Training Error

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1104]
`/project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2`

```
1 Using explicit SALT2 training
  2  ERROR: missing /project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2/SALT2.MODEL000/salt2_template_0.dat
  3  ERROR: missing /project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2/SALT2.MODEL000/salt2_template_1.dat
  4  ERROR: missing /project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2/SALT2.MODEL000/salt2_color_correction.dat
  5 
  6  FIRST JOB FAILURE -> Create FAIL_SUMMARY.LOG
  7     *** FAIL   1 for TRAINOPT000.LOG   FAIL_MODE=UNKNOWN  found_zero=False
  8  ERROR: missing /project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2/SALT2.MODEL001/salt2_template_0.dat
  9  ERROR: missing /project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2/SALT2.MODEL001/salt2_template_1.dat
 10  ERROR: missing /project2/rkessler/SURVEYS/DES/USERS/parmstrong/SALT2/SALT2.MODEL001/salt2_color_correction.dat
 11     *** FAIL   2 for TRAINOPT001.LOG   FAIL_MODE=UNKNOWN  found_zero=False
 ```

**Comment by geotaylo** [comment]
Usually if there's something wrong in the SALT2/3 training stage, it's either a timeout error or you can find useful info in the TRANOPT00*.LOG file. In this case I can see that the training can't find the training sample - this may be my bad, you're pointing to the one in my user dir and I might have moved it when clearing files recently. I'll point you to a new one - are you wanting to use the old JLA training sample or the new K21 sample (which includes JLA data)?

**Comment by OmegaLambda1998** [comment]
Ahh gotcha, thanks Georgie.

I'm still using your T21 suite of 70 systematically perturbed surfaces, so whichever one that points to.

**Comment by geotaylo** [comment]
Ah yeah I had compressed it, try now
