### ISSUE TITLE
Duplicate host galaxies within ~500 days with HOSTLIB_MINDAYSEP_SAMEGAL  10000

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1105]
_Directory:_ /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/paleo/YSEtests
_Command:_ ./DEBUG_ONEHOST.sh
_Description:_ HOSTLIB_MINDAYSEP_SAMEGAL is set to 10,000 days, but galaxies are being repeated within that time in the simulation. This seems to only appear when the number of events is high enough (hence the debug simulates 50k). Look for HOSTGAL_OBJID: 7937650931, which is matched to e.g., both SN2586699 at MJD_TRIGGER: 59459.320 and SN2591443 at MJD_TRIGGER: 58956.266 (503 days earlier), as well as SN2597952, SN2613737, and SN2627683.

**Comment by alexandergagliano** [comment]
Problem is not fixed when lowering HOSTLIB_MINDAYSEP_SAMEGAL to 999, but _is_ fixed when decreasing to 500, even though the logic statement you refer to has been changed on Cori to 
if ( INPUTS.HOSTLIB_MINDAYSEP_SAMEGAL < 99999 ).

**Comment by RickKessler** [comment]
Forcing unique GALIDs would force lower-prob galaxies such that the overall distributions does not obey the WGTMAP.  So I will close this issue.
