### ISSUE TITLE
Adding extra filters in kcor file for host photometry alone 

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1109]
I need to run a set of simulations where the host galaxy has photometry in more passbands than the matched transient. If I modify the kcor file to include the additional passbands but don't simulate any transient observations in those bands, will they still show up in the output files for the galaxy?

**Comment by RickKessler** [comment]
yes, this works without any changes to the code.

**Comment by alexandergagliano** [comment]
Great, I'll close the issue as soon as I can confirm this on my end.

**Comment by alexandergagliano** [comment]
Looks good.
