### ISSUE TITLE
SERSIC_wsum error

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#111]
In `$SNANA_DEBUG/mvincenzi/DESSIMBIAS5YRIA_UVIR_G10` there are all the input files I used to run a SNe Ia simulation using `sim_SNmix`

One of the jobs aborted with this error:

```
 FATAL ERROR ABORT called by GEN_SNHOST_POS
   Could not find random Sersic profile for Ran0=0.999991
   SERSIC_wsum = 0.723110 0.999990 0.000000 0.000000

```
is this a problem of Sersic profiles?
In my HOSTLIB  ($DES_ROOT/simlibs/MICECAT_MVv5.HOSTLIB) I have two-component Sersic profiles (i.e. a0,a1,b0,b1,n0,n1,w0,w1)
Is there a problem with my weights? (I did check that w0+w1 always sum to one).

**Comment by RickKessler** [comment]
this was a subtle bug due to truncation of Sersic weights at E-5 level. Sum of weights was 0.99999, and a random number above this (and below 1) caused the abort. Fix is to re-normalize the Serisc weights. Fixed code will be updated on Midway later tonight (US, May 12).
