### ISSUE TITLE
kcor.exe asks for SURVEY parameter

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1110]
_Location:_ /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/CCARNN_resubmission
_Command:_ kcor.exe kcor_ZTF_AGAG.input
_Error:_ 

  Read user input file: kcor_ZTF_AGAG.input 

	 Found MAGSYSTEM 'AB' with offset =  -48.600 (INDX=1->1)
	 Could not find default /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/ZTF/ROOT/filters/20200919/ZPOFF.DAT => no ZP offsets. 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by storeFilterInfo
   Must associate SURVEY with filter ZTF-X
   Add  'SURVEY: <surveyList>' in kcor-input file

**Comment by RickKessler** [comment]
top of each filter file has
wave tput

Either remove it or put a hash
# wave tput

**Comment by alexandergagliano** [comment]
Looks like you're the owner of these files, and I don't have edit access. Could you change the permissions?

**Comment by alexandergagliano** [comment]
Header has been removed, and error persists.

**Comment by RickKessler** [comment]
"kcor.exe kcor_ZTF_AGAG.input" works fine now ... please clarify the problem.

**Comment by alexandergagliano** [comment]
I've added a ZTF survey to the header, and now the kcor file works.
