### ISSUE TITLE
BIASCOR_SALT2GAMMA_GRID: -0.06  0.06 not properly generating a grid of gamma

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1113]
I just noticed that for some reason the command:
   `BIASCOR_SALT2GAMMA_GRID: -0.06  0.06` is not properly generating a grid of gamma values in my DES 7D G10 biascor sim.

I created a test example here:` /project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/no_mass_grid`.
You can recreate the simulation running: `submit_batch_jobs.sh PIP_D5YR_SIM_V1_DESSIMBIAS_7D_G10.input`
The DUMP file in `/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/no_mass_grid/TEST_D5YR_SIM_V1_DESSIMBIAS_7D_G10/TEST_D5YR_SIM_V1_DESSIMBIAS_7D_G10.DUMP` has the info about the simulated values of alpha, beta, gamma and mass and shows that gamma is always + 0.06 mag:

```
VARNAMES:  CID GENTYPE SIM_alpha SIM_beta SALT2gammaDM LOGMASS_TRUE
SN:  2420 1 1.20000e-01 3.50000e+00 6.00000e-02 1.04150e+01
SN:  1915 1 1.20000e-01 2.70000e+00 6.00000e-02 1.12850e+01
SN:  6944 1 2.00000e-01 3.50000e+00 6.00000e-02 1.07280e+01
SN:  459 1 1.20000e-01 3.50000e+00 6.00000e-02 1.06150e+01
SN:  619 1 2.00000e-01 3.50000e+00 6.00000e-02 1.01020e+01
SN:  6913 1 1.20000e-01 2.70000e+00 6.00000e-02 8.03400e+00

```

**Comment by RickKessler** [comment]
fixed a few functions that defined "int GALID" instead of "long long int GALID" ; proper cast for GALID fixed the problem.
