### ISSUE TITLE
Some changes in comment handling in BBC is broken

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1117]
I have a BBC input file that was perfectly working yesterday but is crashing today.
I think the problem is that SALT2mu doesnt like the CONFIG: block before #END_YAML

In `/project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/pippin_output/D5YR_SMP_V1/6_BIASCOR/P21NOM_SIGINT_COLOR/outputReject_ITER1/SCRIPTS_BBCFIT`

Broken example:
`TEST_wCOMMENTS.CMD`
Working example (I removed the entire block of text from CONFIG: ..... #END_YAML):
`TEST_NOCOMMENT.CMD` and everything works.

**Comment by RickKessler** [comment]
Fixed that bug earlier today.
