### ISSUE TITLE
Crazy SIGMA values in SNIa SALT3 model

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1121]
_Directory:_ /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/agaglian/CCARNN_resubmission/SIMLOGS_AGAG_wHost_ZTF10x_Ia
_Command:_ ./testSmear.sh
_Error Message:_ 

 ****************************************************************** 
   init_modelSmear: init intrinsic SN smearing with model=G10  
	 Smear-mode: complete wavelength dependence. 
	 ISMODEL = SALT3
  Read SALT2-smear file: 
  '/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/paleo/YSEtests/YSE_MODELS/SALT3.K21/salt3_color_dispersion.dat' 
    Read 901 SALT2-Smear values from lambda=  2000 to  11000 
    SIGCOH = 0.106
    SMEAR *= [ 1 +  0.000000*(LAM-2157)]   LAM < 2157 
    SMEAR *= [ 1 +  0.000108*(LAM-2157)]   LAM > 2157 
	 Set LAM-node  0 at  2000.0 A : SIGMA= 3.000  <== flagged as crazy value
	 Set LAM-node  1 at  2800.0 A : SIGMA= 0.227  
	 Set LAM-node  2 at  3600.0 A : SIGMA= 0.039  
	 Set LAM-node  3 at  4400.0 A : SIGMA= 0.017  
	 Set LAM-node  4 at  5200.0 A : SIGMA= 0.014  
	 Set LAM-node  5 at  6000.0 A : SIGMA= 0.019  
	 Set LAM-node  6 at  6800.0 A : SIGMA= 0.030  
	 Set LAM-node  7 at  7600.0 A : SIGMA= 0.050  
	 Set LAM-node  8 at  8400.0 A : SIGMA= 0.064  
	 Set LAM-node  9 at  9200.0 A : SIGMA= 0.051  
	 Set LAM-node 10 at 10000.0 A : SIGMA= 0.021  
	 Set LAM-node 11 at 10800.0 A : SIGMA= 0.003  
	 Set LAM-node 12 at 11000.0 A : SIGMA= 0.002  

   `|```````|`    
   < | o\ /o   |>    
    |    ' ; '     |     
    |     ___   |        ABORT program on Fatal Error. 
    |     |' '|    |     
    |   `---'   |     
    \_______/    

 FATAL ERROR ABORT called by init_genSmear_SALT2
   Found 1 crazy SIGMA values
   Either trim rest-frame wave range or fix model dispersion

**Comment by RickKessler** [comment]
This crazy sigma test was recently added to prevent crazyFlux abort that is hard to trace. For SALT3.K21 model I added
    COLOR_DISP_MAX: 2
in SALT3.INFO file, but I can't run your test job because HOSTLIB does not have group-read permission.

**Comment by alexandergagliano** [comment]
HOSTLIB Permissions changed.

**Comment by alexandergagliano** [comment]
Fixed.
