### ISSUE TITLE
Segmentation Violation when running SNANA

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1122]
Hi Rick, 

I've been trying to generate some light curves with settings that were successfully run with 3 months ago, but I get a "segmentation violation" - were there any big updates since then? 

Here is the log file - /scratch/midway2/rkessler/PIPPIN_OUTPUT/JASON_MISMATCH_TO_WFIT_PLUS_LOWZ/1_SIM/DESSIM_REGULAR_PLUS_LOWZ/PIP_JASON_MISMATCH_TO_WFIT_PLUS_LOWZ_DESSIM_REGULAR_PLUS_LOWZ.LOG

Thanks!
Jason

**Comment by RickKessler** [comment]
If it worked 3 months ago, then I wouldn't trust it. It crashes because of this key,
    DNDZ: POWERLAW2 2.27E-5 1.7 ##Frohmaier 2018
that is missing the min and zmax arguments; see manual.

**Comment by jasonlee17** [comment]
Note: The key "POWERLAW" doesn't need redshift range to be specified but "POWERLAW2" does.
