### ISSUE TITLE
Add HOSTLIB-SIMLIB matching 

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1127]
Hi,

Following our discussion : 

We can add HOSTLIB-SIMLIB coordinates matching by adding a column "GROUPID" in the HOSTLIB and a key "HOST_GROUPID" in the SIMLIB such that host are randomly selected for each SN in a LIBID entry from the matching HOST groups.

The HOST_GROUPID key could accept multiple groups given by comma separated id, for example: 
`HOST_GROUPID: 1, 2`
will random select a host between those that lie in group 1 or 2

**Comment by RickKessler** [comment]
Please setup example following snana manual
4.22.17 Correlating SIMLIB and HOSTLIB with GROUPID
The code is written but not tested, so a test input is needed for debugging.

**Comment by bastiencarreres** [comment]
Hi,
I have setup an example following the SNANA manual 4.22.17, for precision I also used:
`HOSTLIB_MSKOPT: 536 # Use Host coord (+8), adjust SN redshift (+16), and peculiar velocity (+512) `

The `GROUPID`  feature seems to work on my side! Thank you!

**Comment by RickKessler** [comment]
let's keep this issue open until new GROUPID  feature is working

**Comment by RickKessler** [comment]
wow, I can't believe it worked the first time. This is quite rare.
