### ISSUE TITLE
Add the option to use HOSTLIB ZTRUE as SNe ZCMB

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1129]
Hi,

I noticed that when using `HOSTLIB_MSKOPT += 16` (adjust the SN redshift, SN mags, and μ to galaxy redshift) the redshift of the SN is matched to the host redshift such as ZHEL = ZTRUE. 

Can we add an option such as HOSTLIB ZTRUE is used as SN's ZCMB (ZCMB = ZTRUE) and then the simulation can add the CMB motion if needed?

**Comment by RickKessler** [comment]
I think the safest implementation is to allow an optional ZTRUE_CMB column in the HOSTLIB, and then internally the sim can construct the Hello ZTRUE column so that all current code functions the same way.

**Comment by bastiencarreres** [comment]
I've tested the implementation and using a HOSTLIB with ZTRUE_CMB column but without ZTRUE. And with `HOSTLIB_MSKOPT: 536`. I get this error message:

**Comment by bastiencarreres** [comment]
I've tested the implementation and using a HOSTLIB with ZTRUE_CMB column but without ZTRUE. And with `HOSTLIB_MSKOPT: 536`. I get this error message:

   ```
`|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by read_head_HOSTLIB
   Could not find required HOSTLIB var 'ZTRUE' (IVAR_STORE=1)
   Check HOSTLIB VARNAMES, WGTMAP & HOSTLIB_STOREPAR key.
```
That seems to come from a check between L2297 and L2324 of `sntools_host.c`

**Comment by RickKessler** [comment]
please provide command to reproduce above abort.

**Comment by bastiencarreres** [comment]
I've setup a directory with the configuration files at NERSC to reproduce the abort error, files are here:
`/global/cfs/cdirs/desc-sn/users/bastienc/DUKE_work/SNANA_vel/ERROR_TEST`

The HOSTLIB file does contain a ZTRUE_CMB column but no ZTRUE column.

`snlc_sim.exe sim_LOWZ_ERROR_TEST.input` reproduce the above abort.

**Comment by bastiencarreres** [comment]
Worked on tests
