### ISSUE TITLE
Computation of DLMU with peculiar velocities

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1130]
Hi, 

It seems that the behavior of SNANA relative to DLMU computation changes depending on if we use host or no:

Without host, ZHEL seems to be updated such as: 1 + ZHEL = (1 + ZCMB) * (1 + VPEC/C) * (1 + Z_CMB_TO_HEL) and then DL seems to be evaluated as DL = (1 + ZHEL) * (1 + Z_CMB_TO_HEL) * COMOV_DIST(ZCMB)) with VPEC contains in ZHEL.

However when using host, updates of DLMU in sntools_hos (maybe in TRANSFER_SNHOST_REDSHIFT) seems to throw away the velocity from DLMU computation (even when using random vel not provided by the HOSTLIB). 

Since the two ways do not seem completely correct (even if peculiar velocity effect on DLMU is really small) maybe DLMU computation can be a function of VPEC as:

```
double gen_dLmag(double zCMB, double zHEL, double VPEC, double GLON, double GLAT ) {

  // Returns lumi-distance mag with input cosmology
  // Note that INPUTS.H0 ~ 70 km/s/Mpc, and H0 -> ~2E-18

  double mu ;
  if ( zCMB <= 1.0E-10 ) { return 0.0 ; }  // avoid inf, May 2013

  if ( INPUTS.ANISOTROPY_INFO.USE_FLAG ) {
    INPUTS.ANISOTROPY_INFO.GLON = GLON;
    INPUTS.ANISOTROPY_INFO.GLAT = GLAT;
  }

  mu = dLmag (zCMB, zHEL, &INPUTS.HzFUN_INFO, &INPUTS.ANISOTROPY_INFO );

 // add peculiar velocity effect
  mu += 10 * log10(1 + VPEC / LIGHT_km)

  return(mu) ;

} // end of gen_dLmag
```
Where zHEL in this example does not contains VPEC

**Comment by RickKessler** [comment]
Pec. velocity should only impact measured zHEL (not true DLMU). I think the treatment in sntools_host is correct (follow zPEC), but there is a bug in snlc_sim.c because gen_distanceMag(...) uses zHEL with vpec instead of true zHEL.

**Comment by bastiencarreres** [comment]
True DLMU already contains our peculiar velocity since the difference between zHEL and zCMB is due to our own peculiar motion relative to CMB. In the same way maybe we could include host peculiar velocity effect from relativistic beaming as an effective DLMU separate from true DLMU:

DLMU = DLMU_TRUE + 10 * log10(1 + z)  ?

**Comment by RickKessler** [comment]
I rechecked Davis 2012 paper, and indeed I got my wires crossed in previous comment. Note that dl = ( 1.0 + zHEL ) * rz  (sntools_cosmology.c) where zHEL includes zPec. So the fix is needed in sntools_host.c when transferring coordinates.

**Comment by bastiencarreres** [comment]
Hi,
I think it's not exactly DL = (1+zHEL) * rz with zHEL including vpec, because relativistic beaming add a (1 + v/c)^2 to DL (eq 18 https://arxiv.org/pdf/1012.2912.pdf). Hence if zHEL already contains the peculiar velocity DL = (1 + zHEL) * (1 + v/c) rz = (1 + zCMB) * (1+ zOURPV)  * (1 + zPV) where zOURPV is our velocity from CMB dipole.

**Comment by bastiencarreres** [comment]
Hi, any update on this issue?

**Comment by RickKessler** [comment]
added vPEC input arg to dLmag() and gen_distanceMag() functions
