### ISSUE TITLE
Problem with MERGING at the LCFIT stage

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1142]
In this folder: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_SIM_V2/2_LCFIT/D3_DESSIMBIAS_4D_P21SVA/output/SPLIT_JOBS_LCFIT
`
I'm trying to rerun biascor simulations but something crashes at the merging stage.
I tried to reproduce the error creating the executable file  `command.cmd`

You can see the log file produced at: `sntable_append_MERGE_PIP_D5YR_SIM_V2_DESSIMBIAS_4D_P21SVA_FITOPT000.log`

This is the error:
```
******************************************************************
   Begin Reading Fitres Files.


 --------------------- ADD_FITRES -------------------------
   OPEN_TEXTFILE: MERGE_PIP_D5YR_SIM_V2_DESSIMBIAS_4D_P21SVA_FITOPT000.FITRES

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by SNTABLE_READPREP_TEXT
   End of file reached without finding any HEADER keys.
   Check text file.
```

**Comment by RickKessler** [comment]
Short answer is that the 4GB memory needs to be increased to 8GB for biasCor LCFIT jobs.

I manually re-ran the merge process,
submit_batch_jobs.sh FIT_PIP_D5YR_SIM_V2_DESSIMBIAS_4D_P21SVA.nml --merge_reset
submit_batch_jobs.sh FIT_PIP_D5YR_SIM_V2_DESSIMBIAS_4D_P21SVA.nml -M

and it worked fine ... hopefully pippin can use it. I ran 'top' during the merge process and noticed one of the merge tasks slightly exceeding 4GB memory.
