### ISSUE TITLE
How to get the true SED

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1145]
Hi Rick, I had a question about getting the SEDs for the simulated SNe Ia.

I found in the manual that there's a "TAKE_SPECTRUM" option which can be used to generate spectra, but I also found that I could get the rest-frame spectrum corresponding to the SALT2 model I am using to generate the simulations. It would be more convenient if I could use the spectrum from the SALT2 model but perhaps that's not what I want to do? 

Maybe there's a completely different way to do this.

**Comment by RickKessler** [comment]
Sorry for the delay, but I realized that the LCFIT code has option to store best-fit SALT2 model spectrum, not the simulation. We can add a new sim-code feature to write out the SALT2 SED.

**Comment by RickKessler** [comment]
See new sim-input feature as described in the manual:

<img width="832" alt="write_SEDMODEL" src="https://github.com/RickKessler/SNANA/assets/24592476/ca88f82c-82e8-4958-b37f-770d7833d9c4">
