### ISSUE TITLE
Need more TAKE_SPECTRUM for Roman prism observations

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1146]
There is a hard coded limit of 300 TAKE_SPECTRUM keys allowed. I am trying to simulate a Roman survey that will need more. Error log can be found at `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/SN/LOGS/SIMnorm_PIP_PIPPIN_ROMAN_TRANS_SN_SNIaMODEL0.LOG`.  

```
Found error in file /scratch/midway2/rkessler/PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/SN/LOGS/SIMnorm_PIP_PIPPIN_ROMAN_TRANS_SN_SNIaMODEL0.LOG, excerpt below
        Excerpt:     FATAL ERROR ABORT called by expand_TAKE_SPECTRUM_MJD
        Excerpt:       402 TAKE_SPECTRUM keys exceeds bound of 300
        Excerpt:       Check MXPEREVT_TAKE_SPECTRUM in snlc_sim.h
```

**Comment by RickKessler** [comment]
just increased MXSPECTRA from 300 to 500 ... try again.

**Comment by benjaminrose** [comment]
Thanks @RickKessler, this worked for that model. Regretfully, this was not the largest value (I messed up). It looks like some models are producing 548 TAKE_SPECTRUM keys. Additionally, this is with `NGEN_UNIT: 0.1`, will the number of keys dramatically increase when I run full sims/bias cor sims? Thanks.

**Comment by RickKessler** [comment]
I doubt that NGEN_UNIT affects number of spectra, but please run a test to be sure.

**Comment by benjaminrose** [comment]
Yeah, should have done that. Just ran it now with NGEN_UNIT of 1 and still got 548 TAKE_SPECTRUM.
