### ISSUE TITLE
Subtle SALT2mu bug using COVADD

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#1154]
For COVADD option (BBC method using SALT2mu.exe code), the bias-correction was applied before sigInt map was made and thus 1/MUERR^2 weight was incorrect. This is essentially a chicken and egg problem; computing COVADD term needs b iasCor, but biasCor needs COVADD for 1/MUERR^2 weight. The COVSCALE method doesn't have this problem because SIGINT is computed from SNRMAX>60 events and does not need biasCor map.

**Comment by RickKessler** [comment]
Resolution is to use the original COVSCALE method to get initial 1/MUERR^2 weight. Use this approx weight to create COVADD map and zero out SIGINT used for scale.

**Comment by maria-vincenzi** [comment]
This is an order of operation bug.
In slide 5/6/7 of these [GOODLE SLIDES](https://docs.google.com/presentation/d/1ynHsMg0oFswleKMQPQUvmW772ZPc-nxsi9HOGa8f4nE/edit?usp=sharing) we talk about why things were different and how we fixed the problem
