### ISSUE TITLE
Error while running simulation

### ISSUE THREAD

**Issue by simran2296** [RickKessler/SNANA#1161]
I am using SNANA for simulating SNe and KNe for modeling a DECam search and getting the following SNANA error at the simulation stage. 
` ******************************************************************
   SIMLIB_prepGlobalHeader
         SIMLIB Survey    : DES

# ================================================
  PRE-ABORT DUMP from function splitString :
  string to split: '-30.24,-70.75,2200'
  split separator: ','

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by splitString
   Nsplit = 3  exceeds bound MXsplit=2
   called by function  parse_geoSURVEYDEF`
   

SNANA code command:

`snana.exe NOFILE PRIVATE_DATA_PATH LightCurvesReal VERSION_PHOTOMETRY LightCurvesReal VERSION_REFORMAT_FITS LightCurvesReal_1 > LightCurvesReal/convert_dat_to_fits.log`

**Comment by RickKessler** [comment]
problem was that EUPS version at FNAL was still buggy, but current version here on GitHub is ok.
