### ISSUE TITLE
Mismatch between NDAY for SIMSED model

### ISSUE THREAD

**Issue by berniez** [RickKessler/SNANA#1164]
Working on create my own models, when trying to simulate light curves from modeled SEDs, this error appears

Read  NDAY from largest file  SED  from : 
    /opt/ohpc/pub/apps/SNANA/sndata/models/SIMSED/SIMSED.BBH_merger_Juan/[SED_bbh_mdot0.2_dSMBH2400_MBBH120.0_vk1500.0.txt](https://github.com/RickKessler/SNANA/files/11749465/SED_bbh_mdot0.2_dSMBH2400_MBBH120.0_vk1500.0.txt)
  malloc_FLUXTABLE_SEDMODEL : allocate   0.77 Mb of memory for integral-flux tables. 
	 Table bins include   8 DAYs. 
	 Table bins include   4 FILTERs. 
	 Table bins include 388 SEDs. 
	 Table bins include  10 log10(Z): 0.03872 <= Z <= 0.12138 .
		 ZTABLE[  1] =  0.03872   (LOGZ=-1.4121)
		 ZTABLE[  2] =  0.04396   (LOGZ=-1.3570)
		 ZTABLE[  3] =  0.04991   (LOGZ=-1.3018)
		 ZTABLE[  7] =  0.08293   (LOGZ=-1.0813)
		 ZTABLE[  8] =  0.09416   (LOGZ=-1.0261)
		 ZTABLE[  9] =  0.10691   (LOGZ=-0.9710)
		 ZTABLE[ 10] =  0.12138   (LOGZ=-0.9158)
		 Zero entire SEDMODEL flux table (192555 entries). 

# - - - - - - - - - - - - - - - - - - - - - - - - - 
  Read  (ised=1/388)  SED  from : 
    /opt/ohpc/pub/apps/SNANA/sndata/models/SIMSED/SIMSED.BBH_merger_Juan/SED_bbh_mdot0.01_dSMBH800_MBBH50.0_vk500.0.SED 

 FATAL ERROR ABORT called by init_genmag_SIMSED
   NDAY=10 exceeds expected bound of 8
   Check DAY bins for SED.

All SED files have 10 days in increasing order. I'm running it on a CENT OS 7 cluster in Brazil, in which I had no part in the installation process. I'm just a user. 

Attached is my SIM INPUT file and the file that SNANA is reading in order to get NDAY. 
[model SED](https://github.com/RickKessler/SNANA/files/11749472/SED_bbh_mdot0.2_dSMBH2400_MBBH120.0_vk1500.0.txt)
[input file](https://github.com/RickKessler/SNANA/files/11749475/DEcam_BBH_test.txt)

Thanks

**Comment by RickKessler** [comment]
can you send your SED.INFO file, or a tar file of your SIMSED directory?

**Comment by RickKessler** [comment]
after fixing GENRANGE_PEAKMJD range to overlap the SIMLIB file MJD range, I was able to run snlc_sim.exe with your input file.

**Comment by berniez** [comment]
Thanks for the answer. 
If I understood correctly, the GENRANGE_PEAKMJD should encompass the MJD range in the SIMLIB file. Either way, I attach here a tar file with my SIMSED directory. I still have the same issue no matter how I set the GENRANGE_PEAKMJD (small overlap with the SIMLIB, totally encompassing SIMLIB, totally encompassed by SIMLIB)

[simsed dir](https://github.com/RickKessler/SNANA/files/11792968/model.tar.gz)

Thank you very much for the help

**Comment by RickKessler** [comment]
your SED DAY ranges are quite different. The first SED (SED_bbh_mdot0.01_dSMBH800_MBBH50.0_vk500.0.SED) goes from 51 to 89 days, while SED_bbh_mdot0.2_dSMBH2400_MBBH50.0_vk1100.0.SED  day range is from 1565 to 4148. The SIMSED models were intended to have similar day ranges, so there is likely a bug or rule violation with the vastly different day ranges in your models. I will check further to see if there is an easy fix.

**Comment by RickKessler** [comment]
I updated the abort message to print the acceptable DAYrange of -500 to 1500 (see screen shot) ... the SED above has DAY range above 1565 and is thus ignored. Please revise your SED day ranges to fit within the limits.

<img width="857" alt="abort_message" src="https://github.com/RickKessler/SNANA/assets/24592476/086273f8-31cc-4f17-9d23-6aef63ca06cd">

**Comment by RickKessler** [comment]
closing issue, but please re-open if problems persist after fixing DAY range in the SED time series.
