### ISSUE TITLE
Simulation produces light curve only when format is TEXT

### ISSUE THREAD

**Issue by berniez** [RickKessler/SNANA#1165]
Trying to use SNANA to simulate light curves with a SIMSED model. We only get outputs if the format is set to txt, while in FITS all fields are either -777 or blank. Furthermore, in text mode, only 1 simulation is return even though NGENTOT_LC is set to higher. Attached is one of the SED time series and the input sim file.

[sim file](https://github.com/RickKessler/SNANA/files/11775852/DEcam_BBH_test.txt)

[time series SED](https://github.com/RickKessler/SNANA/files/11775856/SED_bbh_mdot0.1_dSMBH800_MBBH100.0_vk800.0.txt)

**Comment by RickKessler** [comment]
This sim-input key
SIMSED_GRIDONLY:   SEQUENTIAL
is an instruction to process each SED time series only once (see manual). Since there is only 1 SED time-series, only 1 event is generated.
