### ISSUE TITLE
Potential issue with HOSTLIB_MSKOPT: 8

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#117]
Within 
/project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/

I am trying to generate SN with an RA = DEC= 0. The file 'test_catalog.csv'  has RA = DEC = 0, and I have launched "SIM.input" interactively, then fit it with "FIT.nml". The resultant sntable_dump file has some very suspicious RA/DEC values, and none of them are 0.

**Comment by RickKessler** [comment]
need to include Sersic profile to move SN near host.
