### ISSUE TITLE
SNOOPY fits throwing "undefined rest-frame model filters" error

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1172]
I am working with Dan Scolnic on trying to fit some light curves with SNooPy, but none of the snoopy fits are working. Even trying nml files that worked in the past no longer work.

The error can be reproduced in `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3` by calling `snlc_fit.exe SNOOPY_2007on.nml`

Dave Jones tested further and commented that an earlier version of SNANA worked. He tried `v11_03c` and it ran successfully.

The error thrown is this:

```
 ****************************************************************** 
   init_genmag_snoopy for BVugriYJH  

  Begin fits_read_SNGRID for 
  /project2/rkessler/SURVEYS/DES/USERS/epeterson3/dehvils/models/SNOOPY/SNooPy_test.fits 
    read fits keyword IVERSION = 1 
    read fits keyword SURVEY = LOWZ 
    read fits keyword GENMODEL = SNooPy_v2.5.2 
    read fits keyword I2LCPACK = 1000.000000 
    read fits keyword FILTERS = BVugriYJH 
          LOGZ has   1 bins from    -8.0000 to    -8.0000  (ILCOFF=1)
            AV has   1 bins from     0.0000 to     0.0000  (ILCOFF=1)
            RV has   1 bins from     2.2000 to     2.2000  (ILCOFF=1)
       STRETCH has 131 bins from     0.7000 to     1.3000  (ILCOFF=1)
        FILTER has   9 bins from     0.0000 to     8.0000  (ILCOFF=131)
         TREST has  91 bins from   -20.0000 to    70.0000  (ILCOFF=1179)
    Read 131 I2LCMAG pointers: 1 824 1647 .... 106991 
	 read 107813  I2LCMAG  values for GRID 
	 read 107813  I2LCERR  values for GRID 
  
  ######################################################## 
    INIT_PRIOR_SIMEFF: sim-efficiency NOT used for PRIOR.       
  ######################################################## 
  

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by FITPAR_INI
     7 undefined rest-frame model filters (BVugriY)
   Check KCOR/CALIB input file for rest-frame filters

```

**Comment by RickKessler** [comment]
In snlc_fit.car, I had put in this abort that isn't really necessary:

c abort if more than 3 model filters are not defined.
c This is bit arbitrary, but it allows ignoring some
c model-wavelength ranges such as the IR.

I think the logic was to catch silly user mistakes. To allow fitting only two (YH) of the nine CSP bands, this abort trap has been removed. Also fixed a harmless print bug that used the wrong kcor/calib index to print the kcor-symbol (e.g., K_JH) to stdout.
