### ISSUE TITLE
Negative RAs

### ISSUE THREAD

**Issue by rknop** [RickKessler/SNANA#1174]
In the first ELAsTiCC set, there were 1670 objects with RA less than 0.  All of them were between -0.328 and 0.

I've attached a file with the object IDs and the RAs.

(diaObjectId is SNID.)

[objs.txt](https://github.com/RickKessler/SNANA/files/11958819/objs.txt)

**Comment by RickKessler** [comment]
fixed snlc_sim.c so that sim-input "GENRANGE_RA: 0 360" enforces the RA range if smeared RA goes outside. For next ELASTICC sim, the slightly negative RA values will be 359.xyz.
