### ISSUE TITLE
Hostgal_ra and hostgal_dec values

### ISSUE THREAD

**Issue by AnomandarisPurake** [RickKessler/SNANA#118]
Given a HOSTLIB file, in the output HEAD.FITS file, the "hostgal_ra" and "hostgal_dec" columns appear to be offset by the same amount but the opposite sign as the "ra" and "dec" columns from the values of the corresponding host galaxy provided in the host library. 

In addition, some of the "hostgal_ra" and "hostgal_dec" pairs have the value of -999.

The input is snlc_sim.exe /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/SIMGEN_WFIRST_SALT2_Specz_candels.INPUT

The input host libraries are /project2/rkessler/SURVEYS/WFIRST/USERS/kxw/supernova/Test.HOSTLIB
which consists of 100 galaxies at position 0,0
Output is at /project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/RAH/RAH_HEAD.FITS

And a second host library
/project2/rkessler/SURVEYS/WFIRST/USERS/kxw/supernova/Akari_Hosts.HOSTLIB
which consists of 1459214 galaxies distributed realistically
Output is at /scratch/midway2/rkessler/SNDATA_ROOT/SIM/Deep_Spec_KXW/SIMULATEED_SPEC_SURVEY_KXW_SNIa-0001_HEAD.FITS.gz
(If working with fits files is easier than HOSTLIB, the file
/project2/rkessler/SURVEYS/WFIRST/USERS/kxw/supernova/fiducial_lensing_galaxia_truth_gal.fits contains the same information as Akari_Hosts.HOSTLIB except the RA and Dec are in radians instead of degrees)

**Comment by RickKessler** [comment]
Dear AnomandarisPurake; since you have a Midway account, please fill your info in /project2/rkessler/SURVEYS/AAA_USERS.LIST.

**Comment by RickKessler** [comment]
fixed bug, so hopefully now the Galaxy RA,DEC is correct. Your SIMGEN input file aborted because of the redshift tolerance, so I had to set HOSTLIB_DZTOL: 0.15 0.4 0 ; I suggest making a denser HOSTLIB that doesn't leave such large ZTRUE gaps. You can also pass HOSTLIB RA_GAL and DEC_GAL to SIMGEN-dump file using "HOSTLIB_STORE: RA_GAL,DEC_GAL"
