### ISSUE TITLE
LC fitting path error

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1185]
On trying to do an LC fitting, I kept on running into an error. The error message is: FATAL ERROR ABORT : 
   stat: path should be string, bytes, os.PathLike or integer, not list
   Crashed while preparing batch jobs.
   Check Traceback
Inside the folder path  /project2/rkessler/PRODUCTS/SNANA_DEBUG/Keneanumba/LC_Fitting, to reproduce the error, run the command: submit_batch_jobs.sh FIT_LSST+Roman.nml .Thank you.

**Comment by RickKessler** [comment]
comment fields such as   
     #This files tells the filters that the surveys have
work with python, but it breaks fortran nameList input. The fortran comment character is exclamation (!), so I replaced above with
    ! This files tells the filters that the surveys have

I also removed a few tabs from the input since tabs can result in pathological behavior for both fortran, C and python readers.
