### ISSUE TITLE
Option to extend wavelengths (to lower wavelengths) for ideal spectrograph

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1189]
Hi Rick, 

As discussed earlier, let me know if there's a way to have the ideal spectrograph take measurements at lower lambda. 

Thanks!
Jason

**Comment by RickKessler** [comment]
true SED wavelength range is now 
* min of blue filter edge or blue SED-model edge
* max of red filter edge or red SED-model edge

**Comment by RickKessler** [comment]
Add another optional sim-input key LAMRANGE_SED_TRUE,

<img width="859" alt="manual_SED_TRUE" src="https://github.com/RickKessler/SNANA/assets/24592476/1fd13148-9288-4322-b409-17c5ca0b964b">
