### ISSUE TITLE
Lensing parameters are passed through for text output, not fits output

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#119]
I've got a working example on Midway in `$SNANA_DEBUG/jpierel/wfirst_lensing_cc`, which runs interactively with the input file: `simulation/SIMGEN_WFIRST_NONIA_Photozv2.INPUT` from the base directory (i.e. run `snlc_sim.exe simulation/SIMGEN_WFIRST_NONIA_Photozv2.INPUT`)

It's currently set to `FORMAT_MASK: 32` for fits mode and you should see that the output files just have 0's for every lensing parameter, but if you change it to `FORMAT_MASK:2` the correct parameters are passed through. The various parameters are called `SIM_STRONGLENS...`

**Comment by RickKessler** [comment]
fixed bug writing SIM_STRONGLENS_XXX params to FITS file.
