### ISSUE TITLE
`'' is not a valid genmag-model` with `GENMODEL path/to/salt/model`

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1192]
Relavent log files:

.LOG: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS/SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG
_KILL.LOG: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_KILL.LOG
.input: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/PIP_PA_DESFORWARDMODEL_DATASIM_G10_1.input

---

<details>
<summary>Error in .LOG</summary>

 Program class : Simulation 

 Submit host;  midway2-login1
 Program name: snlc_sim.exe
	Batch command:    sbatch
	Batch template:   /project2/rkessler/PRODUCTS/SNANA/SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE
	Batch n_core:     50
 Create output dir:
   /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS
	Copy 3 sim-input files to LOGS

 Write FAIL to done stamp file: 
	ALL.DONE

 Write FAIL to done stamp file: 
	FINISHED.DONE
['Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;', 'LOG created from sim normalization commands :', '  cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \\', '  snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \\', '  INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \\', '  > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \\']
NoneType: None

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \
     snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \
     INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \
     > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 398, in <module>
    program.submit_prepare_driver()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 208, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 611, in sim_prep_NGENTOT_LC
    ngentmp = self.get_ngentot_from_rate(iver,ifile)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 800, in get_ngentot_from_rate
    self.log_assert(False,msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 2486, in log_assert
    util.log_assert(condition, msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 1223, in log_assert
    assert condition, msg_abort_face
AssertionError: 

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \
     snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \
     INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \
     > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \

 Write FAIL to done stamp file: 
	ALL.DONE

 Write FAIL to done stamp file: 
	FINISHED.DONE
[AssertionError("\n\n\n   `|```````|`    \n   <| o\\ /o |>   \n    | ' ; ' |     \n    |  ___  |     ABORT submit on Fatal Error. \n    | |' '| |     \n    | `---' |     \n    \\_______/    \n\nFATAL ERROR ABORT : \n   Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;\n   LOG created from sim normalization commands :\n     cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \\\n     snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \\\n     INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \\\n     > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \\"), 'Crashed while preparing batch jobs.', 'Check Traceback']
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 398, in <module>
    program.submit_prepare_driver()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 208, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 611, in sim_prep_NGENTOT_LC
    ngentmp = self.get_ngentot_from_rate(iver,ifile)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 800, in get_ngentot_from_rate
    self.log_assert(False,msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 2486, in log_assert
    util.log_assert(condition, msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 1223, in log_assert
    assert condition, msg_abort_face
AssertionError: 

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \
     snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \
     INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \
     > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \

 sim_prep_GENOPT(PIP_PA_DESFORWARDMODEL_DATASIM_G10_1) 
	GENOPT(sn_ia_salt2_g10_des3yr.input): GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/     
  FORMAT_MASK = 48 (<built-in function format>) 
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 398, in <module>
    program.submit_prepare_driver()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 208, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 611, in sim_prep_NGENTOT_LC
    ngentmp = self.get_ngentot_from_rate(iver,ifile) 
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 800, in get_ngentot_from_rate
    self.log_assert(False,msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 2486, in log_assert
    util.log_assert(condition, msgerr)        
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 1223, in log_assert
    assert condition, msg_abort_face
AssertionError: 

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \
     snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \
     INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \
     > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 415, in <module>
    program.log_assert(False, msg )
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 2486, in log_assert
    util.log_assert(condition, msgerr)        
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 1223, in log_assert
    assert condition, msg_abort_face
AssertionError: 

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS ;  \
     snlc_sim.exe sn_ia_salt2_g10_des3yr.input  \
     INIT_ONLY 1 GENMODEL /home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/       PATH_USER_INPUT /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1   \
     > SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_1_SNIaMODEL0.LOG \
   Crashed while preparing batch jobs.
   Check Traceback

</details>

---

<details>
<summary>Error in _KILL.LOG</summary>

 Program class : Simulation 

 Submit host;  midway2-login1
 Program name: snlc_sim.exe
	Batch command:    sbatch
	Batch template:   /project2/rkessler/PRODUCTS/SNANA/SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE
	Batch n_core:     50
['Cannot find the input yaml file:\n   /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS/SUBMIT.INFO']
NoneType: None
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 388, in <module>
    program.kill_jobs()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 388, in kill_jobs
    self.kill_sbatch_jobs()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_base.py", line 428, in kill_sbatch_jobs
    submit_info_yaml = util.extract_yaml(INFO_PATHFILE,None,None)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 1233, in extract_yaml
    log_assert(exist,msgerr)
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_util.py", line 1223, in log_assert
    assert condition, msg_abort_face
AssertionError: 

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

FATAL ERROR ABORT : 
   Cannot find the input yaml file:
   /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_1/LOGS/SUBMIT.INFO

</details>

---

<details>
<summary>Input file</summary>

CONFIG:
  BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 50
  BATCH_MEM: 8000
  DONE_STAMP: FINISHED.DONE
  FORMAT_MASK: 48
  GENPREFIX: PIP_PA_DESFORWARDMODEL_DA69d11
  LOGDIR: LOGS
  NGEN_UNIT: 1
  PATH_SNDATA_SIM: $SCRATCH_SIMDIR
  RANSEED_REPEAT: 50 12345
  SIMGEN_INFILE_Ia:
  - sn_ia_salt2_g10_des3yr.input
GENOPT_GLOBAL: {}
GENVERSION_LIST:
- GENOPT(sn_ia_salt2_g10_des3yr):
    GENMODEL: "/home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001/"
  GENVERSION: PIP_PA_DESFORWARDMODEL_DATASIM_G10_1
#END_YAML

</details>

**Comment by RickKessler** [comment]
Your GENMODEL points to 
/home/parmstrong/.julia/dev/IABCosmo/Examples/Outputs/DESForwardModel/SALT_MODEL_1/TRAINOPT001
which is not recognizable to SNANA. If it is a SALT2 or SALT3 model, then the base of the path has to be of the form SALT2.XYZ or SALT3.XYZ
