### ISSUE TITLE
event missing at the create_covariance stage

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1193]
At the BBC stage I got 1829 events but create_covariance drop one of the events for no clear reason.

The output of BBC can be found at this folder:
`/project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/pippin_output/D5YR_SMP_V2/6_BIASCOR/P21NOM_SIGINT_COLOR/output
`
Here 1829 events are found across all the different MUOPTs tested.
While the output of the create_covariance stage can be found at this folder: 
`/project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/pippin_output/D5YR_SMP_V2/7_CREATE_COV/COV_OMW_P21NOM/output`
Here there are 1828 events used.
The missing event had CID== 1682020
Thank you!

**Comment by RickKessler** [comment]
Please re-run two tests with:
1) remove "COSMOMC_DATASET_FILE: dataset.txt"
2) do above and remove EXTRA_COVS key

**Comment by RickKessler** [comment]
solved by removing COSMOMC output option
