### ISSUE TITLE
snlc_fit.exe error calling LEN(VARLIST) too short

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1200]
Working with Dan Scolnic on fitting simulated Roman LCs; however, when I try to fit the simulated Roman LCs, this error is passed:

```
 FATAL ERROR ABORT called by TABLE_VARLIST_FILTERS
   LENSUM=  72 but LEN(VARLIST)=  60 is too short.
   PREFIX=HOST_MAG  NFILT=  6(YJHFZR+)
```

Even though the same code had been working previously (roughly two weeks ago).

The error can be reproduced in `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3` by running:
`snlc_fit.exe FIT_ROMAN.nml VERSION_PHOTOMETRY Dust_Driven_Mass_Step`

We tried revisiting the kcor files, but we were unable to find a solution. Do you happen to know what may be the problem?

**Comment by RickKessler** [comment]
yes I fixed this morning for somebody else. I just updated the fix on Midway.
