### ISSUE TITLE
Transient Precursor Emission Model

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1204]
Starting a thread to discuss/implement a transient pre-explosion emission model in SNANA. The simple parametric model from eqn 19 of [Matsumoto & Metzger](https://arxiv.org/pdf/2206.08377.pdf) assumes an eruptive mass-loss episode whose bolometric luminosity behaves like a mini-IIP, with Mej, R0, and vej as free parameters. I'll add in blackbody assumptions and a parameter grid motivated by observed SNe IIn and IIP.

**Comment by RickKessler** [comment]
Seems to be working within the SIMSED model class, so gonna close this issue for now. Re-open if needed.
