### ISSUE TITLE
[User Error]: How to use GENMAG_OFF_ZP and GENMAG_OFF_MODEL

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1207]
I want to specify precalculated zp and filter offsets when simulating. After reading through the manual I believe the manual I thought the way to do this was:
```
GENMAG_OFF_ZP: a b c d
GENMAG_OFF_MODEL:  v w x y
```
Where a b c d, and v w x y are the offsets in question. These should be in the order of the filters in `GENFILTER` so if you have `GENFILTER: griz` then a is the g zp offset, w is the r filter offset, etc...

I tried this but am not even able to launch anything, getting the error:

`Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_PA_DESFORWARDMODEL_DATASIM_G10_BIASCOR_2_SNIaMODEL0.LOG`

Output is at `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/1_SIM/DATASIM_G10_BIASCOR_2`

**Comment by RickKessler** [comment]
fixed old refactor bug reading GENMAG_OFF_ZP and GENMAG_OFF_MODEL.

**Comment by OmegaLambda1998** [comment]
I am still getting the same error (at the same directory)

**Comment by RickKessler** [comment]
traced to pipping issue. Reopen if needed.
