### ISSUE TITLE
Option to add systematic coordinate shift in SNANA

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1212]
Hi Rick, 

As discussed earlier, can we add an option in SNANA to add a systematic shift in the SNe coordinates as well? Right now, we only have the statistical. 

This would mean that we add a user-specified value for the systematic floor (i.e. 5mas), then add a random shift in both the RA and DEC direction with amplitudes drawn from a Gaussian with mean = 0, sigma = 5mas (or 5mas/cos(DEC) for the RA I believe). 
The implementation would be pretty similar to the S/N and PSF FWHM dependent statistical smearing we already have.

Thanks!
Jason

**Comment by RickKessler** [comment]
Already included as a0 term in sim-input
ATMOSPHERE_DCR_COORDRES_POLY: a0,a1,...  # poly for coordRes(asec) vs. PSF_FWHM/SNR
