### ISSUE TITLE
LCFit Seg Fault

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1216]
```
1 Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
  2 
  3 Backtrace for this error:
  4 #0  0x7ff82dc163ff in ???
  5 #1  0x7ff82dc4e0d4 in ???
  6 #2  0x50e68b in ???
  7 #3  0x50e91c in ???
  8 #4  0x434fce in ???
  9 #5  0x4bc8ce in ???
 10 #6  0x4bcda9 in ???
 11 #7  0x4bdf3e in ???
 12 #8  0x7ff82dc02554 in ???
 13 #9  0x4058a4 in ???
 14 #10  0xffffffffffffffff in ???
 ```
 
 Outputs in: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/2_LCFIT/Fsys_1_DATAFOUNDSIM_4D_P21_1/output/SPLIT_JOBS_LCFIT`

**Comment by RickKessler** [comment]
Recently I added code to require DOCANA for header-overrides, but forgot to test with comma-sep list. It's fixed, and now your job correctly aborts due to lack of DOCUMENTATION block.

**Comment by OmegaLambda1998** [comment]
Got the abort without a DOCUMENTATION block, but after adding it to the file SNANA was complaining about I got the SEGFAULT again:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/2_LCFIT/Fsys_1_DATAFOUNDSIM_4D_P21_1/output/SPLIT_JOBS_LCFIT/PIP_PA_DESFORWARDMODEL_DATAFOUNDSIM_4D_P21_1-0001_FITOPT000_SPLIT010.LOG

**Comment by OmegaLambda1998** [comment]
WHoops, was a typo on my end
