### ISSUE TITLE
Issue creating SIMLIB for new survey

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1218]
Simlib file: `/project2/rkessler/SURVEYS/DES/USERS/parmstrong/dev/files_for_sam/DEBass.simlib`
Output: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/SB_DEBASS_SIMLIB/1_SIM/DATAFOUNDSIM_4D_P21`
LOGS: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/SB_DEBASS_SIMLIB/1_SIM/DATAFOUNDSIM_4D_P21/LOGS`
Error:
```
1  FATAL ERROR ABORT called by simEnd
  2    Every generated event fails NEPOCH>=3 .
  3    GENRANGE_PEAKMJD and SIMLIB probably don't overlap.
```
  
For the simlib we have:
min(mjd) = 59265
max(mjd) = 60154
I have tried both:
GENRANGE_PEAKMJD: 59247 60172 # GENRAGE > SIMLIB
and
GENRANGE_PEAKMJD: 59283 60136 # SIMLIB > GENRAGE
I get the same error for both so I think there's something else we're missing, but delving into the logs isn't helping.

**Comment by RickKessler** [comment]
I noticed a few problems:
1) sim-input file specifies "USE_SIMLIB_PEAKMJD: 1" but there are no PEAKMJD values in the SIMLIB
2) tab character after each S: key breaks parsing
3) u band is specified in the simlib, but is not a defined filter.
4) all MJDs in the simlib are rounded to nearest integer; while this doesn't break the code, it seems very unlikely.

**Comment by OmegaLambda1998** [comment]
After fixing those errors, things are working now!
