### ISSUE TITLE
SNANA crashes if the GENPDF_FILE is gzipped

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1221]
I was trying to use the GENPDF files in 
$SNDATA_ROOT/models/population_pdf/DES-SN5YR/DES-SN5YR_DES_S3_P21.DAT

The SNANA simulation was crashing with Segmentation violation error.
I tried to unzip the GENPDF file and everything started working fine.
I think SNANA doesn't have the function to recognize if the GENPDF file is gzipped and -in case- unzip it.

**Comment by RickKessler** [comment]
The code indicates that gzipped file should be readable; please provide sim-input file that causes crash.
