### ISSUE TITLE
Adding systematic and statistical uncertainties in quadratures for astrometry

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1223]
Hi Rick, 

As discussed, we need to change to sigma_tot^2 = sigma_syst^2 + sigma_stat^2, since we are doing sigma_tot = sigma_syst + sigma_stat at the moment. 

```
    for (SNR=10.0; SNR <= 100.0; SNR+= 30.0 ) {
      double PSF_FWHM = 1.0 ; // arcsec
      double x = PSF_FWHM/SNR;
      ANGRES = eval_GENPOLY(x, RESPOLY, fnam);
      printf("\t ANGRES = %7.4f arcsec for SNR = %4.0f (PSF_FWHM=%.1f asec)\n", 
	     ANGRES, SNR, PSF_FWHM); fflush(stdout);

```

This is from line 158 of sntools_sim_atmosphere.c - a simple fix would be to split the eval_GENPOLY output into the constant term (which would be sigma_syst) and the degree >= 1 terms (which would be sigma_stat) => then you could write ANGRES = sqrt(sigma_stat**2 + sigma_syst**2)
But this does assume that the sigma_syst is always a constant term, while sigma_stat has no offset but only the degree >= 1 terms. 

If we want to accept other forms of sigma_syst and sigma_stat, then I think they have to be taken as separate inputs. 

Best, 
Jason

**Comment by RickKessler** [comment]
I think your original suggestion is the right way to go: add another input, e.g.
ATMOSPHERE_DCR_COORDRES_FLOOR: <floor>

**Comment by jasonlee17** [comment]
Updated SNANA with new key for ATMOSPHERE_DCR_COORDRES_FLOOR and now adding uncertainties in quadratures.
