### ISSUE TITLE
BBC cancelled due to time limit

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1226]
directory: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/6_BIASCOR/P21NOM_SIM_1/output_ITER1/SCRIPTS_BBCFIT

Some jobs finish, other's have `done` in their log but never finish, ending up having their sbatch job cancelled

**Comment by RickKessler** [comment]
Some of the jobs were pending 24 hr, so try a different queue.
