### ISSUE TITLE
FATAL ERROR ABORT called by find_genmag_obs

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1227]
Hi Rick, 

I tried running `snlc_sim.exe SIMGEN_DCR_ASTROZ_REALISTIC_COADD.INPUT NGEN_LC 100` after the new update
but I keep getting this error (which I wasn't getting before)... 

# ================================================ 
  PRE-ABORT DUMP from function find_genmag_obs : 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by find_genmag_obs
   NFIND_MAG=0  but expeced 1
   ifilt_obs=1(u)  MJD=63575.335  TOBS=-31.8  z=0.787

How can I fix this? 

You can find my inputs here: `/pscratch/sd/d/desctd/cfs_mirror/SNANA/SNDATA_ROOT/SIM/JASON_inputs_231102/`

Thanks, 
Jason

**Comment by RickKessler** [comment]
fixed a few bugs related to the synMag crosscheck.
