### ISSUE TITLE
increasing allowed numbers of spectra, wave bins

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#123]
Hi Rick!  In snana.car, could you please increase MXSPECTRUM to something like 40 and MXLAM_SPECTRUM to something more like 20000?  Trying to simulate/fit the SALT2 training sample and there are some long and high-res spectral sequences.  Might also need to increase MXWORDFILE_PARSE_WORDS in sntools.h but I'm not sure yet.

**Comment by RickKessler** [comment]
Done.
