### ISSUE TITLE
Error: >2 Million Wavelength Bins in NBIN_WAVE

### ISSUE THREAD

**Issue by AmandaWasserman** [RickKessler/SNANA#1232]
Code I ran:
snlc_sim.exe /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/amandaw8/store_inputs/SNIa-SALT2_cid1180397_mjd60588.773_new.input 

Error:
FATAL ERROR ABORT called by read_specTable_SNANA
NBIN_WAVE=2132952 exceeds bound of 20000
Reduce NBIN_WAVE or increase MXBIN_SPECBASIS

**Comment by RickKessler** [comment]
some of the sim-input keys had incorrect arguments. To see fixes, 
look for 'RK' in RICK_SNIa_DEBUG.input
