### ISSUE TITLE
Generate a realistic number of transients according to rate model. 

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1234]
Hey Rick, I'm trying to generate transients across the full 10 years of the Rubin LSST. I don't want to specify `GEN_LC` or `GENTOT_LC`, I want to generate how many will be expected per season. I can't seem to do this, even though I couldn't find `GEN_LC` or `GENTOT_LC` keys in the ELAsTiCC input files either. 

_Working Directory:_
$SNANA_LSST_USERS/agaglian/precursorSandbox

_Command:_
snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT

_Error Message:_
```
 init_RateModel  
 dN/dz from 1.00 x Strolger15(CANDELS): 
    MODEL_RATE(z=0.00) = 6.169e-05/Mpc^3/yr    
    MODEL_RATE(z=0.20) = 1.325e-04/Mpc^3/yr    
    MODEL_RATE(z=0.40) = 2.172e-04/Mpc^3/yr    
    MODEL_RATE(z=0.60) = 2.825e-04/Mpc^3/yr    
    MODEL_RATE(z=0.80) = 3.128e-04/Mpc^3/yr    
 Calculated Number of EVENTS per season =  1.934e+10 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by main
   NGEN_LC=0 & NGENTOT_LC=0
```

**Comment by RickKessler** [comment]
So NGEN_UNIT is the key for submit_batch_jobs, and NGEN_SEASON is the key for sim-input file. For consistency, I updated the sim to allow either NGEN_SEASON or NGEN_UNIT, so now this part works. However, your sim is crashing on trying to write SIMSED binary, perhaps a permission issue?

**Comment by alexandergagliano** [comment]
Thanks for the fix! Looks like there was also a typo on my end that was preventing a realistic rate calculation.
