### ISSUE TITLE
create_cov segfault

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1235]
fail_reapeat: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/7_CREATE_COV/COV_SIM/output/SCRIPTS_COVMAT/FAIL_REPEAT_COVMAT_COV_SIM_P21NOM_SIM_10_OUTPUT_BBCFIT.CMD `

Error:
```
[    INFO | create_covariance.py:1606]   Compute covariance for COVOPTS
./FAIL_REPEAT_COVMAT_COV_SIM_P21NOM_SIM_10_OUTPUT_BBCFIT.CMD: line 7: 45662 Segmentation fault      (core dumped) create_covariance.py /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/7_CREATE_COV/COV_SIM/input_file.txt --input_dir /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/6_BIASCOR/P21NOM_SIM_10/output --version OUTPUT_BBCFIT --outdir /scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/7_CREATE_COV/COV_SIM/output/COV_SIM_P21NOM_SIM_10_OUTPUT_BBCFIT --yaml_file COVMAT_COV_SIM_P21NOM_SIM_10_OUTPUT_BBCFIT.YAML --unbinned --systematic_HD
```

**Comment by RickKessler** [comment]
create_covariance is crashing on this line
final_cov = cov.copy() * 0 
I suspect some kind of memory problem with 12k x12k matrix, but not sure.

**Comment by OmegaLambda1998** [comment]
Directory: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_DESFORWARDMODEL/7_CREATE_COV/COV_SIM/output/SCRIPTS_COVMAT`

I don't know if it's the same problem, but just to follow on from this, I tried halving the size of the sims and increasing the memory allocated to the create_cov job. now most jobs succeed by 3 of them fail:
```
  1 FAILURE-0001:
  2   JOB_LOG_FILE:       COVMAT_COV_SIM_P21NOM_SIM_OUTPUT_BBCFIT.LOG
  3   FAIL_REPEAT_SCRIPT: FAIL_REPEAT_COVMAT_COV_SIM_P21NOM_SIM_OUTPUT_BBCFIT.CM    D 
  4   FAIL_MODE:          UNKNOWN
  5   
  6 FAILURE-0002:
  7   JOB_LOG_FILE:       COVMAT_COV_SIM_P21NOM_SIM_3_OUTPUT_BBCFIT.LOG
  8   FAIL_REPEAT_SCRIPT: FAIL_REPEAT_COVMAT_COV_SIM_P21NOM_SIM_3_OUTPUT_BBCFIT.    CMD 
  9   FAIL_MODE:          UNKNOWN
 10   
 11 FAILURE-0003:
 12   JOB_LOG_FILE:       COVMAT_COV_SIM_P21NOM_SIM_6_OUTPUT_BBCFIT.LOG
 13   FAIL_REPEAT_SCRIPT: FAIL_REPEAT_COVMAT_COV_SIM_P21NOM_SIM_6_OUTPUT_BBCFIT.    CMD 
 14   FAIL_MODE:          UNKNOWN
 ```
 
Searching through the logs I can see any errors except for:
```
CPU0000_JOBLIST_midway2-login1.LOG:slurmstepd-midway2-0060: error: Detected 1 oom_kill event in StepId=31134910.batch. Some of the step tasks have been OOM Killed.
CPU0003_JOBLIST_midway2-login1.LOG:slurmstepd-midway2-0162: error: Detected 1 oom_kill event in StepId=31134913.batch. Some of the step tasks have been OOM Killed.
CPU0006_JOBLIST_midway2-login1.LOG:slurmstepd-midway2-0353: error: Detected 1 oom_kill event in StepId=31134916.batch. Some of the step tasks have been OOM Killed.
```

I'm wanting to do 10 5-year like sims with some small systematic offsets at the sim stage. I'm not sure why there's such a large covariance matrix being made?

**Comment by RickKessler** [comment]
unresolved, but close it for now ... might be re-opened later.

**Comment by RickKessler** [comment]
While updating create_covariance.py to write PROB1A_BEAMS to Hubble diagram,

**Comment by RickKessler** [comment]
The create_cov code changes result in being able to reproduce the older HD and cov files for the DES sims with~2000 events. Next, I went back to repeat the job for the original failure with 24,000 events:
