### ISSUE TITLE
pippin not launching jobs correctly 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1236]
Howdy howdy ! 

Trying to run a job with pippin - one that I've run before. As of now, it's started to bug out. When launching with pippin, the job no longer runs beyond the SIMnorm stage. The job never fails or anything, it just seems to never launch. The CMD that is generated runs fine interactively, so it's not that. 

Example is here - /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-PW-V1/

with an example of the specific simulation subdirectory here:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-PW-V1/1_SIM/DESSIMBIAS_4D_LOGISTICRV/LOGS

(Only redoing the LOGISTICRV stuff, everything else is run and done already)!

**Comment by benjaminrose** [comment]
I am having the same problem but I don't see a SUBMIT.INFO file. I am working in `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC`.

**Comment by RickKessler** [comment]
the job in 1_SIM/ROMAN_PLAsTiCC failed at the SIMnorm stage, so it didn't even create the SUBMIT.INFO and CPU*.CMD files. I ran the SIMnorm command interactively and it works fine, so I suspect a Midway-node problem.

**Comment by benjaminrose** [comment]
Yes. On Friday and today it runs on the login node, but has not worked on via pippin, even after a few retries.

**Comment by OmegaLambda1998** [comment]
@RickKessler, just fyi "CG" stands for "CompletinG" and is caused by a job that cannot be terminated, see https://slurm.schedmd.com/troubleshoot.html#completing

**Comment by OmegaLambda1998** [comment]
Also, you can't scancel a job in the CG state. It goes into CG when you've tried to scancel but it didn't work

**Comment by benjaminrose** [comment]
Ok. My issue looks like it was a quota issue.
