### ISSUE TITLE
option to generate list of snlc_sim commands from sim_SNmix in interactive mode

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#124]
Hi Rick - potential feature request here.  Since Midway jobs are often super slow, I was wondering if it was possible to have something like:
```
sim_SNmix.pl <inputfile> INTERACTIVE
```
that would just print out the various snlc_sim.exe commands that would be run in a batch job?  It would be a quick, easy/interactive way to see if anything is going to crash when the batch jobs actually do run.

**Comment by RickKessler** [comment]
try already existing feature,
  sim_SNmix.pl <inputfile> NOSUBMIT
which prints out the full set of command-line args for every GENVERSION.

**Comment by RickKessler** [comment]
please check if this issue can be closed.

**Comment by djones1040** [comment]
closed thanks!
