### ISSUE TITLE
marz Formatting Error

### ISSUE THREAD

**Issue by AmandaWasserman** [RickKessler/SNANA#1241]
Code I ran:  snana.exe NOFILE VERSION_PHOTOMETRY ADD_SPEC_SNIa-SALT2_cid1180397_mjd60588.773  MARZFILE_OUT 'cid1180397_marz.fits'
in the folder '/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/amandaw8/4most_files'

Error:
 FATAL ERROR ABORT called by SPECPAK_DATA
 Invalid NLAMBIN = 0 for CCID=1180397[z=0.513,GALID=None] and ID=0 . 
 NLAMBIN must be > 0. 

Note:
Running: snana.exe NOFILE VERSION_PHOTOMETRY ADD_SPEC_SNIa-SALT2_cid1180397_mjd60588.773 
Works fine.

**Comment by RickKessler** [comment]
fixed bug to allow reading spectra for MARZFILE_OUT option.
Also fixed another bug formatting GALID as 12 digits in stead of 9 digits.
