### ISSUE TITLE
Simulations crashing on empty "SIMnorm...LOG" file

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1244]
Working with Dan Scolnic and Dillon Brout on some Roman simulations, and I am unable to successfully use Pippin and SNANA to simulate SNe. The error that is called is `Unable to find NGENTOT_RATECALC: key in SIMnorm_PIP_EP-ROMAN_ROMAN_SN_DATA_Ia_SNIaMODEL0.LOG`. The SIMnorm file is empty, and this seems to be the problem since nothing is written to it.

The error can be reproduced in: `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3`

By running: `pippin.sh -v EP-ROMAN.yml`

Outputted files are written here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/EP-ROMAN`

**Comment by RickKessler** [comment]
it is indeed strange that your SIMnorm log file is empty, so I re-ran myself to see that the error is from non-existing SIMLIB_FILE:

pwd
/scratch/midway2/rkessler/PIPPIN_OUTPUT/EP-ROMAN/1_SIM/ROMAN_SN_DATA_Ia

grep SIMLIB PIP_EP-ROMAN_ROMAN_SN_DATA_Ia.input 
  SIMLIB_FILE: /project2/rkessler/SURVEYS/ROMAN/USERS/brose3/roman/1_sim/roman_ref.simlib

ls -l /project2/rkessler/SURVEYS/ROMAN/USERS/brose3/roman/1_sim/roman_ref.simlib
ls: cannot access /project2/rkessler/SURVEYS/ROMAN/USERS/brose3/roman/1_sim/roman_ref.simlib: 
No such file or directory
