### ISSUE TITLE
snlc_sim.exe ignores user-specified SNR for spectra?

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#125]
Hi Rick - check out `$SNANA_DEBUG/djones/spectra`.  I'm running:
```
snlc_sim.exe JLA_TRAINING_SNLS3_WITHSPEC.INPUT
```
which has a line to specify that spectra should be taken:
```
TAKE_SPECTRUM:  TOBS(-15:29)  SNR_ZPOLY(7)  SNR_LAMOBS(4000:6000)
```
Unfortunately, the output files all have SNR of 0.579.  For example:
```
$SNDATA_ROOT/SIM/JLA_TRAINING_SNLS3_WITHSPEC/JLA_TRAINING_SNLS3_WITHSPEC_SN000803.DAT
```
has these lines:
```
SPECTRUM_ID:       1
SPECTRUM_MJD:      52902.434            # Tobs =   -0.320
SPECTRUM_TEXPOSE:     3600.0            # seconds
SPECTRUM_SNR_COMPUTE:      0.579        # from user SNR request
SPECTRUM_LAMOBS_SNR:    4000.0  6000.0  # range for SNR_COMPUTE
SPECTRUM_NLAM:     621 (of 879)         # Number of valid wave bins
```

**Comment by RickKessler** [comment]
I added this option,
TAKE_SPECTRUM_DUMPCID: 803
which results in
 xxx --------- GENSPEC_TEXPOSE_TAKE_SPECTRUM DUMP for CID=803 ----------- 
 xxx imjd=0  MJD=52902.434 
 xxx SNR_REQUEST = 7.0 , z=0.582  TOBS=-0.32  TREST=-0.20
 xxx LAMOBS = 4000.0 to 6000.0 
 xxx LAMRANGE(stored) = 4000.0 to 6000.0 
 xxx SNR_MIN(3000 sec)=0.579, SNR_MAX(3600 sec)=0.579 
 xxx OPT_FRAME_EPOCH=2(OBS)  OPT_FRAME_LAMBDA=2 
 xxx FINAL TEXPOSE(S,T)=3600.00,0.00   SNR_COMPUTE=0.58  

so it looks like a problem defining the spectrograph properties. Without kcor-input file, I can't trace it back.

**Comment by djones1040** [comment]
have added the kcor input file, `kcor_SNLS.input` (which uses the file spectrograph_table.dat) to the debug directory.  Tried playing around a little bit but having trouble understanding what's needed to make the SNRs line up.

**Comment by RickKessler** [comment]
First row of spectrograph table has
   SPECBIN: 3805.27 3815.16 0.10 132.77 9.92 132.77 9.92

which means SNR(min, max) = 132.77 9.92 for magREF=17, but for magREF=22 SNR(min, max) are exactly the same. I would expect lower SNR for magREF=22. I will add an abort trap so please don't clobber this directory yet.

**Comment by RickKessler** [comment]
I copied your kcor-input file and spectrograph table to work on abort trap, so don't worry about clobbering your files. I'm going to add checks on SNR dependence on both MAG and TEXPOSE (assuming Poisson noise) to hopefully catch more of these mistakes.

**Comment by RickKessler** [comment]
above comment should have been that SNR(min, max) are the same for each exposure time, which makes no sense.

**Comment by RickKessler** [comment]
above spectrograph table has bad SNR values. SNANA kcor program now has some simple SNR checks that catch above problem, and hopefully catch a broader range of problems.

**Comment by djones1040** [comment]
sorry to reopen - tried to fix with a spectrograph table that follows poisson noise but still having some spectrograph issues:
```
cd $SNANA_DEBUG/djones/spectra
kcor.exe kcor_SNLS.input
snlc_sim.exe JLA_TRAINING_SNLS3_WITHSPEC.INPUT
```
results in error:
```
 FATAL[quickBinSearch]:
	 Something is REALLY messed up:
	 Could not find 'getSNR_spectrograph(ZP_S)' bin for VAL=-nan
```

**Comment by RickKessler** [comment]
To avoid the abort noted above, I updated the simulation to skip wavelength bins where the ZP,SKYSIG solution results in negative variance. This pathological solution happens well outside the MAGREF range, around Genmag=33, or 13 mag above the faint MAGREF=20. I left a RUNTEST_RICK file that runs a short sim for z>0.6, and then greps out _NLAM to show that typically a few hundred wavelength bins are missing due to a bad ZP,SKYSIG solution. The missing bins are mostly in the UV, but the missing bins can be anywhere, so be careful to alway read the wavelength bin and don't assume a perfect grid.

Lastly, I would suggest a somewhat brighter MAGREF range, something like 19 to 25. The current 15-20 range is quite bright, and probably doesn't cover much of the useful SNLS range.
