### ISSUE TITLE
wfit error when reading from create_cov hubble_diagram.txt output

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#1258]
description here: https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1704403074012059

**Comment by RickKessler** [comment]
A really long file name (generated by pippin) caused the string length to be 241, slightly exceeding MXCHAR_FILENAME = 240. Fix is to increase MXCHAR_FILENAME to 300.
