### ISSUE TITLE
create_cov 'utf-8' codec error?

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1264]
In the test here /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/pippin_output/D5YR_SMP_V2/7_CREATE_COV/COV_OMW_P21NOM/output/SCRIPTS_COVMAT
you will see a failed attempt to re-run create_covariance. This used to work but for some reason is not working anymore.
The error is:

```
[    INFO | create_covariance.py:1652]   Read Hubble diagrams for version = OUTPUT_BBCFIT
[    INFO |             utils.py:148]   Note: NumExpr detected 28 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[    INFO |             utils.py:160]   NumExpr defaulting to 8 threads.
[    INFO | create_covariance.py:393]   ISDATA_REAL = 1
[   ERROR | create_covariance.py:1845]   'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

```
So it looks like something might have been tarred up or gziped?
I triple-checked all the various input files/folders, and nothing seems to be tarred-up or gzipped, so I'm unsure about what the problem would be.

**Comment by RickKessler** [comment]
The same failure occurs with May 2 2023 version of create_cov, so the failure is not due to the recent Jan 5 2024 changes.

**Comment by RickKessler** [comment]
Crash was due to examining a tilde FITRES file, so I added protection to skip tilde files. 
Still crashing at another code location ...
