### ISSUE TITLE
vpec sign flip error

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1273]
Got the following error in `$PIPPIN_OUTPUT/LSST_COMBINED_CC_V3/6_BIASCOR/BBC_SIMDATA_SPECZ/output_ITER1/`

`SCRIPTS_BBCFIT/OUTPUT_BBCFIT-0005_FITOPT000_MUOPT000.LOG`

`FATAL ERROR ABORT called by check_vpec_sign
   RMS(MURES) is smaller with vpec sign-flip.
   See RMS(MURES) values above.`

**Comment by RickKessler** [comment]
fix bug in TRANSFER_SNHOST_REDSHIFT() that was introduced mid-Jan 2024 when VPEC (from HOSTLIB) was updated to allow for ZTRUE_CMB in HOSTLIB. The bug broke GENSIGMA_VPEC.

The fix is simply to skip TRANSFER_SNHOST_REDSHIFT if there is nothing to transfer (neither redshift or coords).
