### ISSUE TITLE
Abort on  MXOBS_SIMLIB=30000 -> array bound overflow

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1274]
Hi,

I'm trying to run a simulation using `/project2/rkessler/SURVEYS/LSST/USERS/bcarreres/SIMGEN_LSST_WHOST.INPUT`, with the SIMLIB `/project2/rkessler/SURVEYS/LSST/USERS/bcarreres/SIMLIB/baseline_v3.2_10yrs_GRP.simlib` that is a version of `baseline_v3.2_10yrs.simlib` with Host group from `/project2/rkessler/SURVEYS/LSST/USERS/bcarreres/HOSTLIB/baseline_v3.2_10yrs_HOST.HOSTLIB`. The simulaiton run when I simulate a small number of SNs, however when I increase the number (~ more than 1000) I get this abort message:

```
****************************************************************** 
    Begin Generating Lightcurves.   
  Found Max dN/dz * wgt = 5.430980e+04 at z =    0.170 
	 Finished generating        1 of 64128 (CID=1) 
	 Finished generating      500 of 64128 (CID=491) 
	 Finished generating     1000 of 64128 (CID=986) 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by SIMLIB_readNextCadence_TEXT
   Selected 42911 obs from 0 total in LIBID=0
   MXOBS_SIMLIB=30000 -> array bound overflow
```
Seems to come from SIMLIB, does SNANA try to reuse multiple times the first LIBID? Is it from an option that I could change?

**Comment by RickKessler** [comment]
To avoid array bound overflow, need to set
GENRANGE_MJD:   60225 61455
in addition to restricting GENRANGE_PEAKMJD

The other problem is that this array bound overflow corrupted information in the abort message, making it rather confusing. I fixed the code to avoid such corruption and the abort message now looks like this:

 FATAL ERROR ABORT called by SIMLIB_readNextCadence_TEXT
   Selected 42911 obs from 42911 total in LIBID=1273
   MXOBS_SIMLIB=30000 -> array overflow: check input GENRANGE_MJD

**Comment by bastiencarreres** [comment]
This solved the issue.
Thanks!
