### ISSUE TITLE
All DATA events fail cuts in SALT2mu

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1276]
I’m trying to run SALT2mu but I get the message 

```
All DATA events fail cuts.
   Check NCUT vs. cut listed above.
```

.. I’ve checked everything I could think of.
The job in on perlmutter: `/pscratch/sd/m/mvincenz/BBC`

and the error can be reproduced running: `SALT2mu.exe SALT2mu_ALL.input`

**Comment by RickKessler** [comment]
after specifying datafile=[string], the input file also contains
file=none
which overwrites the original datafile. SALT2 code has been update to abort when no data files are specified:

 FATAL ERROR ABORT called by prep_input_driver
   No input data (fitres files) !!!
   Check datafile=None

Beware that there is no duplicate-key checking in SALT2mu.
