### ISSUE TITLE
getZP_SPECTROGRAPH_SEDMODEL with WFIRST_PRISM not working

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1278]
In both `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/SUPERNOVA/LOGS` and `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC/LOGS` simulation jobs are failing with the inability to get use the spectrograph.

``` 
INIT_SPECTROGRAPH_SEDMODEL : prep NONIA spectra for WFIRST_PRISM (NBLAM=206)

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by getZP_SPECTROGRAPH_SEDMODEL
   NLOOP=101 is too much
   LAMMIN=7403  LAMMAX=7422  LAMSTEP=0.0
```

This is a new error in the recent weeks.

**Comment by benjaminrose** [comment]
Saw that the kcor path was renamed. Fixed this and reran sims, but got the same error. I'll continue to look for fixed today, but I'll run the sims in a separate folder. These failure logs should be stable.

**Comment by RickKessler** [comment]
in malloc_METADATA_SEDMODEL(), the allocated arrays were not initialized to zero, which eventually led to a corrupted value resulting in code abort. Fix is to initialize arrays.
