### ISSUE TITLE
Half-gaussian showing boundary issues 

### ISSUE THREAD

**Issue by darcykenworthy** [RickKessler/SNANA#1281]
When using the half-gaussian prior, I noticed that there were too few points appearing in the flat region of the prior, ostensibly the most likely region. Something to do with the interpolation or the definition of the boundary has to be going a bit haywire.

Ideally, including a simple Gaussian prior as an option would be desired, but the boundary behavior of the half gaussian is also likely undesirable for other applications. 

![temp](https://github.com/RickKessler/SNANA/assets/22338475/a522c477-32ab-436f-b633-69ba5b58371c)

Input file: /project2/rkessler/SURVEYS/DES/USERS/dkenworthy/pippinlearning/darcysaltsample.yml

**Comment by RickKessler** [comment]
For debugging, please isolate a stand-alone "snlc_fit.exe" task.
