### ISSUE TITLE
Biascor failing on error related to fieldGroup_biascor

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1282]
Working with Rebecca Chen, Dan Scolnic, and Dillon Brout on supernova simulations with Roman

The FAIL_SUMMARY.LOG in 6_BIASCOR details,
```
FAILURE-0001:
  JOB_LOG_FILE:       OUTPUT_BBCFIT_FITOPT000_MUOPT000.LOG 
  FAIL_REPEAT_SCRIPT: FAIL_REPEAT_OUTPUT_BBCFIT_FITOPT000_MUOPT000.CMD 
  FAIL_MODE:          ABORT 
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by sort_IDSAMPLE_biasCor 
  - Found ROMAN events NOT in FIELDGROUP 
  - Define all fields in fieldgroup_biascor key. 
```

This key is listed as `fieldgroup_biascor=SHALLOW,MEDIUM,DEEP` in the .input file for this stage in 6_BIASCOR, but I do not specify this in my yml or input files.

Also of note, previously my FITRES files had fields only listed as VOID. This has since changed to VOID & DEEP which might be the root of the issue. I am unsure why the FIELD values have since been changed.

The error can be reproduced in `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3` by calling `pippin.sh -v -s 6 EP-ROMAN.yml`

Output files are written to `/scratch/midway2/rkessler/PIPPIN_OUTPUT/EP-ROMAN`

**Comment by RickKessler** [comment]
I do not see any errors in BBC stage ??

**Comment by erikpeterson23** [comment]
The error has been reproduced in `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3` by calling `pippin.sh -v -s 6 EP-ROMAN.yml` and will remain static. I was using a workaround to the problem, defining fieldGroup_biascor = VOID, DEEP, and so the error was not occurring. I apologize for my oversight.

**Comment by RickKessler** [comment]
BBC fit works using 
fieldgroup_biascor=VOID,DEEP

**Comment by RickKessler** [comment]
also see slack comment about SIMLIB using fields that are not defined in $SNDATA_ROOT/SURVEY.DEF
