### ISSUE TITLE
Host magnitude in fitres files 

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1286]
Requesting to include the Host galaxy magnitude column in the fitres files in stage 2 LCFIT output

**Comment by RickKessler** [comment]
done (but not tested) using 
snana.exe NOFILE VERSION_PHOTOMETRY <version>  \
SNTABLE_LIST 'SNANA(text:key, text:host) \
TEXTFILE_PREFIX OUT+HOST
