### ISSUE TITLE
Failure at Stage 1 Sim step

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1293]
location : 
`/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_V3_25/1_SIM/LSST_SIMDATA/`

I get this error, 

```
 FATAL ERROR ABORT called by read_SIMSED_TABBINARY
   Binary file KCOR_FILE: '/pscratch/sd/d/desctd/cfs_mirror/SNANA/SNDATA_ROOT/kcor/LSST/baseline/kcor_LSST.fits' 
   but current KCOR_FILE: '/pscratch/sd/d/desctd/cfs_mirror/SNANA/SURVEYS/LSST/ROOT/kcor/2017-04_approx/kcor_LSST.fits' 
```

<img width="1501" alt="Screenshot 2024-02-29 at 11 23 47 PM" src="https://github.com/RickKessler/SNANA/assets/6508278/14936865-db96-4184-a0a1-be829b5137f2">

I tested with an older successful output, as a test using the following : 
`snlc_sim.exe sn_ia91bg.input` 
and I get the same error,

**Comment by RickKessler** [comment]
try switching your KCOR_FILE to the more current one that was used for Roman-DESC sims. It is the file listed in abort message starting with
Binary file KCOR_FILE: [path]
