### ISSUE TITLE
use refactored WGTMAP utility to weight SEDs in SIMSED model

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#1295]

**Comment by RickKessler** [comment]
begin by adding optional WGT column in SED.INFO file (for SIMSED model class), and use this WGT to select SED with sim-input key
SIMSED_GRIDONLY:  WGT
Internally, the sim uses the same infrastructure as "SEQUENTIAL" to pick the "ISED'th" SED on the list without using a function of SED parameters.

Next step is to enable an external WGTMAP file to override WGT column, or even work if there is no WGT column in SED.INFO file.

**Comment by RickKessler** [comment]
See new sim input argument SIMSED_WGTMAP_FILE and description in snana manual.

**Comment by alexandergagliano** [comment]
Still working on this one...

**Comment by RickKessler** [comment]
passed some tests from A.Gagliano using pre-explosion models ... going to pause this issue.
