### ISSUE TITLE
Mag=99 from PLAsTiCC models in Roman sims

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1296]
Multiple PLAsTiCC models (as NONIaMODELS) are not generating a flux. Outputs, and fail repeat commands can be see in `$PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/1_SIM/ROMAN_PLAsTiCC/LOGS`.  `slsn_lowz.cmd` is a copy of the MODEL0 command where I have been testing this issue. All objects are producing mag = 99 such that they can not pass the `CUTWIN_SNRMAX: 5 RZYJHF 2 -40 100`. Below is an example of the fitres values form the .DUMP file of this test simulation.

```
[brose3@midway2-login2 LOGS]$ get_fitres_values.py -f /scratch/midway2/rkessler/SNDATA_ROOT/SIM/TMP_bros_PIP_PIPPIN_ROMAN_TRANS_ROMAN_PLAsTiCC_NONIaMODEL0-0001_36737/TMP_bros_PIP_PIPPIN_ROMAN_TRANS_ROMAN_PLAsTiCC_NONIaMODEL0-0001_36737.DUMP -v ZCMB,PEAKMAG_Y,PEAKMAG_J --nrow 8

# Read /scratch/midway2/rkessler/SNDATA_ROOT/SIM/TMP_bros_PIP_PIPPIN_ROMAN_TRANS_ROMAN_PLAsTiCC_NONIaMODEL0-0001_36737/TMP_bros_PIP_PIPPIN_ROMAN_TRANS_ROMAN_PLAsTiCC_NONIaMODEL0-0001_36737.DUMP
# Found keyname_id = CID after skipping 6 rows
   CID         ZCMB PEAKMAG_Y PEAKMAG_J
  1539  9.27671e-01        99        99
 24203  7.03586e-01        99        99
 24341  9.90247e-01        99        99
 26984  9.93645e-01        99        99
 32758  8.43319e-01        99        99
  4022  9.82380e-01        99        99
  4022  9.04405e-01        -9        -9
  7865  7.33375e-01        99        99
```

**Comment by RickKessler** [comment]
The following keys are missing from $PLASTICC_MODELS/NON1ASED.TDE-MOSFIT/NON1A.LIST,
FLUX_SCALE:  8.358E-41   # tune this to get right mag, or adjust all SEDs
RESTLAMBDA_RANGE:  1000   11000   # valid range for central lambda of bands
so I manually copied them from SED.INFO file, and now some events are generated.
My hunch is this NON1SED model version was created by an early version of "convert_SIMSED_to_NON1ASED.py," which didn't copy these header keys.

**Comment by benjaminrose** [comment]
These were made with that script. It looks like TDEs worked now. Should I just manually copy these keys over to the other models?
