### ISSUE TITLE
snfitsio not working with simulations that have spectra.

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1298]
In `$/PIPPIN_OUTPUT/PIPPIN_ROMAN_TRANS/2_LCFIT/SUPERNOVA_LCFIT_SUPERNOVA/output/SPLIT_JOBS_LCFIT`, there are 26 errors. Some have Unknown failure modes (likely a memory issue), and some fail from `snfitsio_errorCheck`. `PIP_PIPPIN_ROMAN_TRANS_SUPERNOVA_FITOPT000_SPLIT006.LOG` is an example of the `snfitsio_errorCheck`.  This job fails as such:

```
FITSIO status = 104: could not open the named file
malloc of initial memory failed (mem_createmem)
failed to create empty memory file (compress_open)
failed to find or open the following file: (ffopen)
/scratch/midway2/rkessler/SNDATA_ROOT/SIM/PIP_PIPPIN_ROMAN_TRANS_SUPERNOVA/PIP_P
IPPIN_ROMAN_TRANS_SUaa107_NONIaMODEL1-0010_SPEC.FITS

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by snfitsio_errorCheck
   Open PIP_PIPPIN_ROMAN_TRANS_SUaa107_NONIaMODEL1-0010_SPEC.FITS
   Check cfitsio routines.


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f523560b3ff in ???
...
```

**Comment by RickKessler** [comment]
I ran the snlc_fit job and got this abort (not a crash):
FATAL ERROR ABORT called by get_calib_filterTrans
   No sparse ifilt index for ifiltdef=9(K)
   OPT_FRAME=1 SURVEY=NGRST

The sim data includes K-band, but kcor/calib file does not. 
The crash above might be a quota issue on scratch.

**Comment by RickKessler** [comment]
also note that the sim data SURVEY = ROMAN, but the kcor/calib file has SURVEY=NGRST.
