### ISSUE TITLE
GENPDF Creating Wrong Distributions of SIM_beta

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1306]
Hello! 

I am simulating DES, and trying to generate a fairly normal beta distribution -- 

```GENPEAK_SALT2BETA: 2.07
GENSIGMA_SALT2BETA: 0.22 0.22
GENRANGE_SALT2BETA: .4 3
```
(taken from the GENPDF file here: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/WISEMAN/DES-5YR.GENPDF)

Unfortunately, when it goes to simulation, the output appears to be an entirely flat distribution of SIM_beta, as you can see in this DUMP file: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-DES-COMPLETE/1_SIM/DESSIMBIAS_4D_D5YR/PIP_BP-DES-COMPLETE_DESSIMBIAS_4D_D5YR/PIP_BP-DES-COMPLETE_DESSIMBIAS_4D_D5YR.DUMP

I'm not sure why this happens - might be related to the binning thing we fixed recently? 

The output directory is here: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-DES-COMPLETE/1_SIM/DESSIMBIAS_4D_D5YR

**Comment by RickKessler** [comment]
This is due to an initialization bug that left EXPON_REWGT=0 (instead of 1) for asymGauss profiles specified in the GENPDF file. While this immediate fix is trivial, beware that sim-input GENPDF_EXPON_REWGT doesn't yet work for profiles in the GENPDF map file.

**Comment by RickKessler** [comment]
In set_population_expon_rewgt(), PROB_EXPON_REWGT has been initialized for the genPDF maps ... beware that this fix has not been tested.
