### ISSUE TITLE
in simulating spectra, SNR_COMPUTE is not accurate

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#131]
Hi Rick, check out `$SNANA_DEBUG/djones/spectra2`.  If you run:
```
snlc_sim.exe JLA_TRAINING_SNLS3_WITHSPEC.INPUT
```
and then look at:
```
$SNDATA_ROOT/SIM/JLA_TRAINING_SNLS3_WITHSPEC/JLA_TRAINING_SNLS3_WITHSPEC_SN000817.DAT
```
you'll notice that the SNR of the spectrum between observed wavelengths 4000 and 6000 is nowhere close to 7 (it's about 0.3).

**Comment by RickKessler** [comment]
the flux-sum between 4000 and 6000 should have SNR ~ 7 ... did you sum the flux, or look at the SNR in each wavelength bin ?

**Comment by djones1040** [comment]
oh, sorry - didn't realize it was a binned SNR.  Is there an option to get SNR = some number in each wavelength bin?  That would be the more standard definition of a SNR = 7 spectrum.

**Comment by djones1040** [comment]
related bug, but just keeping this spectra-related issue open.  In $SNANA_DEBUG/djones/spectra3, if you run
```
snlc_sim.exe JLA_TRAINING_SNLS3_WITHSPEC.INPUT
```
you get an error:
```
# ================================================
  PRE-ABORT DUMP from function GENSPEC_TEXPOSE_TAKE_SPECTRUM :
	 SNR_MIN(30 sec)=0.3
	 SNR_MAX(125829104 sec)=11.7



   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by GENSPEC_TEXPOSE_TAKE_SPECTRUM
   Could not converge after NITER=40 (CID=828)
   SNR_REQUEST=7.0  z=0.721  TOBS=3.66
```
Admittedly my spectrograph file might be a bit crazy because I'm trying to get reasonable SNR for every SNLS SN between z=0.2 and 1.0.  I'm getting a lot of these errors though.  spectrograph file and kcor input included in the directory.

**Comment by djones1040** [comment]
btw I figured out a workaround so this is not urgent

**Comment by RickKessler** [comment]
back in djones/spectra2, you can define SNR in arbitrarily small or large wavelength bins. instead of 4000-6000, try something like 5000-5010.
