### ISSUE TITLE
Error: Corners[0] could not be found.

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1310]
Hey Rick, I'm running into an unusual bug with the precursor SED model grid (after dropping down to 6k samples, not yet adding the WGT param): 

_Run directory_:  `$SNANA_LSST_USERS/agaglian/Precursor_32kGrid`
 _Command_: `snlc_sim.exe SIMGEN_TEMPLATE_LSST.INPUT`
_Error Message_: 

``` 
****************************************************************** 
    Begin Generating Lightcurves.   
  Found Max dN/dz * wgt = 1.366329e+03 at z =    0.050 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by interp_flux_SIMSED
   Corners[0] could not be found.
```

Any thoughts on this one?

**Comment by RickKessler** [comment]
It looks like every 5th SED is selected for this TRIMmed SED model, but it seems to have corrupted the multidimensional grid in a way that SNANA cannot handle. The Rstar grid, for example, never repeats.

**Comment by alexandergagliano** [comment]
Hm, I wonder if this is a symptom of the sed_modify code. I'll try a run with the smaller grid but the full SEDs in the morning.

**Comment by RickKessler** [comment]
I think that the preScale has to be more strategic than random rejection. For example, of the first grid parameter dimension has values 1, 2,3,4,5 (plus repeat), then the preScale should take out 1 or more of these grid points consistently in the other dimensions.

**Comment by alexandergagliano** [comment]
That makes sense! Will give this a shot.

**Comment by alexandergagliano** [comment]
Solved (but with another issue opened separately!) by removing grid points consistently in resampling.
