### ISSUE TITLE
Error in preparing data

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1311]
Hello! 

Trying to do the DATAPREP stage on some data in a private directory, and SNANA/pippin seems to be having a rough go of it. When generating the clump.nml file, it does this:

```
     ! data
     PRIVATE_DATA_PATH = '/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MAT+BRODIE-ZTF/ZTF_ROOT/lcmerge/ZTFDR2_COMBINED_ALL'
     VERSION_PHOTOMETRY = ''
```
which is certainly not correct, I would like a version photometry! 

The error log is here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-ZTF-DATASIM/0_DATAPREP/DATAZTF/output.log

with the yml being here: /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-ZTF-DATASIM/BP-ZTF-DATASIM.yml

**Comment by RickKessler** [comment]
This is an issue for Pippin (not SNANA); please post accordingly.
