### ISSUE TITLE
Segfaults on Perlmutter, not on midway

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1327]
Morning! I am transferring some simulation inputs from midway to perlmutter! On midway, these jobs ran successfully, but now on perlmutter I am getting some mysterious segfaults! 

The logs for (one such) example are here:
/pscratch/sd/d/desctd/PIPPIN_OUTPUT/BP-BAYESN-TESTS/1_SIM/PS1-TWO-RV/LOGS/FAIL_SUMMARY.LOG

though everything in /pscratch/sd/d/desctd/PIPPIN_OUTPUT/BP-BAYESN-TESTS/ appears to be failing in the same mysterious way.

The input files live here:
/global/cfs/cdirs/lsst/www/DESC_TD_PUBLIC/users/Brodie/BAYESN_TESTING/

Thank you!

**Comment by RickKessler** [comment]
Please follow these debug steps to get started:
clone SNANA in your home directory
cd src
  [edit Makefile and uncomment line with "EXTRA_FLAGS = -g -fbounds-check"
make clean
make

edit one of the FAIL_REPEAT*.CMD scripts and change snlc_sim.exe to use your private version.
Execute the FAIL_REPEAT script and check for code line numbers in the crash.

**Comment by RickKessler** [comment]
The function get_obs_atFLUXMAX(...) returns of NOBS < 3, but the output was not initialized prior to this early return and thus the output was random garbage depending on compiler and system. Fixed, and pushed to GitHub, Midway, Perlmutter
