### ISSUE TITLE
Increase MXBIN_LENZING_dmu from 100

### ISSUE THREAD

**Issue by paulshah** [RickKessler/SNANA#1329]
Lensing pdfs have sharply defined peaks and extended ranges of support, so 100 points isn't sufficient for linear interpolation. 

Can the default MXBIN_LENZING_dmu be increased to 6000? If memory is an issue MXBIN_LENSING_z  could be decreased from 100 to 30.

**Comment by RickKessler** [comment]
I increased MXBIN_LENSING_dmu to 6000 (and fixed spelling), and left MXBIN_LENZING_z at 100. I also noticed that these MXBIN bounds were never tested, so code would have run with any grid dimension. As a precaution, I added in the expected MXBIN bound check.
