### ISSUE TITLE
Unusual SALT2 error

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#133]
within /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie, running SALT2mu_fit.pl on the RUNME.input file causes some odd error trapping bug: 

 FATAL ERROR ABORT : 
	 Unable to find argument of 
	  

Very strange. Likely a typo on my end, but not sure!

**Comment by bap37** [comment]
Issue is with using INPDIR+STRINGMATCH and NSPLITRAN simultaneously.

**Comment by RickKessler** [comment]
ABORT message fixed;

 FATAL ERROR ABORT : 
	 Unable to find required argument of 
	 datafile= 
	 Either datafile=  key is missing, 
	 or cannot find data file ''  
	 Beware that INPDIR are ignored for NSPLITRAN.
