### ISSUE TITLE
could not read &SNLCINP namelist

### ISSUE THREAD

**Issue by paulshah** [RickKessler/SNANA#1331]
Having run a Biascor sim, subsequent LC fitting fails. 

Excerpts from $PIPPIN_OUTPUT/PS_BIASCOR/PS_BIASCOR.log :

[  NOTICE |           manager.py:453]   FINISHED: SNANASimulation BIASCORSIM_DES_LENS0300 task (wall time 0:18:59, 20 jobs, deps []) with 20 NUM_JOBS. NUM_JOBS now 20
[  NOTICE |           manager.py:370]   LAUNCHING: SNANALightCurveFit D3_BIASCORSIM_DES_LENS0300 task (20 jobs, deps ['BIASCORSIM_DES_LENS0300'])
..
[   ERROR |              task.py:324]   Excerpt:     FATAL ERROR ABORT called by RDSNNML
[   ERROR |              task.py:324]   Excerpt:       could not read &SNLCINP namelist
[   ERROR |              task.py:324]   Excerpt:       Check input-namelist file.

Checking the file 2_LCFIT/D3_BIASCORSIM_DES_LENS0300/FIT_PIP_PS_BIASCOR_BIASCORSIM_DES_LENS0300.nml, we have :
&SNLCINP
    USE_MINOS = F ! Set to T for final analysis

    PRIVATE_DATA_PATH = '$SNDATA_ROOT/lcmerge/DES-SN5YR'
    VERSION_PHOTOMETRY = 'DESALL_forcePhoto_real_snana_fits'

    PHOTFLAG_MSKREJ   = 1016, 0
    SNTABLE_LIST = 'FITRES(text:host)'
    TEXTFILE_PREFIX   = 'DES5YR_DES_CHANGEME'
    ROOTFILE_OUT = 'ROOTFILE.ROOT'

which seems to be 'standard' settings eg as per those in $PIPPIN_OUTPUT/ D5YR_BIASCOR/2_LCFIT/D3_BIASCORSIM_DES/FIT_PIP_D5YR_BIASCOR_BIASCORSIM_DES.nml or 
https://github.com/des-science/DES-SN5YR/blob/main/7_PIPPIN_FILES/base_files/lcfit/desSMP_5yr.nml

Checking Section 5.2 of the SNANA manual, while the folder DESALL_forcePhoto_real_snana_fits doesn't exist in $SNDATA_ROOT/lcmerge/DES-SN5YR, it does exist in /project2/rkessler/SURVEYS/DES/ROOT/lcmerge. 

However, changing PRIVATE_DATA_PATH to this doesn't solve the issue.

Pippin input file used for the run is in $DES_USERS/shahpa/DES-SN5YR_pippinfiles/PS_biascor.yml

**Comment by RickKessler** [comment]
No colons allowed for name list:
   cutwin_Trestmin: -9999.0   5.0
    cutwin_Trestmax: 5.   99999.
