### ISSUE TITLE
Issue Re-Generating kcor file for ZTF+YSE

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1335]
Hey Rick, I'm running into what seems like a bug in generating another kcor file for YSE+ZTF sims. I've added in the path to a spectrograph that I'd like to use, and running filters separately works but the code crashes when they're combined. Any thoughts?

__Command:__
`kcor.exe kcor_ZTF_spec.input`

__Directory:__
`$SNANA_LSST_USER/agaglian/ZTF_youngSNe`

__Error:__

```
 ***** Compute AB flux and ZP in each filter ***** 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by primarymag_zp
   AB flux = 0.000000 for filter = 'X' 
    
```

**Comment by RickKessler** [comment]
$SNANA_LSST_USERS/paleo/YSEtests/filters/20210712/g_ztf.dat
is not valid because the comment line "wave trans" does not have a hash, and thus it's not clear how the C code parser reads wave as a float.
