### ISSUE TITLE
SLSN-I NON1ASED Hang

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#1343]
Hey Rick,

I'm having my jobs hang instead of running to completion. No error messages are printed out, and it always hangs on reading an SED. Is this due to the debug flag? 

__Command:__ `./runJob.sh`

__Directory:__ `$SNANA_LSST_USERS/agaglian/ZTF_youngSNe/SLSN_HANG`

__Last Printout:__ 
```
 ****************************************************************** 
   Prepare 'NON1ASED' Simulation for slsn405.dat (INDEX=391)  
  Read  NON1A-391  SED  from : 
    /pscratch/sd/d/desctd/cfs_mirror/SNANA/SURVEYS/LSST/ROOT/PLASTICC/model_libs/NON1ASED.SLSN-I-MOSFIT/slsn405.dat 
```

**Comment by RickKessler** [comment]
I ran your test script and it works for me.
