### ISSUE TITLE
Simulations are not pulling WEAKLENS_DMU from hostlib

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#1346]
If I remember correctly, about a year or two ago, we were able to use weaklens values from inside a hostlib. Currently I can only get weaklensing if I use a `WEAKLENS_PROBMAP_FILE`.

I am running the `SNANA_ROMAN_USERS/brose3/roman/BR-KW-lensing.yml` pipeline that is outputting to `$PIPPIN_OUTPUT/BR-KW-LENSING/`.

**Comment by RickKessler** [comment]
can you specify evidence that WEAKLENS_DMU is not being used from HOSTLIB ?
