### ISSUE TITLE
simplify specification of DUST scatter model for SNANA sim

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#1347]
In addition to specifying GENPDF_FILE (containing population maps for stretch, color, RV, EBV), there are about half dozen other sim-input keys that are difficult to track.

**Comment by bap37** [comment]
Love this idea - presumably we could have a directory that SNANA looks at that contains these GENPDFs, and any newly published models could be easily added there?

**Comment by wisemanp** [comment]
I would be happy to help provide DUST(W22) as an option here as well.

**Comment by RickKessler** [comment]
After some thought, the original concept of
   GENMAG_SMEAR_MODELNAME: DUST(name)
is not necessary. Instead, some fixes have been made so that specifying GENPDF_FILE is sufficient to avoid the need for command-line (pippin) options. Here are the fixes:

+ fix sim for GENSMEAR_ADDPHASECOR to work without needing  meaningless "GENMAG_SMEAR_xxx" command-line (pippin) keys that were only used to make ADDPHASECOR work properly.
+ put GENPEAK_SALT2ALPHA in GENPDF_FILE instead of command-line (pippin) option. Fix sim to assume delta-function if GENSIGMA and GENRANGE are not provided.
- put MAG_OFFSET key in GENPDF_FILE and remove GENMAG_OFF_GLOBAL from pippin option

**Comment by RickKessler** [comment]
The GENPDF_FILE maps have been updated in $SNDATA_ROOT/models/population_pdf/DES-SN5YR
Update includes adding MAG_OFFSET and GENPEAK_SALT2ALPHA keys to files that already contain SALT2BETA keys. 
These maps will reside on RCC and Perlmutter@NERSC until pippin-verification if complete; then SNDATA_ROOT (including DES5YR files) will be uploaded to zenodo.
