### ISSUE TITLE
SNANA cannot read RV from HOSTLIB file

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#135]
Hey Rick -

I'm trying to feed RV values to my simulation via HOSTLIB. Problem is, it looks like SNANA is using the SIM_c value as the RV value. I've set up a test file in /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie

if you look at the dump file from running 'snlc_sim.exe' on the file in the above directory, you'll find this:
/project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/BP-TEST/BP-TEST.DUMP

Which shows that S2c = RV on the simulation level.

edit: I have HOSTLIB_MSKOPT: 64, because I want to read the RV values from the HOSTLIB

**Comment by RickKessler** [comment]
code was reading EITHER c,Beta or AV,RV from HOSTLIB ... fixed to allow reading both sets of color params. Fix on Github and Midway2.
