### ISSUE TITLE
HOST_RA changed to -999 after SALTfit

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1350]
Hi,

I noticed that some of my simulated SN HOST_RA values changed from the SIM file to the FITRES file from normal value to -999. I'm not sure if this behaviour is expected?

For example on NERSC:
```
sim = Table.read('/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_UCHUU_BC/1_SIM/LSST_G10/PIP_LSST_UCHUU_BC_LSST_G10/PIP_LSST_UCHUU_BC_LSST_G10_SNIaMODEL0-0001_HEAD.FITS.gz').to_pandas()

fit = ascii.read('/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_UCHUU_BC/2_LCFIT/LSST_FIT_LSST_BBC_G10/output/PIP_LSST_UCHUU_BBC_BC_LSST_BBC_G10/FITOPT000.FITRES.gz').to_pandas()
```

For the SN with ID=4 I obtain:
```
fit[['HOST_RA', 'HOST_DEC', 'CID', 'zHD', 'SIM_x1', 'SIM_c']].iloc[1]

HOST_RA    -999.000000
HOST_DEC   -999.000000
CID           4.000000
zHD           0.158070
SIM_x1        0.492980
SIM_c        -0.027471
```

while in the sim file the RA and DEC are well defined:
```
sim[['SNID', 'RA', 'DEC', 'SIM_REDSHIFT_CMB', 'SIM_SALT2x1', 'SIM_SALT2c']].iloc[2]

SNID                b'4               '
RA                            30.751059
DEC                          -43.725646
SIM_REDSHIFT_CMB               0.158068
SIM_SALT2x1                    0.492978
SIM_SALT2c                    -0.027471
```

**Comment by RickKessler** [comment]
please provide fit-input file to reproduce the problem.

**Comment by bastiencarreres** [comment]
The fit input I used is located at `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/bastienc/LSST_SNANA/fit_inputs/LSST_fit.nml`

**Comment by RickKessler** [comment]
events with RA,DEC = -999 are those with DDLR > 4 and thus fail host-matching. The DDLR cut can be adjusted with sim-input key
HOSTLIB_MAXDDLR:  <cutval>
(see manual)

**Comment by bastiencarreres** [comment]
Expected behavior from DDLR cut
