### ISSUE TITLE
BBC REWGT doesn't use WGT when computing sigint_biasCor

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1353]
When testing new biasCor REWGT method on DES sims, noticed w-bias w.r.t. truth w=-1 

------ summary ------
NOM: 0.0035 +- 0.0024 ($PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOM/output)
REWGT: 0.0110 +- 0.0022 ($PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOM/output_rewgt)
REGWT_RADCUT: 0.0112 +- 0.0022 ($PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOM/output_rewgt_radcut)

Rick noticed when comparing BBC_SUMMARY_FITPAR.YAML, sigint(biasCor) is notably larger for REWGT because of forgetting to use the WGT in computing sigint_biasCor

@bap37 so you're aware!

**Comment by RickKessler** [comment]
Visually comparing output parameters for NOMINAL vs. REWGT, the sigint values were quite different. I noticed that WGT_POPULATION was not applied for sigInt_biascor computation so this has now been fixed in SALT2mu function init_sigInt_biasCor_SNRCUT(). I have verified that fitted sigint values are much closer for NOMINAL vs. REWGT, but I have not checked w-bias since that requires re-running on all 50 samples.

**Comment by rebeccachen0** [comment]
Testing with 25 samples w-bias is reduced to 0.0023+- 0.0023!

**Comment by rebeccachen0** [comment]
May have been a bit hasty and looked at the wrong file... the w-bias is actually more like -0.00994 +- 0.00387 so closer to 2 sigma here, is this still a concern?

**Comment by RickKessler** [comment]
please remind which directories to compare nominal (no wgt) and REWGT option

**Comment by rebeccachen0** [comment]
Nominal: $PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOMINAL/output
Rewgt: $PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOM_REWGT/output

**Comment by rebeccachen0** [comment]
With opt_biascor=752, averaged over 25 samples:
NOMINAL: $PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOMINAL/output_opt
w-bias: -0.0026 +- 0.0022

REWGT: $PIPPIN_OUTPUT/RC_DESPZ_V3/6_BIASCOR/P21NOM_REWGT/output_opt
w-bias: -0.0108 +- 0.0022

So if anything, made the bias worse for rewgt. 

For the first simdata sample, 
sigint(NOMINAL) 0.082 -> 0.0812

**Comment by RickKessler** [comment]
gonna close this issue for now ... may come back to the REWEGT bias later. Just don't use this option.
