### ISSUE TITLE
Failure to run PIPPIN job

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1354]
Hello Rick,

When I try to run a pippin job, I encounter this error  ModuleNotFoundError: No module named 'f90nml'. 
This is my file on midway: /project2/rkessler/SURVEYS/ROMAN/USERS/Keneanumba/5K_SNe_training/KA_pippin.yml
This is the output directory path: /scratch/midway2/rkessler/PIPPIN_OUTPUT/KA_PIPPIN

Just some context, I wasn't able to use my .bashrc because it said that I didn't have python3.6 which I presume is a base requirement to be able to do the pippin job. I then basically copied Dan's bashrc which I renamed .bashrc_pippin. I wouldn't know if this has anything to do with not having the f90nml module. 
I'm happy to provide more information if needed.

**Comment by KeneAnumba** [comment]
The problem is that SNANA doesn't recognize my fit model name.
You can reproduce the error by executing this /scratch/midway2/rkessler/PIPPIN_OUTPUT/KA_PIPPIN/2_LCFIT/FIT_LSST_ROMAN/output/SPLIT_JOBS_LCFIT/FAIL_REPEAT_PIP_KA_PIPPIN_LSST_ROMAN_FITOPT008_SPLIT003.CMD

**Comment by RickKessler** [comment]
traced to missing SALT3 prefix in model folder name
