### ISSUE TITLE
Abort on salt2mu - idsurvey mismatch

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#136]
Got errors like this: 
>    `|```````|`    
>    <| o\ /o |>    
>     | ' ; ' |     
>     |  ___  |     ABORT program on Fatal Error. 
>     | |' '| |     
>     | `---' |     
>     \_______/    
> 
>  FATAL ERROR ABORT called by match_surveyGroup
>    Invalid NMATCH_TOT=0 for CID=151573
>    IDSURVEY=63(CFA3S)

input and related files are in $SNANA_DEBUG/mdai/newissue

**Comment by RickKessler** [comment]
please provide a working example to reproduce the problem. On midway, it is common to setup a job under a directory such as $SNANA_DEBUG/Dai

**Comment by mi-dai** [comment]
It can be found in: $SNANA_DEBUG/mdai/newissue

**Comment by RickKessler** [comment]
Please also provide an explicit SNANA command to reproduce the error.

**Comment by mi-dai** [comment]
SALT2mu_fit.pl $SNANA_DEBUG/mdai/newissue/BBC.input

**Comment by RickKessler** [comment]
found and fixed related bugs, but above abort is valid and should be fixed by generating proper sim-data. See $SNANA_DEBUG/mdai/newissue/Run_GetMu_111/AllSurveys_LOWZ_111/AAA_README.TXT
