### ISSUE TITLE
SNANA snlc_fit.exe won't fit mid-infrared filters even if rest-frame wavelength is reasonable

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#1362]
I'm seeing only YJH filters used in the SNANA fit to a high-redshift SN (z=2.9).  I think it should be using redder filters like KLM.  To reproduce:
```
cd /project2/rkessler/PRODUCTS/SNANA_DEBUG/djones/JWST
snlc_fit.exe snfit_JWST.nml
```
Thanks Rick!

**Comment by RickKessler** [comment]
changed default CUTWIN_LAMOBS 2000, 25000 to 
CUTWIN_LAMOBS 2000, 270000
