### ISSUE TITLE
Option to require same events across fitopts in BBC input file

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#1369]
When running submit_batch_jobs.sh for BBC, it is possible to set `FLAG_USE_SAME_EVENTS: 0` to ignore requiring the same events across fitopts (for systematics).

Would it be possible to also implement the inverse? Such that `FLAG_USE_SAME_EVENTS: 1 ` requires the same events across fitopts even if the flag is not set in the LCFIT stage?

**Comment by RickKessler** [comment]
according to 
   submit_batch_jobs.sh -H BBC 

it shows this option
  FLAG_USE_SAME_EVENTS: 0  # disable sync-event flag passed from 2_LCFIT stage

**Comment by rebeccachen0** [comment]
Yes, I see that too! I tried to see if flagging "1" would do the opposite (enable the sync-event flag rather than disable) but it isn't in place

**Comment by rebeccachen0** [comment]
Feature not needed in the end -- deliberately one way. Noted comment in code
