### ISSUE TITLE
Reading EBV from HOSTLIB

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#137]
Hey Rick! 
If it's not too difficult, it'd be nice to read EBV from a HOSTLIB. 
$SDSS_USERS/BAP37/MASS_paper/AS/HOSTLIBS/RIGAULT/
Has two HOSTLIBS that include EBV in the columns if you need an easy test. The $SNANA_DEBUG/Brodie directory is still pretty well situated for this

Thanks!

**Comment by RickKessler** [comment]
Done.
