### ISSUE TITLE
Abort on MXFIT_DATA

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1370]
Hi, while fitting a BBC simulation of LSST (40 times LSST) I got the following error:

```
    `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by LOAD_EPALL
   NFIT_DATA=2066  exceeds MXFIT_DATA=2000   for ITER=1  CID=3903175
   Check param MXFIT_DATA

```

It seems due to a SN that have too much epochs, could this MXFIT_DATA limit be push a bit, I think something like 2500 would be enough?

**Comment by RickKessler** [comment]
please simulate smaller epoch range, or use simlib_coadd.exe to co-add nightly exposures.
