### ISSUE TITLE
Simulation runs for 24 hours and cuts off (continued)

### ISSUE THREAD

**Issue by jmpaulin** [RickKessler/SNANA#1379]
Update: I tried running this with more cores, as you suggested (I ran with 10 cores, then 15 cores), and still had the same issue. Am I doing the right thing to try to simulate years 2-10 (altering GENRANGE_MJD and GENRANGE_PEAKMJD)?

Original issue:

I am trying to simulate years 2-10 of LSST data. To do this, I changed only the GENRANGE_MJD and GENRANGE_PEAKMJD parameters in the input .yml file.

I specified GENRANGE_MJD to be 61211 64398 and GENRANGE_PEAKMJD to be 61161 64448.

The simulation ran for 24 hours before abruptly cutting off, and never even completed the simulation stage. For reference, my outputs are in the following directory: /pscratch/sd/d/desctd/PIPPIN_OUTPUT/JP_LSST_BIASCORR_TEST01.

**Comment by RickKessler** [comment]
pippin stages 1,2,3 all seem to have run properly, but pippin didn't update the status. My hunch is that the background pippin task died ... it is safer to exit the terminal after launching a pippin job to avoid terminal hang up killing background jobs. Pippin and scone were updated Jun 18, a week after your pippin output, so remove stages 3_CLAS (and 4_ and 5_), then re-launch pippin ... it should know to start at stage 3.
