### ISSUE TITLE
with SIMLIB_OUT option, write TAKE_SPECTRUM keys in SIMLIB header

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#138]
using SIMLIB_OUT option with snana.exe, if there are spectra in the data then include a TAKE_SPECTRUM key in the SIMLIB header for each spectrum. This feature is useful to test training by enabling simulating spectra with the same phase and SNR as in the data.

**Comment by djones1040** [comment]
I set up the `$SNANA_DEBUG/djones/specsim` for this.  All of the namelist files in that directory should work for creating SIMLIB files:
```
snana.exe snfit_Hamuy1996.nml SIMLIB_OUT Hamuy86.SIMLIB
```
The SURVEY keys in the LC files don't match up with `$SNDATA_ROOT/SURVEY.DEF` though.  On my local machine I just added these surveys to SURVEY.DEF but that's probably not the best.

**Comment by RickKessler** [comment]
ready to test. See manual 12.3.4 Creating a SIMLIB from Data

**Comment by djones1040** [comment]
running some tests and found that SNR computation is very sensitive to outliers.  Check out `$SNANA_DEBUG/djones/specsim4`.  If you run the command:
```
snana.exe snfit_SNLS3_test.nml SIMLIB_OUT SNLS3_TEST.SIMLIB
```
you'll see two SIMLIB entries from the same SN.  one has a TAKE_SPECTRUM line with SNR of 0.1, one has a TAKE_SPECTRUM line with SNR of 553.  The difference between the two is that I've masked out a few data points with crazy high errors in the second LC file.  These regions were data quality = 0 so they should have been masked anyways.  But this issue might pop back up if there are regions with sky lines or something that have crazy high errors.

**Comment by RickKessler** [comment]
To compute SNR for TAKE_SPECTRUM key in SIMLIB, wave bins are excluded if FLAMERR/FLAMERR_MEDIAN > 50. The "50" is a hard-coded parameter, but can be passed via input if needed. To see summary of rejected bins, grep WARNING STDOUT

**Comment by djones1040** [comment]
at the moment it looks like the remaining SNR discrepancies I was seeing are due to the fact that I wasn't binning SNR correctly.  I'm gonna go ahead and close this out, can always re-open if any other spec simulation issues pop up.
