### ISSUE TITLE
ZTF Data too powerful, too many observations 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#1385]
Trying to do 0_DATAPREP for ZTF data, finding a fun new problem:

```

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by get_PARSE_WORD
   iwd=11940 exceeds NWD_STORE=11940
   Check FILENAME = '/project2/rkessler/SURVEYS/ZTF/ROOT/lcmerge/DR2BINNED/ZTFIDR_ZTF18acuyoyf.dat.gz'

```

/scratch/midway2/rkessler/PIPPIN_OUTPUT/DOVEKIE/0_DATAPREP/DATAZTF/output.log

**Comment by RickKessler** [comment]
visually inspect ZTFIDR_ZTF18acuyoyf.dat.gz and note that it has no photometry, just a spectrum. SNANA code has never been tested for this case, and not sure what the purpose would be.
