### ISSUE TITLE
Plot Utilities for viewing lightcurve fits

### ISSUE THREAD

**Issue by jmpaulin** [RickKessler/SNANA#1386]
Hello. I am trying to learn how to use the plot_snana.py function to view light curves. In the SNANA manual, it says that typing plot_snana.py with no arguments gives a help menu. I tried doing this and instead received an error: "-bash: plot_snana.py: command not found".

I did this after initializing the environment and setting up necessary packages ("source /global/cfs/cdirs/lsst/groups/TD/setup_td.sh").

Is there something else I need to do to see this help menu? 

Thank you.

**Comment by RickKessler** [comment]
Here are the plot utilities in snana:
ls $SNANA_DIR/util/plot_*
/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/plot_fitres.py
/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/plot_peakmag_redshift.py
/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/plot_snana_lightcurves.py
/global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/plot_table.py


I will fix the manual accordingly.
