### ISSUE TITLE
Inability to generate spectra during simulation

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1388]
I was not able to generate spectra for a SALT3 training that I'm currently doing. This is the merge file showing that no spectra was written out in the output directory. /project2/rkessler/SURVEYS/DES/USERS/Keneanumba/5000_SNe_simulation_LSST+Roman/SIMLOGS_KA_250_LSST+Roman_wSPEC/MERGE.LOG . 
I've tried to figure out what could be the issue but I have not been able to identify the problem. This is the master input file /project2/rkessler/SURVEYS/DES/USERS/Keneanumba/5000_SNe_simulation_LSST+Roman/MASTER5_LSSTRoman_DDF.INPUT. 
I also adjusted the MJDs to match but it didn't resolve the problem.

**Comment by RickKessler** [comment]
Looks like a mis-typed key:
"TAKE_SEPCTRUM" should be "TAKE_SPECTRUM"
