### ISSUE TITLE
Hostlib with 2 Sersic components

### ISSUE THREAD

**Issue by AnomandarisPurake** [RickKessler/SNANA#139]
When a HOSTLIB file with 2 Sersic components is used, the output head file has some host galaxies with positions (hostgal_ra, hostgal_dec) set to -999 and magnitudes (hostgal_mag columns) set to 666.

The following input file 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/Master_Survey_spec_candels.INPUT
uses a hostlib file with galaxies described by two Sersic components
/project2/rkessler/SURVEYS/WFIRST/USERS/kxw/supernova/Akari_Hosts.HOSTLIB
with output at
/scratch/midway2/rkessler/SNDATA_ROOT/SIM/Deep_Spec_KXW

The following input file 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/KXW_Test.INPUT
uses a hostlib file with galaxies described by one Sersic component /project2/rkessler/SURVEYS/WFIRST/USERS/kxw/supernova/Test_One_Sersic.HOSTLIB
with output at
/scratch/midway2/rkessler/SNDATA_ROOT/SIM/Test_Sersic_KXW

This is not due to properties of the host galaxies alone. Using the following hostlib file
/project2/rkessler/SURVEYS/WFIRST/USERS/kxw/supernova/Test.HOSTLIB
in the output, the galaxy with GALID 15 had one entry with values changed and the other one with values taken from the hostlib file
/project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/RAH/RAH_HEAD.FITS

(I am Kevin Wang, username kxw, on Midway)

**Comment by RickKessler** [comment]
Cannot find /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/Master_Survey_spec_candels.INPUT
Please setup file(s) and under $SNANA_DEBUG/kwang, and provide more clear indication of problem. For example, generate sim with TEXT format and point to a specific variable in a specific data file.
