### ISSUE TITLE
Attribute Error on fitting file

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1391]
I'm having problem doing the fitting of the simulations before starting out the training. It is raising an AttributeError when I run the submit_batch_jobs.sh command. Here is the file /project2/rkessler/SURVEYS/DES/USERS/Keneanumba/5000_SNe_simulation_LSST+Roman/FIT_250_wSPEC.nml

**Comment by RickKessler** [comment]
see RK comments inside  FIT_250_wSPEC.nml.
This command now works:  snlc_fit.exe FIT_250_wSPEC.nml

**Comment by RickKessler** [comment]
Note that snlc_fit automatically searches these paths for sim data folders:
 $SNDATA_ROOT/SIM/PATH_SNDATA_SIM.LIST
The goal is to keep sims under a few well-defined paths to monitor disk usage and make them easier to find.
