### ISSUE TITLE
Failure to run pippin job

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1393]
I encountered this error which I have tried to resolve but haven't been successful at.
When I run  pippin.sh -v KA_pippin.yml in this path  /project2/rkessler/SURVEYS/ROMAN/USERS/Keneanumba/250_wSPEC
It raises a valueError and says that I should check fileName $SNANA_YSE_SIM

**Comment by RickKessler** [comment]
try logging out and log in again to get updated ENVs in SNANA_setup.

**Comment by benjaminrose** [comment]
This also happened to me, and a rerun of SNANA_setup fixed it.
