### ISSUE TITLE
H11 option retriving more events than when run using SNANA_v11

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1396]
I rerun BBC on the SDSS+PS (aka Amalgame) sample.
I got different results from the original BBC job (which was run in June 2023). 
The main difference is that, in my recently-rerun version, I get 100 more SNe (and these are all SDSS SNe).

I was trying to investigate the cause of the difference so I rerun the exact same job twice.
First, with current SNANA version
Second, with old SNANA version, in particular, SNANA v11 (from May 2023)
Results are in /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/DES_SDSS_PS/, under the folders of **AMALG_output_bin**
and in **AMALG_output_bin_oldSNANA**

In this way, I was able to reproduce the 100 SNe discrepancy.
In **AMALG_output_bin** (BBC using current SNANA), I obtain ~**750** SDSS SNe (I had 813 SDSS SNe in ITER1)
In **AMALG_output_bin_oldSNANA** (BBC using older SNANA, I obtain ~**650** SDSS SNe (I had 812 SDSS SNe in ITER1)

The main cause of the bigger loss of SNe with the older SNANA version is **MUOPT006** i.e., the option that uses H11 ccprior.
With the old SNANA, this MUOPT causes the loss of many SNe (almost ~100).
This problem seems to be fixed in the newer SNANA version, but I'm not sure why.

**Comment by RickKessler** [comment]
traced to chi2 cuts and dependence on H0:
Oct 28 2022: fix to work for any INPUTS.H0 by adjusting INPUTS.M0 accordingly
