### ISSUE TITLE
simlib dump abort

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1397]
`snlc_sim.exe /pscratch/sd/d/desctd/cfs_mirror/SNANA/SURVEYS/LSST/ROOT/simlibs/LSST_DC2_Run2.2i_WFD.SIMLIB SIMLIB_DUMP 1`

aborts with the following error. 

![Screenshot 2024-08-01 at 10 11 18 AM](https://github.com/user-attachments/assets/583090bb-3172-4bbb-898c-f49b395aee83)

**Comment by RickKessler** [comment]
The main issue is that there is no sim-input file and thus snlc_sim interprets the SIMLIB file as a sim input file, and the abort is thus correct.

To simplify implementation of SIMLIB_DUMP, there are two code updates:

1) sim-input file need contain only the SIMLIB_FIKE keys other required keys (GENMODEL, KCOR_FILE, GENFILTERS) are not needed

2) replacing sim-input file with NOFILE, a command-line only argument can be used for the dump ; e.g.
  snlc_sim.exe NOFILE   SIMLIB_FILE $SNANA_LSST_ROOT/simlibs/LSST_DC2_Run2.2i_WFD.SIMLIB \. SIMLIB_DUMP 1
