### ISSUE TITLE
SPECEFF segmentation violation when including HOSTMAG_r

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1401]
When adding the column HOSTMAG_r to my SPEC EFF map, the code with  *** Break *** segmentation violation.

Error can be reproduce here:
/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/speceff_host
using command
./FAIL_REPEAT.CMD

The efficiency map I'm using is here: /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/George_check/SEARCHEFF_SPEC_DES_G10_extra.TXT

**Comment by RickKessler** [comment]
From the manual, here is the list of valid variables for SPECEFF map. Need to fix the sim to abort gracefully on incorrect map variable, and shouldn't be too hard to add host mag variables into the list.

<img width="828" alt="manual_Fig10" src="https://github.com/user-attachments/assets/fd66a64d-a1de-4bbe-a0d0-dd9d5f4e1000">

**Comment by RickKessler** [comment]
Fixed bug in function IFILTOBS_SPECEFF_VAR() (sntools_trigger.c).
