### ISSUE TITLE
Dust generated from GENPDF vs. HOSTLIB not the same

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1402]
Working with Dan Scolnic, Dillon Brout, and Maria Vincenzi (and others) on regenerating DES simulations.

As a baseline, I am trying to regenerate DES5YR sims, but with one modification --- generating the RV and EBV distributions from the HOSTLIB rather than a GENPDF (I am aiming to do this so that I can update the HOSTLIB for intergalactic dust in another simulation); however, I am unable to obtain the same RV distributions when generating from the GENPDF vs. the HOSTLIB (the difference is most apparent for low mass hosts).

I have set up the commands to recreate this issue in `$SNANA_DEBUG/epeterson3`.

Outputs to the commands `BIASCORSIM_DES.CMD` (GENPDF) and `BIASCORSIM_DESfromHOSTLIB.CMD` (HOSTLIB) go here `/scratch/midway2/rkessler/SNDATA_ROOT/SIM/TMP_epet*`. Comparing the two commands (`diff BIASCORSIM_DES.CMD BIASCORSIM_DESfromHOSTLIB.CMD`), I observe that they are very similar. I shortened the sims by a factor of approximately 10 from what I have been doing for my analysis, and I added a SIMGEN_DUMP line to include RV and LOGMASS_TRUE in the output dump files.

The different low mass RV distributions are plotted with `compare_dumps.py` and observed in `genpdf_hostlib_RV.png` where the GENPDF method seems to experience significant selection effects while the HOSTLIB method does not.

**Comment by RickKessler** [comment]
intergalactic dust is not the same as moving all the dust to host or to MW. Need to research meaning of published AV and how to implement.

**Comment by erikpeterson23** [comment]
This issue has since become obsolete for the project I am working on involving intergalactic dust.
