### ISSUE TITLE
Add an option in snlc_fit.exe to not correct for velocities

### ISSUE THREAD

**Issue by bastiencarreres** [RickKessler/SNANA#1404]
Hi,

It seems that by default if a `VPEC` column is present, `snlc_fit.exe` create a  `zHD` column in the output file that is corrected for pec. vel. then this column is used in post-fit analysis code as SALT2mu.exe. Could it be possible to have an option as `CORRECT_VPEC: True/False` to not apply the VPEC correction even if the VPEC column is in the simulation file.

**Comment by RickKessler** [comment]
question: if VPEC correction to zHD is disabled, do you want VPEC = VPEC_ERR = 0 in the output FITRES table, so that the output redshift and VPEC are self-consistent?

**Comment by bastiencarreres** [comment]
I think it's okay to have VPEC = VPEC_ERR = 0 in this case, since I can keep track of simulated VPEC that are stored in the `SIM_HOSTLIB_VPEC` column.

**Comment by RickKessler** [comment]
New input:
&SNLCINP
   OPT_VPEC_COR = 0   ! disable VPEC correction by setting VPEC=0

and default is OPT_VPEC_COR=1
