### ISSUE TITLE
add SIM_SALT2c and HOST_LOGMASS/LOGMASS_TRUE to spec efficiency function

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1407]
Add SIM_SALT2c and HOST_LOGMASS/LOGMASS_TRUE as usable varibales for the spec efficiency function.
Thank you!!!

**Comment by maria-vincenzi** [comment]
Great thanks!!
when adding LOGMASS, I noticed I always get zero event.
The error can be reproduced using the code here:
/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/speceff_bug/FAIL_REPEAT.CMD

**Comment by RickKessler** [comment]
A few years ago we refactored the HOSTLIB code to replace explicit LOGMASS variable with HOSTGAL_PROPERTY array that made it easier to add more variables such as COLOR and LOGsSFR. However, we left an obsolete LOGMASS variables that is no longer filled, and I had mistakenly used this to load values for SPECEFF map. After the fix (and removing a few obsolete variables), your test jobs results in 8/1000 selected (zmax=1.3). Reducing zmax to 1.0, then 12/1000 are selected.
