### ISSUE TITLE
Ignore duplicate CIDs in SALT2mu

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#141]
With the way BS20 interacts with Pippin, it's very difficult to avoid duplicate CIDs in our fitres files. RESET_CIDOFF: 2 doesn't work very well with how we set up our ymls. That being said, it would be nice if we could toggle the option to ignore duplicate CIDs in SALT2mu - right now it immediately aborts. Even better, if we could assign new CIDs in increasing order so that each label is unique, that would be even better, perhaps with another toggle. I've been doing it manually, but I'm recently running into issues that are slowing me down. 

Thanks!

**Comment by RickKessler** [comment]
From top of SALT2mu.c file:
   iflag_duplicate=1  # 0=ignore, 1=abort, 2=merge
