### ISSUE TITLE
creating simlib with spectra

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#1411]
Hi Rick, Qinan and I are working on SALT3 simulations with spectra, and I tried/failed to reproduce steps to get a SIMLIB file with TAKE_SPECTRUM keys.  Could you try the following?

```
cd $SNANA_DEBUG/djones/SIMLIB
snana.exe hicken09_test_spec.nml HEADER_OVERRIDE_FILE hicken09_test.FITRES.TEXT SIMLIB_OUT hicken09.SIMLIB SNCCID_LIST 2001ep
```

and note that the output file, hicken09.SIMLIB, doesn't include any TAKE_SPECTRUM keys even though SN 2001ep does have a number of spectra.  The kcor file referenced by hicken09_test_spec.nml does have a spectrograph defined.  Not sure if HEADER_OVERRIDE_FILE is necessary but I tried it both with and without.  Am I missing something obvious?  Thank you!

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by RickKessler** [comment]
yep, looks like a bug.

**Comment by RickKessler** [comment]
A while ago I modified snana.exe to only read spectra if they are needed, which was for reformatting data (e.g., TEXT->FITS, etc). I had forgotten to include the case when SIMLIB_OUTFILE is set, so this has now been fixed.
