### ISSUE TITLE
Adding Spectra into FITS files

### ISSUE THREAD

**Issue by MatSmithAstro** [RickKessler/SNANA#1412]
Hi Rick, 

As part of an upcoming data release, I'm trying to turn my .DAT files into .FITS files. This worked fine, when the .DAT files only included photometry, but now I'd like to include the spectra too.

To convert the files, I'm running the following command:
`snana.exe NOFILE PRIVATE_DATA_PATH ./ VERSION_PHOTOMETRY ZTF_Ia_DR2_FP_BINNED VERSION_REFORMAT_FITS ZTF_Ia_DR2_FP_BINNED_FITS OPT_YAML 1 OPT_MWEBV 3 OPT_REFORMAT_FITS 128`

- Including, OPT_REFORMAT_FITS=128 as indicated by the manual. 
***
However running this command gives the following error:
```
 FATAL ERROR ABORT called by wr_snfitsio_init_spec
   Invalid INPUTS_SPECTRO.WRITE_MASK = 0
   grep WRITE_MASK sntools_spectrograph.h | grep define
```
Grepping the relevant code, I see the following:
```
#define WRITE_MASK_SPEC_DEFAULT  2  // lammin lammax Flam FlamERR SIM_FLAM
#define WRITE_MASK_SPEC_SED_TRUE 4  // <lam> and SIM_FLAM only
```

Sorry, for being slow, but what does the above mean? The files all have the same spectral VARLIST: 

```VARLIST: LAMMIN LAMMAX FLAM FLAMERR SPECFLAG```

- matching the the .TEXT examples in $SNANA_ROOT

Do the spectra need a SIM_FLAM column or include a particular key? I'm a little stumped, and couldn't find any TEXT to FITS examples. 

An example failure can be found: `/home/smithmat/ZTF_DR2_Conversion/Example`

Many thanks

Mat

**Comment by RickKessler** [comment]
Since SPECTRA are used often is sims, but rarely in real data, a few real-data bugs crept in during some refactors. Mainly trying to read non-existing sim keys. Bugs fixed, and more robust logic has been added to skip sim-only keys that are (unfortunately) sandwiched between required real-data keys.

**Comment by RickKessler** [comment]
While debugging this issue, noticed that TEXPOSE is never read back (data or sim), and that an INSTRUMENT key needs to be added for each spectrum.

**Comment by RickKessler** [comment]
TEXPOSE and INSTRUMENT are read back for each spectrum.
