### ISSUE TITLE
Adding classifier probability to data headers as part of data stream

### ISSUE THREAD

**Issue by mattgrayling** [RickKessler/SNANA#1415]
I have run into several instances when it would be useful to have a classifier probability available as part of the data in a header, rather than having to cross-check this with another file. 

I appreciate this may not be straightforward as there are a variety of different classifiers/scores that currently exists. However, if there is a standard approach being used within a particular project/collaboration it would be useful to have a general key - maybe something like `CLASSIFIER_PIA` - which could be used in downstream analyses.

**Comment by RickKessler** [comment]
I'm gonna hold off on this for a while. Does it make sense to add P_Ia only without Prob for other types? Why not use private variable feature and specify arbitrary P_transient from multiple classifiers?
