### ISSUE TITLE
Modified MWEBV does not change the SN LC.

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1418]
Trying to understand how changing the MWEBV affects the SN LC.

When I run two simulations with the only modification being the addition of `ZVARIATION_POLY EBV_IGM 0,0.5,0.5` (large values for testing), the simulated MWEBV values are modified as expected, but this does not propagate to a change anywhere else in the LC.

I have set up a test example in `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3` where I have two sim commands (run by calling `./DES.CMD` and `./DES_EBV_IGM.CMD`, respectively) with one including ZVARIATION_POLY and the other not. 

I also set up a small python code to compare the two sims which can be run by calling `python compare_sims.py`. One can see that all aspects of the same example simulated SN are the exact same (including SIM_PEAKMAG_g, etc.) with the exception of MWEBV.

**Comment by RickKessler** [comment]
the new EBV_IGM call was made after everything was already computed; so while true MWEBV was updated, the smeared (measured) MWEBV was not updated. I fixed the placement of the call for adding EBV_IGM and checked that regression tests pass when NOT using EBV_IGM ... and leave it to you to test EBV_IGM.
