### ISSUE TITLE
simulate each SIMLIB LIBID exactly once?

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#142]
Hi Rick, potential feature request - if it's possible to simulate each SIMLIB LIBID exactly once, it will be easier to simulate samples that look exactly like real data.  Could work on this from the `$SNANA_DEBUG/djones/specsim3` directory once I update it in a few min.

**Comment by RickKessler** [comment]
try SIMLIB_MSKOPT += 4, and see manual.
