### ISSUE TITLE
simulating spectra results in seg fault

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#1423]
Hi Rick, been meaning to post this for a minute and just got around to it.  If you do a simulation with spectra, snlc_sim.exe appears to seg fault.  To reproduce:
```
cd $SNANA_DEBUG/djones/SIMLIB
snlc_sim.exe SALT3_SIM_FORQINAN.INPUT
```

**Comment by RickKessler** [comment]
original [version].SPEC file was created only for TAKE_SPECTRUM keys in sim-input file .... now it also works for TAKE_SPECTRUM keys in SIMLIB file as specified in your setup.

**Comment by djones1040** [comment]
Hi Rick, still seeing a segfault -- reproduce with the following:
```
cd $SNANA_DEBUG/djones/SIMLIB
snlc_sim.exe SALT3_SIM_FORQINAN.INPUT
```

**Comment by RickKessler** [comment]
In function wr_SIMGEN_DUMP_SPEC(), string allocation wasn't enough for many filters. Fixed to replace fixed-size allocation with NFILT-dependent allocation.

**Comment by djones1040** [comment]
thank you!
