### ISSUE TITLE
sntable doesnot write HOST2_MAG_xxx

### ISSUE THREAD

**Issue by am610** [RickKessler/SNANA#1424]
Based on the manual sec. 12.1 Selecting tables, I added the following in the LCFIT INPUT NML file 

`SNTABLE_LIST = ’SNANA(text:host2)’`

This would add the HOST2 parameters in the output SNANA table (FITRES and ROOT) files. 

However I see while I can produce most of the `HOST2_xxx` listed columns in the output, I am unable to obtain `HOST2_MAG_xx` columns where `xxx =` BANDS eg. `r` or `g` 

I am unable to resolve this issue, there is a working example in Perlmutter 

`/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_ELASTICC_DUST/2_LCFIT/FIT_DATA_PHOTOZ_LSST_SIMDATA/output/SPLIT_JOBS_LCFIT/test.sh`

**Comment by RickKessler** [comment]
Looking at the code (near end of subroutine INIT_TABLE_HOSTVAR inside snana.car), it was clearly writing HOSTGAL_MAGOBS only for 1st galaxy and not for second. I fixed it to write MAGOBS for both hosts in the same way as other variables. I checked that HOST2_MAG_[band] appears in VARNAMES list, but I did not check values. Fix pushed to GitHub and Perlmutter.
