### ISSUE TITLE
Feature request: PARSHIFT key to apply shifts to specific variables

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#1425]
Introduce a a key that allows us to add/subtract an arbitrary shift to a column i.e., all HOST_LOGMASS 

something similar to CUTWIN
PARSHIFT  LOGMASS 0.2
PARSHIFT  c 0.001
PARSHIFT  zHD 1.0E-4

**Comment by RickKessler** [comment]
To get help on this new feature:

SALT2mu.exe | grep PARSHIFT
PARSHIFT(DATAONLY)     zHD          1.0E-4   # shift all data zHD
PARSHIFT(DATAONLY)     HOST_LOGMASS 0.02     # shift all data LOGMASS
PARSHIFT(BIASCORONLY)  VPEC         22       # shift all biasCor VPEC
PARSHIFT               mB           1.0E-4   # shift mB in both DATA and BIASCOR
# Beware that PARSHIFT in BBC is not the same as shifting parameter at LCFIT stage

Currently implement for zHD, VPEC, fit params and HOST_LOGMASS.
