### ISSUE TITLE
Segmentation Violation with snlc_sim.exe

### ISSUE THREAD

**Issue by jasonlee17** [RickKessler/SNANA#1426]
Hi Rick, 

I'm running: `snlc_sim.exe SIMGEN_DCR_ASTROZ_REALISTIC_COADD.INPUT NGEN_LC 10` - but below is the error I get when the light-curves are being generated. 

	 Finished writing      1 of 10 (CID=       1, NEP= 35) 

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
    Module fullname              Module Filename
    ---------------              ---------------
    python/3.9-anaconda-2021.11  /opt/nersc/pe/modulefiles/python/3.9-anaconda-2021.11.lua

Thread 128 (Thread 0x7fd608871700 (LWP 1363835) "snlc_sim.exe"):
#0  0x00007fda35e9270c in pthread_cond_wait

... ... ... (A bunch of lines)

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007fda315407b2 in __vfprintf_internal () from /lib64/libc.so.6
#6  0x00007fda3152d646 in fprintf () from /lib64/libc.so.6
#7  0x000055fa4e4f6c57 in wr_SIMGEN_DUMP_SPEC ()
#8  0x000055fa4e52186f in update_simFiles ()
#9  0x000055fa4e4e0466 in main ()
===========================================================

**Here is the directory to the files: `/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/jasonlee/run_241001`**

Thanks!
Jason

**Comment by RickKessler** [comment]
FATAL ERROR ABORT called by rd2columnFile
   Could not open file
   /global/cfs/cdirs/des/jlee/SN_Ia/star_SEDs/ukk5v.dat

I don't have read permission

**Comment by RickKessler** [comment]
ATMOSPHERE_OPTMASK conflicts with SIMGEN_DUMP-SPEC that was created after DCR paper was submitted. Fix is to disable SIMGEN_DUMP-SPEC when simulating ATMOSPHERE_OPTMASK that generates true SEDs as spectra.
