### ISSUE TITLE
spectral simulation extrapolation (?) issue at red wavelengths

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#143]
```
cd SNANA_DEBUG/djones/specsim5
snlc_sim.exe JLA_TRAINING_OTHER_LOWZ.INPUT
```
the first simulated spectrum should have the issue (and some other spectra should also).

**Comment by RickKessler** [comment]
strange NIR behavior is due to large NIR scatter of G10 intrinsic scatter model. Try C11 or COVSED.SUGAR-L19 models.
