### ISSUE TITLE
SIMLIB can no longer be read

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#1430]
I am working on some Roman simulations, but running a simulation that worked a few weeks ago no longer works, and it seems to be related to reading in the simlib I am using (but haven't changed):

``` ******************************************************************
   SIMLIB_readGlobalHeader_TEXT
         Opened : /project2/rkessler/SURVEYS/ROMAN/USERS/epeterson3/RVroman/ROMAN/rose21_20_percent.simlib

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by readdouble
   Could not read double from string='#exposure-time' ;
   reading item 2 of 6 items.
```

Even when I remove the comment that begins with '#exposure-time' that the error mentions, the error is still thrown with the subsequent text in the simlib posted.

This error can be reproduced here, `/project2/rkessler/PRODUCTS/SNANA_DEBUG/epeterson3` by calling `./ROMAN.CMD`.

**Comment by RickKessler** [comment]
I suspect that for TEMPLATE_TEXPOSE_SPECTROGRAPH key, code is trying to read one value per band ... will check later.

**Comment by RickKessler** [comment]
parsing was confusing TEXPOSE with TEMPLATE_TEXPOSE_SPECTROGRAPH in global header ... fixed.
