### ISSUE TITLE
Support for dust laws with more than one parameter

### ISSUE THREAD

**Issue by stevet40** [RickKessler/SNANA#1434]
Currently, we assumed that the galactic extinction curves are just set by $R_V$. However, there are some more flexible families out there, e.g. the [Gordon et al. (2016)](https://ui.adsabs.harvard.edu/abs/2016ApJ...826..104G/abstract) curve which is a mixture of two kinds of dust (with the ratio set by a new $f_A$ parameter). It would be good to have support for these more flexible extinction laws; we can use this G16 example (with is already implemented with $f_A=0 hardwired) as a test case for what it might look like to have a curve with more parameters.

**Comment by RickKessler** [comment]
added sim-input key
PARLIST_MWCOLORLAW: p0,p1,p2...
where the argument is a comma sep list of float params (no pad spacing). This PARLIST_MWCOLORLAW array is passed to GALextinct,  but not yet used for anything. This update is therefore an infrastructure update only to enable more subtle modeling of MW color law

**Comment by stevet40** [comment]
Perfect, thanks!
