### ISSUE TITLE
wfit regression: Could not find 'wfit_uncertainty_fitpar'

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#1441]
Likely introduced in or around a72bd8a

See:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS_ANALYSIS_DUST_BACKUP/PS_ANALYSIS_DUST

/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS_ANALYSIS_DUST/6_BIASCOR/NOMINALSIM/output/SCRIPTS_BBCFIT/CPU0004_JOBLIST_midway2-login2.LOG

/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS_ANALYSIS_DUST_BACKUP/PS_ANALYSIS_DUST/6_BIASCOR/NOMINALSIM/output/SCRIPTS_BBCFIT/wfit0_OUTPUT_BBCFIT-0005_FITOPT003_MUOPT000.LOG

```
# ===================================================
 Get Marginalized values (speed_flag_chi2=0):
     Get Marginalized w
     Get Marginalized OM

# ============================================
 Estimate uncertainties:
      OM:
     STD OM_sig estimate = -nan (use=0)


# ================================================
  PRE-ABORT DUMP from function quickBinSearch :
     MINVAL=0.000000  MAXVAL=-nan  NBIN=501

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by quickBinSearch
   Something is REALLY messed up:
   Could not find 'wfit_uncertainty_fitpar' bin for VAL=1.585000e-01
```

**Comment by RickKessler** [comment]
You got burned by a rare BBC pathology in which all of the MUDIFERR values are crazy small. Look at 
zmore ../OUTPUT_BBCFIT-0005/FITOPT003_MUOPT000.M0DIF.gz 
and note that warning near top of file.

**Comment by RickKessler** [comment]
Scroll thru OUTPUT_BBCFIT-0005_FITOPT003_MUOPT000.LOG  and note
Check for Crazy Fitted M0 Errors  
	 Found 0 crazy M0 fit-errors and MNSTAT=2    NO_CRAZY_ERRORS HAS_COV_PROBLEM

	 Repeat BBC fit with initial alpha += 0.00100,  beta += 0.01000, 

MNSTAT=2 is a MINUIT flag meaning
"Full matrix, but forced positive-definite"
so BBC tries again with very tiny shift in the initial parameter values ... but it's not working well in this case.
It repeats the fit and gets crazy small errors. I will look into this more early next week.
