### ISSUE TITLE
LC Fit Cut Info Saved to a Table

### ISSUE THREAD

**Issue by nfshermy** [RickKessler/SNANA#1443]
Would it be possible to add a functionality that saves all the LC fit-cut info for all LCs to a single table (not just as printed output) to better examine common issues within the data and fitting? Is there potentially already such a utility that I am just unaware of? I could not identify any in the SNANA Manual.

Thank you!

**Comment by RickKessler** [comment]
if you output the SNANA table using
&SNLCINP
    SNTABLE_LIST = 'SNANA(text:key) FITRES'

you can examine ERRFLAG_FIT to see why events failed fit stage. In short, every event is written to the SNANA table, regardless of whether it is accepted. The ERRFLAG values are a bit cryptic and require grepping  the source code,

grep  ERRFLAG_   $SNANA_DIR/src/snlc_fit.car | grep '&' | grep =
     &  ,ERRFLAG_FITPREP_NOFILTERS  =  1  ! no valid filters
     &  ,ERRFLAG_FITPREP_NOEPOCHS   =  2  ! no epochs in FITINI_COV
     &  ,ERRFLAG_FITPREP_NEPOCH     =  3  ! too few epochs
     &  ,ERRFLAG_FITPREP_QUANTILES  =  4  ! quantiles either negative or not increasing
     &  ,ERRFLAG_FITPREP_ADJUST     =  5  ! bad chi2 on initial params (July 2024)
     &  ,ERRFLAG_FIT_BADCOV         =  9  ! MNSTAT returns ISTAT<3
     &  ,ERRFLAG_FIT_CRAZYERR       = 10  ! insane error detected
     &  ,ERRFLAG_FIT_MARGINALIZE    = 11  ! could not marginalize
     &  ,ERRFLAG_FIT_CUTS           = 12  ! failed 1 or more cuts
     &  ,ERRFLAG_ZFIT_DROPFILTCUTS  = 13  ! fail Zphot-cuts after drop filter
     &  ,ERRFLAG_ZFIT_RANGE         = 14  ! Zphot outside valid range
     &  ,ERRFLAG_FIT_FITPROB_ITER1  = 15  ! 1st iteration FITPROB cut (4/2024)
     &  ,ERRFLAG_FIT_SHAPE_ITER1    = 16  ! 1st iteration SHAPE cut (7/2024)
     &  ,ERRFLAG_FIT_COLOR_ITER1    = 17  ! 1st iteration COLOR cut
