### ISSUE TITLE
check_BADVAL_SALT2errmap

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1447]
Hello Rick,

There are some values that SNANA was not able to handle. They might be outside the range SNANA expects and they occurred in   /project2/rkessler/SURVEYS/ROMAN/ROOT/models/SALT3+SYS/SALT3.MODEL000/salt3_lc_model_variance_1.dat.gz.
Is there a way to let SNANA print them out as well as the wavelength range that they occurred in.

**Comment by RickKessler** [comment]
Updated genmag_SALT2.c to write bad ERRMAP values before abort.
