### ISSUE TITLE
 FATAL ERROR ABORT called by checkval_D

### ISSUE THREAD

**Issue by KeneAnumba** [RickKessler/SNANA#1448]
Hi Rick,
I encountered this issue which has to do color range. While my max colorlaw range is 20000. It seems that SNANA expected a value between 6000 and 18000.
Attached is a screenshot of the error
![Screenshot from 2024-11-21 10-20-45](https://github.com/user-attachments/assets/ae109ac3-54b4-442d-95e9-24eaaba7f00e)

**Comment by RickKessler** [comment]
please provide path and command to produce this abort.

**Comment by RickKessler** [comment]
fixed checkVal call to allow up to 25000 A (instead of 18000)
