### ISSUE TITLE
Fatal ErrorAbort called by ABORT_SIMLIB_FILTER

### ISSUE THREAD

**Issue by simran2296** [RickKessler/SNANA#1450]
Hi,

I am running SNANA simulations of DES machines after a couple of months. The SNANA version being used here is SNANA-11_05e. It was running fine a couple of months ago.

Before getting this error, I made some adjustments to the environment I use on DES machine in case there is a some connection between two.

PRE-ABORT DUMP from function ABORT_SIMLIB_FILTER : 
   isort=0  OBSRAW= 4 of 6 
   LIBID=1  MJD=58710.285  OPTLINE=1

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by ABORT_SIMLIB_FILTER
   Unknown SIMLIB filter=' ' 
   Expecting filter from : 'griz'

**Comment by RickKessler** [comment]
Need path and command to reproduce ABORT.

**Comment by simran2296** [comment]
The command is:

`/home/s1/simrankj/SNANA-11_05e/bin/snlc_sim.exe /data/des80.a/data/simrankj/DES_Followups/events/GW190814_test1_2024/sim_gen/SIMGEN_DES_NONIA.input `

It runs in: `/data/des80.a/data/simrankj/DES_Followups/events/GW190814_test1_2024/sim_gen/`

**Comment by OmegaLambda1998** [comment]
In python b'i' indicates a byte-string instead of a normal string, normally this happens either by literally appending `b` to your string creation (i.e. filter_str = b"...") or by reading a file in as a binary string (i.e. `with open(filter_file, "rb") as io:`)

**Comment by RickKessler** [comment]
Your SIMLIB.txt file looks very strange; compare with files here:
$SNDATA_ROOT/simlib/DES/
