### ISSUE TITLE
Error on table merge in LCFIT

### ISSUE THREAD

**Issue by paulshah** [RickKessler/SNANA#1452]
Fatal error in DES-type analysis run (same was working ~7 days ago).

Pippin yaml file :
/project2/rkessler/SURVEYS/DES/USERS/shahpa/dust_sim_pippinfiles/PS_analysis_dust.yml

Pippin output : 
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS_ANALYSIS_DUST

The logfile containing the error : 
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PS_ANALYSIS_DUST/2_LCFIT/Dsys_DATADESCCSIM/output/SPLIT_JOBS_LCFIT/CPU0008_JOBLIST_midway2-login2.LOG

Excerpt from logfile : 
# ===========================================
# merge_driver: Begin at 2024-11-29 10:45:12 (38712)
# merge_driver: read SUBMIT.INFO
# merge_driver:          Create BUSY_MERGE_CPU0008.LOCK for T_midnight=38712
# merge_driver: examine MERGE.LOG

         !!!! LCFIT_SUBCLASS = SNANA !!!!

# merge_driver: Finished 1 STATE updates (38712).
 Begin table merge for PIP_PS_SIM_NOMINAL_DUST_DATADESSIM_CC-0001_FITOPT001
   merge 40 ROOT table files.
         elapse time: 1.193672 sec for: merge 40 table files

 Write FAIL to done stamp file:
         ALL.DONE
# merge_driver:          Remove BUSY_MERGE_CPU0008.LOCK for T_midnight=38712
['Found 659 events in merged MERGE_PIP_PS_SIM_NOMINAL_DUST_DATADESSIM_CC-0001_FITOPT001.ROOT', 'but expected 766 from summing YAML files.', 'Table merge has a problem. Check command', '  merge_root.exe PIP_PS_SIM_NOMINAL_DUST_DATADESS$
NoneType: None

   

   `|```````|`
   <| o\ /o |>
    | ' ; ' | 
    |  ___  |     ABORT submit on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

**Comment by RickKessler** [comment]
Using submit_batch_jobs with snlc_fit.exe task,  SIM_MJD_EXPLODE can appear in some of the first-event SPLIT samples, but not in others; this can lead to ROOT-MERGE error when SIM_MJD_EXPLODE exists in first ROOT file, but not in another ROOT file. In the case above, SIM_MJD_EXPLODE is missing from PIP_PS_SIM_NOMINAL_DUST_DATADESSIM_CC-0001_FITOPT001_SPLIT007. 

As a quick fix for now, I removed SIM_MJD_EXPLODE from the snana/snlc_fit output tables. The sim sets this variable only for SIMSED models, but not for SNIa, nor V19_CC models, and hence it is not very useful. I don't even recall the original motivation for adding this variable, which was likely long before Covid19 and long forgotten.

For above abort, need to rerun entire snlc_fit.exe task.
