### ISSUE TITLE
kcor issue in dealing with multiple mag system in single kcor file

### ISSUE THREAD

**Issue by qnwang93** [RickKessler/SNANA#1457]
When I tried to run snlc_sim.exe based on UVEXT dataset on nersc server, I came across crazyflux error as follows:

`  PRE-ABORT DUMP from function check_crazyFlux :

 xxx -------------------------------------------------------
 xxx dumpEpoch_fluxNoise_apply called from check_crazyFlux
 xxx CID=685  MJD=57093.100  ifilt_obs=13(V)  LIBID=5
 xxx z=0.010  mu=33.174  Trest=-10.53  Tobs=-10.63  genmag(V)=   6.2
 xxx GEN(AV,RV) =  -9.000 ,  -9.000  SHAPEPAR= -0.276  (c=  0.023,mB=13.920)
 xxx
 xxx FLUXNPE(obs ) = 1.199160e+06 +_  5.663513e+03
 xxx FLUXNPE(true) = 1.209389e+06 +_  5.664416e+03
 xxx FLUXCAL(obs ) = 3.206839e+08, +_ 1.514558e+06
 xxx FLUXCAL(true) = 3.234193e+08, +_ 1.514800e+06
 xxx SKYSIG(S,T) = 0.700, 0.000 ADU/pix   PSFSIG = 0.849 pixels
 xxx ZPT(S,T) = 21.432, -99.000  (ADU)   GAIN=1.000000
 xxx GAURAN(S,T,ZP) = -0.909703, 0.810987, -0.704355
 xxx SIG_pe(SRC,TSRC, SKY,TSKY) = 1099.72,0.00   3.68,0.00
 xxx SIG_pe(ZP,HOST) = 11190.34, 0.00    SQSIG_RAN=-10228.93
 xxx SIG_pe(CALC, FINAL_TRUE, FINAL_DATA) = 1099.73, 5663.51, 5664.42
 xxx

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by check_crazyFlux
   flux=1.199160e+06 exceeds CRAZYFLUX=2.180460e+05
   See dumpEpoch details`

I tried changing the redshift of problematic objects in simlib, but crazyflux also changes in this case and the problem didn't get fixed.

I have put my input, kcor, and simlib files on NERSC server under $SNDATA_ROOT/sample_input_files/UVEXT/ as SALT3_SIM_FORQINAN.INPUT, UVEXT_modz.simlib and kcor_uvext.fits for people to reproduce the error.

**Comment by qnwang93** [comment]
Worked with David and it seems that multiple mag systems in the kcor file is the issue. Changed the mag system from AB to BD17 for SWIFT and with new kcor file the crazyflux error disappear. SNANA doesn't seem to process multiple mag system in the same file correctly so it might still be an issue to be fixed in the future.

**Comment by RickKessler** [comment]
First, I moved the UVTEXT/ subdirectory to
$SNANA_DEBUG/UVTEXT
because $SNDATA_ROOT is only for published products.

Next, which of these kcor input files was used to produce kcor_uvext.fits?
grep fits kcor_uvext*input
kcor_uvext_new2.input:OUTFILE:      kcor_uvext.fits
kcor_uvext_new.input:OUTFILE:      kcor_uvext.fits

**Comment by qnwang93** [comment]
I think kcor_uvext_new.input is the one, though there's only difference in the zeropoint value.

**Comment by RickKessler** [comment]
I tried re-creating the kcor file using both kcor_uvext_new.input and kcor_uvext_new2.input, and both fail. Please fix kcor-input to work and to reproduce the crazy-flux problem.

**Comment by qnwang93** [comment]
added a missing file to the folder and it should be able to run and reproduce the issue now

**Comment by RickKessler** [comment]
There is indeed an obscure trick to convert different mag systems to be on the same system ; see help with
kcor.exe | grep MAGSYST


I made these modification in your kcor-input file;
MAGSYSTEM:  AB->BD17
MAGSYSTEM:   VEGA->BD17


and the sim no longer aborts.
