### ISSUE TITLE
Issue with ring spectra

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#146]
We are creating spectra for a survey using an input spectrograph and galaxy PCA's.
We have noticed that the output simulated spectra have a ringing every 20 or so Angstrom. We are unsure as to why this is occurring. 
A test directory which includes all files along with a readme that has instructions on running have been created here 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/STEVE_SPECS/DEMOSv1/rick
The spectra generated will be for 360000seconds.

Thanks

**Comment by RickKessler** [comment]
split randoms into two streams, where 2nd stream is just for spectral noise. Ringing gone in test sims with DEIMOS.
