### ISSUE TITLE
Issue when running SALT2mu_fit.pl

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#150]
I am trying to run SALT2mu_fit.pl on SALT2mu_fitopt_001_B1b.input in 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/NEW_2020/B1bias/

I am getting an error referring to a specific id number. 
Please help.

**Comment by RickKessler** [comment]
IDSURVEY values for PS1MD are set to CID instead of 15, so the IDSURVEY values make no sense. I added new abort trap,
 FATAL ERROR ABORT called by compute_more_TABLEVAR
   Invalid IDSURVEY=-32768 (beware unsigned short) for BIASCOR SNID=353794
   Check $SNDATA_ROOT/SURVEY.DEF
