### ISSUE TITLE
iflag_duplicate doesn't work in SALT2mu.exe 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#157]
Hey Rick,

the iflag_duplicate flag doesn't work in SALT2mu.exe. I put it in my input file, but no matter what, SALT2mu thinks it's set to 1 and aborts immediately. 

I've set an example file in $SNANA_DEBUG/Brodie that should crash

**Comment by RickKessler** [comment]
removed requirement to abort on sim duplicates. Untested, so beware.
