### ISSUE TITLE
zCMBERR = 0.05 when using opt_photoz=2

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#165]
When running a simulation testing photo-z's using both host + sn (so opt_photoz=2) and applying a spectral efficiency map where in spectra should be obtained up to z=0.3, I seem to get a zCMBERR of 0.05 for objects up to z ~ 0.3. I am not sure why this is happening and is not the case when opt_photoz = 0.

The files for all the data can  be found in this directory 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/NEW_2020

MASTER_Survey_Photoz_B1bias.INPUT is the simulation input so ran sim_SNmix.pl on this.
SHALLOW_B1bias_HOST.NML is an example of a fitting file, so ran split_and_fit.exe on this. 

in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/NEW_2020/B1bias/PHOT_ALL I run BBC.
An example input file for SALT2mu_fit.pl is SALT2mu_fitopt_002_B1b.input  which has the output directory of SALTmu_FIT_002

In RAH the files of interest would be SALT2mu_FITOPT000_MUOPT001 and  SALT2mu_FITOPT001_MUOPT002

look at any object with zCMB between 0.1 and 0.3

**Comment by RickKessler** [comment]
subtle bug: for photo-z fits, ERRMAX_BAD was set to 5E-4. But using OPT_PHOTOZ=2, more precise zSPECERR causes zPHOT to be flagged as bad fit. Fix is to set ERRMAX_BAD=1.0E-8 for OPT_PHOTOZ=2.
