### ISSUE TITLE
HOSTLIB with WGTMAP including x1 

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#166]
Hi!
I was trying to rerun the tests in $SNANA_DEBUG/HOSTLIB_WGTMAP+x1.
I tried to rerun the test with the 1D, 2D and 3D map and I noticed that both 2D and 3D are somehow broken.

When I run the test using 2D wgtmap the code get stuck (probably while creating the pre-computed grids of weights... I see in the output the memory usage is pretty high `Interpolate WGTMAP for each galaxy (248890.57 MB)` 

When I run the test using 3D wgtmap the code seems to work fine (and memory usage is 0.00 MB which looks suspicious) but it crashes with 
` *** Break *** segmentation violation` just before starting generating the lightcurves.
Any idea of what is going on? 
Thanks!

**Comment by RickKessler** [comment]
seems like some odd cut-and-paste mistake had corrupted a line of code by appending '++' on an integer index. Fixed and updated on Midway2.
