### ISSUE TITLE
photoz in SALT2mu

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#167]
Hey Rick - I've been seeing problems with 1D bias corrections using photo-z's for both WFIRST (Rebekah Hounsell) and DES (Rebecca Chen), in that the 1D bias corrections given same inputs as data dont remove distance biases in data.  Im pretty sure this is because the bias corrections are in terms of (mb+ax1-bc), but there are biases in the redshift.  Is there an option to use mu_model(zcmb) in SALT2mu for bias corrections?  I am pretty sure you have an option to use sim_dlmag - which is similar, but set for the true redshift.

**Comment by RickKessler** [comment]
was fixed before July 4 holiday weekend. See slack memo.
