### ISSUE TITLE
FATAL ERROR ABORT called by checkLamRange_SEDMODEL

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#169]
I am finding my fitting aborts with the following error...
PRE-ABORT DUMP from function checkLamRange_SEDMODEL :
 Calling function ‘genmag_SALT2’ passed ifilt=1(‘R062-R’) and z=0.0000
 Rest-frame Lambda-Range (LAMREST_MIN/MAX) = 3499.963392 to 24999.738514
 SED Lambda-Range: 500.000000 to 24990.000000
 LAMFAIL_LO/HI = 0, 1
  `|```````|`
  <| o\ /o |>
  | ' ; ' |
  | ___ |   ABORT program on Fatal Error.
  | |’ ‘| |
  | `---' |
  \_______/
 FATAL ERROR ABORT called by checkLamRange_SEDMODEL
  R062-R lambda range is outside defined SED range.
  Consider using &FITINP variable RESTLAMBDA_FITRANGE.
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0 0x7F38201E5697
#1 0x7F38201E5CDE
#2 0x7F381F3D93EF
#3 0x7F381F4F9336
#4 0x7F38242D3DD7
#5 0x7F38242D421E
#6 0x7F38223A1610
#7 0x7F382429ED7C
#8 0x7F3823C634F9
#9 0x7F3823C623D8
#10 0x7F3823C765AA
#11 0x7F3824267F3F
#12 0x7F3824268769
#13 0x7F381F3DD049
#14 0x7F38242409D2

This occurs when running split_and_fit.pl project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z SHALLOW_A1_HOST.NML

The error file can be found here...
project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/NEW_2020/A1_SHALLOW_HOST_2020/SPLIT_JOBS_LCFIT/Shallow_Photoz_02_NOM_A1_2020_RAH_FITOPT001_SPLIT007.LOG

Thank you

**Comment by RickKessler** [comment]
I think the issue is that MINUIT is attempting a very large variation in zPHOT, which leads to the chi2 function aborting. A simple fix (for one event) is to change the global fit bound,
PHOTOZ_BOUND = 1.0E-6, 2.99
to
PHOTOZ_BOUND = 1.0E-3, 2.99

so that MINUIT will not try crazy-small zPHOT values.

**Comment by RickKessler** [comment]
resolved.
