### ISSUE TITLE
FATAL ERROR ABORT called by SNTABLE_NEVT_TEXT

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#171]
When running SALT2mu_fit.pl with NSPLITRAN option I am receiving this error:

 FATAL ERROR ABORT called by SPLITRAN_read_fitpar
   Could NOT open SPLITRAN file for reading:
   SPLITRAN-0001/SALT2mu_FITOPT000_MUOPT000.fitpar

Checking the logs in SPLITRAN-0001/ I see

 FATAL ERROR ABORT called by SNTABLE_NEVT_TEXT
   Could not open ascii table file:
   'OLD_merged.FITRES'

Input file that is producing error is $PIPPIN_OUTPUT/GT_STAT_03/BIASCOR_ROUND3/OLD/BBC_3YR_OLD_DESSIMDATA_LOWZSIMDATA.input and error logs are in $PIPPIN_OUTPUT/GT_STAT_03/BIASCOR_ROUND3/OLD/output/

**Comment by RickKessler** [comment]
NSPLITRAN has recently been updated to write each SPLITRAN output to a separate subDir for Pippin compatibility, and therefore the input datafile is no longer in the same directory as where the SALT2mu job runs. Thus, need to include full path in datafile by replacing
   file=OLD_merged.FITRES
with
   datafile=[path]/OLD_merged.FITRES
(and note that file= and datafile= are the same, but the latter is more informative to distinguish between biasCor & CCprior)
