### ISSUE TITLE
Crashing without abort traps

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#172]
Hey Rick - I think the new update caused some weird crashing issues. Launching a job (via pippin, but this is a slurm issue, it seems), I get slurm errorcode 2.

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-RV-4/1_SIM/DES_DATA/LOGS/PIP_BP-RV-4_DES_DATA_0001.LOG

Everything within /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-RV-4/1_SIM/ sort of dies immediately for the same reason, this segmentation fault.

I might be missing something? Either way let me know!

**Comment by RickKessler** [comment]
check your scratch quota.

**Comment by bap37** [comment]
Scratch quota is fine, not getting any warnings and it isn't full.

**Comment by RickKessler** [comment]
failure occurred because GENPDF_FILE did not exist, and I had forgotten to leave an abort trap. Abort trap now included in SALT2mu.c

**Comment by bap37** [comment]
Everything seems kosher now... Closing the ticket for the moment.
