### ISSUE TITLE
DONE file reporting success, but LOG file showing abort message.

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#173]
When running SALT2mu_fit.pl (with nsplitran) on 
$PIPPIN_OUTPUT/GT_STAT_03/BIASCOR_ROUND3/OLD/BBC_3YR_OLD_DESSIMDATA_LOWZSIMDATA.input 
I get a  Final STATUS for DONE file: SUCCESS message, but when I check the log in the output subdirectory I see 
FATAL ERROR ABORT called by SPLITRAN_read_fitpar
   Could NOT open SPLITRAN file for reading:
   SPLITRAN-0006/SALT2mu_FITOPT000_MUOPT000.fitpar

The SPLITRAN-0006 dir is empty.  Directories 0001-0005 seem to run as expected?

**Comment by RickKessler** [comment]
I mistakenly had 'cd' command only for first sub-directory; SALT2mu_fix updated on Midway, but not tested, so please try again and let me know what happens.

**Comment by geotaylo** [comment]
It looks to be working correctly now, thanks.
