### ISSUE TITLE
Specz efficiency as a function of SN year of discovery

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#177]
Hello,
I would like to build a z-Host Efficiency function that is not just a function of galaxy properties but also a function of the SN PEAKMJD? Reading the manual (Section 4.17.3) it looks like the list of VARNAMES in the SEARCHEFF_zHOST file can only include HOSTLIB properties, is this correct? Is there a way to implement also PEAKMJD?

**Comment by RickKessler** [comment]
code and manual (page 49) updated (here and on Midway). However, new PEAKMJD_RANGE feature is NOT tested, so please test carefully. Either comment with command to reproduce bug, or close issue if working.

**Comment by maria-vincenzi** [comment]
I tested this and I find few bugs (see $SNANA_DEBUG/EFF_zHOST_PEAKMJD)
I run both:
1) a test simulation using the new Efficiency zHost specified for different Fields and years. INIT_HOSTLIB() gives the error:
```
 FATAL ERROR ABORT called by read_VARNAMES_KEYS
   NVAR=15 exceeds MXVAR=10
   called by read_VARNAMES_zHOST, VARNAMES[0]=r_obs

```
In order to reproduce this run` sim_SNmix.pl Test_sim_EFFzHOST_wPEAKMJD.input` in $SNANA_DEBUG/EFF_zHOST_PEAKMJD and check log files in $SNANA_DEBUG/EFF_zHOST_PEAKMJD/LOG_wPKMJD
2) a test simulation using my old Efficiency zHost which is just a function of the different Fields.
This is not working anymore. When I start to generate light curves I get the error:
```
FATAL ERROR ABORT called by interp_SEARCHEFF_zHOST
   Invalid NMATCH=10 for
   field = 'S2'  PEAKMJD=57122.890

```
In order to reproduce this run` sim_SNmix.pl Test_sim_EFFzHOST_noPEAKMJD.input` in $SNANA_DEBUG/EFF_zHOST_PEAKMJD and check log files in $SNANA_DEBUG/EFF_zHOST_PEAKMJD/LOG_noPKMJD

**Comment by RickKessler** [comment]
fixed a few bugs and extended max number of allowed maps; try again.

**Comment by maria-vincenzi** [comment]
OK! working beautifully!
