### ISSUE TITLE
Output columns hostgal_ssfr and hostgal_logmass not filled

### ISSUE THREAD

**Issue by AnomandarisPurake** [RickKessler/SNANA#178]
We are now using Steve Rodney's hostlib which contains logssfr and logmass columns. However, in the output, the columns hostgal_ssfr and hostgal_logmass contain only the value -9.

The input file is
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/MASTER_Survey_spec_candels_galid.INPUT
and the hostlib is in the same directory.

**Comment by RickKessler** [comment]
which HOSTLIB ?
ls *HOSTLIB
Akari_Hosts_SNR.HOSTLIB         Akari_Hosts_subset_SNR_v3.HOSTLIB
Akari_Hosts_SNR_v5.HOSTLIB      Akari_Hosts_subset_SNR_v4.HOSTLIB
Akari_Hosts_subset_SNR.HOSTLIB  Flipped.HOSTLIB

and please point to 'output' that has -9 values. Do you mean data files, or FITRES files after light curve fitting ?

**Comment by AnomandarisPurake** [comment]
Sorry for being unclear. As of right now, the hostlib is Big_Flipped.HOSTLIB
This one works fine. The output for this is at
/scratch/midway2/rkessler/SNDATA_ROOT/SIM/Deep_Spec_KXW_New_SteveFlipped/
I mean the FITS.gz files in there.

**Comment by RickKessler** [comment]
Under $SNANA_DEBUG, please setup a sim-input file that runs from snlc_sim.exe (not sim_SNmix) and reproduces the issue with a few events. Try changing to TEXT format (FORMAT_MASK: 2) so that it's easier to see the bad host property values.

**Comment by AnomandarisPurake** [comment]
Scripts are here
/project2/rkessler/PRODUCTS/SNANA_DEBUG/kxw
Output text files are here
/project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/KXW_DEBUG
These files do not have hostgal_logmass or hostgal_ssfr. Did we miss some step where we tell SNANA to look for these properties?

**Comment by RickKessler** [comment]
To include arbitrary set of host properties in the output data files,
   HOSTLIB_STOREPAR:  logmass,logssfr 
Note that these variables are automatically passed to output tables (e.g., FITRES table from snlc_fit).
I thought that WGTMAP variables were automatically included in the data files, so I will check if there's a bug or if I can add this auto-store feature.

**Comment by RickKessler** [comment]
simulation is fixed so that WGTMAP variables are automatically written to data files. There is no harm in listing these WGTMAP variables in HOSTLIB_STOREPAR, but no need to do so.
