### ISSUE TITLE
I can't run sim_SNmix.pl (username problems?)

### ISSUE THREAD

**Issue by AnomandarisPurake** [RickKessler/SNANA#180]
sim_SNmix.pl does not work for me (kxw) during file operations. (Hasn't ever worked; Dan and Brodie have run all jobs for me)
I am working in 
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/
the command is
sim_SNmix.pl MASTER_Survey_spec_candels_galid.INPUT
This works for Dan and Brodie.
snlc_sim.exe works fine for me.

The problem is visible in the logs in
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/SIMLOGS_SIMULATED_New_KXW
Looking in
SIMnorm_Deep_Spec_KXW_New_SteveFlipped_SNIa.LOG
my username appears to be treated as kxw "newline"
Compare with logs in
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PHOTO_Z/SIMLOGS_TEST_KXW
The temp files use the first 4 characters of the username. But my username only has 3 characters.

**Comment by RickKessler** [comment]
type 'quota' and check scratch.

**Comment by AnomandarisPurake** [comment]
0.00K used
7 files used

**Comment by RickKessler** [comment]
ok, this is a very strange bug. The sim-version names include first 4 characters of user name, but your user name only has 3 chars ... thus the file names had a blank space which resulted in the aborts. I fixed sim_SNmix to append zeros until there are 4 characters, so kxw should appear as kxw0 .

**Comment by AnomandarisPurake** [comment]
Seems to be fixed
