### ISSUE TITLE
overwriting pythonxxx flags in header files cause merge conflicts

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#182]
Hi Rick, just raising the issue we talked about today about the PYTHONxxx flags that get overwritten during make stage.

**Comment by RickKessler** [comment]
At NERSC the HBOOK flag is masked as USE_HBOOKxxx in sntools_output.h, yet 'git pull' still works without throwing an error about a conflict.  Can you setup an example where PYTHONxxx causes a problem ?

**Comment by RickKessler** [comment]
ignore comment above; issue is time-ordering. What is $SNANA_PYTHON_DIR on Midway ?
