### ISSUE TITLE
BEAMS part of BBC

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#185]
Something I'm doing doesnt seem to be working because a diff on two different runs of BBC (one with BEAMS and one without) returns no differences.

/project2/rkessler/PRODUCTS/SNANA_DEBUG/djbrout/RUNTEST

**Comment by RickKessler** [comment]
Both log files show that CC prior was turned off because u13 wasn't set:
grep WARN S*LOG | grep scale
SALT2mu_NOTYPES.LOG:	 WARNING: scalePCC(u13,p13)=0,0 --> turn off CC prior
SALT2mu_WITHTYPES.LOG:	 WARNING: scalePCC(u13,p13)=0,0 --> turn off CC prior
