### ISSUE TITLE
Vpec_file deprication

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#186]
now that vpec_file is depricated, I have run across the issue that I have some subset of SNe that need updated host masses and a separate subset of sne that need vpec updates but there they arent a 1 to 1 mapping. maybe multiple header override files could be accepted?? (I much prefer that over having to merge them myself and applying some special character to designate when a mass or vpec should not be updated...)

**Comment by RickKessler** [comment]
Updated SNANA on midway to allow comma-separated list; e.g.,
  &SNLCINP
       HEADER_OVERRIDE_FILE = 'file1.dat,file2.dat,file3,dat'
Each variable can appear in only one file.

**Comment by djbrout** [comment]
thank you!!
