### ISSUE TITLE
relative_variance -> variance in SALT3 file names

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#187]
hi Rick, could you change relative_variance -> variance in the SALT3 filenames that SNANA searches for?  I think "relative variance" is confusing, especially with how we're now doing things.

**Comment by RickKessler** [comment]
done ... but not tested.

**Comment by mi-dai** [comment]
hi Rick, I got a Segmentation fault
can reproduce the issue with:
`cd $SNANA_DEBUG/mdai/sim_lowzps1_pipeline`
`snlc_fit.exe $SNANA_DEBUG/mdai/sim_lowzps1_pipeline/pipeline/snfit_TEST.nml.temp.1595536187.7635984_111 VERSION_PHOTOMETRY AllSurveys_LOWZ_111 TEXTFILE_PREFIX AllSurveys_LOWZ_111_FITOPT000_SPLIT010 JOBSPLIT 10 10 MXLC_PLOT 3`

**Comment by RickKessler** [comment]
SALT3.test version has no SALT3.INFO file. And it seems that SALT2 and SALT3 files are mixed together in same model directory; I would suggest Not mixing these files.

**Comment by mi-dai** [comment]
SALT3.test is an old directory. I used SALT3.test_111 in the input nml file.

**Comment by RickKessler** [comment]
variance file is corrupted; e.g., 
   grep '2500.'  salt3_lc_variance_0.dat 

shows lots of nan values

**Comment by RickKessler** [comment]
I am pretty sure this issue is fixed. The segFault above is a different issue, so I added additional checks on the SALT2 error maps, to abort on NaN and crazy values.

**Comment by djones1040** [comment]
yep, I agree - sorry for being slow on this.  I'll fix the crazy SALT3 values ASAP
