### ISSUE TITLE
Error in simulating LCLIB PLAsTiCC models

### ISSUE THREAD

**Issue by rmorgan10** [RickKessler/SNANA#188]
I've tested both AGN and Mdwarf simulations and I get the following error message for both cases:
```
FATAL ERROR ABORT called by get_random_genPDF
   Found 0 PDF options for parName='NULL'
   Requires 1 PDF option; check AsymGauss and GENPDF_FILE.
```
This is new behavior for an snlc_sim.exe input file that has worked previously.

**Comment by RickKessler** [comment]
fixed, but not tested.

**Comment by rmorgan10** [comment]
Tested and works perfectly.
