### ISSUE TITLE
combine_fitres.exe fails on large simulations

### ISSUE THREAD

**Issue by jalasker** [RickKessler/SNANA#192]
When running combine_fitres.exe on a large sim file (~500k events), this error appears; 

*** Error in `combine_fitres.exe': free(): invalid pointer: 0x0000000001c6aa00 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x816b9)[0x7f6aa96c96b9]
combine_fitres.exe[0x4fd989]
combine_fitres.exe[0x4f15ba]
combine_fitres.exe[0x4d1e6a]
combine_fitres.exe[0x4c6868]
combine_fitres.exe[0x4c5cb8]
(and a lot more backtrace....)

Before the error occurs ~11k events are written to the output file. 

This error does not occur when running on the data/datasized sims (~3k events). 

Files necessary to reproduce are in $SNANA_DEBUG/Lasker. README gives code to run there.

**Comment by RickKessler** [comment]
Try disabling HBOOK output using one of the T/t options 
    (see top of combine_fitres.c code for instructions);
combine_fitres.exe <fitres1> <fitres2> .. T   ! [outPrefix].TEXT
        or
combine_fitres.exe <fitres1> <fitres2> .. t   ! [outPrefix].text
      (create only text output; disable default hbook output)

**Comment by jalasker** [comment]
It works with HBOOK disabled. Given that even when it worked up until this week it still threw a ton of supposed errors writing the HBOOK file, I think it's time to make the default behavior no HBOOK.

**Comment by RickKessler** [comment]
when the batch-control scripts are re-written, we can think about changing combine_fitres defaults.
