### ISSUE TITLE
SNANA thinks I'm simulating more spectra than I am?

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#196]
Hi Rick, just went back to try the spectral SALT3 training simulations from a couple months ago and getting a bunch of new errors (does USE_SIMLIB_SPECTRA flag always cause errors now?).  Most I think I solved but there's one in where SNANA is telling me that the number of TAKE_SPECTRUM keys exceeds the bound when it doesn't.  Example is in $SNANA_DEBUG/djones/spectra and you can run it with:
```
snlc_sim.exe JLA_TRAINING_Jha06.INPUT
```
Thanks!

**Comment by RickKessler** [comment]
was silly refactor bug that did not reset the NTAKE_SPECTRUM counter each event; try again.

**Comment by djones1040** [comment]
works now!  though I'm confused what's going on with the USE_SIMLIB_SPECTRA key.  Is this back to working how it used to, where it has to be turned on to use spec in the simlib?  Closing out this issue regardless.

**Comment by RickKessler** [comment]
yes, you need to set
USE_SIMLIB_SPECTRA: 1
to read the TAKE_SPECTRUM keys in the SIMLIB.
