### ISSUE TITLE
Overriding zCMB incompatible with zHELIO (zCMB/zHELIO tolerance error)

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#197]
As discussed, header override doesn't take REDSHIFT_HELIO columns, needs to be recomputed

**Comment by RickKessler** [comment]
zHELIO is now re-computed when REDSHIFT_FINAL is read from HEADER_OVERRIDE ... but I didn't test it.

**Comment by rebeccachen0** [comment]
I'm no longer getting the error, so looks resolved to me. Thank you!
