### ISSUE TITLE
BBC distance residuals don't make sense

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#200]
Hi Rick,

I'm investigating a discrepancy between the SALT2mu_FITOPT000_MUOPT000.FITRES and the SALT2mu_FITOPT000_MUOPT000.M0DIF file that I don't understand, any help would be greatly appreciated.  Basically with GENPERFECT (and normal) simulations with input w = -1, we're not getting w = -1 back.  If we zoom in on the individual FITRES files, there's a discrepancy between the FITRES and M0DIF files that could be pointing to the issue.  Check out:
```
$SNANA_DEBUG/djones/BBC/Run_GetMu_902/AllSurveys_LOWZ_902/SALT2mu_FITOPT000_MUOPT000.FITRES
$SNANA_DEBUG/djones/BBC/Run_GetMu_902/AllSurveys_LOWZ_902/SALT2mu_FITOPT000_MUOPT000.M0DIF
```
you can re-generate these files with:
```
cd $SNANA_DEBUG/djones/BBC
SALT2mu_fit.pl BBC_test.input
```
If I zoom in on the first non-zero bin in the M0DIF file, I see the following:
```
ROW:      5   0.0197  0.0234  0.0217    -0.0341    0.0378  34.8800   10
```
and then if I pull up the FITRES file, I can isolate the 10 SNe contributing to this bin:
```
# CID MURES MUERR
29504.0 0.0418 0.1215
87751.0 -0.0385 0.1137
325.0 -0.0246 0.1143
65097.0 0.0481 0.1251
50292.0 -0.1136 0.1155
90494.0 -0.009 0.1204
40185.0 0.0472 0.1247
80675.0 0.0455 0.1243
80334.0 0.0489 0.1181
11507.0 -0.0197 0.1187
```
The median of these values is 0.0164.  The mean is 0.003.  The weighted average is -6.34e-6.  So why does the M0DIF file disagree?  This isn't a global offset - if I take the highest-redshift bin:
```
ROW:     25   0.5906  0.7000  0.6281     0.0104    0.0212  42.8597   21
```
and do the same procedure, I get a weighted average of -1.4e-5.  My thought was that the final MURES values come after bias correction, etc etc, so should be a good representation of what's in the M0DIF files.

phew, this was a long one.  thanks for all your help Rick!

**Comment by RickKessler** [comment]
at the top of the FITRES file, note this comment:
# MU-RESIDUAL NOTE: MURES = MU-(MUMODEL+M0DIF)

**Comment by RickKessler** [comment]
Note this comment at top of FITRES file:
    MU-RESIDUAL NOTE: MURES = MU-(MUMODEL+M0DIF)

**Comment by djones1040** [comment]
crap thanks Rick.  closing for now at least
