### ISSUE TITLE
wfit.exe results don't make sense?

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#201]
Hi Rick,

Well my previous issue was a dud so I'm still digging.  Check out wfit.exe results for this example FITRES/M0DIF file:
```
cd $SNANA_DEBUG/djones/BBC
wfit.exe Run_GetMu_902/AllSurveys_LOWZ_902/SALT2mu_FITOPT000_MUOPT000.M0DIF
cat Run_GetMu_902/AllSurveys_LOWZ_902/SALT2mu_FITOPT000_MUOPT000.M0DIF.cospar
```
that gives:
```
# w  wsig_marg  OM  OM_sig  chi2  Ndof  sigint  wran  OMran  label
 -1.0500   0.0826   0.3175   0.0320       1.3     18  -0.002  0.00  0.00  none
```
I checked this with cosmomc to make sure I wasn't crazy, and got w = -1.025 +/- 0.02.  Could you investigate why these errors are so high?  8% on w is pretty huge for sub-percent errors.

**Comment by RickKessler** [comment]
what priors are used in CosmoMC ? BAO, CMB ? wFit command doesn't seem to have any prior options, which should result in much larger errors.

**Comment by djones1040** [comment]
just CMB - I thought an OM prior from Planck was default though, which should replicate the planck results?
