### ISSUE TITLE
Command line parser fails on VEL_CMBAPEX 0.0 argument

### ISSUE THREAD

**Issue by charlesprior** [RickKessler/SNANA#208]
Hi Rick, I'm still having a problem with Pippin and command line argument errors. I put an example in $SNANA_DEBUG/cprior:

Running `snlc_sim.exe CP_HALO_SIM_IA.input GENVERSION DEBUG_PIP_CP-HALO-CMB_LOWZ_DATA_norm INIT_ONLY 1 HOSTLIB_FILE /project2/rkessler/SURVEYS/PS1MD/USERS/cprior/peculiar_velocities/halo_sim/hostlibs/HOSTLIB_082120.txt HOSTLIB_MSKOPT 536 HOSTLIB_DZTOL 0.00001 0.0003 VEL_CMBAPEX 0.0 SIMLIB_MAXRANSTART 0
` while in `$SNANA_DEBUG/cprior` produces the following error:
`  CHECK_ARGV ERRORS: 
 	 ERROR: detected un-used command-line arg: 0.0 
...
 FATAL ERROR ABORT called by check_argv
   1 invalid/unknown command line arg(s)
   Check all 17 command-line args
`

**Comment by charlesprior** [comment]
The `SIMLIB_MAXRANSTART 0` also seems to still be causing an issue for me even when I move the VEL_CMBAPEX key into my .input file, but I can't get rid of this from the command line when using Pippin I think.

**Comment by RickKessler** [comment]
HOSTLIB_DZTOL should have 3 arguments (2nd order poly). Since there are only 2 arguments, it reads the next key (VEL_CMBAPEX) as 3rd argument for HOSTLIB_DZTOL
