### ISSUE TITLE
BBC error/clarification

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#211]
Hi Rick,

I'm digging into why BBC implemented in Mi's pipeline is giving too-high intrinsic dispersion and biased alpha/beta, and I'm finding a few weird things in the data that could be bugs or could just be a lack of understanding on my part about how things are working.

I set up a test job:
```
cd $SNANA_DEBUG/djones/BBC3
SALT2mu_fit.pl BBC_test.input
```

The first thing I noticed was that the intrinsic dispersion, 0.1293, is greater than MUERR for a number of SNe, even the first SN (65028).  Shouldn't this be impossible if dispersion is just getting added in quadrature?  Thanks,

David

**Comment by RickKessler** [comment]
first recommended test is to generate sims with z=0.01 and EXPOSURE_TIME 1000, and then check RMS for mu(Tripp) - mu(True). This should clarify if the sigma_int issue is in the simulation or in SALT2mu.
