### ISSUE TITLE
No way to correctly specify library location in Ubuntu

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#212]
Hello,

I tried to install SNANA on Ubuntu 20.04 and had a problem with GSL static libraries location. While they are installed by package manager to `/usr/lib/x86_64-linux-gnu/` which is surely is searchable by the compiler, the `Makefile` specifies library paths as `$(GSL_DIR)/$(LIB_SDIR)/libgsl.a` and `$(GSL_DIR)/$(LIB_SDIR)/libgslcblas.a` where `$(LIB_SDIR)` is not configurable and equals `lib` in my case:
https://github.com/RickKessler/SNANA/blob/ce4339c3520d238cfbf2830478c1e19e6b056a56/src/Makefile#L195-L196

It makes impossible to specify environment variables outside of the `Makefile` to set the right library paths because my path doesn't end with `lib`

**Comment by RickKessler** [comment]
It's been many years since I knew anyone running SNANA with Ubuntu, so I'm not surprised that it doesn't work. Can you hack a Makefile that works, and a way for Makefile to recognize Ubuntu ? Maybe I can incorporate your changes.

**Comment by hombit** [comment]
The problem is not for Ubuntu only, but every Debian-based Linux. Moreover another distributions, like openSUSE 15.2 and Fedora 32, don't provide static libraries at all

The simplest solution is to use dynamic libraries, but probably it will break someone's build script

**Comment by RickKessler** [comment]
Apologies for late response. The current setup works at several national labs and universities where we do our research. Unfortunately we don't have resources to assist with other systems.
