### ISSUE TITLE
New error when using BYOSED

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#214]
Working example is in `$SNANA_DEBUG/BYOSED`. If I run BYOSED on its own outside of SNANA by just running the `genmag_BYOSED.py` file in `$SNANA_DIR/src`, works fine so I know my BYOSED setup file is fine. This error is new since the most recent update, I wasn't getting this before today when I updated to the newest version of SNANA.

```FATAL ERROR ABORT called by get_random_genPDF
   Found 0 PDF options for parName='NULL'
   Requires 1 PDF option; check AsymGauss and GENPDF_FILE.

**Comment by RickKessler** [comment]
fixed interference bug with recent genPDF option.
