### ISSUE TITLE
request to remove echo SNANA_DIR from midway SNANA sourceme

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#215]
Hi Rick, could we please remove this line
```
echo " SNANA_DIR -> $SNANA_DIR "
```
from SNANA_setup.sourceme?  Having that line makes all scp/rsync commands fail when I'm trying to grab files from midway.

**Comment by RickKessler** [comment]
Done. But if you still have problems from the DUI utility, try adding this in your .bashrc file,
[[ $- != *i* ]] && return
