### ISSUE TITLE
Another new Abort when running BYOSED

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#216]
This is another new abort since the update, less obvious because the batch submission appears to work but there is an abort on 1 or more of the jobs, not all. It may be hard to reproduce because I'm running on the BYOSED branch, which should be up-to-date with master, but could have other differences like gcc version, python version, etc. My `SNANA_PYTHON_DIR` is `/project2/rkessler/PRODUCTS/miniconda`, and the sim example is again in `$SNANA_DEBUG/BYOSED`. The command to run here is `sim_SNmix.pl simulation/SIMGEN_WFIRST_SALT2_Specz.INPUT`, and the corresponding snlc_sim.exe job is 

`snlc_sim.exe simulation/SIMGEN_WFIRST_SALT2_Specz.INPUT PATH_SNDATA_SIM /scratch/midway2/rkessler/SNDATA_ROOT/SIM CIDRAN_MIN 0 CIDRAN_MAX 69459 CIDOFF 10000 JOBID 11 NJOBTOT 25 GENVERSION TMP_djon_BYO_BBC-0011_44803 GENPREFIX SIMULATED_SPEC_SURVEY_DMS_SNIa-0011 RANSEED 954321 FORMAT_MASK 48 GENMODEL /project2/rkessler/SURVEYS/WFIRST/USERS/jpierel/hyperion_wfirst/byosed/BYOSED.TEST GENRANGE_REDSHIFT 0.5 1.5 GENALPHA_SALT2 .14 GENBETA_SALT2 3.1 GENPEAK_SALT2c 0 GENSIGMA_SALT2c 4 4 GENRANGE_SALT2c -.4 .4 GENPEAK_SALT2x1 0 GENSIGMA_SALT2x1 10 10 GENRANGE_SALT2x1 -4 4 `

Which appears to run fine. Take a look in the log file here for the abort:

`$SNANA_DEBUG/BYOSED/SIMLOGS_SIMULATED_SPEC_SURVEY_DMS/SIMULATED_SPEC_SURVEY_DMS_0021.LOG`

**Comment by RickKessler** [comment]
49 of the 50 TMP*LOG files have  "Wrote" in them ... please find the one that doesn't. Or, run the new submit_batch_jobs.py, which has much better diagnostics for this sort of problem.

**Comment by djones1040** [comment]
why is "Wrote" a problem?  none of the files with an "ABORT"/seg fault listed have an snlc_sim.exe job in the same file so I honestly don't even know where to start.
