### ISSUE TITLE
memory error with split_and_fit.pl

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#218]
Hi Rick,

I was trying to fit a large sim but failed and there seems to be some memory error. 
An example is in `$SNANA_DEBUG/mdai/lcfit`
I was running `split_and_fit.pl /project2/rkessler/PRODUCTS/SNANA_DEBUG/mdai/lcfit/pipeline/snfit_TEST_biascor.nml.temp.1598895469.1732225_211`

I saw a bunch of memory errors in the .BATCH-LOG files, like below:
`SPLIT_JOBS_LCFIT/FITSPLIT_00040.BATCH-LOG:slurmstepd-midway2-0211: error: Detected 1 oom-kill event(s) in step 4299050.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`

There doesn't seem to be any problem when I was trying smaller sims.

Thanks.

**Comment by RickKessler** [comment]
For biasCor sims, please turn off the spectra generation. This resulted in >1 GB FITS files, and since the FITS files are gzipped, the entire file is stored in memory when read by LC fit code. So with 1 GB memory allocation and > 1GB FITS file, LC fit code dies immediately.
