### ISSUE TITLE
PKMJDINI Protection

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#222]
Could we request that you add a feature to SNANA that is something along the lines of
LCPEAK_MINSNR=2
for the guess for the PKMJDINI?

This would protect against low SNR noise fluctuations from being incorrectly considered the initial guess for the peak.

Thanks!

**Comment by djbrout** [comment]
alternatively could do whar SNLS did which was to ask for at least two filters agreeing on maximum by about 4 days or something like that?

**Comment by djbrout** [comment]
Sorry just updating the request here. Above was incorrect. What we really want is the following
SNR_MAX_PKMJDINI_NODETECT=10
a flag on high S/N but no detection so that the peakmjdini guess is better

**Comment by RickKessler** [comment]
&SNLCINP
    PHOTFLAG_DETECT     = 4096
    CUTWIN_SNR_NODETECT = -100, 10

Changes pushed to Github and Midway
