### ISSUE TITLE
SIMLIB error in Foundation sims

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#224]
Hi Rick, 

I'm trying to run a Foundation simulation that Rebekah has sent to me and am getting a strange error called by gen_fluxNoise_calc. I checked to make sure there is nothing strange in the simlib file and tried tinkering with the formatting but can't get to that bottom of it. Do you know why this is happening? I've placed a minimal working example in $SNANA_DEBUG/pmacias. Thanks!

 FATAL ERROR ABORT called by gen_fluxNoise_calc
   2 invalid observing conditions for ep=2, band=r
   zpt=-inf, psf=2.010, skysig=0.00

**Comment by RickKessler** [comment]
The following line from your input file is corrupt:
    EXPOSURE_TIME_FILTER: r	0.06 
I think there is a tab between r and 0.06, which corrupts the parsing and results in exposure time of zero. I removed your  r 0.06, re-typed it without tabs, and it works. Please avoid tabs or any other special characters in the input files.

**Comment by pmacias** [comment]
Thanks Rick, worked for me.

If there is a simple way for me to diagnose something like this myself, please let me know. I'll avoid tabs for any input files in the future.
