### ISSUE TITLE
arbitrary polynomial order for SALT2/3 color law

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#229]
Hi Rick,

We've been playing around with a 5th-order polynomial for the SALT3 color law.  The order of the polynomial is given in the SALT2.INFO file (or SALT3.INFO file), but at a glance it appears that SNANA forces this to be equal to 4.  Would it be possible to read this number from the INFO file instead of forcing it?  I set up an example job here that gives pathological results:

```
cd $SNANA_DEBUG/djones/salt3
snlc_fit.exe SDSS.NML
```

David

**Comment by RickKessler** [comment]
Seems to work fine changing 4 to 5 (and go back to space separator instead of commas). I noticed you had tabs which probably corrupted the C code parsing.

**Comment by RickKessler** [comment]
indeed the 5th parameter was not read due to bug; fixed and stdout includes
     CL-polynomial params: -0.478  0.775 -0.598  0.187 -0.020
