### ISSUE TITLE
DNDZ with zpoly not fully working

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#231]
Reference folder: $SNANA_DEBUG/DNDZ_ZPOLY

I'm trying to generate a simulation with the following Volumetric Rate model:
`DNDZ: ZPOLY 3.31E-05 4.61E-04 -2.22E-04 -1.76E-05 
` (i.e. third order polynomial)

The rate is given in /yr/Mpc3 (as indicated in the manual)
I get that zero LC are generated but it shouldn't happen.

The bug cha be reproduced doing:
```
cd $SNANA_DEBUG/DNDZ_ZPOLY
sim_SNmix.pl test_DNDZ_bug.input

```
Im wondering if it's an input-parsing issue.

Thanks!

**Comment by RickKessler** [comment]
fixed parsing bug for DNDZ ZPOLY
