### ISSUE TITLE
Keep simulation seed consistent but change RANSYSTPAR seed

### ISSUE THREAD

**Issue by MrPop2213** [RickKessler/SNANA#233]
In order to investigate the effects of systematics without any statistical error contaminating the result I'd like to be able to create a simulation with a fixed random seed (so that the events produced are the same each time), but use a new seed for RANSYSTPAR (so that the systematic offset is slightly different each time).

**Comment by RickKessler** [comment]
see new sim-input  RANSYSTPAR_RANSEED_GEN (manual)
