### ISSUE TITLE
Observer-frame peak magnitudes

### ISSUE THREAD

**Issue by temuller** [RickKessler/SNANA#236]
Is there a way to calculate the observer-frame peak magnitudes of a SN with SNANA? Either from the simulations themselves (simulated peak mag) or from SALT2 fits (interpolated peak mag).

For example, if I simulate a SN with griz bands, can I obtain the peak magnitudes of these bands?

**Comment by RickKessler** [comment]
with simulations, can use the SIMGEN_DUMP feature (see manual) and include PEAKMAG_[f] where f is the single-character representation of the band.  For LC fitting, the ROOT file includes model peak mags, m0obs_[f] for each band. Can use sntable_dump to extract the extra variables in ROOT file.

**Comment by temuller** [comment]
thanks
