### ISSUE TITLE
error with new submission script

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#237]
Hi Rick,

There seems to be a small bug here due to type mismatch. An example is in `$SNANA_DEBUG/mdai/new_submission`. Thanks!

` Program class : Simulation 

 Program name: snlc_sim.exe
         Batch command:  sbatch
         Batch template: /project2/rkessler/PRODUCTS/SNANA/SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE
         Batch n_core:   10
 Create output dir:
   /project2/rkessler/PRODUCTS/SNANA_DEBUG/mdai/new_submission/SIMLOGS_SIMULATEED_SPEC_SURVEY_DMS_217

 sim_prep_GENOPT(AllSurveys_LOWZ_217) 
         GENOPT(simulation/lowz/SIMGEN_SALT3TEST.INPUT): GENMODEL SALT2.JLA-B14     NGENTOT_LC 200     GENRANGE_REDSHIFT 0.02 0.08     
 sim_prep_GENOPT(ALLSurveys_PS1_217) 
         GENOPT(simulation/ps1_spec/SIMGEN_PS1SPEC.INPUT): GENMODEL SALT2.JLA-B14     NGENTOT_LC 8000     GENRANGE_REDSHIFT 0.05 0.7     
unsupported operand type(s) for +=: 'int' and 'str'
Traceback (most recent call last):
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_batch_jobs.py", line 376, in <module>
    program.submit_prepare_driver()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 146, in submit_prepare_driver
    self.sim_prep_NGENTOT_LC()
  File "/project2/rkessler/PRODUCTS/SNANA/SNANA/util/submit_batch/submit_prog_sim.py", line 454, in sim_prep_NGENTOT_LC
    ngentot_sum += ngentot
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
`

**Comment by RickKessler** [comment]
bug fixed parsing ngentot. Note that submit_batch does NOT support TEXT format for sims, so need to change FORMAT_MASK from 18 to 48.
