### ISSUE TITLE
Are relative paths still supported for new submission script?

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#238]
Hi Rick,

I have some relative paths in the sim inputs but those doesn't seem to work when using the new submission script. Is this a bug or I have to switch everything to absolute paths?

Here's an example: `$SNANA_DEBUG/mdai/new_submission`

Thanks!

**Comment by RickKessler** [comment]
Somebody else found the same bug about the same time that you did, and it's fixed. Try again.

**Comment by mi-dai** [comment]
Hi Rick, 

This still doesn't work for me. see the fail log: `$SNANA_DEBUG/mdai/new_submission/SIMLOGS_SIMULATEED_SPEC_SURVEY_DMS_217/FAIL_SUMMARY.LOG`

when I tried to run `FAIL_REPEAT_AllSurveys_LOWZ_217_SNIaMODEL0-0001_49855.CMD` from that folder it does work though - maybe the directory for launching the job is wrong within the submission scripts?

**Comment by RickKessler** [comment]
submit_batch is fixed  to automatically append CWD/ to any file with a partial path (ie., there is a slash in the name, but first character is not a slash). However,  that submit_batch does not account for
   KCOR_FILE:  kcor/kcor_SPEC_PS1_LOWZ_COMBINED.fits
and thus you need a full path here.

**Comment by RickKessler** [comment]
ok, got your script to work with relative paths, but I would still recommend absolute paths, or put all files in same directory and exclude path from file name. While the submit_batch script works with relative paths, debugging will be trickier.
