### ISSUE TITLE
salt2mu.exe "same" error

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#239]
Hi Rick,

Per our conversation I'm sending a reminder that we ran into an issue in $WFIRST_USERS/pmacias/ when running 

SALT2mu.exe SALT2mu_WFIRST_BBC5D.input

I get the error 

 FATAL ERROR ABORT called by ISFILE_TEXT
   Could not open TEXT FILE = 
   'same'

which seems to be stemming from the line 

simfile_ccprior=same

For now I will point directly to the biascor files with cc in them.

Thanks!
-Phil

**Comment by RickKessler** [comment]
fixed.
