### ISSUE TITLE
ranseeds not the same

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#242]
Hi Rick, looking here -
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic/MASTER_Survey_spec_candels_galid.INPUT
should be creating 3 versions.

Two versions are identical, one isn't identical due to a very minor change in filter function.  For the non-identical version, none of the SNID's are the same.  I would think for a minor change in filter function, it shouldn't change SNIDs.

Furthermore, for one of our versions that is identical (does get same CID), the .DUMP file doesn't get a header line:  /scratch/midway2/rkessler/SNDATA_ROOT/SIM/Deep_Spec_RK_Yeswiggle_alt/Deep_Spec_RK_Yeswiggle_alt.DUMP 
 
So I think maybe we have a bug somewhere that is causing various issues?

Working on this with @benjaminrose. 

Thanks,
Dan

**Comment by RickKessler** [comment]
This is likely an issue with the batch script, which I am no longer maintaining, and will be disabled in the next week or two. Please translate your input file with
   submit_batch_jobs.sh MASTER_Survey_spec_candels_galid.INPUT --opt_translate 10

Do an eyeball check, and then re-run with new batch script:
 submit_batch_jobs.sh MASTER_Survey_spec_candels_galid.INPUT

**Comment by dscolnic** [comment]
Thanks Rick - we updated the script and are having the same problem: (base) [dscolnic@midway2-login2 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login2 dscolnic]$ submit_batch_jobs.sh MASTER_Survey_spec_candels_galid.INPUT

The difference is the kcor, which has a very tiny effect on filter transmission.  But all of the SNID's are different.  We have a third GENVERSION where filters are exactly the same, and in this case, SNID's are exactly the same.  So how can a small change in filter cause all the SNID's to be different?

**Comment by RickKessler** [comment]
comment out RESET_CIDOFF
