### ISSUE TITLE
snana.exe generates simlib file with zpt = 0

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#243]
Hi Rick,

Strongly suspect I'm doing something dumb here:

cd $SNANA_DEBUG/djones/spec_simlib
snana.exe snfit_Foundation_DR1.nml HEADER_OVERRIDE_FILE Foundation_DR1.FITRES.TEXT SIMLIB_OUT Foundation_DR1.SIMLIB

When I run these commands and then take a look at the SIMLIB file that gets spit out, all the zeropoints are 0!  Any idea what's up?  Thanks,

David

**Comment by RickKessler** [comment]
fixed logic bug to determine whether or not ZP,SKY,PSF should be calculated.
