### ISSUE TITLE
Misspecified CUTWIN paremts in BBC cause hard to track segfault error

### ISSUE THREAD

**Issue by Samreay** [RickKessler/SNANA#244]
For example, CUTWIN_COLUMNAME: 0.9 instead of CUTWIN_COLUMNAME: 0.9 1.0 causes a segfault. Tested on the prob Ia column specifically.

**Comment by RickKessler** [comment]
is there a specific job I can run to reproduce the segFault ?

**Comment by Samreay** [comment]
I can make one up for you, I fixed the original

**Comment by Samreay** [comment]
Feast your eyes: /scratch/midway2/rkessler/PIPPIN_OUTPUT/SRH_REF_DES_5YR_HIGHCONF/6_BIASCOR/FAILFORRICK/output/SCRIPTS_BBCFIT

**Comment by RickKessler** [comment]
added parsing checks on CUTWIN; will be available next SNANA install.
