### ISSUE TITLE
LCFitting SNCID_IGNORE_LIST

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#246]
Sorry for bombarding you. Theres one other slight issue that the SNCID_IGNORE_LIST doesnt appear to be working as intended.
`$SNANA_DEBUG/djbrout/ignorelist/RUNTEST`
^^runs lcfitting which points to the following ignore file
`$SNANA_DEBUG/djbrout/ignorelist/ignore.list`
which has
`1248677`
in it, but that SNID is still making it to the output fitres...
`$SNANA_DEBUG/djbrout/ignorelist/DES3YR_DES_CHANGEME.FITRES.TEXT`

Thanks for your help!

**Comment by RickKessler** [comment]
fixed bug implementing SNCID_IGNORE_FILE. Not sure how long that bug has been there.
