### ISSUE TITLE
non-positive muerrsq

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#247]
Getting a wacky error for one of my FITOPTS (not all just one...)

Reproduce here
```
cd $SNANA_DEBUG/djbrout/muerrsq
./RUNTEST
```

error below

```

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
 FATAL ERROR ABORT called by fcn_muerrsq
   non-positive muerrsq = -2.997921e-03
   for SN = 2009D  alpha=0.180274  beta=3.100000
```

**Comment by RickKessler** [comment]
Fixed subtle numerical artifact in function merge_duplicate(). Nominal merged COV for duplicates is given by
    COV_merge = [ sum 1/cov_orig ]^-1 
which is inspired by the weighted average formula:  1/sigma^2 = sum[1/sigma_i^2]. For 2009D above, the COV(x1,c) element has opposite sign for the two duplicates, and the resulting sum is very close to zero, but slightly negative. This leads to a large negative COV_merge(x1,c) element, causing MUERRSQ < 0. The fix/hack is that whenever an off-diagonal element has a sign flip among the duplicates, COV_merge is the average, not the inverse-square sum above. Note that this artifact may have been present in previous analyses, but a large positive covariance could have been easily missed.
