### ISSUE TITLE
error in submit_batch_jobs.sh for LC fitting

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#248]
Hi Rick,

I'm running into an error regarding FITOPT variations when running 

submit_batch_jobs.sh SIMFIT_WFIRST_ALLz.NML

in $WFIRST_USERS/pmacias/H18_Imaging-Allz and $WFIRST_USERS/pmacias/BIASCOR_H18_Imaging-Allz. 

Both files were translated to the new format, and I think when we last spoke one of the things we did was comment out the lines regarding FITOPT and added in the filters in FITINP. 

Thanks!
- Phil

**Comment by RickKessler** [comment]
SIMFIT input file was missing SNTABLE_LIST = 'FITRES', which is needed to write output tables to ROOT or TEXT file.
I added this key and checked that it runs thru init stage using -n (no submit) option. Try re-submitting.
