### ISSUE TITLE
filter lists in LC fitting

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#252]
Hi Rick,

In running the LC fitting 

submit_batch_jobs.sh SIMFIT_WFIRST_Allz.NML

in 

$WFIRST_USERS/pmacias/H18_Imaging-Allz 

I get an error message about filters not matching from the simulations vs the fitting. As an example, in FAIL_SUMMARY.LOG I have 

FAILURE-0001:
  JOB_LOG_FILE:       WFIRST_IMG-Allz_DEEP_PM_FITOPT000_SPLIT001.LOG
  FAIL_REPEAT_SCRIPT: FAIL_REPEAT_WFIRST_IMG-Allz_DEEP_PM_FITOPT000_SPLIT001.CMD
  FAIL_MODE:          ABORT
  ABORT_MESSAGES:
  - FATAL ERROR ABORT called by PARSE_NML_FILTLISTS
  - Fit-filter Z is not a survey filter.
  - FILTLIST_FIT = YJHFZR  but SURVEY_FILTERS = YJHF

I recall when we were meeting that you recommended putting the list of filters to encompass the three tiers (YJHFZR), but that doesn't seem to be taking. Thanks!

**Comment by RickKessler** [comment]
Your SIMGEN files have
  GENFILTERS:  YJHF
but then you try to fit YJHFZR and it cannot find ZR bands. Need to generate with YJHFZR ... you can always decide later to fit with fewer bands, but you can't fit more bands than are generated.
