### ISSUE TITLE
Turn off Host Poisson error

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#253]
Hello!
Issue reference folder in $SNANA_DEBUG/HostPoissonNoise

I was trying to **turn off** the Host galaxy Poisson errors.
I checked the manual and setting:
 HOSTLIB_MSKOPT: 256
should to the trick.

However I noticed that this was not working i.e. the host-noise contribution was still computed and added to SN noise)
and in the LOG file I get:
```
  HOSTLIB Summary:
         Read 120743 total HOSTLIB entries from
           ...
         HOSTLIB Opt:  compute host-noise contribution to SN noise
         ...
```
Now, in the example I put in $SNANA_DEBUG/HostPoissonNoise I have three files:
`MV_HostPoissonNoise.input `  i.e. THE MAIN INPUT FILE that calls the SIMGEN file -->
`sn_ia_salt2_g10_des5yr.input`  that calls the INPUT_FILE_INCLUDE --> 
`sim_des_5yr_phot_include.input`

In `sim_des_5yr_phot_include.input` the default value for HOSTLIB_MSKOPT is set to 258 but in `MV_HostPoissonNoise.input` I explicitly say to overwrite HOSTLIB_MSKOPT = 256
I think the problem is that HOSTLIB_MSKOPT is not over-written. 
I think that only if I set HOSTLIB_MSKOPT=256 in `MV_HostPoissonNoise.input` **AND** in `sim_des_5yr_phot_include.input`  the host noise is turned off. Do you know what's the reason for that?

**Comment by RickKessler** [comment]
main input file is read first, then the include files. So anything in the INCLUDE file will overwrite main input. Command line overrides anything in the input files. There is a duplicate key check within each file, but not among different input files.
