### ISSUE TITLE
new submission script could not find model

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#257]
Hi Rick,

I ran the new submission script and got an error message like below:

  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by read_SALT2_INFO_FILE 
  - Could not open SALT2 info file: 
  - saltmodels/SALT2.JLA-B14-ext/SALT2.INFO 

while the model folder did exist in the same folder as the input file.

Full example is at: `$SNANA_DEBUG/mdai/salt3_train`
I was running: `submit_batch_jobs.sh REFAC_SALT3_TRAINING_MASTER.INPUT`

Thanks.

**Comment by RickKessler** [comment]
I noticed relative paths for the model,
GENMODEL:   saltmodels/SALT2.JLA-B14-ext
Please absolute path. I would encourage defining an ENV such as $MY_SALT3, and then defining files as $MY_SALT43/sim/whatever.input, etc ...

**Comment by RickKessler** [comment]
please use full path for GENMODEL argument.
