### ISSUE TITLE
Increase MXITER_GENPDF

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#259]
Getting errors about MXITER_GENPDF when trying to run my simulations. Error summary is here- 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-AS-BS20/1_SIM/LOWZ_BC/LOGS/FAIL_SUMMARY.LOG

And the relevant distribution files are here - /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/AS/DISTS/

**Comment by RickKessler** [comment]
increased MXITER_GENPDF -> 1000 (was 200). Please leave above debug job so I can investigate more later today.

**Comment by RickKessler** [comment]
added logic to suppress regions where PROB=0. Runs more efficiently.
