### ISSUE TITLE
header override string length issue

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#260]
still seems to be an issue...
`$SNANA_DEBUG/djbrout/headeroverride/RUNTEST`

**Comment by djbrout** [comment]
```# ================================================ 
  PRE-ABORT DUMP from function TABLEFILE_OPEN : 
  file=
 /project2/rkessler/SURVEYS/PS1MD/USERS/dscolnic/PANTHEON+/header_overrides

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by TABLEFILE_OPEN
   Unknown table-file type
   STRINGOPT = 'read' 
```

doesnt seem to be catching the full filename

**Comment by RickKessler** [comment]
while HEADER_OVERRIDEF_FILE string length was adequate, there was a 200 char limit to each command line arg. Increased to 400; try again.

**Comment by djbrout** [comment]
that works for this simplistic case, thanks rick! but can I request that
you increase it to much longer? like 2500? The reason is because I plan on
adding a bunch of header_override files (one per column).
