### ISSUE TITLE
Crashing in LCFIT stage, reason unclear

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#261]
Running a pippin job, and SNANA seems to die in the LCFIT stage. Error is presented here:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-PS1/2_LCFIT/PS1FIT_PS1_DATA/output/SPLIT_JOBS_LCFIT/CPU0007_JOBLIST_midway2-login2.LOG

But is not super informative. Uncertain what is causing it.

Original file here: /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BBC_paper_2/PS1_usable/BP-PS1.yml

**Comment by RickKessler** [comment]
HBOOK has problems since it was not properly converted to 64 bit many years back. In your NML file, try replacing
	 HFILE_OUT. = 'ps1_final.hbook'
with
	 ROOTFILE_OUT.  = 'ps1_final.root'
