### ISSUE TITLE
Feature request: Configurable option for select SED models

### ISSUE THREAD

**Issue by deepchatterjeeligo** [RickKessler/SNANA#262]
Hi @RickKessler creating this issue based on your request.

This is a feature request to support more flexible ways to select specific SED models.
Currently, the `SIMSED_GRIDONLY` option is used to select a random model with some other support, like a gaussian.
It would be great to have a more flexible way to subselect/constrain SED models from the list of model based on what is specified in `SED.INFO`.

**Comment by RickKessler** [comment]
See updated manual section 9.5, and page 157 in particular;
SIMSED_GRIDONLY: KN_INDEX(3,5,6,9) # pick random among these KN_INDEX values
