### ISSUE TITLE
More MAX_ITER problems

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#263]
In /scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-AS-BS20/1_SIM/LOWZ_BC

I increased the NGEN_UNIT and RANSEED_REPEAT for these because they were significantly smaller than the last time I ran these sims. I'm getting the same MAX_ITER error:

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-AS-BS20/1_SIM/LOWZ_BC/TMP_bap3_PIP_BP-AS-BS20_LOWZ_BC_SNIaMODEL0-0049_46973.LOG

Except most of the iterations are consistent with 0, yet we still get the error.

**Comment by bap37** [comment]
Per discussion, implementing a minimum probability input to cut things that are effectively zero but not quite zero is the intended solution

**Comment by RickKessler** [comment]
defined new parameter PROBMAX_REJECT_GENPDF=1.0E-3 in in sntools_genPDF. Can't be changed from user-input (yet?), but it is hopefully much more robust than before.
