### ISSUE TITLE
Flipped VPEC Large RMS

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#267]
`$SNANA_DEBUG/djbrout/flipvpec/RUNTEST`
``` check_vpec_sign with RMS(MURES) using N(z<0.050) = 623 events:
	 RMS(MURES,nominal)   = 0.5182 
	 RMS(MURES,flip-vpec) = 0.5087 
```
those rms values seem really high. I know its not that bad in the data for the most part. I have a chi2max=22 cut in there but its possible that you need to apply a z>.02 cut when determining RMS as well...

**Comment by djbrout** [comment]
yeah, if i put in my own z>0.03 cut then it fixes the problem

**Comment by RickKessler** [comment]
changed zmax_vpec_check to
zwin_vpec_check=0.01,0.05 
(and to skip vpec check, set  zwin_vpec_check=0,0)
