### ISSUE TITLE
RANSYSTPAR better filter control

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#268]
Add finer control to `RANSYSTPAR_SIGSHIFT_LAMSHIFT` and `RANSYSTPAR_SIGSHIFT_ZP` to be able to specify filters

Currently if you have `griz` then to only add a random offset to the zp of one filter you have to use `RANSYSTPAR_SIGSHIFT_ZP 0.1 0 0 0` This is fine for 4 filters, but once you start getting up to 30 it gets clunky.

Something like `RANSYSTPAR_SIGSHIFT_ZP: g=0.1 r=0.2` would work well, or `RANSYSTPAR_SIGSHIFT_ZP(gr): 0.1 0.2`

**Comment by RickKessler** [comment]
Done; see manual section 4.41 Applying Systematic Errors (RANSYSTPAR)
