### ISSUE TITLE
SALT3 with G10 or C11

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#274]
Is it legal to combine SALT3 with smear models G10 and C11? I’m getting the following error here
`$SNANA_DEBUG/djbrout/salt3/RUNTEST`

```  init_genmag_SALT2 : Done. 
 ****************************************************************** 
   init_modelSmear: init intrinsic SN smearing with model=G10  
	 Smear-mode: complete wavelength dependence. 
   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
 FATAL ERROR ABORT called by read_genSmear_SALT2sigcoh
   Cannot open infoFile 
   /project2/rkessler/SURVEYS/PS1MD/USERS/dscolnic/PANTHEON+/models/SALT3.K20/SALT2.INFO```

which looks like when its loading the smear model its looking for SALT2 related stuff instead of SALT3.

**Comment by djones1040** [comment]
I don't have anything too useful to say but very excited to see this issue :).  Keep in mind that if it's reading the scatter model from the INFO file then the "G10" model here is really the "K20" model so you should have a lot less red scatter, more like C11 in that way

**Comment by djbrout** [comment]
:) A little confused though, did Darcy also implement a scatter model?

**Comment by djones1040** [comment]
we trained a color dispersion model in the training, so I was thinking the G10 model is just that + a gray scatter term.  But rick will know better.

**Comment by RickKessler** [comment]
fixed simulation to use salt2 or salt3 files for scatter model
