### ISSUE TITLE
Extending hard-coded limit of 500 epochs per band in a SIMLIB

### ISSUE THREAD

**Issue by patrickaleo** [RickKessler/SNANA#277]
For a more realistic SIMLIB for ZTF survey which accounts for overlapping fields (a source can be in up to 4 fields--or even more, due two different sky splits) and the case where ZTF observes the same field several times per night (for short-period variables, fast-evolving objects/transients, and for alerts), we exceed the 500 epochs per band limit.

```
FATAL ERROR ABORT called by NEPFILT_GENLC
  NEP=500 exceeds bound for ifilt_obs=2(g).
  Check MXEPSIM_PERFILT 
```

Currently @hombit models the max epoch in g-band = 812, max epoch r-band = 868, and this number may increase. Therefore we humbly ask to make this value runtime constant, not buildtime if possible. 

Thank you for considering our request!

**Comment by RickKessler** [comment]
MXEPSIM_PERFILT has been extended to 1000.
