### ISSUE TITLE
Better method of specifying RANSYSTPAR filter offsets

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#278]
1. Grouping without commas / spaces assigns one offset to all filters (`RANSYSTPAR_SIGSHIFT_ZP(abc): 0.01` assigns an offset of 0.01 to a, b, and c)
2. Grouping with commas can separate the groups (`RANSYSTPAR_SIGSHIFT_ZP(abc, def): 0.01, 0.02` assigns an offset of 0.01 to a, b, and c, and an offset of 0.02 to d, e, and f)
3. Ensure this works for both `RANSYSTPAR_SIGSHIFT_ZP` and `RANSYSTPAR_SIGSHIFT_LAMFILT`
4. Not specifying anything indicates individually listed values (`RANSYSPAR_SIGSHIFT_ZP: 0.01 0.02 0.03` assigns 0.01 to a, 0.02 to b, and 0.03 to c)
4. _(optional)_ choice between space seperated or comma seperated

**Comment by RickKessler** [comment]
Done. See updated manual section 
     4.41 Applying Systematic Errors (RANSYSTPAR).
