### ISSUE TITLE
Header override for SALT2mu

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#279]
Can we use the same format of header_override for snlc_fit but for salt2mu.exe?  This would be super helpful!!!

**Comment by RickKessler** [comment]
please provide explicit example under $SNANA_DEBUG ... preferably without biasCor so that it runs much faster.

**Comment by dscolnic** [comment]
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
SALT2mu.exe  SALT2mu_muopt_oned.input
want it to use this file:
new_header.txt
with something like HEADER_OVERRIDE: new_header.txt
(that file right now has one SN with one new vpec and one new logmass)

**Comment by RickKessler** [comment]
Done. Syntax is near top of SALT2mu.c file:
datafile_override=over1.dat,over2.dat,etc... ! comma-sep list of data-overrides
     ! enabled for VPEC, VPEC_ERR, HOST_LOGMASS
     ! if VPEC [VPEC_ERR] is changed, so is zhd [zhderr]
I did some visual testing of output, but first user should do a brute-force test by comparing to a modified input fitres file, and running it thru BBC to compare nuisance parameters.
