### ISSUE TITLE
new seg fault in simulating spectra

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#282]
Hi Rick,

Running this command, it will crash on the number of spectra but once you fix that, I get a segmentation fault.  Could you investigate when you get a chance?

```
cd $SNANA_DEBUG/djones/salt3sim
snlc_sim.exe JLA_TRAINING_Hicken09.INPUT
```

Thanks,

David

**Comment by RickKessler** [comment]
"USE_SIMLIB_SPECTRA: 1" was not specified in the sim-input file, which revealed a bug. Bug fixed, but will need this key to read spectra from SIMLIB header.
