### ISSUE TITLE
BBC Cut log more than 10 request

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#285]
Request to increase BBC Cut log to max of 100 SNe. 
I'm trying to track down why individual SNe are getting cut at the BBC stage.
Thanks!

**Comment by RickKessler** [comment]
ndump_nobiascor=20       ! dump for first 20 data events with no biasCor
dumpflag_nobiascor=20;   ! idem; legacy input variable
WARNING: not tested !!
