### ISSUE TITLE
Additional fitres column from SALT2mu of new redshift error

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#286]
Hey Rick,

As we are getting a lot more into incorporating cepheid data with SN data to measure H0, one thing that keeps coming up is having a column for MU_ERR without redshift uncertainties propagated (cause SN we use for cepheid comparisons don't care about the redshift used).  Would that be pe possible?  If we actually could get both MUERR_noverr and MUERR_RAW_noverr that would be really great.  You can change the column names however.

(base) [dscolnic@midway2-login1 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login1 dscolnic]$ SALT2mu.exe SALT2mu_muopt_oned.input

Thanks,
Dan

**Comment by RickKessler** [comment]
added output column MUERR_VPEC, the MUERR contribution from v_pec. NOT TESTED, so let me know when you have an output that I can check.
