### ISSUE TITLE
peculiar SNe Ia SIMSED

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#288]
Reference folder $SNANA_DEBUG/mvincenzi/PecIa_SIMSED

I am trying to generate peculiar SNe Ia (both 91bg and Iax) and I just started to get the error:
```
  Read (ised=1/1001) SED surface from binary file :

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by init_flux_SEDMODEL
   invalid ifilt=-9 for ifilt_obs=0
   array bound is MXFILT_SEDMODEL=100

```

I tried to delete the SED surface binary files in `/project2/rkessler/SURVEYS/DES/USERS/mvincenzi/MYPIPPIN/SIMSED_BINARIES` and let SNANA generates them again.. but it still doesn't work for some reason.
Thanks.

**Comment by maria-vincenzi** [comment]
To be a bit more helpful... Everything was still working fine on Nov 11th (morning) but I noticed ./src/genmag_SEDtools.c has been updated later on the same day. Maybe some of the updates are causing the problem?

**Comment by RickKessler** [comment]
fixed a bug introduced by a recent refactor aimed at implementing systematics from training. Try again.
