### ISSUE TITLE
TRAINOPT SALT2PATH feature

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#302]
It'd be helpful to have an option in a train_salt2.input file for submit_batch_jobs.sh that allows a user to specify a pre-perturbed SALTPATH to use for SALT2 training.  This would make it easier to bypass some of the complications that come from the non-one-to-one survey mappings, while keeping a consistent output structure.  Maybe a description of the perturbations, to be written to the SALT2.info file, might also be needed in this case?

**Comment by RickKessler** [comment]
new option to pick different SALTPATH,
  TRAINOPT:
  - PATH_INPUT_CALIB  $SNANA_DEBUG/submit_batch_devel/SALTPATH_for_TRAINOPT

However, beware that calibration changes are NOT propagated to SALT2.INFO file for SNANA.
