### ISSUE TITLE
Add more variables to SALT2mu override

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#306]
Would like  zHEL zCMB zHD
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
SALT2mu.exe SALT2mu_muopt_oned.input
has in it
datafile_override=new_header.txt

Thanks!
Dan

**Comment by RickKessler** [comment]
zHD[ERR] is already enabled. Added zCMB[ERR] (for next update), although it's not used in SALT2mu. zHEL[ERR] are not read or used.
