### ISSUE TITLE
NSTORE_ALL=1000000 exceeds bound of CIDRAN_MAX = 10

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#309]
ran snana through pippin with config yaml path: `$DES_USERS/helenqu/pippin_config/helen_plasticc.yml`
pippin output directory: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_PLASTICC/`
error discovered in log path: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_PLASTICC/1_SIM/PLASTICC_SIM_IA/LOGS/TMP_hele_PIP_HELEN_PLASTICC_PLASTICC_SIM_IA_SNIaMODEL0-0001_79666.LOG`

error excerpt:
```
58    init_CIDRAN: initialize 1000000 RANDOM CIDs (CIDOFF=0)
 59
 60    `|```````|`
 61    <| o\ /o |>
 62     | ' ; ' |
 63     |  ___  |     ABORT program on Fatal Error.
 64     | |' '| |
 65     | `---' |
 66     \_______/
 67
 68  FATAL ERROR ABORT called by init_CIDRAN
 69    NSTORE_ALL=1000000 exceeds bound of CIDRAN_MAX = 10
 70    NSTORE_ALL= 0(CIDOFF) + 1000000(NGEN_LC) + 0(NGENTOT_LC)```

**Comment by RickKessler** [comment]
fixed submit_batch to abort on incompatible NGEN_LC and random CID option.
