### ISSUE TITLE
BYOSED and SNEMO being called NFILTERS*NPHASES times, instead of just NPHASES 

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#311]
This is not an urgent issue things work fine as is, but sims are slower than they need to be right now:

SNANA calls `genmag_PySEDMODEL` to get the rest frame SED. This function loops through the rest frame phases and calls the python code, which returns the flux at all wavelengths at that phase. `genmag_PySEDMODEL` returns the mag and magerr lists for all phases. 

This all happens for a single filter, but then SNANA moves onto the next filter and goes through the exact same process again. The python file returns the exact same flux vs. wavelength array at all the same phases, and the only thing that changes is the integration for the new filter. If we could shift things around so the python file gets called just once per phase instead of NFILTERS time per phase, the sims would be much faster. All that needs to happen is to break this function into two, have SNANA call a new `genflux_PySEDMODEL` once to get the flux at all wavelengths at each necessary phase, then loop through filters and integrate this SED at each phase to get the correct magnitudes.

**Comment by RickKessler** [comment]
two flags are already passed to genmag_PySEDMODEL: NEWEVENT and filter index ... so it's up to the python module to optimize itself for speed. Reducing the number of python calls would require returning multiple SEDs per call ... not clear if there's a benefit for such a refactor.

**Comment by jpierel14** [comment]
@benjaminrose I've "solved" this in BYOSED by checking to see if I've already returned the phase being requested. If yes, I know it's just another filter at the same phase and return the same flux saved in a dictionary with phases as keys and flux arrays as values. This saves the time needed to create the flux array each time if you've already done it once. Optional for you, just could speed up the sim somewhat.

**Comment by benjaminrose** [comment]
@RickKessler, I don’t understand the use of a filter index inside the BOYSED framework. These are always full SEDs and have no knowlage of filters. The python code can be optimized, as described by @jpierel14, but I don’t undersand what in SNANA requires the per filter call to a full size SED. 

That being said, I totally understand if this is only a someday/maybe task that never becomes worth the optertunity cost it would take to impliment it.

**Comment by RickKessler** [comment]
sorry for confusion; you don't need the filter index. There are other places in SNANA where it is more practical to return the SED only within the filter range.
