### ISSUE TITLE
kcor issue in combine_dataVersions.py

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#312]
hi Rick, got an error when the combine script was generating the combined kcor file:

```
  Read user input file: kcor_JLA_LOWZ_COMBINED.input 
   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
 FATAL ERROR ABORT called by index_primary
   Could not find primary for '[['BD17'],'
   Check PRIMARY_SED key(s) in kcor-input file.
```

the kcor input has lines like this which didn't seem readable by the kcor program

```
MAGSYSTEM:   [['BD17'], ['BD17']] 
FILTSYSTEM:  [['COUNT'], ['COUNT']] 
FILTPATH:    [['PS1/Pantheon/SNLS3-Landolt'], ['filters/Keplercam']] 
```

files and logs are in here: $WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/sim/combine_lowz

Thanks!

**Comment by RickKessler** [comment]
Hopefully fixed when splitting the data into sub-surveys. combine_dataVersions was not designed to work on partially merged light curves.
