### ISSUE TITLE
SALT2mu override issue

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#314]
(base) [dscolnic@midway2-login2 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login2 dscolnic]$ SALT2mu.exe SALT2mu_muopt_oned.input

VARNAMES: CID CIDint IDSURVEY TYPE FIELD CUTFLAG_SNANA zHEL zHELERR zCMB zCMBERR zHD zHDERR VPEC VPECERR
Check out SN: 2001V 1 63 0 NULL 3 0.01489 0.00090 0.01592 0.00090 0.01622 0.00124 -0.000 250 
but in override:
VARNAMES: CID zHD VPEC
SN: 2001V 0.0159200 -0.0000000
So vpec=0 which is good, but zCMB is getting set to the input zHD, and I dont know how zHD is calculated?

Dan+Erik

**Comment by dscolnic** [comment]
Rick - another issue same example - not sure what is being done with MUMODEL when redshift overrides are taking place, but it doesnt equal LCDM(zHD).

**Comment by dscolnic** [comment]
Note this problem happens even if we only have a vpec column, no zHD.  I think the mumodel is not being recalculated.

**Comment by RickKessler** [comment]
can you update the $SNANA_DEBUG example to include zHEL and/or VPEC ? Combining zHD and VPEC is ambiguous and result in an ABORT.

**Comment by RickKessler** [comment]
Fixed to work with zHEL and VPEC,VPECERR. Specifying zHD and VPEC -> abort. Very limited debugging with visual checks that output has changed; users need to do science debug.
