### ISSUE TITLE
G10 (and C11) not being correctly applied to BYOSED

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#315]
I've got this in my sim-input: `GENMAG_SMEAR_MODELNAME  G10:$SNDATA_ROOT/models/SALT2/SALT2.P18_UV2IR`, no error but in the end the RMS is consistent with an identical sim with a `GENMAG_SMEAR=0.01`, meaning that it doesn't appear to actually introduce any scatter.

**Comment by RickKessler** [comment]
Indeed the original G10-scatter implementation for BYOSED was buggy, and a few more bugs have appeared during the pandemic. Hopefully all is fixed, and I verified with side-by-side comparisons of PEAKMAGs for SALT2(c=x1=0) vs. BYOSED(SALT2-M0 only) with fixed redshift and no Galactic extinction.
