### ISSUE TITLE
different chi2max for different sample

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#317]
Hi,
I have a feature request for SALT2mu.c i.e. allow different chi2max for different IDSURVEY.
Thanks

**Comment by RickKessler** [comment]
chi2max=16             # default cut to all events
chi2max(DES,PS1)=12    # apply cut only to DES & PS1
chi2max(CSP)=10        # apply cut to CSP
     = chi2-outlier cut applied before fit, using initial values. Beware 
       that initial and final chi2 can differ, so allow slop in the cut.
  Cut applied to -2log10(ProbIa_BEAMS + ProbCC_BEAMS); see Eq 6 of BBC paper.
  Note that multiple chi2max inputs are allowed. In the avove example, 
  chi2max=12 is applied to DES & PS1 events; chi2max=10 is applied to CSP; 
  chi2max=16 is for all other surveys (e.g., SDSS, other lowz, etc...)

**Comment by maria-vincenzi** [comment]
Hello,
it looks like the new feature is not yet available on SNANA on midway?
See `/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/chi2max_issue`
When I run:
`submit_batch_jobs.sh test_chi2max.input
`
all the muopts that use chi2max(DES) option crash with the error:
`syntax error near unexpected token `('`
Thanks!

**Comment by RickKessler** [comment]
I had forgot to protect reading () on command line ... should be fixed. However, I cannot run your job above because if permission issues,
ls /scratch/midway2/rkessler/PIPPIN_OUTPUT/MV_BBCP2/5_MERGE/
ls: cannot open directory /scratch/midway2/rkessler/PIPPIN_OUTPUT/MV_BBCP2/5_MERGE/: Permission denied
