### ISSUE TITLE
increasing the bound-check on PSF

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#318]
Reference folder on cori.nersc: `/global/homes/m/mvincenz/desc/debug`

I'm running a simulation using the simlib` /global/homes/m/mvincenz/desc/simlibs/baseline_nexp1_v1.6_10yrs_WFD.simlib`
I get the error:
```
 FATAL ERROR ABORT called by checkval_D
   PSF1(item 0) = 10.060000 fails bounds-check
   Expected  0.000000 < PSF1 < 9.900000  
```
The error can be reproduced running:
`submit_batch_jobs.sh REFAC_SIMGEN_MASTER_LSST_WFD.INPUT`
in the folder above.

**Comment by RickKessler** [comment]
increased PSF abort value from 9.9 to 20.
