### ISSUE TITLE
sim issue about spectra

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#319]
Hi Rick,

Got an error like below. Can reproduce with:

`$WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/SIMLOGS_SIM_SALT3TRAIN_301/FAIL_REPEAT_SALT3TRAIN_SNLS3_301_SNIaMODEL0-0001_55698.CMD`

```
# ================================================ 
  PRE-ABORT DUMP from function GENSPEC_TEXPOSE_TAKE_SPECTRUM : 
	 SNR_MIN(30 sec)=25.6 
	 SNR_MAX(30720 sec)=819.3 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by GENSPEC_TEXPOSE_TAKE_SPECTRUM
   Could not converge after NITER=40 (CID=4126)
   SNR_REQUEST=199.2  z=0.470  TOBS=-8.60
```

**Comment by RickKessler** [comment]
This abort was due to just barely missing the 2% tolerance for SNR convergence, so it wandered off to increasingly wrong SNR until aborting. I increased tolerance convergence to 3%.
