### ISSUE TITLE
Issue when running tests on new  DES CC  templates

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#32]
I am having an issue running 
snlc_sim.exe  /project2/rkessler/SURVEYS/DES/USERS/rhounsell/CC_TEMPLATES/sim_1247531.input 

When I  do I get an  error stating 
# ================================================ 
  PRE-ABORT DUMP from function rd_sedFlux : 
	 DAYrange = -150.00 to  500.00  (NBIN=3) 
	 LAMrange =   100.0 to 30000.0  (NBIN=951) 
	 iep=3  ilam=142 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by rd_sedFlux
   Found LAM=3672.4 at day = 6.000000 
   But expected LAM=3691.60 (ilam=142)

I have never had issues running this file before and have  generated  light curves in the past. Has something changed? 
Thank you

**Comment by RickKessler** [comment]
fixed bug in rd_sedflux (inside sntools.c) reading line lengths > 80 chars with fgets. Rather than abort, it corrupted reading of next line. Extend char-read limit to 120 per line, and add abort if line  length exceeds bound or if there are < 3 words on a line.
