### ISSUE TITLE
NSTORE_ALL exceeds bound of CIDRAN_MAX

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#320]
Hi Rick, this may not be a bug but just I didn't know how to set it up correctly. logs are in `$WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/SIMLOGS_SIM_SALT3TRAIN_BIASCOR_401/`

```
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by init_CIDRAN 
  - NSTORE_ALL=303170 exceeds bound of CIDRAN_MAX = 267580 
  - NSTORE_ALL= 263170(CIDOFF) + 0(NGEN_LC) + 40000(NGENTOT_LC) 
```

**Comment by RickKessler** [comment]
Try    RESET_CIDOFF: 1

**Comment by RickKessler** [comment]
issue was related to --fast option combined with subtle bug using NGENTOT_LC from GENOPT. Fixed.
