### ISSUE TITLE
check batch_submit_jobs with newly installed snpca on midway. 

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#323]

**Comment by geotaylo** [comment]
I've tested this, and it seems to be working as expected.  The line `export LD_LIBRARY_PATH=/project2/rkessler/PRODUCTS/snpca/local/snfit/lib:$$LD_LIBRARY_PATH` needs to be called before training - could we add this under the hood?

**Comment by RickKessler** [comment]
I appended LD_LIBRARY_PATH in the SNANA_setup, so it's there for batch or interactive use.

**Comment by RickKessler** [comment]
seems to still be working. And I updated the --purge option to remove the _TRAIN sub-directories.
