### ISSUE TITLE
Plasticc sims all failed the NMJD_INCLUDE cut

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#327]
Hi Rick,

I was trying to fit PLAsTiCC (Ia) sims with snlc_fit.exe, but I got nothing left after the NMJD_INCLUDE cut (and maybe some others). I don't think I set those cut in the input file. Are they internal? And why did all SNe fail?

(Also, with an older version of SNANA on another machine I was able to fit with no problem)

```
    Finished processing       0 SN after snana  cuts   (     20 before cuts)
  
    ** WARNING ** EVERY SN FAILS CUTBIT  17 :  NMJD_INCLUDE
    ** WARNING ** EVERY SN FAILS CUTBIT  20 :  NFILT_SNRmax
    ** WARNING ** EVERY SN FAILS CUTBIT  21 :  NFILT_SNRmax2
    ** WARNING ** EVERY SN FAILS CUTBIT  22 :  NFILT_Trestmin
    ** WARNING ** EVERY SN FAILS CUTBIT  23 :  NFILT_Trestmax
    ** WARNING ** EVERY SN FAILS CUTBIT  24 :  NFILT_Trest2
    ** WARNING ** EVERY SN FAILS CUTBIT  27 :  NFIELD

```

**Comment by mi-dai** [comment]
Oh sorry, forgot to post the debug example: $SNANA_DEBUG/mdai/plasticc_lcfit

**Comment by RickKessler** [comment]
The original PLASTICC data used a COMPACT FITS format to reduce disk space. I fixed a bug to enable snana jobs to process COMPACT format. The other issue is that you need to either remove CUTWIN_TREST, or set OPT_SETPKMJD. Seems that the stored PEAKMJD values are sometimes way off.

**Comment by mi-dai** [comment]
It looks like there is a version of LSST_DDF_MODEL90 in this folder `/project2/rkessler/SURVEYS/LSST/SIM/LSST_DDF_MODEL90`, which I thought was the plasticc data, but turns out to have only 10ish light curves in it. I was trying to set `PRIVATE_DATA_PATH` to point to my version of plasticc data but it complained there were two versions with the same version name. How can I tell SNANA to ignore the wrong folder above?
