### ISSUE TITLE
Point to specific FITOPT during a MUOPT

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#328]
$SNANA_DEBUG/djbrout/mfo/RUNTEST

here is the command
```
SALT2mu.exe REALDATA5D.input \
     prefix=OUTPUT_BBCFIT_FITOPT000_MUOPT004 \
     datafile=INPUT_FITOPT000.FITRES \
     write_yaml=1 \
   u1=0 p1=0.15781 u2=0 p2=2.92756 u5=0 p5=0.04838 FITOPT=20
```

and here is the error
``` 
FATAL ERROR ABORT called by override_parFile
   Invalid command-line override:
   FITOPT=20
```

**Comment by RickKessler** [comment]
I think this request is for the submit_batch script to select out appropriate inputs for SALT2mu.exe

**Comment by djbrout** [comment]
yes, requesting a comma separated list to facilitate the following
0+0,20&4

**Comment by RickKessler** [comment]
rather than comma-sep list, it uses YAML-list feature:

  FITOPTxMUOPT: 
  - 0+0   # process FITOPT=000 or MUOPT=000 ...
  - 2&4   # and include FITOPT002 x MUOPT004
  - DUMP  # optional flag to dump explicit matrix for FITOPTxMUOPT

for help, 
    submit_batch_jobs.sh -H BBC
