### ISSUE TITLE
Can't run 5D BBC

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#33]
When I tried to run SALT2mu.exe on /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/BBC7D_Test/BBC7D_FINAL/5DCorr.input
I get the error stored here:
/project2/rkessler/SURVEYS/SDSS/USERS/BAP37/MASS_paper/BBC7D_Test/BBC7D_FINAL/DMP

 FATAL ERROR ABORT called by get_BININFO_biasCor_alphabeta
   3593 SIM_gammaDM values exceeds bound of 2
   Check biasCor sample.

I tried setting OPT_DEVEL_BBC7D: 0, but that still causes the gamma to have the odd tau distribution you saw earlier. 

Thanks Rick!

**Comment by RickKessler** [comment]
ok, I think I see the problem. SALT2mu auto-detects 6D or 7D by the presence of SIM_gammaDM bins and by input nbin_logmass. But for 5D biasCor, you have the nominal SIM_gammaDM-vs-logMass from regular gamma definition. The continuous distribution (see attached) results in more than 2 SIM_gammaDM bins, so it aborts. The quick solution is to generate the biasCor sample without the gamma effects; i.e., turn off the 4 bit in HOSTLIB_MSKOPT. However, I need to think of a convenient way to force 5D even if it detects SIM_gammaDM bins.

<img width="573" alt="SIM_gammaDM" src="https://user-images.githubusercontent.com/24592476/73852309-8fe58f00-47f4-11ea-9aa9-10dd14e3b868.png">

**Comment by RickKessler** [comment]
Fixed code to ignore gammaDM dimension if more than 5 gammaDM values are found; this allows doing a 5D bias Correction with above gamma-vs-logMass profile. Update pushed to Midway.
