### ISSUE TITLE
invalid wavelength called by GALextinct

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#331]
Hi Rick,

In 

$WFIRST_USERS/pmacias/pippin/config

when I run

pippin.sh WFIRST_starterKit.yml

I receive the following error:

FATAL ERROR ABORT called by GALextinct Invalid WAVE=12062.8 A for Fitzpatrick 99 color law. Avoid NIR (>12000.0), or update Fitz99 in NIR

I did a little digging but couldn't fix it myself. Also, my $PIPPIN_BASE points to $WFIRST_USERS/pmacias/pippin, so that would have to be changed to run it yourself. I can move things into the original $PIPPIN_BASE if need be.

Thanks!
Phil

**Comment by RickKessler** [comment]
This is a known feature, not a bug. Problem is that the original polynomial function is only valid out to 12000 A, so for protection it aborts for longer wavelengths. Hoping to eventually find a volunteer to fix it to work out to 25,000 A.
