### ISSUE TITLE
HOSTLIB_GENZPHOT_BIAS changes makes SN efficiency = 0?

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#332]
(base) [dscolnic@midway2-login2 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login2 dscolnic]$ source snlc.sh

This script works fine if HOSTLIB_GENZPHOT_BIAS .000 -.000 .000 .000 but if any of these numbers are non-zero
HOSTLIB_GENZPHOT_BIAS .001 -.000 .000 .000 then the efficiency drops to 0 of detected SNe.  Why would that be?

snlc_sim.exe /project2/rkessler/SURVEYS/DES/USERS/rebeccachen/base/RC_DES_BASE_SIM_IA.input GENVERSION TMP_rebe_RC_RM_DES5YR_ERR_SNIaMODEL0-0001_43858 GENPREFIX RC_RM_DES5YR_ERR_SNIa
MODEL0-0001 NGENTOT_LC 5000 NGEN_LC 0 RANSEED 223459 FORMAT_MASK 48 CIDRAN_MIN 0 CIDRAN_MAX 53467 CIDOFF 0 JOBID 1 NJOBTOT 1 WRFLAG_MODELPAR 0 WRFLAG_YAML_FILE 1 PATH_SNDATA_SIM /scr
atch/midway2/rkessler/SNDATA_ROOT/SIM PATH_USER_INPUT /project2/rkessler/SURVEYS/DES/USERS/rebeccachen/photoz_bias SIMGEN_DUMPALL 3 CID S2mb MAGSMEAR_COH HOSTLIB_GENZPHOT_FUDGEPAR .0
8 -0.1 .03 .03 .20 HOSTLIB_GENZPHOT_BIAS .001 -.000 .000 .000

**Comment by RickKessler** [comment]
Fixed refactor bug that read HOSTLIB_GENZPHOT_BIAS as double instead of float.
