### ISSUE TITLE
SALT3 with Scatter Model changes reverted?

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#333]
Please do not address this if you are on vacation!

It looks like this commit somehow got reverted. 
https://github.com/RickKessler/SNANA/commit/8d5b69b8cc057813a3dd656d94d4364b52f2a352

because in the latest version of the code those changes are no longer present and this means I cant run SALT3 with a scatter model anymore. It looks like it got re-hardcoded to SALT2 again here
https://github.com/RickKessler/SNANA/blob/master/src/sntools_genSmear.c#L1119

Oh, I see, you changed things for BYOSED. So how do I specify G10 with SALT3 now so that it points to the salt3 file instead of the salt2 file? see error below

```  
init_genmag_SALT2 : Done. 

 ****************************************************************** 
   init_modelSmear: init intrinsic SN smearing with model=G10  
	 Smear-mode: complete wavelength dependence. 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by read_genSmear_SALT2disp
   Cannot open smearFile 
   /project2/rkessler/SURVEYS/PS1MD/USERS/dscolnic/PANTHEON+/models/SALT3.K20/salt2_color_dispersion.dat

```

**Comment by RickKessler** [comment]
Fixed, but not tested. Please remove the salt2_color_dispersion.dat from SALT3.K20 and try again.
