### ISSUE TITLE
simulation looked for SALT3 file for a SALT2 model

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#335]
Hi Rick,
This seems a bug. I specified a SALT2 model for sim but got an error looking for `SALT3.INFO`
```
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by read_genSmear_SALT2sigcoh 
  - Cannot open infoFile  
  - /project2/rkessler/SURVEYS/WFIRST/USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/saltmodels/SALT2.JLA-B14-ext/SALT3.INFO 
```
logs are in this dir `$WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/SIMLOGS_SIM_SALT3TRAIN_102/`

It seemed a little weird though I was using the same model for a few different GENVERSIONS but only 2 of the 6 failed.

**Comment by RickKessler** [comment]
Issue is that SALT3 string is in the path, even though it's a SALT2 model.
Fixed to check version string starting 5 characters before the dot, so no longer care about name of path.
