### ISSUE TITLE
Error in SALT2mu_exe.pl: SIGINT and BIASCOR

### ISSUE THREAD

**Issue by wycombe7** [RickKessler/SNANA#34]
Hi Rick, 

I'm trying to look at how the mass step evolves with redshift and how the SN parameters vary as a function of mass. To do this, I'm splitting in to mass and redshift bins and running SALT2mu. Doing this, I get a range of crashes, all apparently related to the BIASCOR in high SNR events (being either high, zero or crazy).

Example outputs can be found here: 

- $PIPPIN_OUTPUT/MS_5YR_DESONLY_SNIRF_MASSSPLIT/6_BIASCOR/5YR_SNIRF_5D/output/SALT2mu_FITJOBS/SALT2mu_FITOPT000_MUOPT005.LOG

>init_sigInt_biasCor_SNRCUT for all IDSAMPLEs combined:
        sigInt[ia,ib,ig=0,0,0] = 0.0695 (17 events with SNR>60)
        sigInt[ia,ib,ig=0,1,0] = 0.1017 (21 events with SNR>60)
        sigInt[ia,ib,ig=1,0,0] = 0.0886 (21 events with SNR>60)

> FATAL ERROR ABORT called by quickBinSearch
> VAL = 1.000000e+00 outside 'init_sigInt_biasCor_SNRCUT' range defined for 6.882215e-01 < VAL < 9.918132e-01

- $PIPPIN_OUTPUT/MS_5YR_DESONLY_SNIRF_MASSSPLIT/6_BIASCOR/5YR_SNIRF_5D/output/SALT2mu_FITJOBS/SALT2mu_FITOPT003_MUOPT001.LOG 
> FATAL ERROR ABORT called by next_covFitPar
   Crazy parval_next(sigint) = 148.649997  at NFIT_ITER=2
   redchi2=-0.00, parval[orig,step]=21.208,0.050

- $PIPPIN_OUTPUT/MS_5YR_DESONLY_SNIRF_ZSPLIT/6_BIASCOR/5YR_SNIRF_5D/output/SALT2mu_FITJOBS/SALT2mu_FITOPT000_MUOPT004.LOG

> FATAL ERROR ABORT called by init_sigInt_biasCor_SNRCUT
   NUSE[ia,ib,ig=0,0,0] = 0 is too small.
   Check biasCor events with SNR> 60.0

The latest error is due to the fact that there are no high S/N events in the BiasCor at high-z (an issue I don't know how to get around - there shouldn't be any!), but the other two confuse me. 

Any thoughts?

**Comment by RickKessler** [comment]
for init_sigInt_biasCor_SNRCUT failure, there are only ~20 events to compute RMS, which is too small. The failure is likely due to a fluctuation that the numerical recipe can't handle, and not worth fixing since I wouldn't trust it even if I forced it to run without aborting. I suggest removing the 11-12 LOGMASS bin, or modify your LOGMASS bins to contain more events in the high-mass bin.

**Comment by RickKessler** [comment]
for the last issue at high redshift, this is known issue that intrinsic dispersion for the biasCor sample cannot be determined without a high-SNR sub-sample. However, you can force a particular sigInt with input such as sigint_biascor=0.10

**Comment by wycombe7** [comment]
Thanks Rick: 

> for init_sigInt_biasCor_SNRCUT failure, there are only ~20 events to compute RMS, which is too small. The failure is likely due to a fluctuation that the numerical recipe can't handle, and not worth fixing since I wouldn't trust it even if I forced it to run without aborting. I suggest removing the 11-12 LOGMASS bin, or modify your LOGMASS bins to contain more events in the high-mass bin.

For this, do you mean that the biasCor simulation doesn't have enough high-mass events? In which case, weighting or increasing the simulation size might help? 

> for the last issue at high redshift, this is known issue that intrinsic dispersion for the biasCor sample cannot be determined without a high-SNR sub-sample. However, you can force a particular sigInt with input such as sigint_biascor=0.10

Gracias: exactly what I was looking for!

Is the 2nd error basically a consequence of the first?

**Comment by RickKessler** [comment]
for the remaining issue (Crazy parval_next), what were the options in  FITOPT003 ?

**Comment by wycombe7** [comment]
> for the remaining issue (Crazy parval_next), what were the options in FITOPT003 ?

FITOPT: 003 [SALT22_cal] FITMODEL_NAME '$PS1_ROOT/models/SALT2/SALT2.sys2'

**Comment by RickKessler** [comment]
for remaining issue, grep IDSAMPLE <stdout> shows that there are only 2 events, so not surprised that the fit doesn't work. The LOGMASS range 5-8 doesn't have enough events.

**Comment by wycombe7** [comment]
Thanks Rick :)
