### ISSUE TITLE
Query: FAIL_REPEAT scripts when running in batch mode

### ISSUE THREAD

**Issue by deepchatterjeeligo** [RickKessler/SNANA#340]
In the event of a failure while running batch jobs in SNANA, there are a set of FAIL_REPEAT scripts that are generated for every species in the MASTER INPUT file. Are these intended for resubmission or checkpointing? I noticed that FAIL_REPEAT scripts are created for a species even when sims of that particular species successfully complete, while another fails. Example, if the INPUT file contains SLSN and mdwarf flares, and say the latter fails, there is a FAIL_REPEAT for SLSN also created. Any advice on using these scripts and their intended use is welcome.

**Comment by RickKessler** [comment]
The FAIL_REPEAT scripts are to help developers debug problems and are not intended for regular use. When a failure occurs, check the ABORT comment in the FAIL_SUMMARY; if that isn't helpful, post a GitHub issue with directory location.
