### ISSUE TITLE
Bug in coadded NEXPOSE 

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#341]
Reference folder on NERSC (Cori): `/global/homes/m/mvincenz/desc/DEBUG_SIMLIBCOADD`
I run `simlib_coadd.exe baseline_nexp1_v1.6_10yrs_DDF.simlib`
and I noticed everything works correctly except the number of co-added exposures, NEXPOSE, is not correctly reported in the
IDEXPT column.

**Comment by RickKessler** [comment]
IDEXPT*NEXPOSE should be fixed now on Cori. I also added a print summary at the end for min/max NOBS and min/max MJD. Max NOBS is 1219, well below the max allowed of 5000.

**Comment by maria-vincenzi** [comment]
I tested this and it works perfectly for me!
