### ISSUE TITLE
Error related to random seed when running snana in batch mode

### ISSUE THREAD

**Issue by deepchatterjeeligo** [RickKessler/SNANA#342]
I am facing an error when running SNANA, that is related to the random seed (I think). I am trying to run sims in batch.
My input yaml file is 
`/global/cfs/cdirs/snana/SURVEYS/LSST/USERS/deep/plasticc-sims/SIMGEN/REFAC_SIMGEN_MASTER_LSST_WFD.INPUT` on nersc.

The error message looks something like this. All the log files in the simlogs, has the similar error.

```
 FATAL ERROR ABORT called by init_CIDRAN
   Unable to try CIDTMP = 983162 or 1038660  (CIDRAN=1010911)
   CIDMAX=1038660  NPICKRAN=1  i=38659 of 1011420  CID=0
```

**Comment by RickKessler** [comment]
fixed.
