### ISSUE TITLE
weird bug about model path

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#343]
There is a weird bug somewhere that causes SNANA to look for a model path that's not defined anywhere in the sim input when calling from SALT3 pipeline.
```
ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by read_SALT2_INFO_FILE 
  - Could not open SALT2 info file: 
  - /project2/rkessler/SURVEYS/WFIRST/USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/lcfitting/SALT2.JLA-B14-ext/SALT2.INFO 

```
logs are at `$WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/SIMLOGS_SIM_SALT3TRAIN_103 
`

The command called by pipeline was `submit_batch_jobs.sh SALT3_TRAINING_MASTER.INPUT.temp.1609362621.522742_103` in `$WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/`

**Comment by RickKessler** [comment]
was caused by $SNANA_MODELPATH override. This obsolete feature will now result in abort.
