### ISSUE TITLE
Error when I try to install snana?

### ISSUE THREAD

**Issue by liuchengqi** [RickKessler/SNANA#344]
../src/sntools.h:176:32: error: array has incomplete element type
      'struct random_data'
  struct random_data  ranStream[MXSTREAM_RAN];
                               ^
../src/sntools.h:176:10: note: forward declaration of 'struct random_data'
  struct random_data  ranStream[MXSTREAM_RAN];

**Comment by RickKessler** [comment]
Try these C flags in sntools.h
//#define  ONE_RANDOM_STREAM  // enable this for Mac (D.Jones, July 2020)
//#define  MACOS              // another MAC OS option, D.Jones, Sep 2020

**Comment by liuchengqi** [comment]
Thank you very much
