### ISSUE TITLE
SED template errors

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#35]
New DES CC SED templates currently exist within 
/project2/rkessler/SURVEYS/DES/USERS/rhounsell/CC_TEMPLATES/NON1ASED.DES_CC 
Note only the DES*  files are being  used. 
The grid for these templates can  be found in 
/project2/rkessler/SURVEYS/DES/USERS/rhounsell/CC_TEMPLATES/GRID

Could we please incorporate the SED errors into SNANA  so we can apply them in psnid. 
Thank  you

**Comment by RickKessler** [comment]
Template errors seem to be working so closing out issue, at least for now.
