### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by liuchengqi** [RickKessler/SNANA#350]
When I run the example using snlc_sim.exe of the User's manual, I got an error like:

<img width="456" alt="bd91ca40a0d43b3f153fec472d872fb" src="https://user-images.githubusercontent.com/56668397/104534554-76c59f00-564f-11eb-9ac0-24344f9a0fe1.png">

means there is not a PDF(point distribution function)?

**Comment by RickKessler** [comment]
The distribution (PDF = Prob Distr. Func)  for stretch (x1) is not specified. Early SNANA codes had many defaults, but over time people forgot about the defaults which led to problems in our analyses. My suspicion is that these sample input files rely on defaults that are no longer available ... I will check them.

**Comment by RickKessler** [comment]
I fixed the sample_input_files/SALT2 files, but it might be a while before we update SNDATA_ROOT in Zenodo. In the meantime, this subDirectory is here:
[sample_input_files_SALT2.tar.gz](https://github.com/RickKessler/SNANA/files/5816682/sample_input_files_SALT2.tar.gz)

**Comment by liuchengqi** [comment]
I got it, Thank you very much.
