### ISSUE TITLE
RANSYSTPAR has no effect

### ISSUE THREAD

**Issue by moonwalkermedia** [RickKessler/SNANA#351]
Including RANSYSTPAR in the simulation stage appears to have no effect.

I have three pippin input files: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_SIM_NOSYS_3YR/`, `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_SIM_REALSYSG10_3YR/`, and `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_SIM_BIGSYSG10_3YR/`

These have no systematic offset, realistic systematic offsets (zp and wavelength), and big systematic offsets (zp and wavelength) respectively. However the simulated lightcurves, and the final cosmology of all three is identical!

**Comment by OmegaLambda1998** [comment]
Sorry, was logged in on the wrong account, this is my issue.

**Comment by RickKessler** [comment]
There was a very minor bug changing the SEED for each SURVEY, but the SEED is indeed changed for each sample.

**Comment by OmegaLambda1998** [comment]
Issue on my end, RANSYSTPAR works fine.
