### ISSUE TITLE
FITOPTs formatting error?

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#353]
Running `submit_batch_jobs.sh /project2/rkessler/PRODUCTS/SNANA_DEBUG/rebeccachen/SIMS_RC.NML`
causes "argument of type 'NoneType' is not iterable" error

The fitting runs fine with snlc_fit.exe and as batch job with all fitopts commented out so seems like the error is related to the fitopts. (Specific FITOPT keys used are USE_SNHOST_ZPHOT T, DOFIT_PHOTOZ T OPT_PHOTOZ 1)

Edit: Suspect it has something to do with formatting but based off the manual for submit_batch_job options it looks okay, so I am not sure

Thank you!

**Comment by RickKessler** [comment]
fixed recent refactor bug. Try again.

**Comment by rebeccachen0** [comment]
Think that fixed it, thanks!
