### ISSUE TITLE
add abort when spectra are not simulated successfully

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#355]
Hi Rick, there's an issue in SNANA where if no SPECTROGRAPH is given in a kcor file, a simulation that should be simulating spectra will not abort - it will just run the simulation and produce no spectra.  I think it would be best to throw an ABORT flag in this case

**Comment by mi-dai** [comment]
example:
```
cd $SNANA_DEBUG/mdai/no_spectrograph
snlc_sim.exe JLA_TRAINING_COMBINED_LOWZ.INPUT 
```

**Comment by RickKessler** [comment]
sim now aborts if spectra are requested (via SIMLIB or input file) but there is no SPECTROGRAPH defined in the kcor file.

**Comment by djones1040** [comment]
thanks!
