### ISSUE TITLE
define SPECTROGRAPH in kcor when using combine_dataVersions.py

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#357]
Currently when combining data versions no SPECTROGRAPH is defined in the kcor input - this causes no spectra being simulated with the combined kcor file. Can this be added in the combine_dataVersions.py script?
The combine example is in `$WFIRST_USERS/mdai/combine_lowz/combine_lowz/`

**Comment by RickKessler** [comment]
is this your input file: COMBINE.INPUT.ref ? If so, I don't find the IFU table in the kcor files.

**Comment by RickKessler** [comment]
is this your input file: COMBINE.INPUT.ref ? If so, I don't find the SPECTROGRAPH table in the kcor files.

**Comment by mi-dai** [comment]
this is the input `combine_jla_lowz_after_split.input`
I added the SPECTROGRAPH table files in the dir `kcor_for_combine`
The separate kcor files for each survey were made by myself and I don't think I was aware that I needed to add that SPECTROGRAPH key. Should I add those first, in each of the kcor files?

**Comment by RickKessler** [comment]
should be working ... try it.

**Comment by mi-dai** [comment]
tested and worked
