### ISSUE TITLE
No Output from SALT2 Sim with Hostlib

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#359]
When running a batch job for simulated SNe Ia with ZTF_DR3 using a custom hostlib, no output is produced even though no error message is reported in the logs. The input file on nersc is located at `/global/cfs/cdirs/snana/SURVEYS/LSST/USERS/agaglian/ZTFtests/REFAC_SIMGEN_MASTER_ZTF.INPUT` and the simlogs are located at `/global/cfs/cdirs/snana/SURVEYS/LSST/USERS/agaglian/ZTFtests/SIMLOGS_AGAGLIAN_ZTF/`. The last line in the log is:

 `******************************************************************
   INIT_HOSTLIB(): Read host-galaxy library.`

**Comment by RickKessler** [comment]
Remove commas from HOSTLIB file, and check HOSTLIB format in snana manual Fig 8 (near page 60). When valid HOSTLIB keys are not found, I updated the sim to abort with message instead of hanging ... fix will be at NERSC with next SNANA update.
