### ISSUE TITLE
Printing  MWEBV

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#36]
I am trying to print MWEBV in FITOPT000.FITRES file.  
I have included the line 
APPEND_FITRES: MWEBV
in my NML file.

When I  run 
split_and_fit.pl  
/project2/rkessler/SURVEYS/DES/USERS/rhounsell/MAKE_TEMPLATES/SNANA_PSNID_ALL.NML

My output fitres files in /project2/rkessler/SURVEYS/DES/USERS/rhounsell/MAKE_TEMPLATES/DES_ALL/DESALL_forcePhoto_real_snana_fits do not seem to have it appended. 

Please advise.  
Thank  you.

**Comment by RickKessler** [comment]
The above APPEND syntax is incorrect. Scroll down through the instructions in $SNANA_DIR/util/split_and_fit.pl and note the following:
#  APPEND_TABLE_TEXT:  <var1>  <var2> ...
#     (extract variables from hbook or root file and append text table)
#
#  APPEND_FITRES: FITRES  <var1>  <var2> ... 
#     (OBSOLETE: please switch to APPEND_TABLE_TEXT key above)
