### ISSUE TITLE
Large sims crash CID

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#360]
Very large sim crashes due to CID 
$PIPPIN_OUTPUT/AM_DES5YR_SIMS/1_SIM/42XDES/LOGS/TMP_amol_PIP_AM_DES5YR_SIMS_42XDES_NONIaMODEL3-0017_37124.LOG

init_CIDRAN: initialize 158045522 RANDOM CIDs (CIDOFF=153312752)  
  
   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by init_CIDRAN
   CIDRAN_MAX=366965460 exceeds limit of MXCID_SIM=299999999
   Reduce CIDRAN_MAX to be <= 299999999

**Comment by RickKessler** [comment]
with NGEN_UNIT=42 and RANSEED_REPEAT=30, the multiplier is 30x42=1260! This large sample exceeds the current bound of 300 million per submit. If really necessary, the bound can be increased, but please check if/why such a large sample is needed for DES.

**Comment by RickKessler** [comment]
please rebalance CC types and try to stay under 300 million total generated.

**Comment by anaismoller** [comment]
Can at least the fitting limit be increased? I have the sim but can't fit it....

$PIPPIN_OUTPUT/AM_DES5YR_SIMS/2_LCFIT/T_28XDES/output/SPLIT_JOBS_LCFIT/PIP_AM_DES5YR_SIMS_28XDES_FITOPT000_SPLIT016.LOG, excerpt below
[   ERROR |           manager.py:395]   	Excerpt:     FATAL ERROR ABORT called by RDVERSION_FITS
[   ERROR |           manager.py:395]   	Excerpt:       NROW= 4249374 exceeds bound MXSNLC= 4000000
[   ERROR |           manager.py:395]   	Excerpt:       Check MXSNLC parameter in snana.car
[   ERROR |           manager.py:395]   	Excerpt:    
[   ERROR |           manager.py:395]   	Found error in file

**Comment by RickKessler** [comment]
increased bound from 4 million to 5 million.
