### ISSUE TITLE
sim error about INODE

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#361]
Logs in `$WFIRST_USERS/mdai/salt3_local/SALT3/examples/SALT3_training_pipeline/SIMLOGS_SIM_SALT3TRAIN_901`

FAIL_SUMMARY:
```
FAILURE-0001:
  JOB_LOG_FILE:       TMP_mida_SALT3TRAIN_Foundation_901_SNIaMODEL0-0001_75427.LOG 
  FAIL_REPEAT_SCRIPT: FAIL_REPEAT_SALT3TRAIN_Foundation_901_SNIaMODEL0-0001_75427.CMD 
  FAIL_MODE:          ABORT 
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by get_genSmear_SALT2 
  - Could not find INODE for lam=10806.8 
  - NNODE=12  INODE=-9 
```

**Comment by RickKessler** [comment]
there was a subtle index bug that occurred only when using SPECTROPGRAH with SALT2 model. Last fix was not the right fix, but hopefully correct this time. Try again.

**Comment by mi-dai** [comment]
worked! thanks!
