### ISSUE TITLE
new batch failure due to checking jobs in queue

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#364]
Hi Rick, I'm getting an error from submit_batch_jobs.sh:
```
['27 of 45 jobs NOT in queue.', 'Check for sbatch problem; e.g., njob limit.']
```
I think the reason is that the jobs are finishing so quickly that the batch script can't see them and then it crashes.  Here's an example:
```
cd /project2/rkessler/SURVEYS/PS1MD/USERS/djones/RAISIN/cosmo/fit
submit_batch_jobs.sh REFAC_CSP_RAISIN_sys.nml
```

**Comment by RickKessler** [comment]
what is $RAISIN_ROOT ?
And beware of tabs ; e.g., 
   "sbatch\t /home/djones1741/djones/SBATCH_sandyb.TEMPLATE 45"

**Comment by RickKessler** [comment]
Earlier today I fixed a related bug caused by extra batch submissions that have no jobs; for these I added an extra 10 sec delay before exiting so that the Npid check works. This fix might fix your problem too, so try again.

**Comment by djones1040** [comment]
it did work earlier today, so will assume it's fixed until I find out otherwise!
