### ISSUE TITLE
rejected by NEPOCH<1 ?

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#367]
not sure if this is a bug.

I was trying to generate a large biascor sim and noticed a large fraction of the events were "rejected by NEPOCH<1" (from the README file). There wasn't a CUTWIN option about NEPOCH set so I'm not sure how and why this happened.

logs are here: $WFIRST_USERS/mdai/SALT3_training_tests/all_tests/baseline_copy/SIMLOGS_SIM_SALT3TRAIN_BIASCOR_biascor_991

Thanks!

**Comment by RickKessler** [comment]
My guess is that many PEAKMJD selections do not overlap the MJD range of the SIMLIB, so it's normal behavior.

**Comment by mi-dai** [comment]
ah I see. I'll try narrowing the MJD range and report back. Thanks!
