### ISSUE TITLE
Option for using IAUC names over SNID

### ISSUE THREAD

**Issue by AnthonyC958** [RickKessler/SNANA#370]
Many supernovae have multiple internal names or IDs, so if we can use their single IAUC name instead, we'll be able to catch duplicates. If a SN only has an SNID and no IAUC (or IAUC unknown), the SNID should sill be used.

**Comment by RickKessler** [comment]
Try IAUC option in snana manual 12.1.4 Working with IAUC names. It's an old feature, so may be buggy from lack of use. Please report problems here.
