### ISSUE TITLE
APPLY_SEARCHEFF_OPT: 5 doesn't work

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#371]
trying to use `APPLY_SEARCHEFF_OPT: 5` with a `SEARCHEFF_zHOST_FILE:` but failed.

```
  PRE-ABORT DUMP from function check_APPLYMASK_SEARCHEFF : 
	 APPLY_SEARCHEFF_OPT += 1 --> detection pipeline.
	 APPLY_SEARCHEFF_OPT += 2 --> SPEC confirmed.
	 APPLY_SEARCHEFF_OPT += 4 --> zHOST.

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by check_APPLYMASK_SEARCHEFF
   Invalid user-input 'APPLY_SEARCHEFF_OPT: 5' 
   Simulation can produce SEARCHEFF mask 3 
```
this can be reproduced by `snlc_sim.exe $SNANA_DEBUG/mdai/searcheff_opt/JLA_TRAINING_COMBINED_LOWZ.INPUT`

**Comment by RickKessler** [comment]
Your input file does not specify EFF_SPEC, so by default EFF_SPEC=1 which conflicts with your request to select photometric sample only. EFF_SPEC can be set to zero with
   SEARCHEFF_SPEC_FILE:   ZERO 
which I have added to your JLA input file.
The zHOST map did not have sufficient redshift coverage for GENRANGE_REDSHIFT, so I copied SEARCHEFF_zHOST_LOWZ.dat locally and added a few more rows to this table (see # RK comments)
