### ISSUE TITLE
No simulation in ZTF i band

### ISSUE THREAD

**Issue by bcarreres** [RickKessler/SNANA#379]
Hi,
I would like to simulate SN in ZTF gri bands. 

I create the kcor input :
```
# Prepare SNANA calibration file with command:
#   kcor.exe  kcor_ZTF.input
#
# The output ".fits" file is the KCOR_FILE argument
# in the simulation and fitting program.
#
# ======================== BEGIN INPUT  =========================


# specify spectral template for supernova
SN_SED: Hsiao07.dat   # see $SNDATA_ROOT/snsed
# BD17_SED:     bd_17d4708_stisnic_005.dat
LAMBDA_RANGE: 2100 9100
# specify filters
MAGSYSTEM: AB     (define mag system for filters below)
FILTSYSTEM: COUNT
FILTPATH:  $SNDATA_ROOT/filters/ZTF/ztf_information_28_2018
SURVEY: ZTF_MSIP
FILTER: ZTF-g   ztf_g_band.dat   0.0
FILTER: ZTF-r   ztf_r_band.dat   0.0
FILTER: ZTF-i   ztf_i_band.dat   0.0

# define lambda range for SN templates;
# template lambda binning is used internally
LAMBDA_RANGE: 2100 12000

# define output file
OUTFILE: kcor_ZTF.fits
```
and I didn't get any problem when I use kcor.exe on it, the logfile is : [kcor_ZTF.log](https://github.com/RickKessler/SNANA/files/5953669/kcor_ZTF.log)

I create manually a "fake" simlib with observation in gri bands : [ZTF_TEST_SIMLIB.txt](https://github.com/RickKessler/SNANA/files/5953653/ZTF_TEST_SIMLIB.txt)

And I use the option :
`GENFILTERS: gri`
In the SIM INPUT file.

But no one of my SIM SN has a flux in i band... I think I've made a mistake but I don't find it..

**Comment by RickKessler** [comment]
what SNIa model is used ? If SALT2, note that default wavelength range is 2800 -7000 A for central wavelengths, so i,z are excluded at very low redshifts. There are IR-extended models; e.g. 
   GENMODEL: $SNDATA_ROOT/models/SALT2/SALT2.P18_UV2IR

**Comment by bcarreres** [comment]
Thank's ! I've missed that !
