### ISSUE TITLE
SALT2 P18_UV2IR color correction

### ISSUE THREAD

**Issue by bcarreres** [RickKessler/SNANA#380]
Hi,
I've a question about the SALT2.P18_UV2IR model taht I would like to use to produce simulations.
In the file SALT2/SALT2.P18_UV2IR/SALT2.INFO I find the color correction parameters:
```
RESTLAMBDA_RANGE: 1700. 23000.  # extended using snsedextend tools 
COLORLAW_VERSION: 1 
COLORCOR_PARAMS: 2800 7000 4  -0.50429400 0.78769100 -0.46171500 0.08156190
COLOR_OFFSET: 0.0 

```
But in the SALT2/SALT2.P18_UV2IR/salt2_color_correction.dat.gz I have:
```
4
-0.98462437
0.42685586
-0.08311382
0.00571099
Salt2ExtinctionLaw.version 1
Salt2ExtinctionLaw.min_lambda 2800
Salt2ExtinctionLaw.max_lambda 10000
```
That aren't the same parameters for the polynomial of the colorlaw.

When I launch simulation it seems that SALT2 use the parameters given in the INFO file (same as SALT2.JLA-B14 color law)
to plot the table :
![Capture d’écran du 2021-02-10 14-19-04](https://user-images.githubusercontent.com/64126910/107515332-2a687300-6bab-11eb-9c29-2cfaa03e274d.png)

Which ones are the "good" parameters for SALT2.P18_UV2IR model and which are used in the simulation?
Thanks

**Comment by jpierel14** [comment]
@RickKessler? I'm fairly certain the params in SALT2/SALT2.P18_UV2IR/salt2_color_correction.dat, at least when SNCosmo constructs a SALT2 model it reads the color law parameters out of there and plotting them side-by-side says that's the right set. But does SNANA ignore that file and stick with whats in the SALT2.INFO? If so, we'll need to swap that out unless you're ensuring the original color law is used for a reason.

**Comment by RickKessler** [comment]
SNANA uses the SALT2.INFO file. The old salt2_color_correction.dat file is a relic of Julien's original file that I forgot to remove after creating the SALT2.INFO file.
