### ISSUE TITLE
Value of zHD

### ISSUE THREAD

**Issue by bcarreres** [RickKessler/SNANA#381]
Hi,
In the manual of SNANA I read that zHD = (1+zCMB)(1+VPEC/c) - 1. 
But when I run a simulation and then a fit of SN the FITRES file give is such that zHD = (1+zCMB)/(1+VPEC/c):
![image](https://user-images.githubusercontent.com/64126910/107636173-8ba44b00-6c6c-11eb-84e9-f794d14b2fe0.png)
and I have zHD=SIM_ZCMB.
Are the 2 redshifts reversed?
Thanks

**Comment by RickKessler** [comment]
The above is correct and a bit confusing. SIM_ZCMB is indeed the true CMB redshift. But observed zCMB (and zHELIO) have peculiar velocity offsets. zHD is corrected back to CMB frame and should equal SIM_ZCMB if there is a perfect VPEC correction.
