### ISSUE TITLE
seg fault issue  and (unrelated) RV/AV abort issue

### ISSUE THREAD

**Issue by reneehlozek** [RickKessler/SNANA#383]
I'm running SNANA on NERSC and trying to re-run some PLAsTiCC models. However, I'm getting lots of my runs aborting due to segmentation faults.
` Initialize NstringMatch for sim-input file

 *** Break *** segmentation violation
  Read user input file 2: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/rhlozek/pfs/SIMGEN_INCLUDE_SNIax.INPUT`

An example of one of the files detailing the crash is attached: [TMP_rhlo_RH_PFS_MODEL52_SNIax_NONIaMODEL0-0010_47898.LOG](https://github.com/RickKessler/SNANA/files/5968794/TMP_rhlo_RH_PFS_MODEL52_SNIax_NONIaMODEL0-0010_47898.LOG)

Also note that I'm working here: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/rhlozek/pfs/SIMLOGS_RH_PFS

A separate issue was in previous models where only the AV was specified - I needed to correct the PLAsTiCC models to have both AV and RV specified in order to complete.

**Comment by RickKessler** [comment]
hmmm, very strange. AGN are different here because they have a redshift but are described by LCLIB. I can debug this outside your directory, so try again for now without AGN. Note that once any job fails, submit_batch kills all other jobs so the other failures are probably not real.

**Comment by RickKessler** [comment]
ok, turned out to be a silly bug reading LCLIB_CUTWIN. I checked that one of your FAIL_REPEAT scripts now works. You can continue with AGN.
