### ISSUE TITLE
GENVPEC when VEL_CMBAPEX: 0

### ISSUE THREAD

**Issue by bcarreres** [RickKessler/SNANA#384]
Hi,

I would like to set VEL_CMBAPEX = 0 to run some tests, but when I run the simulation all my SN have Vpec = 0 km/s
The command in my SIM INPUT are :

```
GENSIGMA_VPEC: 300
VEL_CMBAPEX: 0
```

And in the sim README there is the 2 lines : 

```
v(cmb)=0 -> REDSHIFT_HELIO=REDSHIFT_CMB (legacy option)
Peculiar Velocity (VPEC) Gauss sigma: 300.0 km/sec
```
Is it possible to set peculiar velocity and set VEL_CMBAPEX = 0? 

Thanks

**Comment by RickKessler** [comment]
I will check this later, but can you try setting VEL_CMBAPEX: 0.001 ?

**Comment by bcarreres** [comment]
I've checked and VPEC are generated when setting VEL_CMBAPEX: 0.001

**Comment by RickKessler** [comment]
I also fixed the sim so that VEL_CMBAPEX=0 does not suppress VPEC .. will be available next git pull on midway.
