### ISSUE TITLE
[feature request] HOSTLIB option to select single index instead of providing all coefficients

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#386]
We would like to use a single index to select host spectra template given a file of host spectra templates with each column represents one galaxy.

I have compiled a file with 10 galaxy spectra in rest frame: $WFIRST_USERS/mdai/host_spec/host_spec/host_spec_template.txt. 
let me know if anything needs to be added/changed.

Thanks!

**Comment by RickKessler** [comment]
done. Search manual for SPECDATA_FILE and IDSPECDATA
