### ISSUE TITLE
SALT2mu idsample_select issue 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#388]
Right now, the "idsample_select" command for SALT2mu is called _after_ the biascor prep stage. This makes the idsample_select stage mostly useless, because if I want to subselect only DES from a data file with DES+SDSS+SNLS, it will break if I don't also provide the extraneous SDSS/SNLS biascor files. 

I think moving the idsample_select option to go before the biascor_prep stage would be a good idea.

**Comment by RickKessler** [comment]
please provide example job for above issue.

**Comment by bap37** [comment]
/project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/FOR_RICK.INPUT

The data file specified here contains six surveys, but I only want to look at the DES data, which is why I have the simfile_biascor point to DES data only.

**Comment by RickKessler** [comment]
Fixed with one line of code.
