### ISSUE TITLE
RESTLAMBDA_FITRANGE not getting used?

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#389]
see RESTLAMBDA_FITRANGE = 2000 9203 in my nml file 
it doesnt appear to be getting used
`$SNANA_DEBUG/djbrout/lambdarange/FAIL_REPEAT_LOSS_FITOPT037_SPLIT001.CMD`

**Comment by RickKessler** [comment]
RESTLAMBDA_FITRANGE = 2000.0 9203.0 is trying to extend the range of SALT2 SEDs beyond 9200A, which is not allowed. You can restrict it, but not extend it without retraining.
