### ISSUE TITLE
GENSIGMA_RV crashes snlc_sim.exe

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#39]
The following command fails (which contains GENSIGMA_RV 0.15)
$SNANA_DEBUG/dillon/RUNTEST
if you remove GENSIGMA_RV 0.15 then it appears to run fine...
Thanks for your help debugging this new/old feature!

**Comment by djbrout** [comment]
ah, okay looks like you need a left hand and a right hand sigma... seems to be working now. testing implementation of host Rv with SALT now

**Comment by djbrout** [comment]
ok, still not working... 

```
PRE-ABORT DUMP from function exec_GENGAUSS_ASYM : 

# ------------------------------------------- 
 START dump_GENGAUSS_ASYM  for 'SALT2BETA' (INDEX=3) 
	 PEAK = 3.800  
	 RANGE = 2.700 to 3.500 
	 SIGMA(-/+) = 0.000 / 0.000 
	 SKEWNORMAL(LOC,SCALE,SKEW) = 0.000 , 0.000 , 0.000
 END dump_GENGAUSS_ASYM 
# ------------------------------------------- 
 DO_SKEW[SIGMA,NORMAL] = 0, 0 



   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by exec_GENGAUSS_ASYM
   Could not find SALT2BETA RANDOM after 1001 tries 
   Something is crazy.
```

**Comment by RickKessler** [comment]
Your PEAK RV value (3.8) is outside the range (2.7 to 2.5), and SIGMA=0. Hence it can never generate an RV inside your range. Try extending the RV range to 4.

**Comment by djbrout** [comment]
omg

**Comment by djbrout** [comment]
oh, ok but I set my peak to 1.6. See RUNTEST command

```snlc_sim.exe sn_ia_salt2_g10_lowz.input PATH_SNDATA_SIM /scratch/midway2/rkessler/SNDATA_ROOT/SIM CIDOFF 0 JOBID 1 NJOBTOT 1 GENVERSION TMP_djbr_PIP_CC_LOWZcc_bvarC11_hostrv15_36370 GENPREFIX PIP_CC_LOWZcc_bvarC11_hostrv15_SNIa RANSEED 12345 FORMAT_MASK 32 GENMAG_SMEAR_MODELNAME C11 GENPEAK_SALT2BETA 3.8 GENPEAK_SALT2c -0.069 GENSIGMA_SALT2c 0.0 0.15 GENPEAK_RV 1.6 GENSIGMA_RV .1 .9 GENRANGE_RV 1.3 4.5 CIDOFF 1000 NGENTOT_LC 27072 NGEN_LC 0```

**Comment by djbrout** [comment]
so is it using BETA instead of RV? which would kind of make sense... i dont really understand how this is hooked up to the SALT model though

**Comment by RickKessler** [comment]
my comment above is correct if RV is replaced with BETA.
