### ISSUE TITLE
VERSION_REFORMAT_FITS

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#393]
I was trying to convert the Foundation_DR1 lightcurves from txt to fits format (classifiers like SNN don't know how to handle text format).
I tried to run the command:
`snana.exe convert2FITS_Foundation.nml`
in the folder:
`/project2/rkessler/SURVEYS/DES/USERS/mvincenzi/Foundation`

But I get the following error:
```

   Assign integer CID=     1 for 2016afk
     Done Reading CID 2016afk            NMJD(found,stored)= 296  296
       Analyze ISN=       1  for 2016afk          NMJD(stored,cuts)= 296-> 296

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by wr_snfitsio_fillTable
   Cannot write SNID='' (blank string)
   to colnum=2 of table=HEAD

```

I wanted to check if the problem is in the Foundation data format so
I tried to re-convert the DE3YR LOWZ lightcurves running:
`snana.exe convert2FITS_test.nml`
(same folder as above).
But I get the same error so I guess the problem is in snana.exe or in my way of running the code.
Thanks!

**Comment by RickKessler** [comment]
during the I/O refactor, I had noticed this bug and decided not to fix it because the refactored  code will become default soon, and format translation is rare enough that I didn't think anyone would notice. To invoke the refactored I/O ,
    snana.exe convert2FITS_Foundation.nml OPT_DEBUG 21

**Comment by maria-vincenzi** [comment]
perfect!
