### ISSUE TITLE
BBC5D crashing with "Segmentation violation"

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#395]
I noticed that some times BBC is crashing for no reason while the final YAML file is created.
On midway, in the folder:
`/scratch/midway2/rkessler/PIPPIN_OUTPUT/MV_BBCP2/6_BIASCOR/output_LiGaus_SNN/SCRIPTS_BBCFIT`
in the LOG file 
`OUTPUT_BBCFIT-0001_FITOPT000_MUOPT016.LOG`
you can find an example:
```
... everything seemed to work perfectly...


 Open output file with  cutmask_write=0 :
         OUTPUT_BBCFIT-0001_FITOPT000_MUOPT016.FITRES
 Wrote 1882 SN  (1882/3060 used in fit)

 Write MUDIF vs. redshift to OUTPUT_BBCFIT-0001_FITOPT000_MUOPT016.M0DIF

 Write COV_stat matrix to OUTPUT_BBCFIT-0001_FITOPT000_MUOPT016.COV

 ******************************************************************
   write_yaml_info

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
....
```

**Comment by RickKessler** [comment]
Interesting bug. WIth H11 prior there are no simulated CC events, so it bombed at the end trying write NEVT_CPRIOR with an undefined pointer. It is fixed to just write 0 events for H11 prior. I also noticed this fit struggled to converge.
