### ISSUE TITLE
NOBS_RAW and NOBS_APPEND error

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#396]
On NERSC, I was running some LSST sims.
SNANA starts to generate some LCs correctly, but then it crashes and I get a strange error from the function 'SIMLIB_sortbyMJD'.
See an example in folder:
`/global/homes/m/mvincenz/desc/inputs/SIMLOGS_LSSTDDFR2
`
In the LOG file:
`./TMP_mvin_MV_LSSTDDFR2_SNIa-SALT2_NONIaMODEL0-0003_6841.LOG
`
Error:
```
	 Finished generating      300 of 9980 (CID=158770) 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by SIMLIB_sortbyMJD
   Invalid NOBS_SORT=0 for LIBID=0 CID=-9
   NOBS_RAW=101  NOBS_APPEND=101
```

This seems to happen with many of my simlibs (see` /global/cscratch1/sd/mvincenz/simlibs` for my simlibs).
Note that I use the coadded simlibs here (*.simlib.COADD files).
Cheers!

**Comment by RickKessler** [comment]
I do not have permission to read your SIMLIB file

**Comment by maria-vincenzi** [comment]
You should have permission now! Sorry about that.

**Comment by RickKessler** [comment]
another good bug catch!  The long file name in the comment string overwrote the 80 byte allocation to scoop up strings in the SIMLIB file, which wreaks havoc. I extended this allocation to 200 bytes and it runs.
