### ISSUE TITLE
SN fields importing as NULL

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#397]
From the DataPrep stage, all of my DES fields are now NULL, using $SNDATA_ROOT/lcmerge/DES-SN3YR_DES.  An example is at $PIPPIN_OUTPUT/GT_0221_07/0_DATAPREP/DATADES3YR/DES-SN3YR_DES.SNANA.TEXT

Previous jobs with the same inputs haven't had this issue, so I guess something has changed in the last day or two?

**Comment by RickKessler** [comment]
fixed stupid bug where I had accidentally commented out a valid line of code.
