### ISSUE TITLE
How does SNANA parse FITRES files?

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#399]
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-HALO-CMB/6_BIASCOR/1D_ZERO/output/1D.input

When running SALT2mu.exe on this file it will immediately die. This is likely due to me pointing at an edited FITRES file that I saved using space " " as a delineator. While this appears to look good by eye, it causes SNANA to super die violently. What delineator does SNANA use for FITRES files?

**Comment by RickKessler** [comment]
The catenated input FITRES file has no entries, which is why it died.

**Comment by bap37** [comment]
Yes, but if you look at the file that the yaml anchoring is pointing to, it _does_ have entries. I found out that I was accidentally eliding an entire column due to "NULL" being parsed weird, so the problem is resolved!
