### ISSUE TITLE
GEN AV related values dont appear to be working

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#40]
The test here will generate 2 simulations with two different values of GENSIGMA_AV and then compare the simulations
```$SNANA_DEBUG/dillon/RUNTEST```

**Comment by RickKessler** [comment]
GENTAU_AV = 0.13 for both, and indeed GENSIGMA_AV are different. However, the Gaussian/EXPON ratio is 0.01 (at AV=0), so the half Gaussian contribution is negligible.

**Comment by djbrout** [comment]
If i set AV0 = 0.2 then i still get identical AV values

**Comment by RickKessler** [comment]
Fixed a bug computing Gaussian weight, but the issue above was largely because the Gaussian/Expon ratio of integrals was very small.
