### ISSUE TITLE
simulating spectrum warping does not seem to work?

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#407]
Trying to test the `WARP_SPECTRUM:` function according to the manual but it doesn't seem to make any difference. I plotted `FLAM` and `SIM_GENFLAM` and they are exactly the same. 
my input is here `$WFIRST_USERS/mdai/tests/sim_spec_warping/JLA_TRAINING_COMBINED_LOWZ_test.INPUT`
thanks!

**Comment by RickKessler** [comment]
old parsing refactor bug was reading string arg as double, and hence was blank. Fixed.
