### ISSUE TITLE
Calculate 1D biascorr from mu-mu_model (not mb,x1,c comp)

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#41]
Hi - I would like to request an option for SALT2mu to calculate biascor from
mu-mu_model instead of 
(mb-simmb)+alpha*(x1-simx1)-beta*(c-simc)

Normally, this is equivalent.  But if we are messing with simc, will be different.

**Comment by RickKessler** [comment]
Done, and updated here and on Midway. Invoke by adding 128 to opt_biascor. Using this option nuisance parameters (alpha,beta,gamma) are within 0.1% of default settings.
