### ISSUE TITLE
chi2max issue

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#410]
Hello,
I was running BBC on Midway.
I have a file with the two MUOPTs:

```
...
  MUOPT:
  - /MOPT_1/ varname_pIa=PROB_UNITY chi2max=12.25 chi2max(DES)=100
  - /MOPT_2/ varname_pIa=PROB_UNITY chi2max=12.25 chi2max(DES)=16
...

```
I noticed that the results I get from MUOPT1 and MUOPT2 are exactly identical.
For some reason, BBC seems to use chi2max=12.25 everywhere, also for DES.

An example of my BBC input file can be found on midway here:
`$SNANA_DEBUG/mvincenzi/BBC_parsing/test.input`
and the output can be found in `$SNANA_DEBUG/mvincenzi/BBC_parsing/output`
Thanks!

**Comment by RickKessler** [comment]
fixed logic bug; try again. I tested with a range of chi2max and chi2max(DES) cuts, and it looks OK.
