### ISSUE TITLE
spectra are not written out completely

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#412]
Still trying out simulating spectra with host contamination. I wrote the TAKE_SPECTRUM keys all in the simlib so the number of spectra can vary from one SN to the other. While the log says 
```
 Generation Statistics (gen CPU=0.0 minutes): 
         Generated   600 simulated light curves (300/sec) 
         Wrote       214 simulated light curves to SNDATA files (107/sec). 
         Wrote       275 simulated spectra to SNDATA files 
```
There were only 3 spectra in total written out into files  (I checked with `grep NSPECTRA *.DAT`)
I also checked with FITS format and still there were only 3 spectra.

command I ran:
```
cd $WFIRST_USERS/mdai/host_spec/host_spec
snlc_sim.exe sim_found.input
```

**Comment by RickKessler** [comment]
main bug here was related to defining spectra using TEXPOSE option instead of SNR. Also fixed a few other subtle bugs.
