### ISSUE TITLE
submit_batch_jobs.sh without INPDIR's error

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#413]
Working with Dan Scolnic on running `submit_batch_jobs.sh` on a SALT2mu.input file but instead of using many INPDIR’s, we want it to run on a single file (where we have lots of MUOPTs). When we attempt to do this, we get `ERROR: Could not determine program_class.`  

The `.input` file is located in `$SNANA_DEBUG/epeterson3`

and the command is `submit_batch_jobs.sh plus_erik.input --ignore_fitopt`

**Comment by RickKessler** [comment]
submit_batch_jobs.sh doesn't work with stand-alone input data file, but it might be feasible to implement.

**Comment by RickKessler** [comment]
to ignore INPDIR and use the datafile argument,
INPDIR+:  None
I didn't test your job above because of the long time needed to read the biasCor files, but I tested on shorter jobs elsewhere. Try it with your plus_erik.input, and there is no need for the --ignore_fitopt argument since there are no FITOPTs here by definition.

**Comment by erikpeterson23** [comment]
Thank you for implementing this utility!
Attempted with the update of `INPDIR+: None` and without using `--ignore_fitpot`

Job attempt failed with the error message:

```FAIL_SUMMARY:
   NJOB_FAIL(TOTAL):          49  #
   NJOB_FAIL(ABORT):          49  # tail LOG file for more info
   NJOB_FAIL(ZERO_EVENTS):     0  # check cuts, genRanges, etc...
   NJOB_FAIL(UNKNOWN):         0  # segFault? diskQuota? wallTime?


FAILURE-0001:
  JOB_LOG_FILE:       datafile_arg_FITOPT000_MUOPT000.LOG
  FAIL_REPEAT_SCRIPT: FAIL_REPEAT_datafile_arg_FITOPT000_MUOPT000.CMD
  FAIL_MODE:          ABORT
  ABORT_MESSAGES:
  - FATAL ERROR ABORT called by SNTABLE_NEVT_TEXT
  - TOPT000.FITRES.gz'
  - '/scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/6_BIASCOR/REALDATA5D/output/OUTPUT_BBCFIT/INPUT_FITOPT000.FITRES.gz'
  ```

Full FAIL_SUMMARY.LOG here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_erik/`

Copied the updated `plus_erik.input` to `$SNANA_DEBUG/epeterson3`

**Comment by RickKessler** [comment]
your argument of file=.  points to a non-existing file.

**Comment by erikpeterson23** [comment]
Reran with existing file, no issues.
