### ISSUE TITLE
SNANA sim rates error 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#417]
Trying to run /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/CREATE_SIM.INPUT as a batch job, but it crashes with the following error: 

FATAL ERROR ABORT : 
   ngentot=0 in SIMnorm_BROSE_ZFINDER_SNIaMODEL0.LOG ;
   LOG created from sim normalization commands :
     cd /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/SIMLOGS_BZFINDER ;  \
     snlc_sim.exe CS_INFILE.INPUT  \
     INIT_ONLY 1   PATH_USER_INPUT /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone   \
     > SIMnorm_BROSE_ZFINDER_SNIaMODEL0.LOG \

Which is true! But when trying to run in interactive mode, on 
Trying to run /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/CS_INFILE.INPUT there is no error and it proceeds normally. Of note is that I am using a very peculiar redshift distribution with DNDZ ZPOLY.

**Comment by RickKessler** [comment]
fixed ZPOLY bug. However, your rate value is order 50, which is a million times greater than the SNIa rate, so NGENTOT_LC exceeds max number of events using physical rate. Either multiply coefficients by ~E-7, or add this in your input file
DNDZ_ALLSCALE: 1.0E-7
(I already added this key in your debug input file)
