### ISSUE TITLE
+HOSTNBR Hostlib causing segfault

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#42]
Maybe its somehow an artifact of how i created the new hostlib with neighbors but it doesnt seem to be working. It works fine on the hostlib that doesnt have the neighbors (see commented out line in RUNTEST)

Segfault replicated here:
```$SNANA_DEBUG/dillon/RUNTEST```

**Comment by RickKessler** [comment]
fixed a few HOSTNBR bugs. Verified that it runs without crashing or giving valgrind errors.

**Comment by RickKessler** [comment]
Fixed.
