### ISSUE TITLE
Disappearing simulations 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#422]
within /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone

running "submit_batch_jobs.sh CREATE_SIM.INPUT"

will launch jobs that are reflected in sacct, but will stop updating shortly before writing lightcurves. No errors appear, it just... disappears.

snlc_sim.exe works and writes, for some reason it's the batch jobs that's borked up

**Comment by bap37** [comment]
Please note that I manually cancelled the jobs some time later - this is reflected in the log files inside SIMLOG_BZFINDER.

**Comment by RickKessler** [comment]
A recent fix to DNDZ ZPOLY had introduced a really bad non-initialization bug that somehow worked interactively but failed in batch mode. Fixed, and checked with valgrind.
