### ISSUE TITLE
genPDF error for simulating with MLCS

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#424]
error text:
```
FATAL ERROR ABORT called by get_random_genPDF
Found 0 PDF options for parName='DELTA'
Requires 1 PDF option; check AsymGauss and GENPDF_FILE.
```

one of the example log files with error is here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MLCS2K2/1_SIM/PLASTICC_SIM_IA/LOGS/TMP_hele_PIP_HELEN_MLCS2K2_PLASTICC_SIM_IA_NONIaMODEL0-0010_48588.LOG`

the SNANA input file can be found here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MLCS2K2/1_SIM/PLASTICC_SIM_IA/PIP_HELEN_MLCS2K2_PLASTICC_SIM_IA.input`

**Comment by RickKessler** [comment]
These jobs that ran to completion ... if this issue is not resolved, please update issue.

**Comment by helenqu** [comment]
this was resolved once I specified peak/range for the model parameters. thanks!
