### ISSUE TITLE
String Indices must be integers 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#426]
In trying to run submit_batch_jobs.sh on  /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/5D-BC.input, I get the following error: 

   `|```````|`    
   <| o\ /o |>   
    | ' ; ' |     
    |  ___  |     ABORT submit on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
FATAL ERROR ABORT : 
   string indices must be integers
   Crashed while preparing batch jobs.
   Check Traceback

Note that the data file it is pointing to was not made by SNANA's LC-fitter, however, it has been mangled into SNANA-readable form that works with SALT2mu.exe

**Comment by RickKessler** [comment]
the mangled output is not compatible because MERGE.LOG and SUBMIT info are missing everything,
