### ISSUE TITLE
simulation finished but no files in $SNDATA_ROOT

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#428]
https://darkenergysurvey.slack.com/archives/G01EMD2FLDT/p1616514558009600

**Comment by RickKessler** [comment]
In your simgen-master input file, there is a CONFIG line
  GENVERSION: PIP_HELEN_SNOOPY_PLASTICC_SIM_IA
so the final "merged" version is under    
       $SCRATCH_SIMDIR/PIP_HELEN_SNOOPY_PLASTICC_SIM_IA
The TMP_hele_PIP_* versions are temporary versions run on each core, but after they are combined the TMP* versions are deleted. The individual Auxiliary files should be stored under
$SCRATCH_SIMDIR/PIP_HELEN_SNOOPY_PLASTICC_SIM_IA/misc.tar.gz
