### ISSUE TITLE
low rate of SNe passing cuts with mlcs model

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#429]
log example: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MLCS2K2/1_SIM/PLASTICC_SIM_IA/LOGS/TMP_hele_PIP_HELEN_MLCS2K2_PLASTICC_SIM_IA_NONIaMODEL0-0001_40839.LOG`

other details: https://darkenergysurvey.slack.com/archives/G01EMD2FLDT/p1616514797011200

**Comment by RickKessler** [comment]
I don't see a problem; please clarify. The sim generates out to z=1.4 so most of the events are generated in a redshift range that is too faint for detection.

**Comment by helenqu** [comment]
the same redshift range was used for SALT2 simulations and generated a seasonal rate of 13k passing cuts compared to MLCS' 95. example salt2 log: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_PLASTICC/1_SIM/PLASTICC_SIM_IA/LOGS/TMP_hele_PIP_HELEN_PLASTICC_PLASTICC_SIM_IA_SNIaMODEL0-0001_44370.LOG`

**Comment by RickKessler** [comment]
This input line,
CUTWIN_PEAKMAG_ALL:     14 999 
causes most events to be rejected; likely a code bug for this cut using MLCS. I may fix this cut later tonight, but you can just remove the cut and continue.
