### ISSUE TITLE
PSNID diagnostics if an event is rejected

### ISSUE THREAD

**Issue by rmorgan10** [RickKessler/SNANA#43]
I have an object being rejected during a PSNID fit, and when that happens I would like to know why. If possible, it would be great to have an option to force the object to not be rejected so that a fitres file entry is written.

**This is a moderately high priority request for DESGW processing of a LIGO / Virgo event**

**Comment by rmorgan10** [comment]
This is no longer high priority. The event was being rejected because it had a spectroscopic redshift which led to -9 value for redshift error in the dat file. Then in the nml file for PSNID I had OPT_ZPRIOR = 2, which requires a host photo-z (and photo-z error). Setting OPT_ZPRIOR = 0 prevented the event from being rejected.

I'll still leave this issue here because it would be nice for PSNID to tell me why an event was rejected, even though this particular case has been resolved.

**Comment by RickKessler** [comment]
Please leave a working example of a rejected event, and using psnid.exe instead of split_and_fit.

**Comment by masaosako** [comment]
PSNID now prints out a warning message when skipping a candidate due to OPT_ZPRIOR.
