### ISSUE TITLE
MERGE after snlc_sim not executing on Cori/NERSC

### ISSUE THREAD

**Issue by gnarayan** [RickKessler/SNANA#434]
snlc_sim jobs on Cori (single model/or multiple jobs) running with either 2 or 20 nodes end without the output being merge.
The MERGE.LOG indicates that the output should have been combined, but TMP_<user> directories remain in $SNANA_LSST_SIM. 

Additionally, if any job in the queue remains past the 24h Wall time, merge will not ever execute. 

```
# STATE  IVER     GENVERSION     NLC_GEN NLC_WRITE NSPEC_WRITE  CPU  NSPLIT
SPLIT:
  - ['RUN ', 0, 'TMP_gnar_IDEAL_zALL_MODEL42_V19.CC+HostXT_NONIaMODEL0', 0, 0, 0, 0.0, 20]

# STATE     IVER  GENVERSION     NLC_GEN NLC_WRITE NSPEC_WRITE CPU
MERGE:
  - ['RUN ', 0, 'IDEAL_zALL_MODEL42_V19.CC+HostXT', 0, 0, 0, 0.0]


```

An example set of input files:
[snlc_sim_input_files.zip](https://github.com/RickKessler/SNANA/files/6208322/snlc_sim_input_files.zip)

**Comment by RickKessler** [comment]
fixed nasty bug related to dot in GENVERSION name.
