### ISSUE TITLE
MXITER_GENPDF Increase Request

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#435]
Brodie tells me that its a simple request to increase the MXITER which apparently you did for him in the past, but maybe got reset in the last update?? Thanks!

```   
`|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    
 FATAL ERROR ABORT called by get_random_genPDF
   N_ITER=1000 exceeds bound (prob_ref=0.097638)
   Check EBV_PDF or increase MXITER_GENPDF
   ```

**Comment by RickKessler** [comment]
Please provide command to reproduce abort ... I'd like to check for bug before increasing N_ITER

**Comment by RickKessler** [comment]
rather than increase MXITER, added LOGEBV option for GENPDF map to select random EBV more efficiently.
