### ISSUE TITLE
SALT2 outputs changing between February and March 2021

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#437]
Pippin sent jobs for DES-5year data (see `$PIPPIN_OUTPUT/AM_DATA5YR`) only LCFIT job was redone (not the DATAPREP one). Configuration file for SNANA in `$PIPPIN_OUTPUT/AM_DATA5YR/2_LCFIT/D_DATA5YR_DENSE_SNR/FIT_DESALL_forcePhoto_real_snana_fits.nml `

March:  TIME_STAMP_SUBMIT = 2021-03-25 
February: TIME_STAMP_SUBMIT =  2021-02-09

Example converging SALT2 fits in March which are not in February version, SNIDs: 1291766, 1327665, 1280128, 1281601, 1339371, 1657025, 1770191

Example converging SALT2 fits in February which are not in March version, SNIDs: 1258366, 1273075, 1294659, 1295627, 1297926, 1370344, 1892199

Example of events where SALT2 parameters (c,x1) have changed: 1249142, 1252364, 1257070, 1257129, 1257673, 1282626, 1286134

Data files nor configuration files have changed, so I am guessing there was an SNANA update sometime in between? Please clarify what has changed.

**Comment by RickKessler** [comment]
For the seven lost events, here is a trace vs. SNANA code version:

 code     NEVT
 version  CUTS    Notes from $SNANA_DIR/doc/README_UPDATES
# --------------------------------------------------------------
 v11_02f   7
 v11_02g   7
 v11_02h   2      Fixed subtle bug for CUTWIN_PSF and CUTWIN_ZPNPE (see attachment)
 v11_02i   2
 v11_02j   1       Release I/O refactor Tuesday Mar 2 2021, 6pm central.
 v11_02k   0       ??
# --------------------------------------------------------------
I'm still tracking down why the last two events are removed.

<img width="934" alt="CUT-BUG_FIX" src="https://user-images.githubusercontent.com/24592476/112860776-bbbb7800-9079-11eb-8184-fa976b72efcf.png">

**Comment by RickKessler** [comment]
I processed the 2 events from v11_02i that are lost in 02k, and here are the pre-fit PEAKMJD estimates using the Fmax-clump method:

OUT_RICK_02i.LOG:       SET_PEAKMJD(1258366) --> 56615.055   (FmaxClump)             
OUT_RICK_02i.LOG:       SET_PEAKMJD(1294659) --> 56949.125   (FmaxClump)             

OUT_RICK_02k.LOG:       SET_PEAKMJD(1258366) --> 57687.094   (FmaxClump)             
OUT_RICK_02k.LOG:       SET_PEAKMJD(1294659) --> 56987.109   (FmaxClump)     

Note that PEAKMJD estimate changes by 1000 days for SNID= 1258366, and 40 days for SNID= 1294659. I visually inspected the light curves and these both look like junk events, or multi-season events. Not sure what caused the PEAKMJD difference, but I have more confidence in the current/refactored code. Let me know if you find good SNIa (e.g., spec confirmed) that are missing.
