### ISSUE TITLE
SALT2 fits excess c>0 in z>1

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#442]
I am finding many lccd with c>0 at z>1. Taking some of these los and fitting them quickly with sncosmo, I get negative colours (they are different salt models but they should be close enough!). I am wondering if there is a writing issue?

Some examples SNID: 1303551, 1901375, 1263125, 1246444, 1303722.

**Comment by RickKessler** [comment]
I don't see any problem with SNANA LC fits. Try running
./PLOTLC_RICK
which shows the c values are slightly above zero and cERR ~ 0.1. The LC fits look fine visually as well; see DESALL_forcePhoto_real_snana_fits.pdf . Only 1 of the 5 is not well constrained near peak.

**Comment by anaismoller** [comment]
Agree, the light-curves look well-fitted. I am amazed so many c>0 at high-z
