### ISSUE TITLE
Spectra are not generated when using BYOSED

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#444]
I noticed spectra are missing from newly generated BYOSED sims. For example:  `$WFIRST_USERS/mdai/SALT3_training_tests/all_tests/byosed_1dbiascor/SIMLOGS_SIM_MDTEST_SALT3TRAIN_997`
The MERGE.LOG file shows there is 0 spectrum generated. 
Another sim generated from yesterday using exactly the same input did have spectra. So it's possibly a bug from any recent update?

**Comment by RickKessler** [comment]
what is $SALT3TESTS_DATADIR ?

**Comment by RickKessler** [comment]
fixed. See longer story in snana_tests slack channel.
