### ISSUE TITLE
SDSS DEC's all coming out -9

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#446]
Hey Rick - 
Something changed without data being changed.
To reproduce
cd /project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
snlc_fit.exe SDSS.nml
sntable_dump.pl sdss_1.root FITRES -v DEC

**Comment by RickKessler** [comment]
when I released the I/O refactor a few weeks ago, I forgot to check for the legacy DECL key (DEC is default key name). Fixed. Also take note of RICK_REFORMAT, which shows how to extract TEXT data files from FITS ... helps sometimes for debugging.
