### ISSUE TITLE
Unknown table merge problem

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#447]
Running into a merge error when trying to run fits, found at `/scratch/midway2/rkessler/PIPPIN_OUTPUT/RC-G10-DESLOWZX5/2_LCFIT/DATALOWZFIT_DATA_LOWZ2/output/SPLIT_JOBS_LCFIT% vim /scratch/midway2/rkessler/PIPPIN_OUTPUT/RC-G10-DESLOWZX5/2_LCFIT/DATALOWZFIT_DATA_LOWZ2/output/SPLIT_JOBS_LCFIT/CPU0020_JOBLIST_midway2-login2.LOG`

Brodie is encountering a similar error message that may be related: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/SDSS-DATA-CLASS/2_LCFIT/SDSSFIT_DATASDSS/output/SPLIT_JOBS_LCFIT/CPU0033_JOBLIST_midway2-login1.LOG`

**Comment by RickKessler** [comment]
the problem is this line in the input NML file,
  APPEND_TABLE_VARLIST: FITRES RA DEC zHEL zHELERR TGAPMAX HOST_ZPHOT HOST_ZPHOTERR
  should NOT have FITRES (no need to specify table name)
I will fix submit_match to give a more sensible error message.
