### ISSUE TITLE
DAT to FITS conversion missing redshifts 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#448]
Converted, nan-less directory here:
/project2/rkessler/SURVEYS/PS1MD/ROOT/lcmerge/PS1_PS1MD_cen_SIGCLIP_BP/

We seem to be losing the redshifts when converting these dats to FITS files. Example discussed is here
-/project2/rkessler/SURVEYS/PS1MD/ROOT/lcmerge/PS1_PS1MD_cen_SIGCLIP_BP/PS1_PS1MD_PSc000006.snana.dat, which has an actual redshift in the dat file but none in the FITS file.

**Comment by RickKessler** [comment]
there are tabs in the data files, which cause lots of parsing problems. Please remove tabs.
