### ISSUE TITLE
MUERR_RAW includes VPEC uncertainties

### ISSUE THREAD

**Issue by darcykenworthy** [RickKessler/SNANA#450]
For peculiar velocity studies, it'd be useful for this quantity to be simply the supernova distance uncertainty, rather than an uncertainty in the residual relative to the cosmology. It'd be convenient either to redefine this quantity or define a new column that includes only the distance uncertainties (preferably without intrinsic scatter either).

**Comment by RickKessler** [comment]
Done. I tested that BBC isn't broken from this change, but I did not check the new variables ... keep me posted.
