### ISSUE TITLE
Linear RV maps glitch 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#453]
We're having an issue now that when using linear EBV/RV maps, the RV map seems to be fairly busted. This problem doesn't present when using a log(EBV) map, however. I've set up the files here - 

/project2/rkessler/PRODUCTS/SNANA_DEBUG/genPDF_AV/

Check out CREATE_LOG_SIM.CMD and CREATE_LINEAR_SIM.CMD

**Comment by RickKessler** [comment]
closing for now, but re-open later if problems occur.
