### ISSUE TITLE
MUERR_RAW == -nan after submit_batch_jobs.sh 

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#454]
Working with Dan Scolnic on running `submit_batch_jobs.sh` on a SALT2mu.input file but there are two SNe that receive -nan for their MUERR_RAW values: 2011fs and 2013fw in many (if not all) output files.

- SN: 2011fs 49 56 1 VOID 3 0.02110 0.00001 0.01822 0.00001 0.02002 0.00085 0.000 250 0.10090 10.87700 1.30000e-02 -1.03344e+01 -99 55829.6016 21.28897 18.09559 -99 55833.5391 0.4764 0.22524 0.79342 -9.10506e-02 6.11085e-02 15.00336 8.36516e-02 1.78919e-02 1.37850e-03 1.42268e-02 -3.70928e-04 -5.49944e-05 6 1.58010 0.95400 334.331299 35.580601 -999 -999 -9 7.65740 -3.86700e+00 9.68300 -9191 0.54261 -9191 -1.03344e+01 -9191 0 34.6202 34.6982 0.1482 0.1516  `-nan` 0.0913 -0.0825 -0.557 0.0045 0.0112 0.28 0.0031 0.003 0.0135 0.039 0.0056 0.983 0 1

- SN: 2013fw 48 51 1 VOID 3 0.01695 0.00003 0.01570 0.00003 0.01586 0.00085 0.000 250 6.67434e-02 9.76360 -9 -1.11295e+01 -99 56604.1016 135.71698 108.57365 98.70334 56601.9258 0.0577 0.55261 5.06181e-02 -1.89223e-02 2.11503e-02 14.79957 4.84209e-02 2.15860e-02 9.62677e-04 -7.83064e-05 1.76134e-06 -1.55526e-05 86 128.35500 2.10094e-03 318.436707 13.576000 -999 -999 -9 3.93820 -1.15453e+01 39.55470 -9191 -1.36592e+00 -9191 -1.11295e+01 -9191 0 34.2483 34.1867  0.1616  0.1653    `-nan`  0.1151  0.0571  0.353  0.0045  0.0112 0.10 0.0020  0.002 0.0106  0.001 0.0030  0.986 0  1

The .input file is located in $SNANA_DEBUG/epeterson3 along with a number of output files that have the issue.

and the command is submit_batch_jobs.sh plus_erik.input

**Comment by RickKessler** [comment]
it's quite fortunate that we changed the definition of MUERR_RAW because that led to identifying another serious problem. Since MUERR_RAW no longer includes MUERR_VPEC, COV(RAW) should be >0 ... but it is negative for duplicate events!  We didn't catch this before because adding SQMUERR_VPEC was preventing sqrt(negative number). First, I fixed the code to properly trap negative COV and abort with proper error message. Next, I commented out the duplicates (grep '#SN:' INPUT_FITOPT000.FITRES) and checked that SALT2mu runs fine. In addition to COV<0 for duplicates, VPEC = 0, although VPECERR is preserved. I strongly recommend combining duplicates at the light level before LC fits ... hacking the fix in BBC is not reliable and I have never trusted it.

**Comment by erikpeterson23** [comment]
Tried to run the same submit_batch_jobs.sh yesterday. In the logs I found these:

```# ================================================
  PRE-ABORT DUMP from function fcn_muerrsq :
   COV(SALT2) =
     0.001414     -0.000087      0.000540
    -0.000087      0.002552      0.002592
     0.000540      0.002592      0.000383
   COV(MU) =
     0.001414     -0.000014     -0.001610
    -0.000014      0.000064     -0.001223
    -0.001610     -0.001223      0.003406
   muerr_z  = 0.111270 (zerr=0.000834)
   muerrsq(noVpec) = -8.087225e-04
   dmuLens  = 0.000902
   alpha = 0.158260  beta=2.980862

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by fcn_muerrsq
   muerrsq = 1.157233e-02 is less than muerrsq_z = 1.238106e-02
   for SN = 2013fw
```

I have placed a few of these logs in `$SNANA_DEBUG/epeterson3`

2013fw and 2011fs are causing the problem.

The full output of my batch jobs is here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_erik/`

Please let me know if I can provide more information.

**Comment by RickKessler** [comment]
The above abort is correct. You need to fix the inputs so that COV > 0. The merge process for duplicates results in negative COV, and I don't know why. Either remove/fix duplicates in the input file,  or fix the merge_duplicate function in the SALT2mu code.
