### ISSUE TITLE
Extra scatter from MW extinction

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#457]
When using `/project2/rkessler/SURVEYS/WFIRST/USERS/brose3/SNEMO/PeakMag_test_SNEMO.input` and SNEMO's scatter turned off, `OPT_MWEBV:  0` produces a CSP B-band scatter (SNANA filter u)  of 0.013 mag. With `OPT_MWEBV:  3` the scatter becomes 0.2299 mag.

I am uisng:
```shell
$ echo $SNANA_DIR
/project2/rkessler/SURVEYS/WFIRST/ROOT/SNEMO_dev/SNANA

$ which python
/project2/rkessler/PRODUCTS/miniconda/envs/snemo/bin/python
```

**Comment by RickKessler** [comment]
I think this MWEBV scatter is expected because of the wide MWEBV range in the low-z sample.
