### ISSUE TITLE
Crazy Flux values 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#458]
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SNEMO-FLAT/1_SIM/DES_DATA_SALT/LOGS/FAIL_SUMMARY.LOG

Trying to set up some flat simulations, and I'm getting the "Crazy flux" errors. I recall we talked about this before - normally it wouldn't be an issue but I do need the upper/lower ranges of x1 and c for this.

**Comment by RickKessler** [comment]
SHAPEPAR TM*LOG | grep xxx
shows that constraining -0.3 < c < +0.4 should fix the problem.
