### ISSUE TITLE
NSPLITRAN bug in SALT2mu

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#46]
SPLITRAN Summary fails (reported by M.Smith)

**Comment by RickKessler** [comment]
Fixed and updated on Midway, but cannot test due to permission issues.

**Comment by djbrout** [comment]
I too am having NSPLITRAN issues

There is definitely a file=None in my input...
see below:

 NSPLITRAN       = 10

 10 batch-cores





   `|```````|`

   <| o\ /o |>

    | ' ; ' |

    |  ___  |     ABORT program on Fatal Error.

    | |' '| |

    | `---' |

    \_______/


 FATAL ERROR ABORT :

Unable to find argument of

file=None

**Comment by RickKessler** [comment]
Fixed.
