### ISSUE TITLE
increase character limits for GENPREFIX

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#460]
Can we increase the string length limit for GENPREFIX? The pipeline sometimes generate longer names and suffix like `_SNIaMODEL0-0020` is also auto-generated and uses the character quota.
```
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by prep_simpath 
  - GENPREFIX string len = 52 exceeds array bound of 52 
  - See input GENPREFIX: SIM_SALT3TRAIN_5DBIASCOR_biascor_999_SNIaMODEL0-0020
```

**Comment by RickKessler** [comment]
Sorry I can’t change prefix limit because of FITS limitation. Ask Pippin masters to use shorter names. Note that GENPREFIX can simply be survey name; making a complicated name serves no purpose
