### ISSUE TITLE
Batch Jobs eating inputs 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#461]
submit_batch_jobs.sh for a SALT2mu job seems to be eating my inputs -
/project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/5D-BC/
This directory gets autogenerated from /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/5D-BC.input but it's missing a lot of information?

The input file was not made from a SNANA fit, so I had to do my best to mimic the required MERGE.LOG/SUBMIT.INFO files. That's probably where the issue lies

**Comment by RickKessler** [comment]
Please provide clear instructions for how to reproduce  the problem ... and if somethings gets deleted, how to restore it.

**Comment by bap37** [comment]
```
cd /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/

submit_batch_jobs.sh 5D-BC.input 

```

This shouldn't delete anything. The only thing it might be writing over is the /project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/5D-BC/ directory, but that is generated by the above command anyways.

**Comment by RickKessler** [comment]
/project2/rkessler/SURVEYS/WFIRST/USERS/brose3/boone/KYLE_DATA is not valid; MERGE.LOG has one version called PIP_BP-HALO-CMB_LOWZ_DATA, but no such directory exists ??

**Comment by RickKessler** [comment]
I added a more sensible ABORT message about missing version directory.
