### ISSUE TITLE
Issues when using the prism

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#463]
Having issues running a prism simulation in here
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021
using the following command 
snlc_sim.exe SIMGEN_WFIRST_SNIA_SHAL.INPUT FORMAT_MASK 2

and get 
===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fa7f05a645c in waitpid () from /lib64/libc.so.6
#1  0x00007fa7f0523f52 in do_system () from /lib64/libc.so.6
#2  0x00007fa7f4b29e59 in TUnixSystem::StackTrace() () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#3  0x00007fa7f4b2ba5c in TUnixSystem::DispatchSignals(ESignals) () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#4  <signal handler called>
#5  0x000000000041f79b in SIMLIB_prepCadence ()
#6  0x0000000000421006 in SIMLIB_READ_DRIVER ()
#7  0x000000000042348f in gen_event_driver ()
#8  0x000000000043f329 in main ()
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x000000000041f79b in SIMLIB_prepCadence ()
#6  0x0000000000421006 in SIMLIB_READ_DRIVER ()
#7  0x000000000042348f in gen_event_driver ()
#8  0x000000000043f329 in main ()
===========================================================

**Comment by RickKessler** [comment]
with about 200 epochs and 40 synthetic filters, the number of observations exceeded an unchecked array bound. The max number of observations has been extended to 10,000 (was 5000), and there is an appropriate abort trap.
