### ISSUE TITLE
SALT3 doesn't need a lc_dispersion_scaling file

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#464]
Hi Rick - discussed this on slack, please remove the requirement to have a lc_dispersion_scaling file for SALT3 models.  Thanks!

**Comment by RickKessler** [comment]
Fixed. Please run more tests using
GENMODEL:  SALT3.K21              # sim input
FITMODEL_NAME = 'SALT3.K21'    # &FITINP for LC fit
