### ISSUE TITLE
Too many filters 

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#465]
In /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021
trying to do 
snlc_sim.exe SIMGEN_WFIRST_NONIA_SHAL.INPUT
get error 
 FATAL ERROR ABORT called by PREP_SIMGEN_DUMP
   NVAR_SIMGEN_DUMP=417 exceeds array bound of 400.

**Comment by RickKessler** [comment]
increased MXVAR_SIMGEN_DUMP to 600 (was 400); try again.
