### ISSUE TITLE
Definition of SIM_PEAKMJD for BULLA-19 models

### ISSUE THREAD

**Issue by deepchatterjeeligo** [RickKessler/SNANA#468]
The `SIM_PEAKMJD` for the Bulla kilonova models are likely the explosion times

INPUT file to reproduce: `/global/cfs/cdirs/snana/SURVEYS/LSST/USERS/deep/bulla-seds/SIMGEN_TEMPLATE_LSST_BULLA.INPUT`

This simulates a single KN with an ideal 0.1 day simlib. I find that
SIM_PEAKMJD = 53102.88
MJD corresponding to 6144 is 53103.2
MJD corresponding to first 4096 is 53103.1

the latter two being after SIM_PEAKMJD.

**Comment by RickKessler** [comment]
expected behavior; see OPTLFAG in SED.INFO file.
