### ISSUE TITLE
Tracking true hosts

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#47]
Hi Rick!

I noticed that on your guide for the host mis-association in SNANA, keeping track of the true host is marked as to-do! I'm back after my prelim and looking to get back on the work train, so I was wondering if we could add that feature so we can start calculating mis-associations!

Thanks,
Brodie

**Comment by RickKessler** [comment]
Ah, good catch. I will look into it.

**Comment by RickKessler** [comment]
added SIM_HOISTLIB_GALID to output data files and tables, and fixed some bugs reading HOSTLIB with NBR. See updated manual section 4.20.4
