### ISSUE TITLE
Integrating calibration across SNANA and SALTshaker

### ISSUE THREAD

**Issue by darcykenworthy** [RickKessler/SNANA#471]
Current master branch of SALTshaker, there's an example of how to modify the zeropoints/central wavelengths for the training. Run the training script from examples/SALT3_training_v1.0/Train_SALT3_calibshift.conf. the file with the shifts listed is calibrationtest.txt

**Comment by RickKessler** [comment]
Can you set this up on Midway under $SNANA_DEBUB/SALTshaker ? Don't need to re-install the code; just need the input files and full command(s) to run.

**Comment by RickKessler** [comment]
done.
