### ISSUE TITLE
SALT3.INFO not found 

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#472]
Hi Rick,

I got the following error when I tried to run ALT02 with the new SALT3 models and extended wavelength range:

Excerpt:    Cannot open infoFile 
Excerpt:/project2/rkessler/PRODUCTS/SNDATA_ROOT/models/SALT2/SALT3.K21/SALT3.INFO

this is happening in stage 1 when it for one reason or another didn’t have trouble with this last night.
the full error message is in 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+ALT02/1_SIM/FOUND_BIASCOR_G10/LOGS/TMP_pmac_PIP_WFIRST_STARTERKIT+ALT02_FOUND_BIASCOR_G10_NONIaMODEL0-0016_40084.LOG

I'm guessing changing SALT2->SALT3 would fix it and it seems to be looking in the correct folder for other files.

Thanks!

-Phil

**Comment by pmacias** [comment]
I forgot to mention this is when running

pippin.sh WFIRST_starterKit+ALT02.yml &

from 

/project2/rkessler/SURVEYS/WFIRST/ROOT/analysis_inputs/pippin

**Comment by RickKessler** [comment]
fix bug reading SALT3 from sim.
