### ISSUE TITLE
make_marz.nml fail

### ISSUE THREAD

**Issue by srodney** [RickKessler/SNANA#473]
ran snana.exe make_marz.nml

failed with: 
 FATAL ERROR ABORT called by SPECPAK_FILL_MARZ
   Stored NBIN_WAVE=201 for first event ...
   but NBIN(CID=10015[z=0.414]) = 178. Cannot change binning.

full output here:
/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/HOST/make_marz_error_20210503.txt

**Comment by RickKessler** [comment]
used wrong GENVERSION.
