### ISSUE TITLE
Add host galaxy id to MARZ output file

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#475]
Request to add `SIM_HOSTLIB_GALID` to the MARZ output file, so that we can match up spectra with the eazy template file after sims.

**Comment by RickKessler** [comment]
Done.
<img width="350" alt="marz_name+GALID" src="https://user-images.githubusercontent.com/24592476/116939926-c0ec8380-ac32-11eb-9b4f-aab4464eedcd.png">
