### ISSUE TITLE
Host galaxy prism spectra

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#476]
cd /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/HOST
snlc_sim.exe SIMGEN_WFIRST_HOSTSNIA_DEEP.INPUT

  PRE-ABORT DUMP from function GEN_SNHOST_GALID : 
	 CID=10001  ZGEN(SN,GAL) = 1.2546, 1.2780 
	 igal(start,end) =     62,     62   --> IGAL=62 
	 zgal(start,end) = 1.2780, 1.2430 
	 MINiz=101  MAXiz=350 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by GEN_SNHOST_GALID
   ZDIF=-0.023392 exceeds dztol=0.010000
   CID=10001

If I change HOSTLIB_DZTOL: 0.01 0.0 0 to HOSTLIB_DZTOL: 0.05 0.0 0. then I get an issue with the number of hosts
 DUMP_SNHOST for CID = 10003 
    SN-GENERATED z=1.6177, RA=20.000000, DEC=0.000000 deg (FIELD=DEEP).
	 => IGAL-range=74-76  IGAL=-9  ran(GALID)=0.857 
	 => GALID=        -9  ZTRUE=-9.0000  ZGEN-ZTRUE= 10.617663 
	 => a_sep=-9999.0000  b_sep=-9999.0000  phi=0.0000  R_red=-9999.0000 
	 => WGT = 0.000000   SNMAGSHIFT=0.000000 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by GEN_SNHOST_GALID
   Could not find HOSTLIB entry for ZGEN=1.6177 .
   Each HOST used only once -> need larger library.

I am using a refined library of hosts with only 100 entries - I have been asked to simulate a spectra for each one. Perhaps I should modify my input file overall?

Thanks

**Comment by RickKessler** [comment]
DZTOL=0.01, but the HOSTLIB has many gaps that are much larger. Need to set DZTOL to larger value, or make a denser HOSTLIB.
