### ISSUE TITLE
segfault when using WGTMAP and zHOST SEARCHEFF.

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#478]
Hi Rick,

I am running into a segfault when running snlc_sim from the analysis_inputs sim directory:

cd /project2/rkessler/SURVEYS/WFIRST/ROOT/analysis_inputs/sim

snlc_sim.exe SIMGEN_WFIRST_Allz_SNIA.input

everything works on its own (i.e. the search efficiency file runs, the WGTMAP runs) but combining yields the segfault. As far as I can see the formatting is matched up with what is expected from the manual.  

Thanks!
- Phil

**Comment by RickKessler** [comment]
cd $NGRST_ROOT/analysis_inputs/sim/searches
diff euclid_shallow euclid_shallow+fix | more

and note that your table has two non-uniform bins which causes the segFault. I am adding a more stringent test on bin uniformity.
