### ISSUE TITLE
HOSTMAG_r option missing from ROOT file

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#479]
HOSTMAG_r (and other bands) appear to be missing from ROOT files when generating simulations for at least SDSS. This can be seen here:

`cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/SDSS-TEST-2/2_LCFIT/SDFITsimnosys_SIMSDSS_SMALL_G10/output/PIP_SDSS-TEST-2_SIMSDSS_SMALL_G10
sntable_dump.pl FITOPT000.ROOT FITRES`

Where this directory is set up to just generate an SDSS simulation with perfect efficiency.

**Comment by RickKessler** [comment]
fixed. During I/O refactor a few months ago, I accidentally lost the code that read HOSTMAG from data files.
