### ISSUE TITLE
Allow zero sigma int

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#48]
Would like to request the ability to have SNANA Salt2mu not fail when rms is below average mu error (causing effectively a negative sigma int) could it just gracefully set sigma int to zero in these cases?
![DD70A360-B27C-411A-AF3E-1706C707316B](https://user-images.githubusercontent.com/5403753/75499279-406e3980-5a15-11ea-89df-e1aefdb0ae71.png)

Thanks in advance!

**Comment by RickKessler** [comment]
please using option to fix biasCor sigma-int to zero:  sigint_biascor=0, and/or option to fix the same biasCor, sigint_fix=0.0
