### ISSUE TITLE
Host galaxy prior not applied for SN photoz fit

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#483]
I am trying to run photoz fits on data, one fitopt with host galaxy prior, and one fitopt without. It looks like the one where the host galaxy prior is supposed to be applied is identical to the one without, and in the logs it looks like PRIOR_ZERRSCALE is autoset to 1000 despite not being input as an option. 

Error reproduced with snlc_fit.exe $SNANA_DEBUG/rebeccachen/PHOTOZ_FITOPT.NML

And the log is saved at LOG.txt, which shows PRIOR_ZERRSCALE=  1000.00000

**Comment by RickKessler** [comment]
PRIOR_ZERRSCALE=1000 multiplies host-galaxy error by 1000, so this is equivalent to flat prior. To use informative prior, set PRIOR_ZERRSCALE=1

**Comment by rebeccachen0** [comment]
Oh, I see, didn't realize the default! Thanks!

**Comment by rebeccachen0** [comment]
Did this change recently? I have the same settings on a simulation run and it did not have the same problem.
