### ISSUE TITLE
Prism survey scaling keyword

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#489]
It would be useful to have a keyword within a simulation to scale the size of the region that will have prism spectroscopy.
For instance in the roman survey you may have a shallow imaging survey with a small region of that being observed by the prism. Having matching light curves and spectra is important here for testing spec-z's vs photo-z's, and typing.

Thanks

**Comment by RickKessler** [comment]
See TAKE_SPECTRUM_PRESCALE key in manual section
4.26.3 Field-Dependent PreScale for SN Spectra
