### ISSUE TITLE
Back-compatibility since last changes

### ISSUE THREAD

**Issue by Nora-n** [RickKessler/SNANA#491]
Since last changes in SNANA, running only a part of a simulation while keeping the others of a same job gives an error:

```
        Excerpt:    FATAL ERROR ABORT :
        Excerpt:       'OPT_SNCID_LIST'
        Excerpt:       Crashed while preparing batch jobs.
        Excerpt:       Check Traceback
```

There should be a back-compatibility check for jobs that were ran before said changes.

Thanks,
Nora

**Comment by RickKessler** [comment]
fixed; try again.

**Comment by Nora-n** [comment]
Thanks, it's running as intended now!
