### ISSUE TITLE
BIASCOR Fatal error on muErrsq points to LCFIT with negative SNRMAX1

### ISSUE THREAD

**Issue by Nora-n** [RickKessler/SNANA#493]
Hi Rick,

Our job crashed here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/NN_G10_PANTH-MSK66-BP_V3/6_BIASCOR/PS1_BIASCOR/output/SCRIPTS_BBCFIT/OUTPUT_BBCFIT_FITOPT000_MUOPT000.LOG`, with error
```
        Excerpt:     FATAL ERROR ABORT called by makeMap_sigmu_biasCor
        Excerpt:       Invalid muErrsq=665.099357 for ievt=235020
        Excerpt:       Something is messed up.
```

Some debugging points to this being an issue at the LCFIT stage, seeing `/scratch/midway2/rkessler/PIPPIN_OUTPUT/NN_G10_PANTH-MSK66-BP_V3/2_LCFIT/PS1FIT_PS1_SIM/output/PIP_NN_G10_PANTH-MSK66-BP_V3_PS1_SIM/FITOPT000.FITRES`. In particular, on line 235448 (CID=1457977) the entry has `SNRMAX1=-1.82549`, and so the distance is blowing up.

Any idea how that could have happened? The simulation has a strict requirement that only things with 2 epochs of S/N>5 are selected, i.e.: `CUTWIN_SNRMAX:   5 griz 2 -20. 80.` in `/scratch/midway2/rkessler/PIPPIN_OUTPUT/NN_G10_PANTH-MSK66-BP_V3/1_SIM/PS1_SIM/ps1_g10_infile.input`. It seems that an object got through LCFIT with no detections, despite only detected objects being allowed to make it through the SIM stage. Our guess would be that outlier rejection is the cause, but we have no idea how to deal with that.

Thanks,
Nora

**Comment by RickKessler** [comment]
I don't see any problems ? Please check directory with error.

**Comment by Nora-n** [comment]
Sorry I had launched another simulation on top that erased this issue. I recreated it at exactly the same place with the same ranseed so the error is exactly the same.

**Comment by RickKessler** [comment]
fixed subtle bug; the crazy-COV check was accidentally made w.r.t. x0 instead of mB. So now the crazy event is discarded.
