### ISSUE TITLE
abort when combining SEARCHEFF files 

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#494]
Hi Rick,

When running

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/sim

snlc_sim.exe SIMGEN_WFIRST_Allz_SNIA.input

I am getting an error, I think because of conflicting HOSTEFF coming from the 2 maps that are stitched together in 

/project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/sim/searcheff/roman_deep+fix+lowz 

I know that this should take a logical OR here and tried to follow the formatting from the manual, but am coming up short. 

Thanks in advance for your help!
-Phil

**Comment by RickKessler** [comment]
fixed to take logical OR among maps ... but only tested to run without aborting. Needs better testing.
