### ISSUE TITLE
SALT2mu SUBPROCESS 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#495]
Trying to get SALT2mu SUBPROCESSes up and running with 2D tables. Having an issue now where SALT2mu is not initialising something properly  - 

/project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/debuglog
which was created by doing "python runparallelemcee.py --debug"

**Comment by bap37** [comment]
I worry that the issue may be on my end in the script somewhere. Not certain though.

**Comment by bap37** [comment]
Specifically, in line 522 of debuglog, SALT2mu reads 

`SALT2mu_SUBPROCESS:  TABLE-0  VARNAME = 'x1  NBIN=12  RANGE=-3.000 to 3.000`

This is a problem because it's picking up an extra quotation mark from somewhere that's being added next to the x1. 

I printed the command that SALT2mu is seeing on line 187, which is the following - 
SALT2mu.exe SALT2mu_DESNN_SIM_nolowz.input SUBPROCESS_FILES=parallel/0_PYTHONCROSSTALK_OUT.DAT,parallel/0_SUBROCESS_SIM_OUT.DAT,parallel/0_SUBPROCESS_LOG_SIM.STDOUT SUBPROCESS_VARNAMES_GENPDF=SIM_x1,HOST_LOGMASS,SIM_c,HOST_LOGMASS SUBPROCESS_OUTPUT_TABLE='x1(12,-3:3)%c(12,-0.3:0.3)'

This seems right, but this error doesn't arise when I use the command line SALT2mu SUBPROCESS, as in /project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/RUNTEST_SUBPROCESS_SIM

**Comment by RickKessler** [comment]
try removing the quotes from argument ... they are supposed to be optional.

**Comment by bap37** [comment]
That looks like it worked, new error has occurred. This is probably resolved.
