### ISSUE TITLE
Issue when trying to create host magnitudes from synthetic filters

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#497]
When running 
snlc_sim.exe SIMGEN_WFIRST_Allz_SNIAv2.input +HOSTMAGS
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL

Process runs correctly when only specifying RZJYHFabcdefghij but when running for and additional filter k a segmentation fault occurs.

****************************************************************** 
   rewrite_HOSTLIB_plusMags  
	 NGAL[READ,STORE] = 446, 446 
	 Processing igal        0 of      446 

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fbe9dbc245c in waitpid () from /lib64/libc.so.6
#1  0x00007fbe9db3ff52 in do_system () from /lib64/libc.so.6
#2  0x00007fbea2145e59 in TUnixSystem::StackTrace() () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#3  0x00007fbea2147a5c in TUnixSystem::DispatchSignals(ESignals) () from /software/ROOT-5.34.14-el7-x86_64/lib/libCore.so
#4  <signal handler called>
#5  0x00000000004d0834 in addComment_HOSTLIB_APPEND ()
#6  0x00000000004d0fdb in rewrite_HOSTLIB_plusMags ()
#7  0x000000000040fb70 in rewrite_HOSTLIB_DRIVER ()
#8  0x000000000044016a in main ()
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00000000004d0834 in addComment_HOSTLIB_APPEND ()
#6  0x00000000004d0fdb in rewrite_HOSTLIB_plusMags ()
#7  0x000000000040fb70 in rewrite_HOSTLIB_DRIVER ()
#8  0x000000000044016a in main ()
===========================================================

**Comment by RickKessler** [comment]
memory overwrite bug since I had not anticipated large VARNAME strings. Fixed.
