### ISSUE TITLE
+HOSTMAGS not writing out the full filter list 

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#500]
In directory,

/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL
I am running, 

snlc_sim.exe SIMGEN_WFIRST_Allz_SNIAv2.input +HOSTMAGS

which produces the output AKARI+specbasis_small.HOSTLIB+HOSTMAGS 
However not all filters requested are being output. Please advise. 

Thanks

**Comment by RickKessler** [comment]
I see lots of added filters; please clarify an example filter that is missing.

**Comment by RickKessler** [comment]
allocated more memory for appended string, along with error check

**Comment by RickKessler** [comment]
allocated even more memory; hopefully it's really fixed this time.
