### ISSUE TITLE
Maximum-Line Error on SN Ia WGTMap Runs

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#501]
Running a job to simulate SNe Ia with our PLAsTiCC Hostlib and Weightmap returns the following error: 

FATAL ERROR ABORT called by read_GRIDMAP
  NROW_READ=50000 exceeds MXROW=50000

If I decrease the size of the Weightmap until it's below 50k rows, I get errors that SNANA isn't able to interpolate the grid finely enough for specific galaxies.

**Comment by RickKessler** [comment]
Please indicate directory & command to reproduce error.

**Comment by RickKessler** [comment]
increased MXROW to 500k (was 50k)
