### ISSUE TITLE
SNANA hangs at initialization stage for 1+ hr

### ISSUE THREAD

**Issue by marlena6** [RickKessler/SNANA#504]
I'm running SNANA with the input file `SIMGEN_MASTER_IDEAL_zALL_GHOSTLIB_SNII.INPUT` in `$SNANA_LSST_ROOT/PLASTICC/survey_config`. It starts running but hangs after:

```
########################################################
     INIT_SNVAR: Init variables.
  ########################################################
   Allocate 12.50 MB for CIDMASK array (to check duplicates)
```

I cancelled the jobs after about 1 hr.
Logs can be seen in `SIMLOGS_ML_IDEAL_zALL_TEST_GHOSTLIB_SNII`

**Comment by RickKessler** [comment]
Please try trimming the number of HOSTLIB variables down to 1 or 2 dozen: mags, Sersic, wgtmap variables plus a few others. Since the entire HOSTLIB is read into memory, it was never intended to be a complete library of all HOST parameters.

**Comment by RickKessler** [comment]
This was due to array bound overflow that wasn't caught, and likely corrupted some part of memory. Array overflow is now trapped and abort gives error message.
