### ISSUE TITLE
Unable to add all hostlib params to storepar

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#505]
I'd like to store host galaxy parameters within my SNANA run, but am hitting a length limit.

**Command:**  submit_batch_jobs.sh SIMGEN_MASTER_IDEAL_zALL_GHOSTLIB_SNIa.INPUT

**Directory:** /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC/survey_config

**Error Message:**

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by check_arg_len
   len(HOSTLIB_STOREPAR) = 662 exceeds bound of 300
   Shorten arg, or increase array bound.

**Comment by RickKessler** [comment]
HOSTLIB should only include what is needed for the sim, plus a few other related variables. It is not intended to be storage for large number of host properties.
