### ISSUE TITLE
MXEPSIM_PERFILT limit hit with high-cadence IDEAL sims

### ISSUE THREAD

**Issue by gnarayan** [RickKessler/SNANA#506]
I am running a set of sims with very high cadence (0.1 day sampling) IDEAL sims for @fedhere for her cadence studies. The plan is to interpolate these IDEAL light curves and then resampling them onto any arbitrary LSST cadence for use with the metrics analysis framework.

The simlib for these high cadence IDEAL sims is on cori at 
`$SNANA_LSST_ROOT/simlibs/LSST_IDEAL_0.1DAY_LONG.SIMLIB`

The short version of the same SIMLIB (same MJD start and step, much smaller range - similar filename without _LONG) works fine, but when I launch the sim with the long (~150 day) SIMLIB I see this error: 

```
 FATAL ERROR ABORT called by NEPFILT_GENLC
   NEP=1000 exceeds bound for ifilt_obs=1(u).
   Check MXEPSIM_PERFILT
```   

which I think is related to the number of epochs in each filter. 

While I agree that 150 days at 0.1 day sampling will generate a lot of observations, I'm also keen to accommodate this request since it impacts the LSST Cadence Discussions. Is there some way we can increase the limit? Or if not is there a way to use a different SIMLIB per model? This way fast-evolving transients and variables can use the 0.1-day SIMLIB, while slower evolving sources can use a lower cadence SIMLIB.

**Comment by RickKessler** [comment]
MXEPSIM_PERFILT is now doubled to 2000, but don't know if the code will run or abort somewhere else. Give it a shot. In future GitHub postings, please include command to reproduce error.
