### ISSUE TITLE
Issue when running prism input file with multiple synthetic filters 

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#507]
I am running snlc_sim.exe SIMGEN_WFIRST_Allz_SNIA.input

in

/project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL

and am receiving the error 

    Begin Generating Lightcurves.   
  Found Max dN/dz * wgt = 9.037781e+05 at z =    0.997 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by SIMLIB_TAKE_SPECTRUM
   NOBS=13496 exceeds MXOBS_SIMLIB=10000
   Check number of synthetic bands from SPECTROGRAPH

please advise 

Thank you

**Comment by RickKessler** [comment]
MXOBS_SIMLIB -> 15,000 (was 10k). However, the real could be that the Roman SIMLIB file now includes 3 years instead of 2 years ?
