### ISSUE TITLE
segmentation violation in BBC

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#508]
Hi Rick,

I've been running into a FAIL_MODE: UNKNOWN error in stage 6 BBC for the ALT04 runs. 

We originally suspected a memory issue, so I increased --mem-per-cpu=4GB in a custom batch file located here 

/project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/batch_templates/SBATCH_Midway2b.TEMPLATE

and pointed to in my pippin input, located and run as follows

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/pippin 
pippin.sh -r -s 6 WFIRST_starterKit+ALT04.yml &

The segfault reports are here

cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+ALT04/6_BIASCOR/BBC/output_ITER1/SCRIPTS_BBCFIT
grep seg * 

Thanks!
- Phil

**Comment by RickKessler** [comment]
I recently refactored parse_cidFile_data, and forgot to open with the utility that checks for gzipped file.
