### ISSUE TITLE
Unusual prescale outcomes in SALT2mu SUBPROCESS

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#509]
We're finding some odd outcomes in SALT2mu SUBPROCESS - specifically, this log file 
/project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/parallel/1_SUBPROCESS_LOG_SIM.STDOUT

indicates that only one supernova was used. This seems to be common among the walkers, as a `grep -r '# NSNFIT:' *SIM*` inside the /project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/parallel directory shows we've got a number of walkers that are only drawing a handful of supernovae. 

I've set up a test file here - /project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/RUNTEST_PRESCALE which _should_ reproduce the 1 SNe error.

**Comment by RickKessler** [comment]
works fine for me, getting 6099  events:
more prescale-test/1_SUBPROCESS_LOG_SIM.STDOUT

**Comment by RickKessler** [comment]
fixed nasty SALT2mu-SUBPROCESS bug that applied cumulative REWGT and PRESCALE cuts; now these cuts are reset each iteration.
