### ISSUE TITLE
SNANA compilation on mac

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#51]
A couple compilation errors in `sntools_trigger.c`:

`../src/sntools_trigger.c:2156:22: error: non-void function 'setObs_for_PHOTPROB' should return a value [-Wreturn-type]
  if ( NMAP == 0 ) { return ; }
                     ^
../src/sntools_trigger.c:2176:21: error: non-void function 'setObs_for_PHOTPROB' should return a value [-Wreturn-type]
  if(NMATCH==0 )  { return; }
                    ^
../src/sntools_trigger.c:2186:7: error: non-void function 'setObs_for_PHOTPROB' should return a value [-Wreturn-type]
    { return; }
      ^
3 errors generated.`

**Comment by RickKessler** [comment]
Fixed casting bug in sntools_trigger.c[h]. Pushed to GitHub.
