### ISSUE TITLE
Issue when running input file 

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#510]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL
running SIMGEN_WFIRST_Allz_SNIAv2.input

get error 
****************************************************************** 
   Init SIMGEN_DUMP file   
	 open /project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/RAH_WFIRST_2021_1A/RAH_WFIRST_2021_1A.DUMP

 ****************************************************************** 
    Begin Generating Lightcurves.   
  Found Max dN/dz * wgt = 9.037781e+05 at z =    0.997 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by genSpec_HOSTLIB
   Cannot generate host spectrum without spec basis or data.
   Check HOSTLIB_SPECBASIS[DATA]_FILE key in sim-input.

**Comment by RickKessler** [comment]
I'm pretty sure that this is fixed. Reopen if needed.
