### ISSUE TITLE
BBC 

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#511]
Hello!
I was making a test on Cori. I was trying to run BBC (1D) version.
The input file is here:
/global/homes/m/mvincenz/snana_debug/BBConDATA/BBC1D.input

I'm testing three different MUOPTs
MUOPT000 --> applying P(Ia)>0.5
MUOPT001 --> applying P(Ia)>0.9
MUOPT002 --> applying P(Ia)>-1 (i.e. no cut)

I checked the results and in MUOPT001, it looks like SALT2mu is applying the PIa cut also to the Low-z sample. I set:
`idsurvey_list_probcc0=CFA3K,CFA4p1,CFA4p2,CSP,CFA3S,FOUNDATION
`
so I thought this was assuming all low-z SNe have PIa=1.
Also, in MUOPT002, it looks like SALT2mu is still applying the PIa>0.5 cut.
Thank you!
Maria

**Comment by RickKessler** [comment]
files are read protected; see slack message.

**Comment by maria-vincenzi** [comment]
Sorry, I fixed the data permission and moved everything to the folder:
`/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/mvincenz/snana_debug/BBConDATA/
`

**Comment by RickKessler** [comment]
still permission denied. Need to 
  chgrp -R lsst BBConDATA
  chmod +s BBConDATA

**Comment by maria-vincenzi** [comment]
Sorry again! I should have fixed this now!

**Comment by RickKessler** [comment]
your BBC1D job has no CC prior, and thus probcc0 is ignored since the probabilities are not used. Also remember that BBC1D doesn't work with BEAMS.

**Comment by maria-vincenzi** [comment]
ok thanks! And is there a reason why in MUOPT002, it looks like SALT2mu is still applying the PIa>0.5 cut even if I set:
`- /MUOPT002/ CUTWIN PROB_SNNTRAINV19_z_TRAINDES_V19 -1. 1.1 
`?
