### ISSUE TITLE
MUERR_VPEC scaled by biasScale_muCOV

### ISSUE THREAD

**Issue by darcykenworthy** [RickKessler/SNANA#513]
The peculiar velocity scatter is getting scaled by biasScale_muCOV; preferably this would only apply to the actual SN Ia distance error.

**Comment by RickKessler** [comment]
debug_flag=68 will now enable
  muerrsq   = (muerrsq-muerrsq_vpec) * muCOVscale + muerrsq_vpec ;
and muCOVscale is computed from the biasCor sample without VPECERR. I am not sure if this feature will slowly become default, or if it will always remain an option; hence for now, use debug_flag=68 for testing. I have checked that current SALT2mu code gives same results, and that the new debug_flag=68 has very small effect in the SNANA_tester jobs ... but I have not done any science testing.
