### ISSUE TITLE
Issue when running snlc_sim.exe

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#514]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL
running 
snlc_sim.exe SIMGEN_WFIRST_Allz_SNIAv2.input

 ****************************************************************** 
   Init SIMGEN_DUMP file   
	 open /project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/RAH_WFIRST_2021_1Av2/RAH_WFIRST_2021_1Av2.DUMP

 ****************************************************************** 
    Begin Generating Lightcurves.   
  Found Max dN/dz * wgt = 9.037781e+05 at z =    0.997 
	 Finished generating        1 of 400 (CID= 10001) 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by GENSPEC_HOST_CONTAMINATION
   IMJD=0 is not a host spectrum
   Cannot add host contamination to SN spectrum.

(base) [hounsell@midway2-login1 FULL]$ pwd

**Comment by RickKessler** [comment]
fixed index bug for HOST. sim job still aborts on too many epochs because SIMLIB includes extra (3rd) year that shouldn't be there.
