### ISSUE TITLE
weird snana dataprep bug

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#516]
So in the dataprep task where we run snana.exe clump.nml we're hitting weird errors that we cant seem to trace down.

see here
```
cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS/0_DATAPREP/DATAKAITDS15
snana.exe clump.nml
```
produces this error
```
  *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
   Assign integer CID=    48 for 2001ex
     Done Reading CID 2001ex            NMJD(found,stored)=  24   24
       SET_PEAKMJD(2001ex) --> 52205.500   (FmaxClump)             
       Analyze ISN=      48  for 2001ex          NMJD(stored,cuts)=  24->  24
At line 40034 of file ../src/snana.f
Fortran runtime error: Index '-9' of dimension 1 of array 'isnlc_nepoch_filt' below lower bound of 1
```

if I comment out this SN from the photometry list file, the error just ends up popping up for another SN

**Comment by RickKessler** [comment]
looks like array bound overwrite, and I probably left debug flag turned on by accident, otherwise we would likely miss this error. Waiting for Midway to come back alive.

**Comment by RickKessler** [comment]
added a missing abort trap for undefined filter:
 FATAL ERROR ABORT called by RDOBS_DRIVER
   Invalid IFILT_OBS= 42(L) for CID=2002bf
   Check FILTERS key and MJD=52408.210
