### ISSUE TITLE
Extend CID number limit

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#517]
I was trying to run SALT2 on a specific list of CIDs using the command:
`     SNCID_LIST_FILE = 'my_list_of_CID.txt'
`
But my list has >25.000 CIDs, so I get the error:
```
    Read list of CIDs from 
    my_list_of_CID.txt
  
  ######################################################## 
    RDFILE_SNCID_NOFMT  
  ######################################################## 
  

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by CHKARRBOUND
   NCCID_LIST-index **** outside valid range  1-25000   (FUN=RDFILE_SNCID_NOFMT  )
   Check above CID-list file
```
I was wondering if this hard-coded limit of 25000 can be increased to something higher (my file has 50000 CIDs, but maybe fixing it to something like 10^6 would just avoid the problem for the future).
Thanks!

**Comment by RickKessler** [comment]
extended max list size from 25k to 75k ... but at some point the brute-force CID-matching will slow things down a lot ... might need to use a hash table at some point.
