### ISSUE TITLE
split_and_fit returns different values from snlc_fit.exe

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#52]
Hi Rick, I've set up an example in `SNANA_DEBUG/djones/github_lcfitting`.  If you try both:

`split_and_fit.pl foundation_sys.nml`

and 

`snlc_sim.exe foundation_sys.nml`

and then compare for example the x1 values in `Foundation.FITRES.TEXT` and `FOUNDATION_TEST/Foundation_DJ17/FITOPT000.FITRES`, you'll see that they're different.  Not sure why that would be.

**Comment by RickKessler** [comment]
The merge process from split_and_fit failed because "APPEND_FITRES: FITRES RA DECL TGAPMAX TrestMAX" has invalid DECL ... should be DEC.  Also, please switch to using APPEND_TABLE_TEXT:  RA DEC etc ... (no need to specify table name).
