### ISSUE TITLE
Issue when running non Ia simulation

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#520]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL

running 
snlc_sim.exe SIMGEN_WFIRST_Allz_NONIA.input GENRANGE_REDSHIFT: 0.02 1.00

Getting 
 ============ END OF SIMULATION SUMMARY ============== 

  Random Number Sync: 
	 RANDOM SEED: 12945   (RANLIST_START_GENSMEAR: 1)
   FIRST/LAST Random Number (List=1): 0.546307 0.062774  AVG(wrap) = 1.9 +_ 4.7 
   FIRST/LAST Random Number (List=2): 0.278138 0.886073  AVG(wrap) = 0.0 +_ 0.1 
   FIRST/LAST Random Number (List=3): 0.779674 0.060031  AVG(wrap) = 0.3 +_ 0.0 

  Generation Statistics (gen CPU=0.4 minutes): 
	 Generated   100 simulated light curves (4/sec) 
	 Wrote         1 simulated light curves to SNDATA files (0/sec). 
	 Wrote         1 simulated spectra to SNDATA files 
  Spectroscopic-type: 0 -> 0 (before -> after cuts)
  Photometric-type:   1 -> 1 (before -> after cuts)
  Rejection Statistics: 
	     0 rejected by NEPOCH<1 
	     0 rejected by GENRANGEs 
	    99 rejected by SEARCH-TRIGGER 
	     0 rejected by CUTWIN-SELECTION 
  SEARCH+CUTS Efficiency:  0.0100 +-  0.0099 

  Number of SNe per season AFTER CUTS :    383 +-   383

**Comment by RickKessler** [comment]
Problem is zHOST map; let's continue discussion on slack
