### ISSUE TITLE
Allow lowercase or uppercase in hostlib

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#522]
Is it possible that a recent change to SNANA caused this? backwards compatibility to the Hostlibs that Brodie has been making me (with capital letters for X1 and C) would be really appreciated.

to duplicate
```
cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_7DSIMS_WITHT20/1_SIM/SIMDATADES_7D_C11/LOGS/
source RUNME
```

error is below
```	 Reading /project2/rkessler/SURVEYS/PS1MD/USERS/dscolnic/PANTHEON+/HOSTLIBS/F2/HIZ-SPEC-C11.HOSTLIB 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by read_head_HOSTLIB
   Found zero SN params for HOSTLIB_MSKOPT(67) & 64 option.
   Expected 1 or more of 'x1 c alpha beta SNMAGSHIFT RV AV EBV '
```

**Comment by RickKessler** [comment]
oof, the HOSTLIB logic was getting confused between filters a_obs and A_obs, so I removed the "case-insensitivity" for varname matching. I think I can treat  "X_obs" different than other variables to preserve case-insensitivity. Stay tuned.

**Comment by RickKessler** [comment]
Fixed.
