### ISSUE TITLE
WGTMAP out of bounds abort

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#523]
Hi Rick,

I am trying to incorporate the V21 WGTMAP on a test sim on type IIs

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/sim

snlc_sim.exe SIMGEN_WFIRST_Allz_NONIA.input

and I'm falling off the grid resulting in an abort. 

PRE-ABORT DUMP from function init_HOSTLIB_WGTMAP : 
	 GALID = 1275908  (ibin_SNVAR=0, igal=4)
	 logmass = 4.064000  (WGTMAP range: 5.000000 to 13.960000)
	 logsfr = -4.667000  (WGTMAP range: -20.100000 to 3.980000)

Is there a way to extrapolate similar to what is done for the zHOST maps?

Thanks!
-Phil

**Comment by RickKessler** [comment]
<img width="951" alt="OPT_EXTRAP_WGTMAP" src="https://user-images.githubusercontent.com/24592476/121762432-772d6d80-cafb-11eb-8158-2d051ff6164c.png">

Try this new feature highlighted in yellow. It's NOT tested, so send me command if it doesn't work.

**Comment by pmacias** [comment]
Hi Rick,

This is perfect, thanks.

It ran through on a small test of 1000 SNe; I'll do some checks on the output once I have it run through the full sim.

Best,
Phil

**Comment by RickKessler** [comment]
gonna close for now ... re-open if needed.
