### ISSUE TITLE
init_HOSTLIB_WGTMAP

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#526]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL
running 
snlc_sim.exe SIMGEN_WFIRST_Allz_NONIA_II.input
error 
 FATAL ERROR ABORT called by init_HOSTLIB_WGTMAP
   Could not interpolate WGTMAP for GALID=1275908 .
   interp_GRIDMAP() returned istat = -1

**Comment by RickKessler** [comment]
Please note that Phil had the same issue, and is hopefully resolved: https://github.com/RickKessler/SNANA/issues/523
