### ISSUE TITLE
SALT2 fit sometimes fails for snlc_fit.exe

### ISSUE THREAD

**Issue by patrickaleo** [RickKessler/SNANA#527]
Hi,

When I run this command `snlc_fit.exe snfit_YSE_v4.nml > snfit_YSE_v4.log` in my directory `/global/cfs/cdirs/snana/SURVEYS/LSST/USERS/paleo/YSEtests` I sometimes get this error:

<img width="613" alt="snfit_error" src="https://user-images.githubusercontent.com/12074873/121946562-acfc6d00-cd1a-11eb-9ace-06fb8695eda3.png">

    
 Is this a problem with my SALT2 fit params in the .nml file, or something else? Should I simply remove this object from my .LIST file in my lcmerge directory: 
  
    `/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/lcmerge/yselc_v4_photoz`

Thanks

**Comment by patrickaleo** [comment]
Also, a separate but related follow up is for `snana.exe` when the SIMLIB_OUT &SNLCINP key is set, is it required for every data file to have all the filters (g,r,i,z)? Is there an option to turn this off?

<img width="767" alt="Screen Shot 2021-06-14 at 3 27 54 PM" src="https://user-images.githubusercontent.com/12074873/121955056-184b3c80-cd25-11eb-97f4-b712c5550800.png">

**Comment by RickKessler** [comment]
For 2019zcp, 
     REDSHIFT_FINAL:  -99.0000 +- -99.0000  (CMB)
so negative redshifts usually cause problems. You can remove these events with
&SNLCINP
     CUTWIN_REDSHIFT 0.0, 2.0
