### ISSUE TITLE
SIM_RV not in IVAR_TABLE for GENPDF

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#529]
/project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/

Run `RUNTEST_SUBPROCESS_SIM`, and enter iteration 0. This will cause the following crash: 

   `|```````|`                                                                                                                      
   <| o\ /o |>                                                                                                                      
    | ' ; ' |                                                                                                                       
    |  ___  |     ABORT program on Fatal Error.                                                                                     
    | |' '| |                                                                                                                       
    | `---' |                                                                                                                       
    \_______/                                                                                                                       
 FATAL ERROR ABORT called by SUBPROCESS_SIM_REWGT                                                                                   
   Could not find IVAR_TABLE for GENPDF var = 'SIM_RV'                                                                              
   Check command-line arg SUBPROCESS_VARNAMES_GENPDF

**Comment by RickKessler** [comment]
GENPDF should accept RV and AV (not SIM_RV)

**Comment by RickKessler** [comment]
fixed.
