### ISSUE TITLE
SALT2mu_SUBPROCESS on fake data

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#530]
/project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/

Running RUNTEST_SUBPROCESS_BS20DATA will work just fine right now. However, if you change the file in SALT2mu_BS20_REALDATA_ALL_nolowz.input from 

file=$SDSS_USERS/BAP37/POPULATIONS/REF2/DES_SPEC_G10/MASS_0_DATA.FITRES

to

file=$PIPPIN_OUTPUT/BP-DES-DUST-EXAMPLE/2_LCFIT/DFIT_DES_DATA/output/PIP_BP-DES-DUST-EXAMPLE_DES_DATA/FITOPT000.FITRES.gz

(eg just comment one, uncomment the other) - then the script will break. Don't know why.

**Comment by RickKessler** [comment]
new input key
force_realdata=1
treats sim data like real data.
