### ISSUE TITLE
Cannot Modify Search Radius for Host Neighbor Matching

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#532]
Hi,

When I try to generate the hostlib with nearest neighbors, the command-line argument "SEPNBR_MAX" does not change the search radius from 10''. 

_Directory_: 
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config

_Command_:
snlc_sim.exe SIMGEN_TEMPLATE_LSST_AG.INPUT +HOSTNBR SEPNBR_MAX 80.0

**Comment by RickKessler** [comment]
fixed refactor bug from last year when SEPNBR_MAX was mistakenly dropped from reading inputs.
