### ISSUE TITLE
Issue locating file

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#533]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL
running submit_batch_jobs.sh RAH_WFIRST_SIMDATA_G10.input
get error 
- FATAL ERROR ABORT called by SNTABLE_NEVT_TEXT
 - Could not open ascii table file:
 - 'eazy_13_spectral_templates.dat'

But file exits in my directory

**Comment by RickKessler** [comment]
HOSTLIB_SPECBASIS_FILE: eazy_13_spectral_templates.dat
works interactively, but submit_batch runs the snlc_sim job in a different directory and thus the file name needs a full path. Large files (SIMLIB, HOSTLIB*) are NOT copied, so a full path is needed.
