### ISSUE TITLE
Abort that I cant figure out

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#534]
See here, the jobs seem to run fine but there is a corrupted root file or something that doesnt allow it to merge? the only way to reproduce this is to run submit_batch as far as i can tell.

`/scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_7DSIMS_BS20TUNE/2_LCFIT/FFITsimdatanosys_SIMDATAFOUNDBIG_4D_BS20/output/SPLIT_JOBS_LCFIT`

**Comment by djbrout** [comment]
ah okay weird, I found the command

```
['Cannot get NEVT from merged ROOT table after 2 attempts; ', '   MERGE_PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG_4D_BS20_FITOPT000.ROOT', '---> table may be corrupted.', ' ', 'Full table-merge command wa\
s', '  merge_root.exe PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG_4D_BS20_FITOPT000*ROOT MERGE_PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG_4D_BS20_FITOPT000.ROOT  > MERGE_PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDB\
IG_4D_BS20_FITOPT000_ROOT.LOG  ', ' ']
NoneType: None



   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT submit on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

FATAL ERROR ABORT :
   Cannot get NEVT from merged ROOT table after 2 attempts;
      MERGE_PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG_4D_BS20_FITOPT000.ROOT
   ---> table may be corrupted.

   Full table-merge command was
     merge_root.exe PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG_4D_BS20_FITOPT000*ROOT MERGE_PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG_4D_BS20_FITOPT000.ROOT  > MERGE_PIP_PLUS_7DSIMS_BS20TUNE_SIMDATAFOUNDBIG\
_4D_BS20_FITOPT000_ROOT.LOG

```

and when i run the command it seems to work... is it possible that the merge command is happening before the root files have been fully written?

**Comment by RickKessler** [comment]
looks like a conflict with two jobs trying to merge the root files.

**Comment by djbrout** [comment]
but I'm only running one job! just reran it last night to confirm and it failed again...

**Comment by RickKessler** [comment]
underlying sntable_dump.c program had allocated 200 chars for file names, but this file name has 201 chars and corrupted. Fix is to use MXPATHLEN = 300 to define file name lengths. Dillon validated fix using --merge_reset / -M options.
