### ISSUE TITLE
Unknown fail

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#535]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL/
running submit_batch_jobs.sh RAH_WFIRST_SIMDATA_G10.input 
Each job fails with unknown error.

**Comment by RickKessler** [comment]
jobs died due to insufficient memory; see BATCH_MEM key that I added in your input file.  Also remember to run short interactive job before submitting ... jobs don't work interactively, so they won't work in batch.
