### ISSUE TITLE
FATAL ERROR ABORT called by gen_fluxNoise_calc

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#539]
in /project2/rkessler/SURVEYS/WFIRST/USERS/rhounsell/CYCLE8/PRISM/APR2021/FULL
running 
 submit_batch_jobs.sh RAH_WFIRST_SIMDATA_G10.input 
error 
FATAL ERROR ABORT called by gen_fluxNoise_calc
  3 invalid observing conditions for ep=3594, band=a
  mjd=55684.000 zpt=0.00, psf=0.000, skysig=0.00

**Comment by RickKessler** [comment]
Fixed rare/evil bug; a 0.1 day padding was used to select SIMLIB epochs, but NOT used to select spectroscopic epochs. Now the same padding is used for both.
