### ISSUE TITLE
in SALT2mu_fit.pl, option to combine all INPDIR+ regardless of STRINGMATCH and STRINGMATCH_IGNORE

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#54]
Hi Rick, last github issue for today, sorry for the spam.  In a SALT3 telecon we'd discussed with you an option to combine all directories specified by INPDIR+ keys into combined BBC distances, regardless of the STRINGMATCH and STRINGMATCH_IGNORE keys.

**Comment by RickKessler** [comment]
waiting for example directories to read with SALT2mu/BBC

**Comment by RickKessler** [comment]
See new BBC input 
STRINGMATCH_IGNORE:  IGNORE  
However, this new feature needs more testing.

**Comment by djones1040** [comment]
the example I'd provided was missing one of the necessary biascor files.  I fixed this, and now the results look good, see:
```/project2/rkessler/PRODUCTS/SNANA_DEBUG/SALT2mu_fit_noSTRINGMATCH/OUT_TEST_BBC/BYO_BBC```
