### ISSUE TITLE
[Request] Pass user defined systematic offsets to SNANA_SIM

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#540]
When working with forward modelling systematics it would be nice to be able to define my own set of systematic offsets for the _n_ simulations defined by `RANSEED_CHANGE: n seed`. This would allow finer control over the systematics, for instance drawing them from a custom covariance matrix.

The syntax of the file can be whatever is easiest for SNANA to read but I imagine something like:

```
REDSHIFT MWEBV ZP_g ZP_r ZP_i LAMFILT_g LAMFILT_r LAMFILT_i
0.01 0.1 0.3 0.3 0.3 0.001 0.002 0.003
.
.
.
0.04 0.12 0.28 0.27 0.25 0.05 0.003 0.006
```
Where you have the first row defining the systematics to be offset, and each successive row is the offset for the ith simulation realisation.

**Comment by OmegaLambda1998** [comment]
`/project2/rkessler/SURVEYS/DES/USERS/parmstrong/SNANA-pa` has my implementation of this request. Running `submit_batch_jobs.sh` on `/project2/rkessler/SURVEYS/DES/USERS/parmstrong/tests/PIP_PA_WSET_DESSIM_w_1.input` produces an error: `Cannot specify 3 INPUT_INCLUDE_FILE keys`

**Comment by RickKessler** [comment]
The side-issue about INPUT_INCLUDE_FILE is fixed ; see closed issue 541.

**Comment by RickKessler** [comment]
see merged pull for reading list of INCLUDE files
