### ISSUE TITLE
GENMOD mask 1 doesn't prevent angle match

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#543]
It looks like `GENMOD: foobar 1 + 2 + 4` doesn't disable `ANGLEMATCH_b`

**Comment by RickKessler** [comment]
"GENMOD:" is not a valid key for anything. Please check manual, or point to a PLASTICC input that uses GENMOD. To disable angle matching, see manual 
Section 9.10.4 GENMODEL_MSKOPT Options
