### ISSUE TITLE
COMMENT keyword is not allowed in LCLIB anymore

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#544]
I see some regression: usage of LCLIB gives an error which wasn't an error yesterday:
```
 FATAL ERROR ABORT called by get_PARSE_WORD
   iwd=7 exceeds NWD_STORE=7
   Check 'COMMENT: Created at 2021-06-24 by Konstantin Malanchev
```

Probably related to the fix of #542

**Comment by RickKessler** [comment]
Sorry I forgot to warn you that I updated LCLIB code to no longer read COMMENT keys, and instead the LCLIB should have a standard DOCUMENTATION block that is YAML-compliant; see new Fig 13 in manual.

**Comment by RickKessler** [comment]
fixed genmag_LCLIB.c to skip COMMENT lines and to skip DOCUMENTATION block, so obsolete COMMENT lines should no longer cause problems.
