### ISSUE TITLE
ANGLEMATCH_b: 90 leads to hanging

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#545]
I'm trying to build LCLIB including `ANGLEMATCH_b` keyword to properly simulate Galactic events. I've found that even if I have a good coverage of `b` for all my events SNANA hangs at light-curve generation. Then I tried to set `ANGLEMATCH_b: 90` to each event (which I believe a maximum reasonable value due to eq 36 of the manual) but it hasn't solved this issue too.

**Comment by hombit** [comment]
Looks like it happens only in the case of equatorial coordinates, but everything works fine for galactic coordinates

**Comment by RickKessler** [comment]
please provide command to reproduce the problem.

**Comment by hombit** [comment]
Minimal `LCLIB` reproducing the problem

```
SURVEY: LSST
FILTERS: ugrizY
MODEL: TEST
RECUR_CLASS: RECUR-PERIODIC
NEVENT: 1

START_EVENT: 0
NROW: 3 RA: 0.0 DEC: 45.0
ANGLEMATCH_b: 90.0
S:  0.0000 10.000 10.000 10.000 10.000 10.000 10.000
S:  1.0000 12.000 12.000 12.000 12.000 12.000 12.000
S:  2.0000 10.000 10.000 10.000 10.000 10.000 10.000
END_EVENT: 0
```

But if you replace `RA` -> `l` and `DEC` -> `b` it starts to work

**Comment by RickKessler** [comment]
I need a command such as
cd $path
snlc_sim.exe <inputFile>

**Comment by RickKessler** [comment]
I made a fix moving the RA,DEC translation to before the angle match cut ... but it's not tested.

**Comment by hombit** [comment]
It still doesn't work on Cori.

Commands to reproduce:
```sh
cd ~kostya/snana-issue545
snlc_sim.exe  SIMTEST.INPUT
```
