### ISSUE TITLE
Code produces empty files

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#550]
I am trying to obtain simulations but these keep failing.

My files are in `/global/homes/c/catarina/simulations/baseline_nexp2_v1.7_10yrs` and I run the following command
```
$ submit_batch_jobs.sh SIMGEN_MASTER_LSST_DDF.INPUT --fast
```

I downloaded the resulting `.FITS` files from 
```
/global/cscratch1/sd/kessler/SNANA_LSST_SIM/TMP_cata_LSST_DDF_MODEL90_SNIa-SALT2_NONIaMODEL0-0001_32512
```
but they were empty/compromised.

**Comment by RickKessler** [comment]
check FAIL_SUMMARY.LOG and note the following:

  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by SIMLIB_readNextCadence_TEXT 
  - NOBS=18614 exceeds bound for LIBID=1. 
  - Check bound: MXOBS_SIMLIB = 15000
