### ISSUE TITLE
Cannot find HOSTGAL2 parameters in sim output

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#555]
I am running a small job to get a run with SN Ia galaxies and their nearest neighbors. 90% of galaxies in the hostlib have at least one nearest neighbor, yet the "HOSTGAL2_" parameters that get written to file are all 0, -9, or -99. 

_Directory_:
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config

_Command_:
submit_batch_jobs.sh SIMGEN_MASTER_IDEAL_zALL_GHOSTLIB_SNIa.INPUT

**Comment by RickKessler** [comment]
in TEXT format it writes out HOSTGAL2 info, but seems to be duplicating first HOST.  And SB is corrupted.

**Comment by RickKessler** [comment]
fixed index bug, and checked 2nd HOST in TEXT format.
