### ISSUE TITLE
Error converting SNANA FITS output to text

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#560]
When using the quick_commands.py script to convert an SNANA fits file, no text file is produced (model is named MLAG_IDEAL_zALL_MODEL90_SNIa-SALT2_80k and file generated is called MLAG_IDEAL_zALL_MODE).

_Directory:_
/global/cscratch1/sd/kessler/SNANA_LSST_SIM

_Command:_
quick_commands.py -v MLAG_IDEAL_zALL_MODEL90_SNIa-SALT2_80k --cidlist_text TEN

_File Output:_
DOCUMENTATION:
  GENVERSION: MLAG_IDEAL_zALL_MODEL90_SNIa-SALT2_80k 

#                   NLC_GEN   NLC_WRITE  NSPEC_WRITE  CPU(minutes)
  STAT_SUMMARY: 
  - TOTAL            162393     160000         0        163.1
  - NONIaMODEL0      162393     160000         0        163.1

  INPUT_FILES:
  - MASTER    SIMGEN_MASTER_IDEAL_zALL_GHOSTLIB.INPUT 
  - NONIa     SIMGEN_TEMPLATE_LSST.INPUT 

  SUBMIT_DIR:  /global/cfs/cdirs/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config
DOCUMENTATION_END:

**Comment by RickKessler** [comment]
fixed.
