### ISSUE TITLE
Feature Request: Add a MINDDLR/ minimum angular separation in arcseconds as a model keyword

### ISSUE THREAD

**Issue by gnarayan** [RickKessler/SNANA#561]
Some models (e.g. KN) will be found preferentially at high angular separation. When generating transient simulations for these models, SNANA currently creates an angular offset from the host position using the light profile, which will result in most generated objects being near the center of the host. While it is possible to scale the light profile, there's no way to avoid an overdensity at lower distances. While there is a MAXDDLR keyword to control how far away the simulation can be for an association, there is no corresponding MINDDLR keyword to exclude some region near the center.

**Comment by RickKessler** [comment]
See new HOSTLIB_MNINTFLUX_SNPOS parameter in snlc_sim.c[h], sntools_host, and in manual.
