### ISSUE TITLE
Roman prism spectra sims

### ISSUE THREAD

**Issue by masaosako** [RickKessler/SNANA#562]
There are numerous rows in the SPECTRO_HEADER extension with values NBIN_LAM=0 and PTRSPEC_MAX<PTRSPEC_MIN.  Example sims can be found on Midway in:

  /scratch/midway2/rkessler/SNDATA_ROOT/SIM/RAH_WFIRST_SIMDATA_G10/

**Comment by RickKessler** [comment]
main bug was that for spectra rejected by pre-scale, the spectra were still written with NLAM=0. Bug fixed, along with a few other bugs related to reading these large events.
