### ISSUE TITLE
SNANA Not Reading gzipped WGTMAP

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#563]
When running a small job on the head node, I get an error that the gzipped WGTMAP is not being read in by SNANA. the unzipped version of the WGTMAP throws no error.

_Directory:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/BIGWGTMAP_DEBUG/

_Command:_
./ALEX_TEST.sh > ALEX_OUT.LOG & 

_Error Message:_

 FATAL ERROR ABORT called by read_VARNAMES_WGTMAP
   Reached EOF before finding WGTMAP or GAL key.
   Check format for HOSTLIB_FILE.

**Comment by RickKessler** [comment]
for gzipped files, it will work if you add a DOCUMENTATION block, or anything such that VARNAMES is not the first element in the file. See slack message for details.
