### ISSUE TITLE
NFIT_ITERATION error

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#568]
Hi Rick,

I have been running into an unknown error in stage 2 of my pippin runs, so I tried to run an interactive job 

cd /project2/rkessler/SURVEYS/WFIRST/USERS/pmacias/dev/lcfit
snlc_fit.exe SIMFIT_WFIRST_Allz.NML 

and it failed with the error message 

 FATAL ERROR ABORT called by RDSNNML
   NFIT_ITERATION =   0
   NFIT_ITERATION must be > 0 (see &SNLCINP namelist).

but NFIT_ITERATION = 2 in my .NML. I tried to change it to something ridiculous like 200, it seems to be ignored and many things are defaulting but not all, e.g. changing VERSION_PHOTOMETRY is reflected in the output but not NFIT_ITERATION. 

Please let me know if I'm missing something here.

Thanks!
- Phil

**Comment by RickKessler** [comment]
KCOR_FILE argument needs single quotes around it, and fortran comments have exclamation, not hash.
