### ISSUE TITLE
FLUXCALERR is nan with MWEBV

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#569]
When running an ideal LSST sim with MWEBV turned on, FLUXCALERR = -nan in the output. This was found to be because ra, dec=0 in the simlib, and so the extinction is never calculated. 

_Directory:_ 
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/FLUXCALERR_DEBUG

_Command:_
./DEBUG.sh

**Comment by RickKessler** [comment]
fixed. And tested.  To see the fix, search for RA_LAST
