### ISSUE TITLE
"Stack smashing" for some of the sample_input_files

### ISSUE THREAD

**Issue by ycwang427** [RickKessler/SNANA#57]
I am using Windows' Ubuntu 18.04 subsystem and SNANA v10_75d. When running the sample simulation following the instruction in "getting started quickly", `snlc_sim.exe sim_SDSS.input`, a stack smashing problem occurred. (The same problem seemed to occur for `snlc_sim.exe sim_HST.input`, etc. as well; I have modified nothing of the input and data files in the package. ) The last few lines printed are:
```
Begin Generating Lightcurves.
  Found Max dN/dz * wgt = 0.000000e+00 at z =    0.020
*** stack smashing detected ***: <unknown> terminated
Abort (core dumped)
```
I have no idea where the problem may come from.

**Comment by RickKessler** [comment]
I fixed several sample input files that were no longer working. Please Git pull most recent source code, download SNDATA_ROOT from snana.uchicago.edu, and try again. If still not working, please provide full path of input file under $SNDATA_ROOT.

**Comment by ycwang427** [comment]
I tried the latest version of the code and SNDATA_ROOT. It seems that $SNDATA_ROOT/smaple_input_files/SALT2/sim_SNLS.input works well, but for sim_HST, sim_SDSS, sim_LOWZ, the problem still exist. Here is the 
[sample_input_files](https://github.com/RickKessler/SNANA/files/4338873/sample_input_files.tar.gz) 
under $SNDATA_ROOT.

**Comment by RickKessler** [comment]
I processed the above sim-input files with valgrind debugger, and got zero errors. I searched your error message online, and found a warning that valgrind is not very good at detecting this kind of problem. Please try valgrind on your computer to see if it catches something (and enable -g in Makefile by uncommenting the line with -g)

**Comment by ycwang427** [comment]
This is part of the output of running `valgrind --leak-check=full snlc_sim.exe sim_SDSS.input`.
[valgrind_output.txt](https://github.com/RickKessler/SNANA/files/4350345/valgrind_output.txt)

**Comment by RickKessler** [comment]
please indicate which tagged version of the code so I can find the line number in snlc_sim.c

**Comment by ycwang427** [comment]
I ran it again using v10_76b. This is the new output:
[valgrind_output_v10_76b.txt](https://github.com/RickKessler/SNANA/files/4353858/valgrind_output_v10_76b.txt)

```
==3921==    by 0x154115: gen_cutwin (snlc_sim.c:19131)
```

**Comment by RickKessler** [comment]
The above line is not an executable line of code, so maybe you have an intermediate update. Can you provide the snlc_sim.c code ? Also, please check that there is enough memory on your computer (2GB should be plenty).

**Comment by RickKessler** [comment]
Also, please follow the valgrind suggestion: "For counts of detected and suppressed errors, rerun with: -v"

**Comment by ycwang427** [comment]
This is snlc_sim.c (c files are not supported so I added ".txt")
[snlc_sim.c.txt](https://github.com/RickKessler/SNANA/files/4355089/snlc_sim.c.txt)
And line 19131 in this file is just the end of function `gen_cutwin`:
```C
} // end of gen_cutwin  //this is line 19131
```

Result of rerunning with -v:
[valgrind2.txt](https://github.com/RickKessler/SNANA/files/4355208/valgrind2.txt)
It seems that it catched nothing more.

**Comment by RickKessler** [comment]
Unfortunately I don't know how to fix this issue, and it could be related to libraries installed on your local computer. I suggest searching online for help about this stack smashing error. Please let me know if you figure it out.

**Comment by ycwang427** [comment]
Thank you very much for your help with this issue. Now I suppose it is indeed related to libraries installed on my Linux system, or the system itself. I ran the code on another Linux system, and everything worked well so far. By the way, it seems that you've removed these in the later edition of input files:
```
# cosmological params for lightcurve generation and redshift distribution
OMEGA_MATTER:  0.3
OMEGA_LAMBDA:  0.7
W0_LAMBDA:    -1.00
H0:           70.0   
```
Are these parameters still useable? I am intending to explore how simulated data changes with cosmological parameters.

**Comment by RickKessler** [comment]
regarding cosmological parameters, the code defaults have recently been updated to use the Planck 2018 values (OM=0.315), so users are encouraged to remove their private cosmo params.
