### ISSUE TITLE
hostgal_mag_err not updated in SNANA output

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#570]
None of my jobs have mag_errors within the output hostgal data. This is true for all of my sims, but for debugging the directory from a previous git issue can be used: 

_Directory:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/FLUXCALERR_DEBUG

_Command:_
./DEBUG.sh

**Comment by RickKessler** [comment]
the HOSTLIB contains [band]_obs columns, but not [band]_obs_err ... so there is no information about uncertainties. Can either add error columns, or we can compute errors based on specifying SNR at a particular mag.

**Comment by alexandergagliano** [comment]
I've just found mag errors within the cosmoDC2 catalog, so I can add these to the hostlib! Do they have to have a certain name to be propagated through to the data outputs?

**Comment by alexandergagliano** [comment]
I've just added error columns as u_obs_err, b_obs_err, etc. and the host mag errors are still not getting written to the output. 
Directory:
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config

Command:
submit_batch_jobs.sh SIMGEN_MASTER_IDEAL_zALL_GHOSTLIB_SNIa.INPUT

I'll manually add them through STOREPAR for now to get a sample alert.

**Comment by RickKessler** [comment]
We need to write a little sim code to identify the mag-err info and include it in the data file output. Let's setup zbug time on slack.

**Comment by RickKessler** [comment]
Done.
