### ISSUE TITLE
SNe used for MUDIF not present in FITRES

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#573]
Was looking closer at the SNe causing absurd MUDIF values (row 6,9) in this file: `/project2/rkessler/SURVEYS/DES/USERS/rebeccachen/photoz_bias/RC-G10-DESLOWZX5-FIX/OUTPUT_BBCFIT-0091/FITOPT003_MUOPT004.M0DIF`, and it looks like they are not present in the corresponding output FITRES. It looks like there are 5 more SNe used in the M0DIF file than are present in the FITRES, and the redshift ranges line up with the redshifts of the 5 SNe cut because of a chi2 cut (CID are 200040, 171390, 11940, 76590, 2790). In other words, seems like SNe that are cut with chi2 cut are somehow still being used for MUDIF calculations.

The input SALT2mu file is at `/project2/rkessler/SURVEYS/DES/USERS/rebeccachen/photoz_bias/RC-G10-DESLOWZX5-FIX-BBC.input`

**Comment by RickKessler** [comment]
looks like the chi2max cut is commented out.

**Comment by rebeccachen0** [comment]
Sorry, forgot I had edited that file after running— it was not commented out when I ran it.

**Comment by RickKessler** [comment]
when chi2max cut rejects events, call setup_zbins_fit() for 2nd time to update NFIT(z), and check for z-bin drop-outs.  This fixes subtle bug if chi2max cut causes z-bin to be empty; empty z-bin was still included in the fit. Also fixes cosmetic bug for NFIT column in .M0DIF outfile.
