### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#586]
Yesterday I ran the `simlib_coadd.exe` without any problem but today the same code is giving me the following error:
```
$ simlib_coadd.exe footprint_8_v1.710yrs_WFD.simlib                        
Segmentation fault
```
This file along with a test file (`aa.simlib`) are in $SNANA_LSST_ROOT / simlibs

**Comment by RickKessler** [comment]
I had accidentally left the debug flag on when updating SNANA on Cori last night, which is actually a good thing because it catches more subtle bugs like the one you found. It's fixed.
