### ISSUE TITLE
Missing/weird files

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#589]
I run SNANA simulations similar to PLAsTiCC for DDF and WFD. They were run separately.

For the DDF, the output was simply folders like `LSST_DDF_MODEL42_SNII`. However, for WFD, in addition to those folders, I also got several folders like `TMP_cata_CSA_LSST_WFD_MODEL42_V19_CC+HostXT_NONIaMODEL0-0020_64628` . Is there something wrong? There are also missing the simulations of the `CSA_LSST_WFD_MODEL90_SNIa-SALT2`.

In both cases, I ran (changing between WFD and DDF)
``` 
submit_batch_jobs.sh SIMGEN_MASTER_LSST_WFD.INPUT
```
and there were no FAILS files.

**Comment by RickKessler** [comment]
Each batch job creates a TMP_cata_XXX folder, and then the folders are merged and removed at the end. If TMP_cata_ folders remain, this means that something aborted or crashed, in which the cleanup is skipped.

**Comment by Catarina-Alves** [comment]
Thank you. I will try to run again with the `--fast` flag to see if I can identify the issue. I will leave this issue open because the problem will probably persist.

**Comment by RickKessler** [comment]
What directory did you launch jobs ?

**Comment by Catarina-Alves** [comment]
I started a run with `--fast` yesterday and it has not finished yet. I launched the jobs from `/global/homes/c/catarina/simulations/footprint_8_v1.710yrs`.

**Comment by RickKessler** [comment]
Fixed a bug implementing CIDRAN_MIN, and set abort trap in case a similar bug occurs in the future.  I think this bug had resulted in accessing bad memory addresses, causing a crash.
