### ISSUE TITLE
BBC not converging

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#591]
Hi Rick,

Pippin runs are aborting in stage 6, here is what I've been able to dig up:

cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+RUBIN/6_BIASCOR/BBC/output

grep -B 2 -A 2 ABORT FAIL_SUMMARY.LOG

shows that something is failing in ITER1, so after a bit more digging i found FITOPT012 is the issue,

more /scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_STARTERKIT+RUBIN/6_BIASCOR/BBC/output_ITER1/SCRIPTS_BBCFIT/wfit_OUTPUT_BBCFIT_FITOPT012_MUOPT000.LOG

shows lack of convergence, but i'm not sure what to do from there. I think this job is failing which then throws everything else after out of whack. 

Thanks!
- Phil

**Comment by RickKessler** [comment]
This is a very rare and subtle bug that I have not been able to fix in the past. Kludge fix is to  change p2 by very small amount.
