### ISSUE TITLE
TAKE_SPECTRUM of host not bound by TAKE_SPECTRUM_PRESCALE rules

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#596]
I am creating SNe and host spectra. 
I have 
# spectra stuff non-Ia
TAKE_SPECTRUM(DEEP): MJD(55000:55724:8.0) TEXPOSE_ZPOLY(3600) #every 8 days at 3600 sec - deep
TAKE_SPECTRUM(SHALLOW): MJD(55000:55724:4.0) TEXPOSE_ZPOLY(900) #every 4 days at 900 sec - shallow

# scales are of prism spectra to imaging
TAKE_SPECTRUM_PRESCALE: SHALLOW/6.17+DEEP/5.0

# adding in host contamination
TAKE_SPECTRUM_HOSTSNFRAC: 0.1  #scale FLAM(HOST) so Sum(HOST)/Sum(SNPEAK) = 0.1

#Take spectrum stuff for host
TAKE_SPECTRUM: HOST TEXPOSE_ZPOLY(100000) #do not need to specify mjd

It seems like I am getting host spectra for galaxies outside of my prism area range - i.e. the prescale is not working.
Could you please verify this is the case. 
Thanks

**Comment by RickKessler** [comment]
found this in the snlc_sim code to verify: 
   // check field-dependent pre-scales for SN spectra (MJD>0);                 
    // host spectra always generated.                                           
    if ( CHECK_PS && MJD > 0.0 ) {
