### ISSUE TITLE
GENPDF Beta does not work 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#600]
Tinkering around with the GENPDF function for beta, I have found that we're getting a new error about non-uniform bins when using the new SIM_beta options. I'm getting the following error - 

  PRE-ABORT DUMP from function init_interp_GRIDMAP : 
	 VALMAX - VALMIN  = 2.982301e+00 (0.000000e+00 to 2.982301e+00)
	 (NBIN-1)*BINSIZE = 2.973451e+00 (168 x 1.769912e-02) 
	 Ratio-1 = -2.967359e-03 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by init_interp_GRIDMAP
   Non-uniform binning for idim=0
   Check map = 'SIM_beta' 

from the GENPDF map - /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/testplot/299_PYTHONCROSSTALK_OUT.DAT-2

The result is repeatable by running the following script:

/project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/RUNTEST_SUBPROCESS_BOUND

**Comment by RickKessler** [comment]
subtle numerical bug in compute_genGauss_GRIDMAP. Loop over bins has to extend to RANGE[1]+1.0E-6 to ensure that last bin is loaded. Bug was that loop to RANGE[1] just missed last bin by a ridiculously small number.
