### ISSUE TITLE
SALT2 training features

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#602]
It seems that the submit_batch_jobs.sh implementation of SALT2 training is the most user-friendly way of training on Midway, but there's currently no way to train an unperturbed surface  (i.e. if you don't specify a TRAINOPT perturbation, the script won't compile). The script automatically trains an unperturbed surface alongside any TRAINOPTS specified, could we add an option to train this unperturbed surface without requiring TRAINOPTS?

Along the same line, the training sample is currently specified "under the hood" (in $PRODUCTS/snpca/train_SALT2.py) as 'trainingsample_snls_sdss_v5.list' in the base folder (PATH_INPUT_CALIB in the submit_batch input script). To change the training sample used, I need to copy the entire base folder and edit the training sample list, without changing the name. Can we add a feature to specify the full path of the training sample, rather than taking it from PATH_INPUT_CALIB? I can make any changes to the train_SALT2.py script if needed.

**Comment by RickKessler** [comment]
GT added TRAINOPT_GLOBAL feature.
