### ISSUE TITLE
Two SUBPROCESS issues 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#609]
First one is found by running /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/RUNTEST_SUBPROCESS_BOUND in its home directory - with iteration 2, we get the following error:

 FATAL ERROR ABORT called by SUBPROCESS_PROB_SIMREF
   Did not find bounding functions for 'SIM_c'
   Bounding func must be specified for all variables or none!

However, the bounding function for c is present - /scratch/midway2/rkessler/PIPPIN_OUTPUT/HIGH-REDSHIFT-BOUND/1_SIM/SIMDES_4D_BS20/PIP_HIGH-REDSHIFT-BOUND_SIMDES_4D_BS20.input has GENPEAKRANGE defined for c! 

The second one comes from changing the iteration number, and can be seen by doing 

cd /project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver
python runparallelemcee.py --debug

This will run for two iterations before crashing due to the following:

2021-07-29 08:07:29 DEBUG     FATAL ERROR ABORT called by checkStringUnique
2021-07-29 08:07:29 DEBUG       2  'GENPEAK_SIM_beta:' keys exceeds limit=1 in SALT2mu command-line override.
2021-07-29 08:07:29 DEBUG       Calling function is NstringMatch .

which can be found at /project2/rkessler/SURVEYS/DES/USERS/djbrout/dustdriver/logs/log_walker_0.log

I think these may be related, but I'm not sure how, exactly

**Comment by RickKessler** [comment]
First issue is subtle mis-conception in SUBPROCESS_PROB_SIMREF where index mapping is set only on ITER=0 and 1, and assumes that the code never exits. Application above exited between iterations and thus failed. Fix is to set index mapping for every iteration.

**Comment by RickKessler** [comment]
For 2nd issue, I think the problem is that on the 2nd read of SIM_beta_XXX, it exceeds the limit of only 1 allowed key. I added a function call.
  uniqueOverlap(STRINGMATCH_INIT,"SUBPROCESS");
to reset the counter for each iteration. Fix is pushed to GitHub and Midway, but NOT tested. Lemme know if it works.
