### ISSUE TITLE
SNANA Job Hangs when 0 SNe output

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#611]
The submit script submit_batch_jobs.sh on Cori hangs if 0 SNe are written out. It should instead abort. The job below runs okay interactively but hits the walltime of 48 hours with submit_batch_jobs.sh.

_Directory:_
agaglian@cori12:/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/agaglian/ZTF_youngSNe

_Command:_
submit_batch_jobs.sh AG_REFAC_SIMGEN_MASTER_YSE.INPUT

**Comment by RickKessler** [comment]
sorry for late reply here, but I checked your current AG_REFAC_SIMGEN_MASTER_YSE.INPUT job, and it seems to have mysteriously died after about 20 minutes. I tailed the TMP log files, and the generation rates are < 20 /sec, which is more than order-of-mag slower than normal. But slow generation should cause jobs to die.

**Comment by alexandergagliano** [comment]
Job timed out due to incorrect key in simlib. Correct simlib fixes the issue and new job runs to completion.
