### ISSUE TITLE
SNooPy fitting doesn't find the best parameters

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#612]
Hi Rick,

Have been digging into SNANA-SNooPy recently, and noticed some disagreement in the high-z data between the python code fitting and the SNANA fitting.  When I checked the actual fitting itself though, I found that there are cases where the SNooPy value produces a better total chi^2 than the SNANA value.  I put an example in `$SNANA_DEBUG/djones/RAISIN`:

```
# first, allow snlc_fit.exe to find the best parameters
snlc_fit.exe DES_RAISIN_optnir.nml

# second, fix the STRETCH to the best-fit SNooPy-python value, 0.92
snlc_fit.exe DES_RAISIN_optnir_fixst.nml
```

The first example produces a chi2/DOF of 84/59 while the second is 73/64.  Do you have any idea what's going on, or perhaps changes I could make to my NML files to get the lowest possible chi2?  Thanks so much.

**Comment by RickKessler** [comment]
in FITINI_ADJUST, we added optional color (AV) loop in addition to delta-PEAKMJD loop for estimating initial params. 
   grep  INIVAL_GRIDSEARCH_ snlc_fit.car
