### ISSUE TITLE
GENGAUSS_ASYM and GENPDF can be used together

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#625]
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PLUS_SMALLBS20/1_SIM/SIMDATADES_4D_BS20/LOGS/test.CMD launches an interactive job with both GENPDF and GENGAUSS_ASYM specified for colour. This results in GENGAUSS being used and the simulation not aborting.

If possible, it would be ideal for a command line GENPDF to override the regular input file, so that we don't have to scrub all inputs of GENGAUSS just to use a GENPDF.

**Comment by RickKessler** [comment]
first, the correct column names are SALT2c and SALT2x1 (not c, x1).
Next, I modified the sim so that command-line GENPDF can override GENGAUSS from input file ... and vice-versa. If both GENPDF map and GENGAUSS are from input file (or both from command line), sim aborts due to ambiguous priority.
