### ISSUE TITLE
What are the units of the prism spectra 

### ISSUE THREAD

**Issue by rebekah9969** [RickKessler/SNANA#629]
What are the flux units of the prism spectra please

**Comment by RickKessler** [comment]
According to SNANA manual, dF/dlam units are erg/s/cm^2/A

<img width="810" alt="SPECTROGRAPH_units" src="https://user-images.githubusercontent.com/24592476/129412619-aeedaa5f-d238-4de7-8ec5-d251443eeb0e.png">
