### ISSUE TITLE
Low redshift uncertainties on high-z SNe for SN z fit without prior

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#630]
Redshift uncertainties are lower than expected for SN z fit without prior, even at high redshift.

Reproduced at $SNANA_DEBUG/rebeccachen/z_err with submit_batch_jobs.sh $SNANA_DEBUG/rebeccachen/z_err.NML

FITOPT002 is SN fit + prior and FITOPT003 is SN fit without prior.
SN 106496 is zCMB = 0.7958 with zCMBERR = 0.00641

**Comment by RickKessler** [comment]
Unresolved; See slack messages.
