### ISSUE TITLE
c cutoff in snlc_fit at c=1

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#636]
Hi Rick,

There is a cutoff in snlc_fit with SALT2 at c=1.  

(base) [dscolnic@midway2-login1 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login1 dscolnic]$ snlc_fit.exe SWIFTNEW.nml > log

Here we are fitting a single SN - 2014J, which is famously very red, like should be c=1.5.  SALT2 hits the bound at c=1 and doesnt move past.  We see this for both real and simulated data.  I'm guessing there is some hard-coded cut somewhere.  Thanks for checking!

Dan and Ben

**Comment by RickKessler** [comment]
red color bound in snlc_fit was hard-coded at 1.0; changed to 2.0
