### ISSUE TITLE
Segfault when generating DLR-nearest neighbors for HOSTLIB

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#638]
_Location:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config

_Command:_
snlc_sim.exe SIMGEN_TEMPLATE_LSST_AG.INPUT +HOSTNBR NNBR_WRITE_MAX 5

_Error:_
	 Processing igal  1820000 of  1827293  (NNBR_MAX=15 for GALID=11189484370)
# ---------------------------------------------------- 
 Crosscheck dump for igal_read=1827291, GALID=12064899172 
	 READ  NBR list: 1813465
	 GALID NBR list: 12063682729

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002aaaafb3e1da in waitpid () from /lib64/libc.so.6
#1  0x00002aaaafabb76f in do_system () from /lib64/libc.so.6
#2  0x00002aaaab745823 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0xe58db80) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:2106
#3  TUnixSystem::StackTrace (this=0xe58db80) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:2400
#4  0x00002aaaab748064 in TUnixSystem::DispatchSignals (this=0xe58db80, sig=kSigSegmentationViolation) at /project/projectdirs/swowner/wbhimji/root/root-6.18.00/core/unix/src/TUnixSystem.cxx:3631
#5  <signal handler called>
#6  0x00002aaaafb15b73 in __strcpy_sse2_unaligned () from /lib64/libc.so.6
#7  0x00000000004d31d5 in rewrite_HOSTLIB_plusNbr ()
#8  0x000000000040e6f7 in rewrite_HOSTLIB_DRIVER ()
#9  0x0000000000440de6 in main ()
===========================================================

The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00002aaaafb15b73 in __strcpy_sse2_unaligned () from /lib64/libc.so.6
#7  0x00000000004d31d5 in rewrite_HOSTLIB_plusNbr ()
#8  0x000000000040e6f7 in rewrite_HOSTLIB_DRIVER ()
#9  0x0000000000440de6 in main ()
===========================================================

**Comment by RickKessler** [comment]
fixed bug that was caused a loop over 1 billion elements regardless of HOSTLIB size.
