### ISSUE TITLE
TAKE_SPECTRUM error

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#640]
Got an error like below:
```
 FATAL ERROR ABORT called by parse_input_TAKE_SPECTRUM
   Cannot mix TAKE_SPECTRUM keys in sim-input & SIMLIB.
   Remove one of these TAKE_SPECTRUM sources.
```
but there were no TAKE_SPECTRUM keys in the sim-input.

Error can be reproduced by running the FAIL_REPEAT commands in this dir:
`$SNANA_DEBUG/mdai/take_spec/SIMLOGS_SIM_SALT3TRAIN_train_804`

**Comment by RickKessler** [comment]
fixed bug from recent refactor.
