### ISSUE TITLE
lcfitting sncid_ignore_file doesn't work

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#646]
My ignore file has SNIDs in it but the following is happening. See slack for command to replicate
 ```
 ######################################################## 
    RDSNIGNORE  
  ######################################################## 
  
  Loaded            0  IGNORE-candidates from 
   IGNORE_LIST.TXT
```

**Comment by RickKessler** [comment]
fixes for SNCID_IGNORE_FILE: 
  + works with/without DOCANA, 
   + ignores comments after hash
   + prints 1st/last CID.
