### ISSUE TITLE
HOST_ZPHOTERR doesn't match HOSTLIB ZPHOTERR

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#647]
When running fits with USE_SNHOST_ZPHOT = T, the resulting HOST_ZPHOTERR does not match the ZPHOTERR from the HOSTLIB -- not sure if this is a problem with the fit or the original simulation.

Problem reproduced with snlc_fit.exe $SNANA_DEBUG/rebeccachen/HOST_ZPHOTERR.NML

For reference, the original HOSTLIB is at /project2/rkessler/SURVEYS/DES/USERS/rebeccachen/photoz_bias/RM_bias_added_zonly_zphoterrzero.HOSTLIB where to ZPHOTERR are set to zero.

**Comment by RickKessler** [comment]
was due to confusion between ZERR and ZPHOTERR columns; see slack messages.
