### ISSUE TITLE
Flat x1,c simulation generation 

### ISSUE THREAD

**Issue by anaismoller** [RickKessler/SNANA#65]
Searching to simulate flat c,x1 profiles. Manual says to use GENSIGMA_SALT2c / x1 but if this option is not using gaussian profile it crashes. 
Error after devil face:
   FATAL ERROR ABORT called by check_crazyFlux
   flux=3.309154e+04 exceeds CRAZYFLUX=2.275730e+04
   See dumpEpoch details

**Comment by RickKessler** [comment]
Please copy input file under $SNANA_DEBUG/Anais (and command) so that I can reproduce the abort.

**Comment by anaismoller** [comment]
Thanks. The file is there and now also the command in a text file

**Comment by RickKessler** [comment]
The SALT2 color range is too wide:
   GENRANGE_SALT2c:   -0.700  0.700     
and the crazy mag has c=-0.674 where the SALT2 model is just doing crazy color-law extrapolations from a high-order polynomial. Suggest using more restricted range -0.4 to +0.5.
