### ISSUE TITLE
SALT2mu nan issues

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#651]
Hey Rick - a number of people (Erik, Brodie, Dillon, myself) have suddenly started seeing nan's pop up as outputs of SALT2mu.  

(base) [dscolnic@midway2-login2 dscolnic]$ pwd
/project2/rkessler/PRODUCTS/SNANA_DEBUG/dscolnic
(base) [dscolnic@midway2-login2 dscolnic]$ SALT2mu.exe plus_erik_dan.input

See things like this -
# SALT2mu fit results:
#  NSIM(6D-BIASCOR)   = 5484518   (N_alpha x N_beta = 1 x 1)
#  sigint(6D-BIASCOR) = 0.000
#  NSNFIT        = 1819
#  -2log(L)     = 100000000000000.00
#  chi2(Ia)/dof = 1350.76/1797 = 0.752
#  sigint   = 0.0000  (3 iterations)
#  alpha0         =        nan +-      nan
#  beta0          =        nan +-      nan
#  m0_00-<M0avg>  =        nan +-      nan  (0.001 < z < 0.014, N=175)
#  m0_01-<M0avg>  =        nan +-      nan  (0.014 < z < 0.027, N=274)
#  m0_02-<M0avg>  =        nan +-      nan  (0.027 < z < 0.042, N=173)
#  m0_03-<M0avg>  =        nan +-      nan  (0.042 < z < 0.058, N=77)
#  m0_04-<M0avg>  =        nan +-      nan  (0.058 < z < 0.075, N=42)

Thanks!
Dan

**Comment by RickKessler** [comment]
underlying problems was in function sigint_muresid_list();
covtotfloor = 0.1**2 was too large; reduced to 0.02**2.
