### ISSUE TITLE
Low uncertainties on SN z fit with prior

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#656]
Pathologies reproduced as discussed.

snlc_fit.exe $SNANA_DEBUG/rebeccachen/z_err.NML 

produces $SNANA_DEBUG/rebeccachen/z_err.FITRES.TEXT, which has multiple examples of high redshift and low redshift error (e.g. 263291, 10998)

**Comment by RickKessler** [comment]
try using SALT3.K21; seems to avoid crazy-small uncertainties. I will try hunting down the chi2-vs-zphot kink.
