### ISSUE TITLE
Is it possible to run AGN models with a HOSTLIB included? 

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#666]
_Directory:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/DEBUG_AGN

_Command:_
./DEBUG_AGN.sh

_Error Message:_

# ================================================ 
  PRE-ABORT DUMP from function read_gal_HOSTLIB : 
  HOSTLIB z-HEL range: 1000000000000000000.00000 - -1000000000000000000.00000 
  Gen     z-HEL range: -0.00200 - 0.00200 (GENRANGE_REDSHIFT +- 0.0020)
  Gen     z-CMB range: 0.00000 - 0.00000 (GENRANGE_REDSHIFT)

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by read_gal_HOSTLIB
   HOSTLIB z-HEL range does not contain user GENRANGE_REDSHIFT;
   See redshift ranges above.

**Comment by RickKessler** [comment]
Looks like I broke the AGN model back on June 23 2021 when I refactored the LCLIB parsing. It only broke for keys used by AGN, so the other models were OK.
