### ISSUE TITLE
WARP_SPECTRUM key

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#668]
Hi Rick, 

I wanted to understand how WARP_SPECTRUM key works but it doesn't seem to make any difference for me. Here is an example:
$SNANA_DEBUG/mdai/warpspec/gensims

each `.cmd` file generates one set of sim, the only difference is in the simlib file: 
for nowarp.cmd, no WARP_SPECTRUM in the simlib; for poly_const_slope.cmd: there is this line before each TAKE_SPECTRUM block `WARP_SPECTRUM:  LAMPOLY(1,1.0E-5)`; and for poly_vary_slope it's this line: `WARP_SPECTRUM:  LAMPOLY(1,-1.0E-5:1.0E-5)`

you can check the two figures I made for comparing one spectra from each sim (they share the same randseed) - they seem identical.

Could you help to check?
Thanks!

**Comment by RickKessler** [comment]
fixed sim to read WARP_SPECTRUM from SIMLIB
