### ISSUE TITLE
CUTWIN Not being used

### ISSUE THREAD

**Issue by djbrout** [RickKessler/SNANA#677]
I think it has something to do with trying to maximize the number of SNe that pass all fitopts, but in this case where Im running some systematics for Anthony, we want some SNe to be cut by the cutwin.

`/project2/rkessler/PRODUCTS/SNANA_DEBUG/djbrout/cutwin/RUNME`

CUTWIN VPECERR -1 999

is in the input file, but there are SNE that pass despite having VPECERRs of 10000000....

**Comment by RickKessler** [comment]
this command in RUNME disables all cuts:
   CUTWIN NONE
