### ISSUE TITLE
SIM_HOSTLIB(LOGMASS_TRUE) and SIM_HOSTLIB(LOG_SFR) are -9 for all events in fits output

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#679]
_Directory:_ /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/DEBUG_Ia

_Command:_ ./RUN_Ia.sh

_Notes:_  In debugging this I added a comment at line 1634 of sntools_dataformat_fits.c:

printf("xxx %s: ipar: %i igal: %i %s: %f\n", fnam, ipar, igal, SNDATA.SIM_HOSTLIB_KEYWORD[ipar], SNDATA.SIM_HOSTLIB_PARVAL[ipar][igal]);

This prints the correct values:

xxx wr_snfitsio_update_head: ipar: 0 igal: 0 SIM_HOSTLIB(LOGMASS_TRUE): 10.830850
xxx wr_snfitsio_update_head: ipar: 1 igal: 0 SIM_HOSTLIB(LOG_SFR): 0.207844

So I'm not sure where they're getting re-written. These values look good in text output:
SIM_HOSTLIB(LOGMASS_TRUE):                11.441 -9.000 
SIM_HOSTLIB(LOG_SFR):                     -0.331 -9.000

**Comment by RickKessler** [comment]
HOSTGAL_sSFR is an allowed data variable (along with HOSTLIB_LOGMASS), but it isn't yet determined by the simulation. I vaguely recall adding the HOSTGAL_sSFR variable as a placeholder in case we decided that we needed it. Your HOSTLIB uses LOG_SFR and it seems to be getting passed correctly to the output. If you want, we can teach the sim to recognize sSFR or SFR in the HOSTLIB and fill output HOSTGAL_sSFR with something meaningful.
