### ISSUE TITLE
Negative value in CSP filter transmission

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#682]
$SNDATA_ROOT/filters/PS1/Pantheon/CSP_Str11/r_texas_WLcorr_atm.txt has a negative value at wavelength = 7180. Not sure if this is intentional or not, but SALT2 doesn't like negative values in filters so thought I'd raise it.

**Comment by RickKessler** [comment]
In r_texas_WLcorr_atm.txt file,
fix this line
   7180.  -0.004337063     # bug found by G.Taylor
to be
   7180.  0.0
