### ISSUE TITLE
GENPERFECT = 6 removes host-galaxy information from output

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#685]
_Directory:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/DEBUG_IcBL

_Command:_
./DEBUG.sh

_Error:_
Currently debugging in text output. Output files show no host galaxy info: 

HOSTGAL_NMATCH:      1  
HOSTGAL_NMATCH2:     1  
HOSTGAL_OBJID:       9564082511  
HOSTGAL_FLAG:        0  
HOSTGAL_PHOTOZ:      -9.0000  +- -9.0000 
HOSTGAL_SPECZ:       -9.0000  +- -9.0000 
HOSTGAL_RA:          -999.000000    # deg 
HOSTGAL_DEC:         -999.000000    # deg 
HOSTGAL_SNSEP:       -9.000       # arcsec 
HOSTGAL_DDLR:        -9.000       # SNSEP/DLR  
HOSTGAL_CONFUSION:  -99.000

**Comment by RickKessler** [comment]
GENPERFECT mask 32 is now for disabling HOSTLIB.
