### ISSUE TITLE
sim spectra have shorter wavelength range than shown in the SIMLIB

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#695]
Not sure if this is a bug or it's something wrong with my inputs. In the SIMLIB there are wavelength ranges extends to >10000A, but the simulated spectrum only covers to ~9000. Why is the spectrum cut out in the redder part?

I put an example sim here: `$SNANA_DEBUG/mdai/take_spec/wave_cutout`

As an example, for SNID=16431, the SIMLIB shows:
```
LIBID:      136     # cadence from SNID=2005bo  min(MJD-PEAKMJD)= -0.5
RA:   192.421000        DEC:  -11.096500     MWEBV:  0.0400
NOBS:   54     PIXSIZE:  0.500     REDSHIFT:  0.01443     PEAKMJD: 53478.742
SUBSURVEY: CSP
TAKE_SPECTRUM:  TOBS(-0.5)   SNR(1138.3)   SNR_LAMOBS(3537.5:7357.8)
TAKE_SPECTRUM:  TOBS(21.5)   SNR(1264.5)   SNR_LAMOBS(3537.5:7357.8)
TAKE_SPECTRUM:  TOBS(26.5)   SNR(1378.5)   SNR_LAMOBS(3403.7:10346.8)
```
but the last spectrum is only simulated to wave=9214

**Comment by RickKessler** [comment]
I modified kcor program to extend stored wavelength range if there is a spectrograph that extends bluer/redder than the filters. Somebody needs to check that this fixes the problem with truncating simulated spectra.

**Comment by mi-dai** [comment]
Hi Rick,

This was tested but it didn't look like the problem was fixed. When rerunning the kcor.exe, the log says
```
Global wave range of all filters: 2950 to 9215 A 
 Global wave range of spectrograph: 2975 to 12564 A
 Final wavelength storage range: 2950 to 12564 A 
```
However the spectra is only extended to ~9400A. (see below)
![image](https://user-images.githubusercontent.com/17929627/141037751-6bb95402-f8df-481d-8095-953439aaa318.png)

**Comment by RickKessler** [comment]
in the kcor program I found another wavelength cut that I missed earlier, so it's fixed now. When writing sims in TEXT format, there is a new SPECTRUM_LAMRANGE key showing the wavelength range for each spectrum. These values are for visual inspection only and are not used for anything. 

The sim now generates spectra out to about 10,500 A, which is well below the 12,500 A range of the spectrograph. There is some improvement, but I will debug more later to track down the remaining wavelength clipping.

**Comment by RickKessler** [comment]
I think that the spectrum truncation is correct corresponds to the spectral range of the spectrum in the data. LIBID=1, for example, points to 2001v for spectral SNR:
TAKE_SPECTRUM:  TOBS(15.4)   SNR(4073.8)   SNR_LAMOBS(3352.6:10348.1)
TAKE_SPECTRUM:  TOBS(23.4)   SNR(12586.9)   SNR_LAMOBS(4402.1:6817.9)
TAKE_SPECTRUM:  TOBS(24.3)   SNR(5632.4)   SNR_LAMOBS(3352.6:10447.6)
TAKE_SPECTRUM:  TOBS(41.4)   SNR(11057.6)   SNR_LAMOBS(4402.1:6817.9)

and the SNR_LAMOBS ranges are indeed the simulated wavelength ranges.

**Comment by RickKessler** [comment]
I think this issue is resolved, but re-open if there are unexpected problems.
