### ISSUE TITLE
SN Ia run with HOSTLIB has HOSTGAL_LOGMASS=-9 entries in FITS output but not TEXT output

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#707]
_Directory:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/kessler/debug/AG_Ia

_Command:_
./LOGMASS_ISSUE.sh

_Notes:_
In all cases (FITS and TEXT output), the value in SIM_HOSTLIB(LOGMASS_TRUE) is correct. Only HOSTGAL_LOGMASS is affected. This may be connected to our earlier zbug session where we set LOGMASS_OBS = LOGMASS_TRUE, because in this case LOGMASS_ERR = -9.

**Comment by RickKessler** [comment]
beware of default DDLR<4 cuts. Can change cut with HOSTLIB_MAXDDLR key.

**Comment by RickKessler** [comment]
I found obsolete/relic sim code that always set the host galaxy mag regardless of DDLR match; I removed it and visually checked that HOSTGAL mags are 99 in FITS file when NMATCH=0.
