### ISSUE TITLE
SALT2beta NSTRINGMATCH problem

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#714]
Summary is here - 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/P21-SYS/1_SIM/SIMDES_4D_BS20-BEST/LOGS/FAIL_SUMMARY.LOG

 FATAL ERROR ABORT called by get_random_genPDF                                                                                                                                                            
   Found 2 PDF options for parName='SALT2BETA'                                                                                                                                                            
   Requires 1 PDF option; check AsymGauss and GENPDF_FILE.  

For the other GENPDF options, we made an exception that GENPDF would override the asymGauss, such as RV/AV. Can we do the same thing with beta?

**Comment by RickKessler** [comment]
I added SALT2ALPHA and SALT2BETA to function prioritize_genPDF_ASYMGAUSS().
Pushed to GitHub and Midway2.
