### ISSUE TITLE
SNANA cannot use FORMAT_MASK = 2

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#717]
Trying to write a couple of supernova to text file for SALT2 retraining, as that's all Georgie needs to do the retraining. 

Unfortunately, FORMAT_MASK=2 sets an error flag such as the following 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SALT2/1_SIM/SIMFOUNDBIG_4D_BS20-BEST/PIP_BP-SALT2_SIMFOUNDBIG_4D_BS20-BEST.LOG 

with root directory:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-SALT2

This seems intentional, as the flag occurs before SNANA submits any batch jobs at all

**Comment by RickKessler** [comment]
TEXT format is not allowed in batch mode. Can only write TEXT format using interactive
   snlc_sim.exe <inputFile>
