### ISSUE TITLE
rate of wrong hosts doesn't match expected rate (ie WRONGHOST_POLY)

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#719]
https://darkenergysurvey.slack.com/archives/C02FLLVLV54/p1636403073001100

**Comment by RickKessler** [comment]
For comma-sep list of polynomial coefficients, cannot have pad spaces. I fixed sim to abort:

 FATAL ERROR ABORT called by INIT_WRONGHOST
   Invalid input PROB_WRONGHOST_POLY: 0.01782801,
   pad spaces not allowed with commas.
