### ISSUE TITLE
SALT2mu nmax testing

### ISSUE THREAD

**Issue by pmacias** [RickKessler/SNANA#721]
Hi Rick,

We're not seeing nmax being taken into account in stage 6. To reproduce:

cd /scratch/midway2/rkessler/PIPPIN_OUTPUT/WFIRST_FOUND10_WIDE+DEEP/6_BIASCOR/BBC/output/SCRIPTS_BBCFIT
./test_nmax

Thanks!
-Phil

**Comment by RickKessler** [comment]
Problem is that you had set “CUTWIN NONE” which disables nmax.
