### ISSUE TITLE
Adjust host galaxy mags to SN redshift

### ISSUE THREAD

**Issue by RickKessler** [RickKessler/SNANA#732]

**Comment by RickKessler** [comment]
Done; but not yet tested.

**Comment by alexandergagliano** [comment]
Job run for SNe Ia, host apparent photometry reported at z~0.9 with HOSTGAL_MAG is identical to what's in the HOSTLIB (hasn't been shifted).
 
Directory: 
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/DEBUG_Ia

Command: 
./RICK_Ia.sh

Output:
more /global/cscratch1/sd/kessler/SNANA_LSST_SIM/TMP_rkes_MLAG_IDEAL_zALL_MODEL90_SNIa-SALT2/LSST_SN1079301.DAT

**Comment by RickKessler** [comment]
works with
    HOSTLIB_GALID_UNIQUE: 1
