### ISSUE TITLE
duplicate SIMGEN_INFILE_Ia key in sim_SNmix.pl input

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#74]
Hi Rick,
I was getting an error if I remove `SIMGEN_INFILE_Ia` key in the global parameter section in the sim input for `sim_SNmix.pl`. Since we are using multiple `GENVERSION`s and each has a different `SIMGEN_INFILE_Ia` key, it's a bit confusing to require this global `SIMGEN_INFILE_Ia`. (The outputs do seem to follow the individual `SIMGEN_INFILE_Ia` so the value of the global key doesn't seem to matter.)

**Comment by RickKessler** [comment]
Fixed. Please close this issue once fix is verified in pipeline.

**Comment by mi-dai** [comment]
tested and worked. thanks!

**Comment by mi-dai** [comment]
reopening this because similar error occurred again after updating and reinstalling SNANA. got a clearer error this time though: 
`FATAL ERROR ABORT : 
	  Must specify sim-input file for Ia and/or NON1A. 
	  Add 1 or more of the following keys in /home/midai/salt3_local/SALT3/examples/sim_lowzps1_pipeline/pipeline/MASTER_LOWZ_PS1.INPUT_114 : 
	   SIMGEN_INFILE_Ia: <inFile>  
	   SIMGEN_INFILE_SNIa: <inFile>  
	   SIMGEN_INFILE_NONIa: <inFile> `

**Comment by RickKessler** [comment]
cannot read because of 'permission denied'. Please fix your pipeline to ensure g+rw on all output files, and that all output files are under group pi-rkessler.

**Comment by mi-dai** [comment]
I put the input file here: `$WFIRST_ROOT/SALT3/examples/sim_lowzps1_pipeline/pipeline/MASTER_LOWZ_PS1.INPUT_114`

**Comment by RickKessler** [comment]
I cannot run your script (with NOSUBMIT argument) because files are either missing, or don't have read permission. Either fix the permissions, or copy all relevant input files to another directory.

sh: /home/midai/salt3_local/SALT3/examples/sim_lowzps1_pipeline/SIMLOGS_SIMULATEED_SPEC_SURVEY_DMS_114/Sim.DONE: Permission denied



   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT : 
	 Sim-input file 'simulation/lowz/SIMGEN_SALT3TEST.INPUT' does not exist; 
	 Check arguments of 'SIMGEN_INFILE_NONIa:' 
	 and 'SIMGEN_INFILE_Ia:' keys

**Comment by mi-dai** [comment]
oh sorry! I made a folder here: `$SNANA_DEBUG/mdai/issue74`

**Comment by RickKessler** [comment]
fixed again .. hopefully correct this time.
