### ISSUE TITLE
Prior on w in wfit

### ISSUE THREAD

**Issue by dscolnic** [RickKessler/SNANA#744]
Hi Rick et al. - could there be a prior on w in wfit? There can be a prior on Omm.  

Relatedly, is there a way to just do a simple LCDM (w=-1 fixed) fit in wfit?

Thanks,
Dan

**Comment by RickKessler** [comment]
wFit includes a Gaussian OM prior; e.g. 
   -ompri 0.31 -dompri 0.01
and also includes a flat w-prior with -wmin and -wmax. 
I will look into an LCDM fit with w  = -1

**Comment by RickKessler** [comment]
add -lcdm argument to fit for OM (with w=-1)
