### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#748]
I am running DDF and WFD simulations for the PLAsTiCC cadence and Baseline v2.0 cadence.

When I run `submit_batch_jobs.sh <INPUT_FILE> --check_abort` I only get errors resulting from creating zero events, which I expect.

For the Baseline v2.0 cadence I am using the files `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMGEN_MASTER_LSST_DDF.INPUT` and `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMGEN_MASTER_LSST_WFD.INPUT`. The simulations run successfully for DDF but I obtain the following error for WFD:
```
  ######################################################## 
     INIT_SNVAR: Init variables.
  ######################################################## 
  
   Allocate 12.50 MB for CIDMASK array (to check duplicates)
   HOST MACHINE = x86_64-conda_cos6-linux-gnu   (x86_64-suse-linux)
   SNDATA_ROOT = /global/cfs/cdirs/lsst/groups/SN/snana/SNDATA_ROOT
   SNANA_DIR = /global/cfs/cdirs/lsst/groups/SN/snana/SNANA    (v11_04d)
   sizeof(INPUTS) =   1.641 MB 
   sizeof(GENLC)  =   7.819 MB 

  init_SNDATA_GLOBAL: 
 --------------------------------------------------------
  Initialize NstringMatch for sim-input file
  Read user input file 1: SIMGEN_TEMPLATE_LSST.INPUT 
 --------------------------------------------------------
  Initialize NstringMatch for sim-input file
  Read user input file 2: /global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/ELASTICC/model_config/SI
MGEN_INCLUDE_SNII-NMF.INPUT 

# ================================================ 
  PRE-ABORT DUMP from function find_pathfile : 
   Called by function prep_user_input 
   File not in path: /global/u1/c/catarina/simulations/baseline_v2.0_10yrs 
   File not in path: /global/cfs/cdirs/lsst/groups/SN/snana/SNDATA_ROOT/kcor 

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by find_pathfile
   Could not find file in paths listed above:
   fileName = NONE
```
The logs for this WFD run are in `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMLOGS_CSA_LSST_WFD_fast`.

A similar thing happens when I run the file `/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/ELASTICC/survey_config/SIMGEN_MASTER_LSST_WFD_to_test.INPUT`. The logs are in `/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/ELASTICC/survey_config/SIMLOGS_ELASTICC_TEST01_LSST_WFD_that_failed`. In this case the fail does not refer to SNII-NMF but rather to SNIa91bg.

**Comment by RickKessler** [comment]
the FAIL_REPEAT script works, so my suspicion is that the file system briefly disappeared/hung when the job ran. Unfortunately need to re-run to include this model ... or we can start testing with this one model missing.
