### ISSUE TITLE
added NSPLITRAN param causes fatal error

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#75]
Hi Rick,

Adding NSPLITRAN=50 to my salt2mu.input file seems to have caused fatal errors in the BIASCOR stage. The relevant commands and files can be found in `$SNANA_DEBUG/helen`. 

Thanks for your help!

**Comment by RickKessler** [comment]
scroll down thru $SNANA_DIR/util/SALT2mu_fit.pl and read the NSPLITRAN instructions. It does not use INPDIR, and instead it uses file= argument. Above input has file=none, which won't work.

**Comment by djbrout** [comment]
So then is it possible that we can get this to play nice with Pippin?
Currently pippin only uses INPDIR as far as I'm aware.

**Comment by RickKessler** [comment]
still low on priority list, gonna close this now. Can re-open later if needed.
