### ISSUE TITLE
What is the flux unit of "snflux_1a_Nugent2002.dat" spectrum file from SNDATA_ROOT

### ISSUE THREAD

**Issue by liuchengqi** [RickKessler/SNANA#753]
SNANA is a amazing Software package for SNe analysis. I am sorry to bother you, but I have a problem about the SNDATA_ROOT. I downloaded the SNDATA_ROOT from the website you provide. In the SNDATA_ROOT, I find a folder called "snsed", there are three spectrum files of SNe called "snflux_1a_Nugent2002.dat", "snflux_1a_Riess.dat" and "Hsiao07.extrap.dat", respectively.  I opened these three spectrum files, but it only contains data, there are no any explanation about the data, I even do not know the flux unit. So I want know whether the spectrum have been converted to the rest frame 10 pc away and what is the flux unit of these three spectrum files?  if it is not in the rest frame 10 pc away, how can I use these three spectrum files in my own code?  I am very looking forward to your reply.  Thanks very much!
<img width="132" alt="ad1f815fcc73be663e2ac9cd1524dd7" src="https://user-images.githubusercontent.com/56668397/144086448-d471a2dd-4a09-4531-bb42-2e165ef63878.png">

**Comment by RickKessler** [comment]
those SN SEDs are some of the oldest files in SNANA environment, and thus not documented. I just added a DOCUMENTATION.README file for next public SNDATA_ROOT update:

DOCUMENTATION:
  PURPOSE: SN SED time series for k-corrections and template-matching codes
  REF:
  - AUTHOR:  E. Hsiao et al, 2007 (Hsiao SN templates)
    ADS:     https://ui.adsabs.harvard.edu/abs/2007ApJ...663.1187H
  - AUTHOR:  Nugent, Kim, Perlmutter,  2002 (SNIa Kcor and extinction)
    ADS:     https://ui.adsabs.harvard.edu/abs/2002PASP..114..803N  
  NOTES:
  - sed format is    epoch(day)  lambda(A)  flux(erg/s/cm^2/A)
  - NON1A directory is obsolete; use $SNDATA_ROOT/models/NON1ASED

DOCUMENTATION_END:

**Comment by liuchengqi** [comment]
I see, Thanks a lot!
