### ISSUE TITLE
snlc_fit.exe is either not reading or cutting all of the SN

### ISSUE THREAD

**Issue by Nora-n** [RickKessler/SNANA#757]
Hi Rick,

Mat and me have run into something in SNANA that we don't understand: snlc_fit.exe is either not reading or cutting all of the SN in one of our simulations, and we have no idea why.

The log is here: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/NN_FULL_SK/2_LCFIT/SDSSFIT_SDSS_DATA/output/SPLIT_JOBS_LCFIT/PIP_NN_FULL_SK_SDSS_DATA_FITOPT000_SPLIT099.LOG (line 276)`.

The error:
```
Found      0 SN Candidates to Process
```

But the simulation in `/scratch/midway2/rkessler/PIPPIN_OUTPUT/NN_FULL_SK/1_SIM/SDSS_DATA/PIP_NN_FULL_SK_SDSS_DATA` has 4391 objects in it... Any idea what would cause this / how best to debug it?

Thanks,
Nora

**Comment by RickKessler** [comment]
Your sim data files are empty; e.g., try
   fv PIP_NN_FULL_SK_SDSS_DATA_SNIaMODEL0-0001_HEAD.FITS.gz 
Not sure why the output sim data is corrupted, but a common cause it two pippin jobs running simultaneously.

**Comment by Nora-n** [comment]
Thanks, that might have been the case indeed.
