### ISSUE TITLE
fieldlist

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#764]
I was trying to use the fieldlist option in BBC
When I run it on DES sample only and set fieldlist to:
```
  - '/deep_only/ fieldlist=3'
  - '/shallow_only/ fieldlist=X1,X2,C1,C2,E1,E2,S1,S2,S1+S2,E1+E2,C1+C2,X1+X2'
```

everything work fine (see example `REALDATA_testfields_DESONLY.input` in `$SNANA_DEBUG/mvincenzi/field_list`)

But when I combine DES + Lowz + Foundation, BBC is crashing.
For the Lowz and Foundation samples, we don't have info about the field and the FIELD column is just VOID.
So I changed the fieldlist to:

```
 - '/deep_only/ fieldlist=3,VOID'
  - '/shallow_only/ fieldlist=X1,X2,C1,C2,E1,E2,S1,S2,S1+S2,E1+E2,C1+C2,X1+X2,VOID'
```
but this doesn't seem to work (see example `REALDATA_testfields.input` in `$SNANA_DEBUG/mvincenzi/field_list`)

How can I fix this?
You can run the test in $SNANA_DEBUG/mvincen
Thanks!
Maria

**Comment by maria-vincenzi** [comment]
Somewhat related question, is there a way to run biascor for DES-SHALLOW and DES-DEEP separately (as we do for LOWz and Foundation for example) as if SHALLOW/DEEP were "independent" surveys?

**Comment by RickKessler** [comment]
I ran a FAIL_REPEAT script and it worked, so I suspect that 2GB  default  memory isn't enough. Try doubling it.

Here are examples for defining biasCor by FIELD group:
fieldGroup_biascor='shallow,medium,deep'             ! for biasCor & CCprior
fieldGroup_biascor='C3+X3,X1+E1+S1,C2,X2+E2+S2+C2'

BiasCor is automatically applied by survey.

**Comment by maria-vincenzi** [comment]
ok great. yes the command 
```
 - '/deep_only/ fieldlist=3'
  - '/shallow_only/ fieldlist=X1,X2,C1,C2,E1,E2,S1,S2,S1+S2,E1+E2,C1+C2,X1+X2'

```
works when I increase the batch memory.

However, the command:
```
fieldGroup_biascor=X3+C3,X1+X2+S1+S2+E1+E2+C1+C2
```
crashes with the error:
```
 FATAL ERROR ABORT called by override_parFile
   Invalid command-line override:
   fieldGroup_biascor=X3+C3,X1+X2+S1+S2+E1+E2+C1+C2
```
which is a bit puzzling.

Also, in DES some SNe occur between two fields. 
Let's say I have a SN in the field X1+X3 and I set the option `fieldGroup_biascor=X3+C3,X1+X2+S1+S2+E1+E2+C1+C2`, which fieldGroup will the SN be assigned to? A SN with field X1+X3 will have a partial match to both the first group of fields (X3+C3) and the second group of fields (X1+X2+S1+S2...).

Thanks!

**Comment by RickKessler** [comment]
Fixed silly case-parsing bug. The internal variable name is fieldGroup_biascor, but the code was parsing fieldgroup_biascor. Fixed code to accept either fieldGroup_biascor or fieldgroup_biascor (but not tested).

**Comment by RickKessler** [comment]
fieldgroup_biascor is ill-defined for field-overlaps. It uses FIELD column in the FITRES file produced by LCFIT, which is a list of all field overlaps separated by plus sign. So check for entries such as X1+X3 in FIELD column. Since fieldGroup requires only a partial match, it probably matches to first (or last?) field group with a match and thus might depend on the order of entries in fieldgroup_biascor. To see the fieldGroup associations for overlaps, check IDSAMPLE in the BBC output. Also note that this arbitrary assignment, good or bad, should be the same for data and biasCor sim.

**Comment by maria-vincenzi** [comment]
I tried MUOPTS:
  MUOPT:
```
  - '/deep_only/ fieldlist=3'
  - '/shallow_only/ fieldlist=X1,X2,C1,C2,E1,E2,S1,S2,S1+S2,E1+E2,C1+C2,X1+X2'
  - '/separate_biascor/ fieldGroup_biascor=X3+C3,X1+X2+S1+S2+E1+E2+C1+C2'

```
First and second run smoothly.
Third option I got the ABORT message:
```
  ABORT_MESSAGES:
  - FATAL ERROR ABORT called by sort_IDSAMPLE_biasCor
  - IDSAMPLE=1(DES(X1+X2+S1+S2+E1+E2+C1+C2)) copied 2 times.
  - but should be copied once (NSAMPLE=4, NSORT=6)

```
but I'm not sure what this means.
Thanks!

**Comment by maria-vincenzi** [comment]
In folder /project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/field_list/output_MARIATEST/SCRIPTS_BBCFIT
run ./test

and this is the error:
```
 ****************************************************************** 
   Begin prepare_IDSAMPLE_biasCor  

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by sort_IDSAMPLE_biasCor
   IDSAMPLE=1(DES(X1+X2+S1+S2+E1+E2+C1+C2)) copied 2 times.
   but should be copied once (NSAMPLE=4, NSORT=6)

```

**Comment by RickKessler** [comment]
These two inputs were causing DES to be double-counted:
  fieldGroup_biascor=X3+C3,X1+X2+S1+S2+E1+E2+C1+C2
surveygroup_biascor='CFA3S+CFA3K+CSP(zbin=0.02),FOUN(zbin=0.D02),DES(zbin=0.05)' 

I fixed SALT2mu to allow DES in both, and checked that it runs.

**Comment by maria-vincenzi** [comment]
ok! rerun my test and this seem to be solved. Happy to close the issue!
