### ISSUE TITLE
unrecognized DATATYPE

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#765]
Hi Rick,

Could you check out the following error?
```
cd /project2/rkessler/PRODUCTS/SNANA_DEBUG/djones/datatype
snlc_fit.exe REFAC_CSP_RAISIN_optical_sys.nml
```

gives
```
 FATAL ERROR ABORT called by RDGLOBAL
   Unrecognized DATATYPE =
   Check DATATYPE key in FITS header.
```

Thanks!

**Comment by RickKessler** [comment]
for now, add
FAKE: 0      # 0 -> real data 

to header, and later I will fix the TEXT reader to read the DATATYPE key. 
Also need to put in the right value for NOBS.
