### ISSUE TITLE
+HOSTNBR segfaults

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#767]
https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1641333307001700

**Comment by RickKessler** [comment]
fixed recent refactor bug. However, job aborts because a LOGMASS value is outside the WGTMAP range. For +HOSTNBR, there is no need to WGTMAP.

**Comment by helenqu** [comment]
removed WGTMAP input key and the script completes successfully but I couldn't find a new hostlib with neighbors that the script should have generated. the output directory is `/scratch/midway2/rkessler/SNDATA_ROOT/SIM/TEST_HOSTNBR` and the hostlib I used is `/project2/rkessler/SURVEYS/DES/USERS/mvincenzi/MYPIPPIN/sims_instrument/DES_SVA2+LOGMASS_LOGSFR_Sullivan10.HOSTLIB`.

**Comment by RickKessler** [comment]
there was a subtle bug regarding position of +HOSTNBR arg w.r.t other args. If +HOSTNBR appeared after HOSTLIB_MSKOPT, it worked; if +HOSTNBR came before, then HOSTLIB_MSKOPT erased the HOSTNBR option. Code fixed so that order doesn't matter.
