### ISSUE TITLE
Help with CrazyFlux Abort

### ISSUE THREAD

**Issue by nfshermy** [RickKessler/SNANA#770]
Hi!

We are running simulations for newly minted BBH models for DESGW analysis and are unfortunately triggering the crazyFlux error: 

```

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by check_crazyFlux
   flux=6.342102e+07 exceeds CRAZYFLUX=2.082852e+07
   See dumpEpoch details


```
We are struggling to winnow our models to circumvent this error, but cannot figure out how to move from integrating the model fluxes over wavelength (final units ergs/cm/cm/s) to what we believe SNANA's crazyFlux units are (ADU).

What is the best method of negotiating crazyFlux in this context and curating our models to work?

Many thanks!

**Comment by RickKessler** [comment]
Where is the sim-input and stdout file so that I can see more information? Usually this error is from a problem with the model since the crazyFlux setting  is much much brighter than SNIa.

**Comment by nfshermy** [comment]
Thanks a lot for your help! Please let me know anything else I can provide.

The sim-input: `/data/des40.a/data/nsherman/DESFollowup_Testing/DES_Followups_w_Tristan/templates/SIMGEN_DES_BBH.input`
The stdout file: `/data/des40.a/data/nsherman/DESFollowup_Testing/DES_Followups_w_Tristan/events/GW200224/logs/sim_tr_bbh.log`

**Comment by RickKessler** [comment]
Here is the full ABORT dumb that includes the pre-abort dump. 
At z=0.27 the model mag is 12.9, about 8 mag brighter than SNIa.
I suspect a model-normalization issue.

<img width="834" alt="simLog" src="https://user-images.githubusercontent.com/24592476/149014564-08881f8b-99b5-4124-af6a-68ae4da63208.png">
