### ISSUE TITLE
FATAL ERROR ABORT called by gen_random_coord_shift

### ISSUE THREAD

**Issue by alexandergagliano** [RickKessler/SNANA#775]
_Run Directory:_
/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/ROOT/PLASTICC_DEV/survey_config/DEBUG_II

_Command:_
./SNII_TEST.sh

_Description:_
Simulation with option MXRADIUS_RANDOM_SHIFT: 0.25 runs successfully when simulating 500 transients but fails at 1000 with the following abort message: 

  PRE-ABORT DUMP from function gen_random_coord_shift : 
 CID = 1008914 
 Original RA,DEC = 297.203, -57.209 deg 
 random phi    = 3.904942 radians
 random radius = 0.221125 degrees 
 shift(RA,DEC) = -0.295007, -0.152874 
 actual ANGSEP = 0.220886 
 ANGSEP(actual)/ANGSEP(expect) = 9.989173e-01 
 ANGSEP(actual)-ANGSEP(expect) = -8.618482e-01 arcSec

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by gen_random_coord_shift
   Problem with random coord shift.
   See preAbort info above.

**Comment by RickKessler** [comment]
changes angle-ratio tolerance to 10'' tolerance on actual-true separation. The RA and DEC-shift computation is an approximation resulting in sub-arcsecond differences.
