### ISSUE TITLE
Wacky gamma issues 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#78]
Don't know what to title this.

So, within /project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie/

I've run the file "SIMGEN_SNIa+C11.INPUT" twice, once with HOSTLIB_MSKOPT: 322 and once with HOSTLIB_MSKOPT: 326. 

The results are output as text files in 

/project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/BP_Testing_C11         (MSKOPT 326)
/project2/rkessler/PRODUCTS/SNDATA_ROOT/SIM/BP_Testing_C11-N    (MSKOPT 322)

Looking at the SN000001.DAT in both directories, 

BP_Testing_C11-N_SN000001.DAT has "SIM_SALT2gammaDM: -0.920"
BP_Testing_C11_SN000001.DAT has "SIM_SALT2gammaDM: 0.025" 

So this -0.920 is pretty unreasonable and is likely a glitch!

**Comment by RickKessler** [comment]
nasty "forgot to init" bug during recent refactor and update of adding x1 & c into weight map. Fixed.
