### ISSUE TITLE
Fatal abort on NstringMatch

### ISSUE THREAD

**Issue by Nora-n** [RickKessler/SNANA#783]
Hi Rick,

I have a simulation that ran correctly at the start of January (7th) and that I moved locally. I now want to relaunch it but got this error for all the `1_SIM` tasks I tried:

> FATAL ERROR ABORT called by checkStringUnique
>   2  'GENTYPE:' keys exceeds limit=1 in sim-input file.
>   Calling function is NstringMatch .

Directory is `$PIPPIN_OUTPUT/NN_FULL_SK/`, and this specific log file is from `$PIPPIN_OUTPUT/NN_FULL_SK/1_SIM/LOWZ_DATA-SK/LOGS/SIMnorm_PIP_NN_FULL_SK_LOWZ_DATA-SK_SNIaMODEL0.LOG`. Apparently, the `NstringMatch` function would fail when reading the different `.input` files, while they are the same on my local folder and on Midway. I saw that an update to SNANA was made on the 15th, that might have to do with this?

Thanks in advance,
Nora

**Comment by RickKessler** [comment]
See this recent code update:
   https://github.com/RickKessler/SNANA/issues/781

There are two GENTYPE keys in your sim-input files, so one of these keys has to be removed.
