### ISSUE TITLE
Galaxy (Sersic) profile NOT defined 

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#788]
I ran DDF simulations with `SMEARFLAG_ZEROPT 3` and the same hoslib information as PLAsTiCC but that provided an error:
```
  ABORT_MESSAGES: 
  - FATAL ERROR ABORT called by init_GALMAG_HOSTLIB 
  - Galaxy (Sersic) profile NOT defined 
  - ==> cannot compute galaxy mag at SN position.
```
I then successfully reran the simulations with `SMEARFLAG_ZEROPT 1`. Does `SMEARFLAG_ZEROPT 3` only work with the new host galaxies?

The failed attempt is `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMGEN_TEMPLATE_LSST_fail.INPUT`, whose logs are in `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMLOGS_CSA_LSST_DDF_fail`.

The successful attempt (`SMEARFLAG_ZEROPT 1`) is `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMGEN_TEMPLATE_LSST.INPUT`, whose logs are in `/global/homes/c/catarina/simulations/baseline_v2.0_10yrs/SIMLOGS_CSA_LSST_DDF`.

**Comment by RickKessler** [comment]
The abort is related to 
HOSTLIB_MSKOPT:  258  # 2=noise + 256=verbose
This option requests Poisson noise from the host, but there is no Sersic profile in the HOSTLIB needed to compute Poisson noise.
