### ISSUE TITLE
Error fitting Plasticc light curves 

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#790]
I got an error like below. Error can be reproduced by running the following:
```
cd $SNANA_DEBUG/mdai/plasticc
./FAIL_REPEAT_LSST_DDF_MODEL90_FITOPT000_SPLIT001.CMD
```

```

   `|```````|`    
   <| o\ /o |>    
    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by copy_SNDATA_HEAD
   Unknown key = LCLIB(tau) (copyFlag=-1)
   stringVal='NOTSET'  parVal=-999.000000
```

**Comment by RickKessler** [comment]
Original PLASTICC data used LCLIB(name) key, but later it was changed to LCLIB_PARAM(name) ... code fixed to check both keys. Your job above runs now, but zero events pass cuts ?

**Comment by mi-dai** [comment]
It looks like there is a version of LSST_DDF_MODEL90 in this folder /project2/rkessler/SURVEYS/LSST/SIM/LSST_DDF_MODEL90, which I thought was the plasticc data, but turns out to have only 10ish light curves in it. I was trying to set PRIVATE_DATA_PATH to point to my version of plasticc data but it complained there were two versions with the same version name. How can I tell SNANA to ignore the wrong folder above?
