### ISSUE TITLE
propagating sSFR info into simulated data files

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#797]
My hostlib has the following columns: 
`VARNAMES: GALID GALID2 RA DEC ZTRUE ZERR u_obs g_obs r_obs i_obs z_obs n0_Sersic a0_Sersic b0_Sersic a_rot ZPHOTFLAG LOGMASS LOGMASS_ERR LOG_SFR LOG_SFR_ERR SNMAGSHIFT LOG_sSFR obs_gr
`
When I run a simulation, the info that is propagated is HOST_LOGMASS (and I usually scale HOST_LOGAMSS_ERR to 0., so that the LOGMASS values are propagated ex
actly as they are reported in the HOSTLIB). The info about `LOG_sSFR` is not propagated and in the HEAD.FITS files the columns related to `HOST_sSFR `is always -99.

Is there a way to propagate the info about sSFR as well?

**Comment by RickKessler** [comment]
Try adding
  HOSTLIB_STOREPAR: LOG_SFR,LOG_sSFR

**Comment by maria-vincenzi** [comment]
This worked and added these columns in the HEAD:` 'SIM_HOSTLIB_GALID', 'SIM_HOSTLIB(LOG_SFR)', 'SIM_HOSTLIB(LOG_sSFR)',  'SIM_HOSTLIB(r_obs)'`!

However, the info is not propagated to the fitres when I run a fit file (I tried running the fit with the option `SNTABLE_LIST = 'FITRES(text:host)'`, but it only added the column SIM_HOSTLIB_GALID).
How can I fix this?
Also, I noticed that the `HOST_MAG_r` in the HEAD is not the same as `SIM_HOSTLIB(r_obs)`, what are the differences between the two?

**Comment by maria-vincenzi** [comment]
Hello!
I created a folder in here `$SNANA_DEBUG/mvincenzi/HOST_INFO_propagation.`
There are two sub-folders:
1) a `sim` sub-folder: where I generate a small DES-like simulation using a HOSTLIB that has LOGMASS, LOG_sSFR and UR info.
2) a `fit` sub-folder: where I perform a SALT2 fit of the small DES-like simulation and of real data.

For both simulations and data, I'd like the info about LOG_MASS, LOG_sSFR and UR to be propagated into the FITRES file.
Let me know how I can help!
Maria

**Comment by RickKessler** [comment]
Done, and see explanation in new manual section
    4.22.2 Hostgal properties
