### ISSUE TITLE
Alpha/Beta grid in biascor

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#80]
Hi!

Normally, we get around needing an alpha/beta grid by using opt_biascor=1 in our SALT2mu input files.

But what if we want z/x1/c/mass corrections, but no alpha/beta? Unfortunately, SALT2mu breaks.

Try running SALT2mu.exe on both the files in this directory. 
/project2/rkessler/PRODUCTS/SNANA_DEBUG/Brodie

Ideally, we want to do a 6D-type analysis, but hold alpha/beta fixed while still bias-correcting c/x1/z/mass.

**Comment by bap37** [comment]
Also: we're having some issues with opt_biascor values. Try out running 
opt_biascor=128 
opt_biascor=224

Both of those ^ should crash, whereas

opt_biascor=225 
should work. That seems to indicate that 5D is the issue, and that opt_biascor=64 is maybe not defined?

**Comment by RickKessler** [comment]
problem was DES and LOWZ ranges for alpha were different. Added abort trap in SALT2mu to make more clear error message.
