### ISSUE TITLE
Trouble with Creating Binary Files

### ISSUE THREAD

**Issue by nfshermy** [RickKessler/SNANA#803]
Hello! I am attempting to run `snlc_sim.exe` for 2000 SEDs and aiming to create binary files to speed up the process later on. 

`snlc_sim.exe` runs without trouble when I have ```SIMSED_USE_BINARY: 0``` but breaks with 
```
   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by rd_sedFlux
   day_last = 0.000000   but day=-1.950000
   New day must increment.
```
when I set  ```SIMSED_USE_BINARY: 1``` and set `SIMSED_PATH_BINARY`. Since I have run with these models before (not creating binary files), I am pretty confident that nothing in them is out of order. 

Path to input file `/data/des40.a/data/nsherman/DESFollowup_Testing/DES_Followups_w_Tristan/events/GW200224/SIMGEN_DES_BBH.input`

**Comment by RickKessler** [comment]
every SED file has the following in 1st line:
"# DAY" WAVELENGTH FLUX

try remove the double quotes so that # is first character of line.

**Comment by nfshermy** [comment]
Thank you!
