### ISSUE TITLE
BBC4D unable to fix beta variable for fitting 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#808]
Within /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/ANALYSIS

I want to fix beta (u2=0) and run a 4D fit. I have made a script here - /project2/rkessler/SURVEYS/SDSS/USERS/BAP37/BS20-PHOT/ANALYSIS/UNBINNED

that should do that very thing. Unfortunately, when I attempt it, I get the following error:

```
		 Global Alpha,Beta Binning
  setup_BININFO_biasCor: define  1 SIM_alpha bins from  0.167 to  0.167


 FATAL ERROR ABORT called by get_BININFO_biasCor_abg
   194708 SIM_beta values exceeds bound of 2
   Check biasCor sample.
```

I think SNANA should be skipping this step, or at least avoiding this error if I'm fixing beta

**Comment by RickKessler** [comment]
fixed to avoid abort when u2=0.
