### ISSUE TITLE
interp_GRIDMAP error with new deep hostlib

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#821]
https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1645112935298619

**Comment by RickKessler** [comment]
The real problem is a galaxy with a0_Sersic=0 and b0_sersic=0, leading to NaN for local SB. I updated the sim to abort on zero profile size as shown here for the above example:

 FATAL ERROR ABORT called by get_Sersic_info
   Profile size is zero for GALID=698370266
   Check Sersic params.
