### ISSUE TITLE
SALT.INFO file: remove filter mapping in MAGSHIFT/WAVESHIFT

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#822]
When MAGSHIFT and WAVESHIFT are applied, remove the filter-mapping and keep only SURVEY-filter_name (currently this is SURVEY-filter_name/mapped_filter_name)

**Comment by RickKessler** [comment]
released. Legacy code can be invoked with 
   snlc_fit.exe <input_file> DEBUG_FLAG  -4077
(arXiv number for pantheon+)
