### ISSUE TITLE
segmentation fault in SUBPROCESS

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#829]
Trying to include a Ia file and a CC prior in the SALT2mu SUBPROCESS, uh, process. Unfortunately, looks like doing this causes a segmentation fault.

Made a script to reproduce the error here: 

/project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/D2D_SIM_CC/RUNTEST_SUBPROCESS_DATA

Which points to SALT2mu_ALL_DATA.input. 

When "file" key in SALT2mu only points to 1 file, it runs fine! But I have successfully pointed the "file" key at multiple files before, so not sure what's happening.

**Comment by RickKessler** [comment]
increased size of DROPLIST array to fix memory overwrite bug.
