### ISSUE TITLE
BBC requires 2 gammaDM bins

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#83]
Hey Rick! Setting this up as a persistent reminder. With the new 4D method, we'd like to bias correct for z/x1/c/mass bins. Unfortunately, the current coding is such that if we have two mass bins, we also need two gammaDM bins. We'd like to be able to set gammaDM=0, so this is presently a problem.

The files have been set up in $SNANA_DEBUG/Brodie/

already! 

Thank you!

**Comment by RickKessler** [comment]
I think the biasCor sample is too small. If problem persists with much larger biasCor, re-open this issue.
