### ISSUE TITLE
Create the kcor file

### ISSUE THREAD

**Issue by liuchengqi** [RickKessler/SNANA#836]
When i try to write my own kcor_PS1.input file:

SURVEY:  PS1MD
MAGSYSTEM: AB
FILTSYSTEM: COUNT
FILTPATH: $SNDATA_ROOT/filters/PS1/Pantheon/PS1
FILTER: PS1-g g_filt_tonry.txt 0.0
FILTER: PS1-r r_filt_tonry.txt 0.0
FILTER: PS1-i i_filt_tonry.txt 0.0
FILTER: PS1-z z_filt_tonry.txt 0.0
FILTER: PS1-y y_filt_tonry.txt 0.0
OUTFILE: kcor_PS1.fits

then i run kcor.exe kcor_PS1.input, but the error appears:
![image](https://user-images.githubusercontent.com/56668397/156332806-f4f604dc-0b24-4c44-9a30-2dc06d688c35.png)

I have added the SURVEY, but i don't known what's the "Must associate SURVEY with filter PS1-g" means? 
Extremely grateful！！！

**Comment by RickKessler** [comment]
SURVEY key goes after MAGSYSTEM key, otherwise SURVEY is ignored and results in abort.

**Comment by liuchengqi** [comment]
That's works, Thanks!
