### ISSUE TITLE
segfault with DEEP_X3_looser_v2 hostlib + new sersic fits

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#837]
https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1646239130242569

**Comment by helenqu** [comment]
the new a0 values go up to >800 arcsec whereas the original hostlib only had a0 up to ~30 arcsec. do you think this could possibly be the reason for the crash?

**Comment by RickKessler** [comment]
max service index is now increased to 11 (was 8). Also fixed memory overwrite bug that caused crash instead of abort.
