### ISSUE TITLE
Co-add non consecutive observations in same filter

### ISSUE THREAD

**Issue by Catarina-Alves** [RickKessler/SNANA#838]
The desired behaviour of the function `simlib_coadd.exe` is to combine observations within 0.4 days into a single co-added observation for each passband. At the moment, this only works if the observations in the same passband are consecutive. 

It would be great if the function `simlib_coadd.exe` also worked for non-consecutive observations, or at least to have a setting to choose what we wanted to do (I can imagine wanting non-consecutive observations to be separate for analysing fast transients).

**Comment by Catarina-Alves** [comment]
Here is the full DDF simlib file zipped: [baseline_v2.0_10yrs_DDF_before_COADD.simlib.zip](https://github.com/RickKessler/SNANA/files/8193444/baseline_v2.0_10yrs_DDF_before_COADD.simlib.zip). You can also find this file on Cori at `/global/cfs/cdirs/lsst/groups/SN/snana/SURVEYS/LSST/USERS/SIMLIB_DEV/baseline_v2.0_10yrs_DDF_before_COADD.simlib`

**Comment by RickKessler** [comment]
Try new option
   simlib_coadd.exe <simlib> SORT_BAND

on Midway or Cori. The LSST-DDF test shows very small differences for <10% of rows; 1E-4 change in MJD or PSF. These small changes are likely due to replacing old float variables with double as part of refactor.

**Comment by Catarina-Alves** [comment]
I used this setting to generate a new coadded simlib, make light curves and verified that it also works for non-consecutive observations. I am happy this issue is solved.
