### ISSUE TITLE
stack smashing

### ISSUE THREAD

**Issue by liuchengqi** [RickKessler/SNANA#840]
I have followed the manual in Chapter 4.2 Getting Started Quickly. 
I did the command in my computer:
 > cd $SNDATA_ROOT/sample_input_files/SALT2
then:
>  snlc_sim.exe sim_SDSS.input
the error appears like:
![image](https://user-images.githubusercontent.com/56668397/156556375-0d66c71e-8e37-4674-a79e-3e88b7c573e0.png)

I also have tried snlc_sim.exe sim_DES.input,  sim_HST.input ,and  sim_SNLS.input, all have appeared the same errors except the  snlc_sim.exe sim_SNLS.input.

I want to know what's going on? why stack smashing always appears?  Thanks!

**Comment by RickKessler** [comment]
If this error is on your laptop, I cannot help. I ran the same command on our computing cluster and it works.

**Comment by liuchengqi** [comment]
In the sim_SDSS.input file, if I add a note before SIMGEN_DUMP:  4  ZCMB  PEAKMJD SALT2c SALT2x1 like:
![image](https://user-images.githubusercontent.com/56668397/156885590-cbcf4738-2e92-4002-bd7a-28951a614506.png)

then snlc_sim.exe sim_SDSS.input works.

I am a newer in SNANA, I also have read the manual, but I still don't know why the SIMGEN_DUMP can cause stack smashing.
![image](https://user-images.githubusercontent.com/56668397/156885823-20cd1e45-2665-4752-b12a-bc27a6920666.png)
