### ISSUE TITLE
Need to add new variables to SUBPROCESS_OUTPUT_TABLE

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#841]
Starting to adapt Dust2Dust for sSFR and U-R, but we need to add those options as output for the SUBPROCESS_OUTPUT_TABLE. I believe that only HOST_LOGMASS works right now. 

Can reproduce the error using the following command: 
/project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/DUST2DUST/RUNTEST_SUBPROCESS_SIM

**Comment by RickKessler** [comment]
I ran above script and didn't see an error. And please prepare biasCor sample that is x10 smaller using sntable_cat.py

**Comment by bap37** [comment]
SUBPROCESS pipes errors to STDOUT files, the associated one for the script is found here
 
 /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/DUST2DUST/parallel/299_SUBPROCESS_LOG_SIM.STDOUT
 
 ```    | ' ; ' |     
    |  ___  |     ABORT program on Fatal Error. 
    | |' '| |     
    | `---' |     
    \_______/    

 FATAL ERROR ABORT called by SUBPROCESS_STORE_BININFO
   Unknown output table var = 'HOST_COLOR'
   Check SUBPROCESS_OUTPUT_TABLE args
```

**Comment by RickKessler** [comment]
Fixed so that it runs, but need to check the subprocess code does something sensible.

**Comment by bap37** [comment]
Further discussion and some fixes means it's working now
