### ISSUE TITLE
input files for SALT2mu

### ISSUE THREAD

**Issue by fhenryco** [RickKessler/SNANA#846]
Dear,
I'd like to reproduce the Pantheon analysis (and plan to do the same for the Pantheon+ analysis when all data is released: not the case so far, right?)
first i'm trying to run SALT2mu on simulated data.

one problem i have is that at the begining of SALT2mu.c there is this explanation:

 The 'file' argument is required, and it is usually the 
FITRES_DMPFILE argument in the &FITINP namelist that is input to the snlc_fit.exe program. So if you have the following namelist for the snlc_fit.exe program,
    &FITINP
       FITRES_DMPFILE = 'mySN.fitres'
    &END
then for the SALT2mu input   file='mySN.fitres'.

so i added a FITRES_DMPFILE in my input .nml file for snlc_fit.exe. But this keyword is not recognized...

so i tried another way: run sntable_dump.py for the FITRES table on my .root file output from snlc_fit.exe

This way i indeed get a fitres file but there is no indication which parameters are needed by SALT2mu which i should include in the dump.

Eventually i'm wondering if the necessary input files are really available to be able to reproduce the Pantheon analysis.
https://github.com/dscolnic/Pantheon says that a folder is provided:
"-> A folder of all the SNANA set-up scripts to fit each sample. This is included in the SNANA release of this data that can be grabbed by downloading http://snana.uchicago.edu/"

but it is not clear for me what folder is this and which are these files. Any help would be highly appreciated. thanks in advance.

regards, 
Fred

**Comment by RickKessler** [comment]
Thank you for reminding that FITRES_DMPFILE is quite obsolete; the associated obsolete comments in SALT2mu.c  will be fixed next SNANA update.  Also note that snana.uchicag.edu is obsolete for the past few years and it points to a code repo here: https://github.com/RickKessler/SNANA . Concerning Pantheon+ folders to reproduce the analysis, I would suggest contacting Scolnic or wait for the Brout-analysis paper to be accepted.

**Comment by fhenryco** [comment]
thank you ! so just to be sure, do you confirm that there is no more up to date public code and data available elsewhere to try to reproduce the analysis already published with Pantheon data. I ask because scolnic github page https://github.com/dscolnic/Pantheon  also points to your https://github.com/RickKessler/SNANA

**Comment by RickKessler** [comment]
SNANA GitHub repo has most of the public code (CosmoSIS and Vpec code is elsewhere). We are working to integrate Pantheon+ data and meta data into the public SNDATA_ROOT, but it's not ready yet.
