### ISSUE TITLE
negative muCOVADD causes muerrsq to go negative

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#848]
```
  ABORT_MESSAGES:
  - FATAL ERROR ABORT called by MNCHI2FUN
  - Insane muerrsq = -0.00015 for snid=1251645 (muerrsq_orig=0.00715)
  - muCOV[scale,add] = 1.06877,-0.00730
```
error can be replicated in $SNANA_DEBUG/mvincenzi/negative_muCOVADD running the FAIL_REPAT.CMD file (if you rerun it, keep in mind it takes 10/15 minutes to hit the abort message)
In principle, negative muCOVADD terms shouldn't be allowed, I think.

**Comment by RickKessler** [comment]
changed muCOVscale>1 requirement to muCOVadd>0. Also note new input   restore_mucovadd_bug
