### ISSUE TITLE
missing SUBSURVEY column in sims

### ISSUE THREAD

**Issue by mi-dai** [RickKessler/SNANA#850]
There used to be a SUBSURVEY column in the combined lowz sims but now missing, causing an error for saltshaker.
An example sim can be found here `$SCRATCH_SIMDIR/SALT3TRAIN_LOWZ_train_105` 
or generate by running `$SNANA_DEBUG/mdai/sim_subsurvey/RUN_TEST`
thanks!

**Comment by RickKessler** [comment]
Fix bug introduced in recent updates. SUBSURVEY column is there for sim, but need to check values.

**Comment by mi-dai** [comment]
checked SUBSURVEY values and they look ok. saltshaker code runs again.
