### ISSUE TITLE
Segmentation Fault in the snlc_sim.c code 

### ISSUE THREAD

**Issue by Shin107** [RickKessler/SNANA#851]
On running snlc_sim.exe with input sim_SDSS.input the code gace an error saying segmentation fault , on checking the c file snlc_sim.c , the error corresponded to line 25626.
![Screenshot from 2022-03-14 16-35-11](https://user-images.githubusercontent.com/70331825/158160176-cf32c559-f448-4377-87bc-693b5b6faf1d.png)

**Comment by RickKessler** [comment]
Unfortunately I don't recognize this seg fault error. Is this error on your laptop or a university computer system? The code line numbers change all the time, so please paste in the relevant line of code where it crashed.

**Comment by Shin107** [comment]
This is in my personal laptop
The error in line 26048 corresponds to the syntax error "(" while on 26074 to the segmentation fault. 
Also the error in 26048 is surprising since the same command has been used before this without any error. 
Please dont mind the printf("no new error ")  they were put by me to find the error location
![error](https://user-images.githubusercontent.com/70331825/158252575-9722fb31-d7db-45e0-9e97-261615a3325a.png)

**Comment by Shin107** [comment]
The error has been figured it was probably due to the naming of the path of $SNDATA_ROOT
