### ISSUE TITLE
telescope Field of view (FoV)

### ISSUE THREAD

**Issue by liuchengqi** [RickKessler/SNANA#852]
I want to add a new survey, then do my own SN simulation. However, I don't know how to use the field of view (FoV) of the telescope. Can I add Fov to kcor input file? or simlib input file? thanks!

**Comment by RickKessler** [comment]
Read manual section
4.24 Simulating Rate vs. Redshift: Volumetric and per Season
and note the SOLID_ANGLE key for total area of the survey. There is FoV input to the simulation.

**Comment by liuchengqi** [comment]
Yes, there is only the SOLID_ANGLE key for total area of the survey. 
In the SIMLIB file, we can input RA, DEC for the observations like :
![image](https://user-images.githubusercontent.com/56668397/158292747-44bc55ce-ab70-41a8-bd97-304d6263743c.png)
 If the program don't know the FOV of the telescope (LSST's FoV ~ 9.6 sq degree), when a SN explode nearby RA: 26.430172   DECL: 0.844033 (not exactly), how the SNANA sim program judge whether this SN is observed by this survey?

I also have written a simple program to do the same thing like SNANA, but the FoV of telescope is very important in my program. The FoV can tell the program whether a SN is in the telescope observation. Thanks!

**Comment by RickKessler** [comment]
While FoV is not an input to SNANA simulation, FoV is may be useful for creating a SIMLIB/cadence file. For example, to generate one DECam pointing of 3 deg^2, pick random sky coordinates over this 3 deg^2 FoV and determine the cadence for each random sky location.

**Comment by liuchengqi** [comment]
So how SNANA sim program judge whether a SN is observed by this survey if FoV is not an input to SNANA simulation? Thanks!

**Comment by liuchengqi** [comment]
In manual section
9.10 LCLIB: Galactic Transients:
![image](https://user-images.githubusercontent.com/56668397/159155083-607c6bc3-e1c4-4c7c-aa3a-838fec1e6975.png)
does ANGLEMATCH keys mean the FoV in my simulation?
Thanks!

**Comment by RickKessler** [comment]
AngleMatch has nothing to do with FoV. It is used to sculpt the physical b-distribution for Galactic events.
