### ISSUE TITLE
HEADER_OVERRIDE_FILE not being read

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#855]
Reproduced with `snlc_fit.exe FIT_PIP_RC_DES5YR_DES5YRSIM_G10.nml VERSION_PHOTOMETRY PIP_RC_DES5YR_DES5YRSIM_G10 JOBSPLIT 1 10 TEXTFILE_PREFIX PIP_RC_DES5YR_DES5YRSIM_G10_FITOPT000_SPLIT001 HEADER_OVERRIDE_FILE $RD_HOME/shuffle.HOSTLIB >& log.txt &` from $SNANA_DEBUG/rebeccachen

I am trying to use a header override file for a fitopt but the variables don't end up overwritten -- seems to read in the file name but the override is never actually initialized.

**Comment by RickKessler** [comment]
what is $RD_HOME ?

**Comment by rebeccachen0** [comment]
Sorry, missed that! `/project2/rkessler/SURVEYS/DES/USERS/rebeccachen/redshift_dists`

**Comment by RickKessler** [comment]
HEADER_OVERRIDE is for real data only; code now aborts with
 FATAL ERROR ABORT called by INIT_READ_DATA
   HEADER_OVERRIDE_FILE is only for data;
   not for simulations
