### ISSUE TITLE
HOST WGT MAPs

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#86]
I built a 1D HOST weight map where the only dependency of the weights is LOGMASS. I tested this map with various hostlibs. I guess SNANA matches the varnames in the weight map file and the varnames in the hostlib, correct? I'm asking because I just realized that one of the hostlibs I was using doesn't have a column called LOGMASS. However SNANA didn't crash or didn't warn me. I guess this means that the weighted map has not been applied at all, correct?

**Comment by RickKessler** [comment]
please provide sample job to illustrate issue (under $SNANA_DEBUB on Midway)

**Comment by RickKessler** [comment]
Not sure what the issue is here, so please re-open when there is more clarification.
