### ISSUE TITLE
iwd exceeds NWD_STORE error while fitting

### ISSUE THREAD

**Issue by Physwiz7** [RickKessler/SNANA#861]
Hi ,
the basic fitting command 
snlc_fit.exe with SDSS input gives the segmentation fault 

![image](https://user-images.githubusercontent.com/102297945/160079091-45dea14e-da2d-4c80-9f4c-1757d6f896ad.png)

some times instead of segmentation fault i get the error malloc(): unaligned tcache chunk detected with same message to check the HOLTZ 0722.dat file
what might be causing this error and how do i fix it ?
Thank You

**Comment by RickKessler** [comment]
Unfortunately the old TEXT format for SDSS_HOLTZ08 is obsolete and no longer readable with SNANA codes. Please process our official data release  SDSS_allCandidates+BOSS. Spec-confirmed SNIa have TYPE=118,119,120.

**Comment by Physwiz7** [comment]
hi , 
so yeah i used SDSS_allCandidates+BOSS but it has some kind of filter error like
 WARNING: fitting filter subset  ugriz  from  ugrizUGRIZ

![image](https://user-images.githubusercontent.com/102297945/160230552-8842dfa2-1f21-4198-a103-36bc0262db7e.png)
how do i get rid of that

**Comment by RickKessler** [comment]
The HOLTZ08 data had ugriz filters, but for final data release we included ugrizUGRIZ, where the latter (UGRIZ) accounted for overlaps between 82N and 82S (the difference between ugriz and UGRIZ is negligible). So in addition to switching VERSION_PHOTOMETRY, the KCOR_FILE also needs to be updated as shown in the attached input file here (GitHub doesn't accept files with .nml extension, so I changed extension to .txt)
[snfit_SDSS.txt](https://github.com/RickKessler/SNANA/files/8355813/snfit_SDSS.txt)

**Comment by Physwiz7** [comment]
hi thanks the code worked and ran successfully , but just one last doubt where is the output stored because i checked for any .fitres file in the $SNDATA _ROOT path and didnt find anything

**Comment by RickKessler** [comment]
simulated data files are written to $SNDATA_ROOT/SIM
