### ISSUE TITLE
GENPDF does not override SALT2beta

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#864]
/scratch/midway2/rkessler/PIPPIN_OUTPUT/P21-TEST/1_SIM/DATASIMDES_4D_BS20-BEST/LOGS/

 FATAL ERROR ABORT called by checkStringUnique
   2  'GENPEAK_SALT2BETA:' keys exceeds limit=1 in sim-input file.
   Calling function is NstringMatch .

SALT2BETA is specified in the GENPDF and needs to be able to override the SIM_INPUT file value. FAIL_REPEAT command is present in the directory.

**Comment by bap37** [comment]
Same with GENSIGMA

**Comment by RickKessler** [comment]
Fixed to run, but I did not check generated distribution. Beware that asymGauss parameters (e.g., SALT2ALPHA or SALT2BETA) read from GENPDF_FILE do not show up in the output README because these asymGauss parameters are treated like a map.

**Comment by RickKessler** [comment]
No complaints so closing issue. Reopen if needed.
