### ISSUE TITLE
Only 1 fit after snlc_fit ?

### ISSUE THREAD

**Issue by Physwiz7** [RickKessler/SNANA#869]
While fitting ,  i get an error
` SNLCPAK_INIT for SURVEY=SDSS  (1 fits per SN)  
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C x86_64-linux-gnu-g++-9   -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
`
but the code runs properly with "ENDING GRACEFULLY" at the end , but in the snfit_SDSS.root  i find only one entry annd i have given inputs from many different light curves the bug still remains and give only 1 fit .
Also i have installed the latest version of root
What could be the probable cause

**Comment by RickKessler** [comment]
check if your fit-input file specifies a single event with SNCID_LIST; if not, which fit-input file did you use?

**Comment by Physwiz7** [comment]
The fits input I used was kcor_SDSS_Bessell90_BD17.fits for kcorrection  and I didn't find any SNCID_LIST in .fits and , but i did find it in snfit_SDSS.nml and it was set to 762 .

**Comment by RickKessler** [comment]
if you remove SNCID_LIST, the code will use CUTWIN_CID instead

**Comment by Physwiz7** [comment]
can you please specify which fits file are you talking about?

**Comment by RickKessler** [comment]
how about if you paste in the input file you are using?
