### ISSUE TITLE
HOSTLIBS break without a_rot

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#87]
Hello! I think this is more of an error trapping issue than anything else.

$SNANA_DEBUG/Brodie/test.input

If you run snlc_sim.exe on this, it will break. That's because the HOSTLIB it is pointing to lacks a_rot. If you change the "sSFR" column to "a_rot", the segmentation fault issue goes away!

**Comment by RickKessler** [comment]
it aborts properly with
 FATAL ERROR ABORT called by read_head_HOSTLIB
   Found zero SN params for HOSTLIB_MSKOPT&64 option.
   Expected 1 or more of 'x1 c alpha beta SNMAGSHIFT '

**Comment by RickKessler** [comment]
with "HOSTLIB_MSKOPT: 4" it crashes.

**Comment by RickKessler** [comment]
fixed ABORT trap.
