### ISSUE TITLE
SDSS filter issue when running SALT3 fits

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#870]
Hello! 

Running into this issue when running SALT3 fits on SDSS data - 

 ERROR: missing SURVEY name for filter = SDSS-u
 ERROR: missing SURVEY name for filter = SDSS-g
 ERROR: missing SURVEY name for filter = SDSS-r
 ERROR: missing SURVEY name for filter = SDSS-i
 ERROR: missing SURVEY name for filter = SDSS-z
 ERROR: missing SURVEY name for filter = SDSS-U
 ERROR: missing SURVEY name for filter = SDSS-G
 ERROR: missing SURVEY name for filter = SDSS-R
 ERROR: missing SURVEY name for filter = SDSS-I
 ERROR: missing SURVEY name for filter = SDSS-Z
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by check_surveyDefined_SEDMODEL
   Missing survey name for 10 of 10 filters (see above).
   Add SURVEY key(s) to kcor/calib input file.

(located here: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-V1/2_LCFIT/Ssys_DATASDSS/output/SPLIT_JOBS_LCFIT/SDSS_allCandidates+BOSS_P19_FITOPT007_SPLIT001.LOG ) 

The fail-repeat command is here: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-V1/2_LCFIT/Ssys_DATASDSS/output/SPLIT_JOBS_LCFIT/FAIL_REPEAT_SDSS_allCandidates+BOSS_P19_FITOPT007_SPLIT001.CMD

**Comment by RickKessler** [comment]
This job is using an old kcor file that does not include survey name; note this comment in the abort message:
    - Missing survey name for 10 of 10 filters (see above). 
    - Add SURVEY key(s) to kcor/calib input file. 

The SURVEY key is needed for calibration systematics, so you will need to remake the SDSS kcor file.
