### ISSUE TITLE
SALT3-NIR needs larger MXBIN_VAR_SALT2 (at least)

### ISSUE THREAD

**Issue by jpierel14** [RickKessler/SNANA#879]
Testing the new SALT3-NIR model, gives the following error:

`FATAL ERROR ABORT called by read_SALT2errmaps NLAM*NDAY=1801*71 = 127871 exceeds bound of MXBIN_VAR_SALT2=120000`

It's possible other array sizes need to be increased and they're simply after this declaration, should be easy to check. Increasing the max bin size to 175,000 or 200,000 should ensure this doesn't happen again (even if we create a new model that's say 1,500-25,000A)

**Comment by RickKessler** [comment]
MXBIN_VAR_SALT2 increased to 200,000
