### ISSUE TITLE
sig_int inconsistent across versions

### ISSUE THREAD

**Issue by erikpeterson23** [RickKessler/SNANA#88]
$SNANA_DEBUG/Erik

in this location:
SALT2mu_combine_wcsp2_darcy_nopv.input
sig_int_issue.sh

The .sh runs the various versions that I tried. Keep in mind the .input file has a set prefix that I changed each time I ran a SALT2mu.exe

I found sig_int to be 0.1052 for 74h and 75
I found sig_int to be 0.1054 for 75d and 75e
I found sig_int to be 0.1127 for the current version (at the time 76d)

**Comment by RickKessler** [comment]
Please take note of the following In README_UPDATES:
     + for +128 bit, sigint_biascor is computed with user-input
        alpha, beta (p1,p2) instead of SIM_ALPHA, SIM_BETA
So the difference in sigma_int(biasCor) is expected.
