### ISSUE TITLE
SUBPROCESS segfault when outputting zCMB as a SUBPROCESS table parameter

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#882]
Able to repeat the command here:

/project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/DUST2DUST/RUNTEST_SUBPROCESS_SIM

**Comment by RickKessler** [comment]
increased MXVAR_GENPDF -> 20 (was 10) and fixed abort trap.

**Comment by RickKessler** [comment]
use zHD instead of zCMB. Fixed code to get abort message with list of valid variables.
