### ISSUE TITLE
30% of simulated SNe not matched to host

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#883]
wrote 20 of these out to text files at `/project2/rkessler/SURVEYS/DES/USERS/helenqu/pippin_config/PIP_HELEN_HOSTNBR_MASAO_DEEP_DESSIM_WRONGHOST_TEXT`

**Comment by RickKessler** [comment]
Found a host in HOSTLIB in which a0_Sersic=16 and b0_Sersci=9, but a[b]_DLR < 1. This results in huge DDLR >> 4. This could be the cause of so many missing hosts. Need to investigate HOSTLIB creation.
