### ISSUE TITLE
RANSEED Sync failure

### ISSUE THREAD

**Issue by jalasker** [RickKessler/SNANA#89]
When simulating sufficiently large samples with the same RANSEED but different CC model mixtures, the Ia samples do not remain the same. This appears to be due to a failure in random number synchronization failure after the first split job. 

For example, here are the random seeds for the first split job for the two CC Model mixtures:

grep -i FIRST DES_Datalike_Contam_3_SNIa-0001.README 
  BRIEF_DESCRIPTION: simulate RANDOM SNe with GENMODEL = SALT2.WFIRST-H17 
	 FIRST/LAST Random Number (List=1): 0.193146 0.975692  
	 FIRST/LAST Random Number (List=2): 0.282461 0.685233  
	 FIRST/LAST Random Number (List=3): 0.574757 0.474366

grep -i FIRST DES_Datalike_Contam_4_SNIa-0001.README 
  BRIEF_DESCRIPTION: simulate RANDOM SNe with GENMODEL = SALT2.WFIRST-H17 
	 FIRST/LAST Random Number (List=1): 0.193146 0.975692  
	 FIRST/LAST Random Number (List=2): 0.282461 0.685233  
	 FIRST/LAST Random Number (List=3): 0.574757 0.474366

And here they are for the second split job:

grep -i FIRST DES_Datalike_Contam_3_SNIa-0002.README 
  BRIEF_DESCRIPTION: simulate RANDOM SNe with GENMODEL = SALT2.WFIRST-H17 
	 FIRST/LAST Random Number (List=1): 0.193146 0.871214  
	 FIRST/LAST Random Number (List=2): 0.282461 0.640003  
	 FIRST/LAST Random Number (List=3): 0.574757 0.679256

grep -i FIRST DES_Datalike_Contam_4_SNIa-0002.README 
  BRIEF_DESCRIPTION: simulate RANDOM SNe with GENMODEL = SALT2.WFIRST-H17 
	 FIRST/LAST Random Number (List=1): 0.193146 0.141852  
	 FIRST/LAST Random Number (List=2): 0.282461 0.115258  
	 FIRST/LAST Random Number (List=3): 0.574757 0.179029

**Comment by RickKessler** [comment]
changing mix of SNII and SNIbc, even with same total rate, results in slightly different number of random CIDs because of how the safety margins are included. So no change or fix needed.
