### ISSUE TITLE
Prob columns messed up when creating INPUT_FITOPT000.FITRES.gz

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#896]
I was trying to run BBC on a big simulation, using the prescale_simdata key.
I noticed that Prob columns are somehow messed up. For example, the PROB_UNITY column (by definition, this should only be 1) has almost all 0 and a small fraction of 1. I checked and the original files definitely have the correct numbers (i.e. PROB_UNITY are all one).
See here on midway:`$PIPPIN_OUTPUT/D5YR_5YRLZ_S3/6_BIASCOR/P21NOM_SIGINT_COLOR_SIM/outputP21/OUTPUT_BBCFIT`
you can imgcat the pdf file test.pdf to see the distribution of PROB_UNITY.

I've seen this happening only when I use prescale_simdata so far. everything works fine when using e.g. real data.

**Comment by RickKessler** [comment]
likely from pippin re-launch confusion
