### ISSUE TITLE
MNSTAT_COV is not a valid input namelist variable 

### ISSUE THREAD

**Issue by Shin107** [RickKessler/SNANA#897]
Is MNSTAT_COV not a valid namelist variable for &SNLCINP  , giving it in the input .nml file snfit_SDSS.root  gives an error 
` FATAL ERROR ABORT called by RDSNNML
   could not read &SNLCINP namelist
   Check input-namelist file.
`
Other namelist variables give no such error.
if MNSTAT_COV is not valid nml variable then what are the ohter ways in whihc I can generate covariance matrix?
Thanks

**Comment by RickKessler** [comment]
light curve fit automatically outputs covariance matrix among mB,x1,c.

**Comment by Shin107** [comment]
The variable MNSTAT_COV in the FITRES table has just a constant value 3 for all the fits , is there any other variable which store the covariance matrix?

**Comment by RickKessler** [comment]
Please see SNANA manual section 5.4.1 minuit Covariances. MNSTAT=3 means that the covariances are all good.

**Comment by Shin107** [comment]
Yes,  so the cov generated are among x1 and  c only so should it be assumed that cov( mb ,c)and cov(mb,x1) is zero ?

![image](https://user-images.githubusercontent.com/70331825/165812724-3697996c-2b04-4be4-8b05-da4ac354941c.png)

**Comment by RickKessler** [comment]
Note there are cov terms among x0 as well, where mB = -2.5*log10(x0) + offset. So one can compute COV(mB,?) from COV(x0,?).

**Comment by Shin107** [comment]
Ah Alright thanks
