### ISSUE TITLE
snlc_sim.exe terminated due to stack smashing

### ISSUE THREAD

**Issue by andersonlai** [RickKessler/SNANA#9]
I was trying to follow SNANA's manual and running lightcurve simulation using the sample sim_SDSS.input file. But it prompted a "stack smashing" message as I run it, I wonder if I have been missed anything necessary. Here's my SNANA version and the system that was used to run it:

SNANA version: v10_73

System: windows subsystem for linux - ubuntu 16.04

necessary packages: cfitsio-3.47, gsl-2.5

I've also attached the message in the end. Please let me know if I have missed any necessary files or steps, thank you.
[output.txt](https://github.com/RickKessler/SNANA/files/3369556/output.txt)

**Comment by RickKessler** [comment]
somebody else noticed a similar problem with the examples, which had become obsolete over time. I recently fixed them in $SNDATA_ROOT (snana.uchicago.edu). Note that SNDATA_ROOT is still on the old repository.
