### ISSUE TITLE
SALT2mu_fit.pl is choosing crazy locations for output directories

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#90]
in `$SNANA_DEBUG/djones`, run `SALT2mu_fit.pl WFIRST_BBC.input`.  The output directory will be placed in `/project2/rkessler/SURVEYS/WFIRST` for some reason.

**Comment by RickKessler** [comment]
the default output dir is the maximum string overlap of the INPDIRs, and so /project2/rkessler/SURVEYS is indeed the maximum overlap string.  The idea was that INPDIRs would be under a well-defined topDir rather than distributed. Consider setting your own output path with
OUTDIR_OVERRIDE: <TOPDIR>
