### ISSUE TITLE
Add binary TRUE column to hostlib

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#901]
TRUE=1: can be used for simulation (ie can be true host)
TRUE=0: only used for matching, cannot be true host

more details: https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1651521980628069

**Comment by RickKessler** [comment]
implemented by setting WGT=0.0 for galaxies with TRUE=0. Needs testing.

**Comment by helenqu** [comment]
got error: `FATAL ERROR ABORT called by init_HOSTLIB_WGTMAP Could not interpolate WGTMAP for GALID=2100595196 . interp_GRIDMAP() returned istat = -1`
the referenced galaxy is TRUE=0 and has no logmass estimate

TRUE=0 galaxies should not be subject to the same requirements as TRUE=1 galaxies (i.e. should not be required to have LOGMASS in the WGTMAP range or have a redshift, etc)

**Comment by RickKessler** [comment]
Fixed logic so that sim job runs, but not clear what happens for DLR-matched galaxies with ZTRUE < 0
