### ISSUE TITLE
sim_SNgrid.pl not working

### ISSUE THREAD

**Issue by vpetrecca** [RickKessler/SNANA#902]
Hi, I am getting this error if I try launching the `sim_SNgrid.pl` script:

`perl sim_SNgrid.pl                             
Can't locate sntools.pm in @INC (you may need to install the sntools module) (@INC contains: /global/cfs/cdirs/desc-td/SOFTWARE/SNANA/util /global/common/cori_cle7up03/software/darshan/perl-packages/perl-Pod-LaTeX/lib/ /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/sim_SNgrid.pl line 59.
BEGIN failed--compilation aborted at /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/SNANA/util/sim_SNgrid.pl line 59.`

Could someone help providing the requested module?

**Comment by RickKessler** [comment]
Back in January I removed some obsolete perl scripts and accidentally removed the sntools.pm utility. It is now restored, so try again.

**Comment by vpetrecca** [comment]
Thanks, now I can launch the script but I still got an error if I try re-generating the SDSS templates using `$SNDATA_ROOT/models/psnid/SDSS/SNgrid/sim_SDSS_NONIA-S11.input`

```
%> sim_SNgrid.pl sim_SDSS_NONIA-S11.input

 ------------------------------------- 
 Created OUTDIR SNgrid .
 -------------------------------------- 
 Prepare sim-input file: sim_SDSS_NONIA-S11.input 
	 SURVEY   = SDSS 
	 GENMODEL = NONIA 
	 GRIDFILE = GRID_SDSS_SNCC-S11.FITS 
	 INCFILE  = SIMGEN_INCLUDE_NONIA-S11.input 

 Will launch jobs in 3 seconds ... 

# =========================================== 
#       BEGIN PROCESSING GRIDs  
# =========================================== 

 Process sim_SDSS_NONIA-S11.input ... 
	 copy INCLUDE file: 'SIMGEN_INCLUDE_NONIA-S11.input' 
cp: cannot stat 'SIMGEN_INCLUDE_NONIA-S11.input': No such file or directory
	 Sim-job:  snlc_sim.exe  sim_SDSS_NONIA-S11.input  GRID_FORMAT FITS  
	 copy $SNDATA_ROOT/SIM/RKTESTSDSS_NONIA-S11/RKTESTSDSS_NONIA-S11.GRID 
	  --> GRID_SDSS_SNCC-S11.FITS 
cp: cannot stat '/global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SNDATA_ROOT/SIM/RKTESTSDSS_NONIA-S11/RKTESTSDSS_NONIA-S11.GRID': No such file or directory

 Done. 
 Output is in  SNgrid/ 
 0 of 1 jobs finished OK. 
 WARNING: at least one sim job failed !!! Check SNgrid/*.LOG 
```
It seems to try looking for files in this directory $SNDATA_ROOT/SIM/RKTESTSDSS_NONIA-S11/ which not exist

**Comment by RickKessler** [comment]
Fixed a few bugs in sim_SNmix.pl and created example for LSST under $SNANA_DEBUG/SNgrid (on Cori).

**Comment by vpetrecca** [comment]
Great! I will close this issue then, thank you
