### ISSUE TITLE
Option to turn off abort on BADVAL_SALT2errmap errors

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#903]
Following on from this issue - could we have an option to turn off this abort on BADVAL_SALT2errmap errors? I'm trying to check regularization of some new SALT2 surfaces which requires lc fitting, and am getting stuck. I've tried adding ERRMAP_BADVAL_ABORT:0 to the SALT2.INFO file, but no luck.

_Originally posted by @geotaylo in https://github.com/RickKessler/SNANA/issues/681#issuecomment-1116898467_

**Comment by RickKessler** [comment]
Try leaving a pad space before the zero; e..g,
ERRMAP_BADVAL_ABORT:  0
If this doesn't work, please slack me a sim-input example location.

**Comment by geotaylo** [comment]
That worked, thank you!
