### ISSUE TITLE
AUTOSTORE related error

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#905]
In /scratch/midway2/rkessler/PIPPIN_OUTPUT/D5YR_5YRLZ_S3/2_LCFIT/Fsys_DATAFOUND/output 
I noticed SALT3 fittings are crashing because of this error:
```
  ABORT_MESSAGES:
  - FATAL ERROR ABORT called by SNTABLE_AUTOSTORE_INIT
  - varName='VPEC' already defined in AUTOSTORE
  - Check previous AUTOSTORE declarations.
```

**Comment by RickKessler** [comment]
Due to earlier refactor that makes use of AUTOSTORE utility, the above job uses AUTOSTORE twice. Fixed bug by adding missing AUTOSTORE_RESET command.
