### ISSUE TITLE
SNLS_biascorr

### ISSUE THREAD

**Issue by fhenryco** [RickKessler/SNANA#907]
Dear, 
I'm trying to reproduce the yellow curve from fig 5 in https://arxiv.org/pdf/1401.4064.pdf
This is the bias in SNLS as a function of z, i.e. = <µFIT_lightcurve − µ_SIM_Cosmo_model>(z)

So i just ran SNANA codes:

 snlc_sim.exe sim_SNLS.input
 
 snlc_fit.exe snfit_SNLS.nml > snfit_SNLS.log &

using sim_SNLS.input and snfit_SNLS.nml from SNANA/SNDATA_ROOT/sample_input_files/SALT2

then get a data file with $SNANA_DIR/util/sntable_dump.py snfit_SNLS.root FITRES -v IDSURVEY,zHD,zHDERR,mB,mBERR,c,cERR,x1,x1ERR

and do the plots with my own python code. 

But at the end i get no bias (zero compatible at all z) for the SN after cuts if i build  
<µ_true_after_cuts − µ_SIM_Cosmo_model>(z)
which is unexpected because the sample of selected SN after cuts should have a mean lower true mu than mu of simulated cosmo model.

and i get a slightly positive bias (which is again nonsense: bias should be negative)  for 
<µ_FIT_lightcurve − µ_SIM_Cosmo_model>(z)
actually i get almost the opposite of the yellow curve (so at least the order of magnitude seems to be  correct) 

so i'm wondering if i'm using correct input files and where should i find the input files to reproduce the published bias. Once i have it correct i intend to apply the method to an alternative model (not LCDM) but i would very much appreciate to at least have the input files allowing to reproduce the SNLS bias(z) for LCDM. Thank you in advance for any helpfull advice or suggestion.

I dont believe it's related but i did not find any cov_x1_mB variable, only cov_x1_x0 is provided, so i use simplified errors (diagonal terms only) so far...

best regards

fred

**Comment by RickKessler** [comment]
The example sim-input file for SNLS does not include the selection bias. To apply an alternative cosmology model, I would suggest starting with the publicly released JLA files that include SALT2 parameters and distance bias.

**Comment by fhenryco** [comment]
Thannk you for your fast answer ...are you talking about other sim-input files published somewhere else ? and then where could i find them ? because if you are talking about SALT2 fit OUTPUT files that were obtained assuming LCDM, i already analyzed them and i'm afraid the corresponding biascorr cannot be applied for an alternative model that predicts very different luminosity distances  in the SNLS redshift range , hence different true mB, hence a different bias !

**Comment by fhenryco** [comment]
What i could do is translate the biascorr_LCDM(z) data into biascorr(mB) data (knowing predicted mB_LCDM(z)) to then get biascorr_Alternative_model(z) (knowing predicted mB_Alternative_model(z)). May be this what you are suggesting ...(?)

**Comment by RickKessler** [comment]
If your model produces "very different luminosity distances", is this model consistent with other measurements such as BAO ? 
Regarding the simulation of biases, JLA did not release the relevant sim-input files because the vast majority of people are only interested in the SALT2 output files. Try checking Pantheon data release page since they may have released more information on how to simulate bias corrections.

**Comment by fhenryco** [comment]
Fit of my model to the BAO main data is not so bad for the full shape BAO measurements. My luminosity distances are actually only significantly less than LCDM for z < 0.7 for which the SNLS bias is very small, and quite similar to LCDM beyond 0.7 ... so indeed i could as everybody else be satisfied by the JLA output file (with bias estimation assuming LCDM) for SNLS...

**Comment by fhenryco** [comment]
... actually i have no problem to fit JLA data with my model, but now i'm getting in serious tension with Pantheon after it has reduced the systematics in a very model dependent way (the 5-d bias correction)...and in this case it becomes crucial for me to be able to correct biases assuming the model that i want to test and not LCDM ! As the Pantheon analysis is much more complicated and the tools are not provided to perform a  bias correction for a specific model different from LCDM... i wanted to investigate in a first step the JLA SNLS case to see if i'm able to get the bias myself at least in this case.
