### ISSUE TITLE
SDSS simulation hangs when loading in a HOSTLIB 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#913]
Afternoon! 

I'm trying to run an SDSS simulation with a new HOSTLIB (which works for DES, LOWZ, and FOUNDATION), but when I try to simulate SDSS, it just... hangs! There's no error message, it just stops going after a couple minutes. I'm working in this directory - 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/PW-ALLSURV/1_SIM/SDSSSIMBIAS_4D_P21OLD/LOGS

and using this command:

CPU0000_JOBLIST_midway2-login1.CMD

I ran it, and it got to here:

    Load GRIDMAP-020 'WGTMAP(LOGMASS_TRUE WGT SNMAGSHIFT )'  NROW=180
         malloc_GRIDMAP: allocate
         Implement SNMAGSHIFT in WGTMAP
         Reading /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/AURA/AURAquench_v0.HOSTLIB
         Reading /project2/rkessler/SURVEYS/DES/USERS/mvincenzi/AURA/AURAquench_v0.HOSTLIB
                 read 400000 GAL rows
                 read 800000 GAL rows
                 read 1200000 GAL rows

before not updating for 40 minutes!

**Comment by RickKessler** [comment]
Fixed a very subtle bug that causes thousands of spurious realloc calls leading to > 100GB memory consumption.
