### ISSUE TITLE
snlc_fit trouble with specifying SNCCID_LIST

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#915]
Hi Rick, getting an abort in snlc_fit.exe.  To reproduce:
```
cd $SNANA_DEBUG/djones/snlc_fit
snlc_fit.exe Foundation_test.nml
```
For whatever reason, a shorter version of the SNCCID_LIST (see Foundation_test-2.nml) works just fine, but the example one causes errors.  Thanks!

**Comment by RickKessler** [comment]
Looks like the number of CIDs exceeds array bound. For large CID lists, better to use a file,
SNCID_LIST_FILE = 'myCID.list'

**Comment by djones1040** [comment]
Thanks!

**Comment by djones1040** [comment]
Trying the SNCID_LIST_FILE option, I'm getting the message "EVERY SN FAILS CUTBIT   1 :  CID".  To reproduce:
```
cd $SNANA_DEBUG/djones/snlc_fit
snlc_fit.exe Foundation_test.nml
```

**Comment by RickKessler** [comment]
fixed refactor bug for unformatted SNCID_LIST_FILE
