### ISSUE TITLE
Redshift values for Galactic events in Elasticc

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#919]
`REDSHIFT_HELIO` header column for all Galactic events gives |z| ~ 1e-5—1e-3, both positive and negative. All `REDSHIFT_HELIO_ERR` equal 0.001. There are two issues with this:
1. These values are obviously not right
2. According to the [Elasticc readme](https://portal.nersc.gov/cfs/lsst/DESC_TD_PUBLIC/ELASTICC/TRAINING_SAMPLES/A_FORMAT.TXT) these values are going to be submitted to the alert stream as `z_final` so they would leak the Galactic nature of these objects

**Comment by RickKessler** [comment]
fixed LCIB-galactic sim to write redshift = -9 +_ -9  so that it appears as a host-less event.
