### ISSUE TITLE
allow multiple photometric systems in kcor files

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#92]
Hi Rick, I have a kcor file with both BD17 and VEGA systems defined for the observer frame, here:

`/project2/rkessler/SURVEYS/PS1MD/USERS/djones/RAISIN/CfANIR2/kcor_PS1_LOWZ_COMBINED_CfANIR.input`

When I run fitting with `snlc_fit.exe snfit_CfANIR2.nml` in that same directory I get the following error:

 FATAL ERROR ABORT called by RDKCOR_SUMMARY
   More than 1 PRIMARY ref not allowed.
   Check kcor file and above list of primary refs.

**Comment by RickKessler** [comment]
Done: use kcor-input syntax such as MAGSYSTEM: VEGA->AB (see instructions near top of kcor.c source code). New feature has been tested on CSPDR3 data where BD17->AB and VEGA->AB are both used in same k-corr input file. Also tested for AB->BD17 for all bands. Testing is quite limited, so be careful.
