### ISSUE TITLE
SNANA cutting SN from public DES-SN3YR sample

### ISSUE THREAD

**Issue by geotaylo** [RickKessler/SNANA#921]
Hi, I'm getting a number of DES-SN3YR sn fail the NFILT_SNRmax cut when light curve fitting with SALT3.FRAG and SALT2.FRAG. My understanding from B19 was that the public sample (I'm using $SNDATA_ROOT/lcmerge/DES-SN3YR_DES) should be passing these cuts, so I feel like I'm missing something here. Any ideas? I'm using:
CUTWIN_SNRMAX       =  5.0, 1.0E8
CUTWIN_NFILT_SNRMAX =  2.0, 99.
Which are consistent with the cuts in the B19 paper.
$PIPPIN_OUTPUT/GT_SALT23_FRAG_3YRTEST/2_LCFIT/LDD_322_DATADES3YR/output/SPLIT_JOBS_LCFIT/CPU0000_JOBLIST_midway2-login2.CMD reproduces this issue, and the log is in $PIPPIN_OUTPUT/GT_SALT23_FRAG_3YRTEST/2_LCFIT/LDD_322_DATADES3YR/output/SPLIT_JOBS_LCFIT/DES-SN3YR_DES_FITOPT000_SPLIT001.LOG

Here's a summary of the log table showing that cuts are applied.
<img width="572" alt="image" src="https://user-images.githubusercontent.com/24376501/171461263-012e575a-5d86-4278-ad6f-82a39b8654c1.png">

I'm also struggling to specifically figure out why some of my low-z SN are failing fit-cuts, if there are any extra logging options available to get this info. My results are in e.g. $PIPPIN_OUTPUT/GT_SALT23_FRAG_3YRTEST/2_LCFIT/LLD_T22_1_DATALOWZ/output/SPLIT_JOBS_LCFIT/DES-SN3YR_LOWZ_FITOPT000_SPLIT001.LOG , which as far as I have seen doesn't seem to have info about why the fit cuts are being applied.

**Comment by RickKessler** [comment]
hopefully resolved using original SALT2 model. DES data release only includes events passing original cuts, hence any analysis change shows only event losses but not event recovery.
