### ISSUE TITLE
Dump MWEBV values even if they are not used by a model

### ISSUE THREAD

**Issue by hombit** [RickKessler/SNANA#923]
Currently we can specify if we'd like to use the 2d Milky Way extinction map for a model and the E(B-V) value used to correct photometry for extinction is dumped to an output file as MWEBV. This means that if a model config specifies to not use Milky Way extinction, then zero MWEBV value will be written. It affects Elasticc models (d-sct, Cepheid, M-dwarf flare, dwarf novae) which turn off SNANA extinction correction and provides light curves corrected by extinction using 3-d dust maps.

I propose to always output 2-d MWEBV values and explicitly say in the documentation that it is just a function of the spherical coordinates.

**Comment by RickKessler** [comment]
In the LCLIB file, please add actual MWEBV used. It serves two purposes: 1) provides true MWEBV for later analysis, and 2) it's a flag for simulation to write SFD98 MWEBV into header but NOT apply it.

**Comment by hombit** [comment]
We will do it. Maybe it should be some other name, for example EBV or extinction? I think users can be confused by the fact that LCLIB specifies one MWEBV, while output contains another one

**Comment by RickKessler** [comment]
and note that MWEBV from LCLIB is automatically renamed to avoid confusion.

<img width="986" alt="LCLIB_MWEBV" src="https://user-images.githubusercontent.com/24592476/171954773-fef06238-d561-4208-a8d3-0c6e3f4906a0.png">

**Comment by hombit** [comment]
This is a very good documentation change, thank you
