### ISSUE TITLE
LOGMASS_TRUE Undefined variable while running Kasen Kilo Nova model on CORI

### ISSUE THREAD

**Issue by dev-ved30** [RickKessler/SNANA#928]
* Last few lines of the error message:
FATAL ERROR ABORT called by MATCH_INDEX_SIMGEN_DUMP
Undefined SIMGEN_DUMP variable: 'LOGMASS_TRUE'

* The input file path on cori:
/global/cfs/cdirs/desc-sn/SNANA/SURVEYS/LSST/USERS/ved/KN_test_Kasen.INPUT

**Comment by RickKessler** [comment]
the LOGMASS in the KN model was confused with LOGMASS host property. I fixed the code so that SIMSED variables are not confused with HOSTLIB variables.
