### ISSUE TITLE
segmentation fault in Dust2Dust 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#930]
in /project2/rkessler/SURVEYS/DES/ROOT/analysis_photoIa_5yr/populations/DUST2DUST/

running RUNTEST_SUBPROCESS_SIM will recreate the segmentation fault

It will ask for an iteration number - please put in "0" and it will proceed normally

**Comment by RickKessler** [comment]
found and fixed another local string with insufficient allocation
(string[12] -> string[40] in sntools_gridmap.c)
