### ISSUE TITLE
FATAL ERROR ABORT called by read_SIMSED_TABBINARY

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#934]
Pippin Output: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_D5YR_SIM`
Error in `/scratch/midway2/rkessler/PIPPIN_OUTPUT/PA_D5YR_SIM/1_SIM/SIMDES5YRCC/LOGS/TMP_parm_PIP_PA_D5YR_SIM_SIMDES5YRCC_NONIaMODEL0-0009_76004.LOG`
Error:
```
ERROR: NBIN(NDAY)=94 from binary table, but request is 99
FATAL ERROR ABORT called by read_SIMSED_TABBINARY
Binary table mis-match =>
Try deleting /project2/rkessler/SURVEYS/LSST/ROOT/PLASTICC/model_libs/SIMSED_BINARIES/SIMSED.SNIax_DES-griz.BINARY
```

**Comment by RickKessler** [comment]
SED.BINARY was updated a few days ago (?), so remake DES flux-table binary.
