### ISSUE TITLE
SDSS SALT2mu segmentation fault 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#938]
Getting a segfault when running SALT2mu on the SDSS-photometric sample:

in /scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-V3/6_HAND/JUST_SDSS/output_ITER1/SCRIPTS_BBCFIT/

There is FAIL_SUMMARY.LOG which lists the error as "UNKNOWN" 

and then FAIL_REPEAT* (eg FAIL_REPEAT_OUTPUT_BBCFIT_FITOPT001_MUOPT000.CMD) will recreate the error

**Comment by RickKessler** [comment]
I don't find any LOG files or FAIL* files.

**Comment by bap37** [comment]
Seems to have fixed itself, can no longer repeat the error.
