### ISSUE TITLE
Bug in create_covariance

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#939]
There's a length mismatch error when I try to run create_covariance but I can't understand what is causing it.
The error can be replicates running ./test.cdm here: /project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/create_cov_bug
Thanks!
Maria

**Comment by RickKessler** [comment]
the first entry for the extra COV is 2013E, but this CID is missing from the Hubble diagram file. I did not write this part of the code, so I am not sure what the original intent is when CIDs don't match.
