### ISSUE TITLE
remove SALT2mu ABORT trap for NMATCH_TOT=0?

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#94]
Was wondering if it would be possible to remove the SALT2mu abort trap for error messages like this:
```
  PRE-ABORT DUMP from function match_surveyGroup :
  NSURVEYGROUP = 5
  surveygroup_biasCor = 'PS1_LOWZ_COMBINED(zbin=0.01),PS1MD(zbin=0.1),CFA3S,CFA3K,CFA4p1'
  SURVEYGROUP(0) = 'PS1_LOWZ_COMBINED'
  SURVEYGROUP(1) = 'PS1MD'
  SURVEYGROUP(2) = 'CFA3S'
  SURVEYGROUP(3) = 'CFA3K'
  SURVEYGROUP(4) = 'CFA4p1'

 FATAL ERROR ABORT called by match_surveyGroup
   Invalid NMATCH_TOT=0 for CID=376225
   IDSURVEY=66(CFA4p2)
```

Basically, if a survey exists in the BiasCor file but does *not* exist in the input file, can BBC just proceed with a warning?  The fundamental issue is that for small simulations of a combined low-z sample, not every survey is always represented in the output simulation.  You can run a test job with `SALT2mu_fit.pl /project2/rkessler/SURVEYS/WFIRST/ROOT/SALT3/examples/sim_lowzps1_pipeline/pipeline/BBC.input_099`

**Comment by RickKessler** [comment]
traced problem to simulating only half of SIMLIB that ignored CFA4p2 sub-sample. Solution is to add NLIBID key in SIMLIB so that each sim job starts at random LIBID.
