### ISSUE TITLE
Generating Bulla KN is failing on Cori.

### ISSUE THREAD

**Issue by dev-ved30** [RickKessler/SNANA#940]
* Last Few Lines of the log file
    Finished generating  2180500 of 6000000 (CID=2180500) 
    Finished generating  2181000 of 6000000 (CID=2181000) 
    
       `|```````|`    
       <| o\ /o |>    
        | ' ; ' |     
        |  ___  |     ABORT program on Fatal Error. 
        | |' '| |     
        | `---' |     
        \_______/    
    
     FATAL ERROR ABORT called by GEN_SNHOST_DRIVER
       Invalid ZGEN(Helio,CMB)=0.014030,0.015050 
       HOSTLIB z-range is 0.0154 to 0.3107

* Input File path on CORI
/global/cfs/cdirs/desc-sn/SNANA/SURVEYS/LSST/USERS/ved/KN_test_Bulla.INPUT

* Other information
I incorporated the changes that I could make sense of from the Kasen input file suggestions you had left from a previous issue but that does not seem to solve the issue

Thank you!

**Comment by RickKessler** [comment]
with such a large sample, it looks like a VPEC fluctuation that causes zHELIO to go below the range of the HOSTLIB. Try increase min redshift (GENRANGE_REDSHIFT) by 0.002

**Comment by RickKessler** [comment]
Going to close this issue now, but re-open it if problems continue.
