### ISSUE TITLE
SNTYPE can be only a typed event (only 0<=)

### ISSUE THREAD

**Issue by jkobori19** [RickKessler/SNANA#944]
In the Pantheon sample (SNDATA_ROOT), the HST subsample consists untyped events
(SNTYPE=-9), which result in the following error:

 FATAL ERROR ABORT called by PASS_SNTYPE
    Invalid data header TYPE =     -9 for CID=garner
    Valid TYPE range is 0 to  1000

**Comment by RickKessler** [comment]
fixed snana.car to allow SNTYPE = -9; internally the SNTYPE is changes to zero.
