### ISSUE TITLE
CONSISTENT_SAMPLE crash error handling 

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#947]
when running CONSISTENT_SAMPLE, if output_ITER1 fails due to an error or abort, BBC is not aware of this crash and continues the output jobs running in the background. 

Will comment in an example directory of this in a little bit.

**Comment by RickKessler** [comment]
2nd iteration of BBC now checks that ALL.DONE has SUCCESS for 1st iteration. If not, 2nd iteration quits.

**Comment by RickKessler** [comment]
Cannot do more without example failure.
