### ISSUE TITLE
FITWIN_TREST and CUTWIN_TREST

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#954]
I think there's something flawed in the logic of 

test available here:
`$SNANA_DEBUG/mvincenzi/Trest_cut`
I'm selecting these fours LC ([LCs plot](https://drive.google.com/file/d/17ND0BYmNRrxgt9ort6JQz4xbg_sMgZeH/view?usp=sharing)) that have very good phase coverage

I'm setting CUTWIN_TRESTMIN -20.0, 0.0 to select only objects that have at least one data point before peak.
Then, Im running three tests:
a) FITWIN_TREST -15 45 to reject points outside the phase range -15 +45
b) FITWIN_TREST +0 45 to reject points outside the phase range +0 +45
c) FITWIN_TREST +4 45 to reject points outside the phase range +4 +45
Tests a),b),c) are so that I can compare LC fitting results when I include/exclude peak data
However, for some reason I don't understand test c) reject ALL the events, and results between test a) and test b) are identical.
I'm not sure what's wrong in the logic I implemented.
Thanks!

**Comment by RickKessler** [comment]
Note that FIT.nml has 
    FITWIN_TREST_FILTER = 'griz 0 45'
which may conflict with command-override options above.
