### ISSUE TITLE
please move Pantheon low-z simlib from midway SNDATA_ROOT to official SNDATA_ROOT

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#96]
I just edited the Pantheon low-z simlib here:

`$SNDATA_ROOT/simlib/PS1/Pantheon/PS1_LOWZ_COMBINED.SIMLIB`

so that NLIBID is specified in the header.

**Comment by RickKessler** [comment]
Installed in SNDATA_ROOT after modifying comment at top of file.
