### ISSUE TITLE
WFit output contour / chi^2 grid

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#968]
Following the discussion on the validation of DES' contours it would be useful if WFit could output the contour / chi^2 grid which it produces, alongside the best fitting values

**Comment by RickKessler** [comment]
try -outfile_chi2grid <fileName>
It's not well tested, so proceed with caution.

**Comment by OmegaLambda1998** [comment]
running `sumbit_batch.py /scratch/midway2/rkessler/PIPPIN_OUTPUT/BV_FR_LAMBDACDM/8_COSMOFIT/WFIT/WFIT_SN_OMW_OMPRI/8_COSMOFIT_WFIT_WFIT_SN_OMW_OMPRI.INPUT` does not seem to produce any chi^2 grid output, with the flag included.

**Comment by RickKessler** [comment]
fixed a bug and integrated this feature into submit_batch_jobs.
