### ISSUE TITLE
HOSTGAL_OBJID matches SIM_HOSTGAL_OBJID in wronghost simulations

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#969]
https://darkenergysurvey.slack.com/archives/DPLPJ1J9Y/p1658855726003389

example sim file: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_MISMATCH_TO_WFIT__SULLIVAN_WGTMAP/1_SIM/DESSIM_WRONGHOST/PIP_HELEN_MISMATCH_TO_WFIT__SULLIVAN_WGTMAP_DESSIM_WRONGHOST-0005/PIP_HELEN_MISMATCH_TO_WFIdbde3_SNIaMODEL0-0005_HEAD.FITS.gz`

interactive sim input file: `/project2/rkessler/SURVEYS/DES/USERS/helenqu/host_galaxy_mismatch/for_rick_wronghost.sh`

**Comment by RickKessler** [comment]
fixed a few refactor bugs.
