### ISSUE TITLE
Possible bug in create_covariance.py

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#972]
In `get_hubble_diagrams` line 392 -> 398:
```
   1     if is_rebin :
   2         label0 = label_list[0]
   3         get_rebin_info(config,HD_list[label])
   4         for label in label_list:
   5             print(f"   Rebin {label}")
   6             HD_list[label]['iHD'] = config['col_iHD']
   7             HD_list[label] = rebin_hubble_diagram(config,HD_list[label])
```

You create `label0` on line 2, but do not use it in line 3. This means that `get_rebin_info` actually runs on the last `label` created in the `for infile in sorted(os.listdir(folder_expand)):` block, i.e. the last file in the BIASCOR directory.

I think this should be `get_rebin_info(config,HD_list[label0])`

**Comment by RickKessler** [comment]
fix is implemented.
