### ISSUE TITLE
Rest frame lambda bug when light-curve fitting

### ISSUE THREAD

**Issue by benjaminrose** [RickKessler/SNANA#975]
When fitting light curves, it seems like the `RESTLAMBDA_FITRAN` key is not being read. I have an object at z~1 where the LC fitting should ignore the Roman R-band, but is causing a failure instead.

```
  PRE-ABORT DUMP from function checkLamRange_SEDMODEL :
  Calling function 'genmag_SALT2' passed ifilt=6('R062-R') and z=1.0840
  Rest-frame Lambda-Range (LAMREST_MIN/MAX)  = 1962.577037 to 3795.595199
  SED Lambda-Range: 2000.000000 to 20000.000000
  LAMFAIL_LO/HI = 1, 0
```

In the nml file, I have `RESTLAMBDA_FITRANGE = 3000. , 20000.`. You can reproduce this bug with the command can be found in `$SNANA_DEBUG/restframe_lambda_bug/`.

**Comment by RickKessler** [comment]
above abort is a protective feature, not a bug. At z=1.08, R-band filter extends 38A bluer than the model limit of 2000 A, so the program aborts to avoid undefined flux. In RICK.nml, I set the min wavelength to 3200 A (instead of 3000) and the event above was fit without error.

**Comment by benjaminrose** [comment]
Why would it ignore the R band with the min fit wavelength set to 3200 but try to fit the R band if the min fit wavelength is set to 3000?

Will SNANA use the band if any part of the band is within RESTLAMBDA_FITRANGE?

**Comment by RickKessler** [comment]
RESTLAMBDA_FITRANGE defines central wavelength of passband ... but the filter edges (blue and red) must be within the SED-model ranges, otherwise it aborts. Shifting 3000 -> 3200 results in excluding R-band as indicated by this stdout line
     FIT OBSERVER FILTERS YJZ
