### ISSUE TITLE
Does GENRANGE_DMPTREST output magnitudes on 'observer frame' epochs?

### ISSUE THREAD

**Issue by MatSmithAstro** [RickKessler/SNANA#978]
Hi Rick, 
I'm looking to compare results results between SNANA and SNCosmo. To check that the models are the same I'm using the GENRANGE_DMPTREST feature in snlc_sim.exe and comparing the model light-curves output to those produced by sncosmo. 

Is the 'TREST' column output by this already corrected for redshift? I'm finding a far better agreement if I convert these phases to observer frame using: 
TOBS = PEAKMJD + TREST 
while, if they were rest-frame phases, I would expect to use: 
TOBS = PEAKMJD + TREST*(1+z)

Sorry if this is not a bug, but a naming convention that I wasn't aware of! 
(I can send you a trial example if needed)

**Comment by RickKessler** [comment]
I have not used this GENRANGE_DMPTREST feature for a very long time, but looking at the code there were some obvious factors of 1+z missing. I fixed these, but didn't run a test so let me know how it goes.

**Comment by MatSmithAstro** [comment]
Thanks Rick: it works! I can confirm that the model magnitudes match that of SNCosmo (after applying a shift in M_abs).
There's a slight discrepancy (0.02 mag) at late times, but that's likely due to differences in filter transmission. 
I'll investigate and let you know if anything comes up, but for now I think you can close this issue. Thanks!
