### ISSUE TITLE
Biascor printout

### ISSUE THREAD

**Issue by bap37** [RickKessler/SNANA#98]
As per our discussion this morning, it'd be nice to have BBC print out a potential error for too-small biascor samples. Maybe "You've lost 3% of your sample due to INVALID BIASCOR!" or something.

**Comment by RickKessler** [comment]
with current stdout, grep Reject <stdout> to see biasCor loss. To make this easier to monitor, the output SALT2mu/BBC FITRES files include a warning for any SAMPLE with more than 2% loss from biasCor. For example,
WARNING(SEVERE): 11 of 423 events (2.6 %) have no biasCor for DES(C3+X3)
