### ISSUE TITLE
LCFIT crash: could not find SNANA version ''

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#981]
example crash log: `/scratch/midway2/rkessler/PIPPIN_OUTPUT/HELEN_DUPLICATE_MISMATCH_TO_WFIT__SULLIVAN_WGTMAP/2_LCFIT/DESFITSYS_DESSIM_WRONGHOST/output/SPLIT_JOBS_LCFIT/PIP_HELEN_DUPLICATE_MISMATCH_TO_WFIT__SULLIVAN_WGTMAP_DESSIM_WRONGHOST-0001_FITOPT000_SPLIT001.LOG`

**Comment by RickKessler** [comment]
your SNANA version exceeds 72 char limit, so I fixed code to abort with proper  error message.
