### ISSUE TITLE
`HOSTGAL_OBJID == 0` in ~10% of regular (no host matching) simulations

### ISSUE THREAD

**Issue by helenqu** [RickKessler/SNANA#982]
ex. sim input file: `/project2/rkessler/SURVEYS/DES/USERS/helenqu/host_galaxy_mismatch/for_rick_wronghost.sh`

**Comment by RickKessler** [comment]
host matching is always done if there is a Sersic profile, and thus NMATCH=0 is possible. To get NMATCH=2 requires +HOSTNBR feature,
