### ISSUE TITLE
ZPHOT_QXX variables from forced Gaussian quantiles (HOSTLIB_MSKOPT 33106) are undefined for SIMGEN_DUMP

### ISSUE THREAD

**Issue by rebeccachen0** [RickKessler/SNANA#985]
Using HOSTLIB_STOREPAR and SIMGEN_DUMP works when photo-z quantiles are read in from the HOSTLIB, but not when the quantiles are force generated with HOSTLIB_MSKOPT option 33106. Trying to add the variables to the SIMGEN_DUMP list results in the following error (tried both ZPHOT_Q0 and HOSTGAL_ZPHOT_Q000 as is formatted in the FITS file): 
`Allowed SIMGEN_DUMP variables

 From SIM-GENERATION:
 CID LIBID NGEN_LIBID IDSURVEY RA RA_SN DECL DEC DECL_SN DEC_SN FIELD NFIELD_OVP MWEBV MWEBVMAP MWEBV_TRUE MWEBVERR ZCMB_SMEAR ZCMB ZHELIO ZHELIO_ERR ZFLAG VPEC VPEC_SMEAR Z GENZ MU DLMAG LENSDMU SL_MAGSHIFT STRONGLENS_MAGSHIFT GALNMATCH GALID GALZTRUE GALZPHOT GALZERR GALZPHOTERR GALSNSEP GALSNDLR GALSNDDLR GALZDIF GALSNDM GALWGT HOSTMAG_g HOSTMAG_r HOSTMAG_i HOSTMAG_z SBFLUX_g SBFLUX_r SBFLUX_i SBFLUX_z SBMAG_g SBMAG_r SBMAG_i SBMAG_z PEAKMJD DTSEASON_PEAK PEAKMJD_SMEAR MJD0 MJD_TRIGGER MJD_DETECT_FIRST MJD_DETECT_LAST MAGT0_g MAGT0_r MAGT0_i MAGT0_z PEAKMAG_g PEAKMAG_r PEAKMAG_i PEAKMAG_z WIDTH_g WIDTH_r WIDTH_i WIDTH_z AV RV DELTA DM15 STRETCH SALT2alpha S2alpha SIM_alpha SALT2beta S2beta SIM_beta S2x0 SALT2x0 SIM_x0 S2x1 SALT2x1 SIM_x1 S2c SALT2c SIM_c S2mb SALT2mb SALT2mB SIM_mb SIM_mB SALT2gammaDM SNMAGSHIFT VSI COLORSHIFT0 COLORSHIFT1 COLORSHIFT2 COLORSHIFT3 COLORSHIFT4 TRISE_SHIFT TFALL_SHIFT MAGSMEAR_COH MAGSMEAR_COH2 GENTYPE SNTYPE TYPE NON1A_INDEX NONIA_INDEX SIM_TEMPLATE_INDEX NOBS NOBS_UNDEFINED NOBS_SATURATE NOBS_NOSATURATE NOBSDIF NEPOCH

 From CUTWIN-ANALYSIS:
 REDSHIFT_FINAL TRESTMIN TMIN TRESTMAX TMAX SNRMAX SNRMAX1 SNRMAX2 SNRMAX3 SNRMAX4 SNRMAX5 SNRMAX_g SNRMAX_r SNRMAX_i SNRMAX_z TGAPMAX T0GAPMAX TIME_ABOVE_SNRMIN CUTMASK SIM_EFFMASK SIM_SEARCHEFF_MASK
	 Example of sim-input file syntax is
	 SIMGEN_DUMP:  5  CID Z RA DEC SNRMAX

   `|```````|`
   <| o\ /o |>
    | ' ; ' |
    |  ___  |     ABORT program on Fatal Error.
    | |' '| |
    | `---' |
    \_______/

 FATAL ERROR ABORT called by MATCH_INDEX_SIMGEN_DUMP
   Undefined SIMGEN_DUMP variable: 'HOSTGAL_ZPHOT_Q000' 
`

Error reproducible with `/project2/rkessler/PRODUCTS/SNANA_DEBUG/photoz_quantiles/DES/run_test_sims`  with output at out_sim_force_qgauss.log

**Comment by RickKessler** [comment]
Fixed. To see code fix, search snlc_sim.c for USE_QGAUSS.
