### ISSUE TITLE
use fit results from external FITRES

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#986]
I was trying to test this here:
`/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/use_fit_results_fromFITRES`
specifying in `FIT_LSST_EUCLID_Honly_fromFITRES.nml` that the external FITRES file is:
```
SNCID_LIST_FILE = '/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/use_fit_results_fromFITRES/FITRES_small_sample.FITRES.gz'
```

and setting INISTP parameters to 0 so the fitting code doesn't move from the initial value:
```
         INISTP_COLOR = 0
         INISTP_SHAPE = 0
         INISTP_PEAKMJD = 0
```
You can reproduce the output running:
`snlc_fit.exe FIT_LSST_EUCLID_Honly_fromFITRES.nml
`
But I get x1 all equal to 0.001 and c all equal to 0.01
You can verify this running:
`get_fitres_values.py -f LSSTDDF_EUCLID_Hfit.FITRES.TEXT -v x1,c,mB,x1ERR,cERR,mBERR --nrow 20
`

**Comment by RickKessler** [comment]
snlc_fit.car fixed to check if INISTP=0 for each parameter.
