### ISSUE TITLE
LOWZ Hack not working

### ISSUE THREAD

**Issue by OmegaLambda1998** [RickKessler/SNANA#988]
Dir: `/project2/rkessler/PRODUCTS/SNANA_DEBUG/LOWZ_HACK`

I'm attempting to hack together a lowz sample to complement my DES-like sample, however haven't been able to get it working. AT the moment we are producing very low numbers of supernovae.

**Comment by RickKessler** [comment]
SALT2.JLA-B14 does not cover i-band at low-z; since SPECEFF depends only on i-band, all low-z events were rejected. Fix is to use a model with extended IR range; e.g., SALT3.K21
