### ISSUE TITLE
possible KCOR issue converting VEGA -> AB

### ISSUE THREAD

**Issue by djones1040** [RickKessler/SNANA#99]
In `$SNANA_DEBUG/djones/raisin`, run `snlc_fit.exe CfA_RAISIN.nml` to get the light curve fit for sn2006D.  SNooPy has a fairly normal AV and a good quality fit for this SN, but in SNANA AV is way too high.  See also `CfAIR2.pdf` in that same directory to see the optical/IR difference, which is generated from the command:
```
$SNANA_DIR/util/plot_snana.py -v CfAIR2 -a -20 -f CfA_RAISIN.nml --plotAll
```
I suspect the issue is from the kcor file with the VEGA -> AB conversion, as the actual photometry looks to be the same as what I was using with SNooPy.  The kcor input file is `kcor_PS1_LOWZ_COMBINED_CfANIR.input` in that same directory.

**Comment by RickKessler** [comment]
please leave the SNOOPY-code fit parameters in a README in above directory.

**Comment by RickKessler** [comment]
I tried to re-run the kcor job to create a stdout logFile, but it aborted ??

**Comment by RickKessler** [comment]
finally got good agreement between Burns-snoopy and SNANA-snoopy.
