### ISSUE TITLE
bliding wfit

### ISSUE THREAD

**Issue by maria-vincenzi** [RickKessler/SNANA#993]
Example here: `/project2/rkessler/PRODUCTS/SNANA_DEBUG/mvincenzi/blinding_lcdm`
Run wfit on DES3yr by executing this cmd `./test.cmd`

First wfit command run wCDM with CMB prior and correctly blinds both w and om (see `wfitopt.yaml`)
Second wfit command run LambdaCDM fit and blinds both w and om (see `wfitopt_lcdm.yaml`, but should only blind om, w should be =-1)

**Comment by RickKessler** [comment]
fixed so that w is blinded only if w is floated.
